### ISSUE TITLE
IDE Explorer/Shell extensions

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#1003]
_Originally posted by @bclothier in https://github.com/twinbasic/twinbasic/issues/1000#issuecomment-1190789094_

FWIW, a quick registry script to help out. This lays out the groundwork for supporting opening & creating new files and giving them a pretty icon. Note that open ~~technically does not work because as indicated, there must be a command line switch to pass in the file name so right now it will simply open the IDE but not open the specific project~~ works with beta version 80 or newer. 

Of course, the paths in the script need to be adjusted to wherever the IDE is. To avoid requiring admin privileges, this can be used in HKCU\Classes instead of HKCR. 

![image](https://user-images.githubusercontent.com/2367644/180087636-b47961dc-e15c-4cd0-8641-3be98fccd936.png)

It may be worthwhile creating a new icon that has a file with tB logo on it to help differentiate it from the executables that has the full tB logo.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.twinproj]
@="twinBasic.Project"

[HKEY_CLASSES_ROOT\.twinproj\twinBasic.Project]

[HKEY_CLASSES_ROOT\.twinproj\twinBasic.Project\ShellNew]
"FileName"="C:\\TwinBasic\\IDE\\BlankProject.twinproj"

[HKEY_CLASSES_ROOT\twinBasic.Project]
@="twinBASIC Project"

[HKEY_CLASSES_ROOT\twinBasic.Project\DefaultIcon]
@="C:\\TwinBasic\\IDE\\twinBASIC.exe"

[HKEY_CLASSES_ROOT\twinBasic.Project\shell]

[HKEY_CLASSES_ROOT\twinBasic.Project\shell\open]

[HKEY_CLASSES_ROOT\twinBasic.Project\shell\open\command]
@="\"C:\\TwinBasic\\IDE\\twinBASIC.exe\" \"%1\""
```

Documentation:
[File Types and File Associations](https://docs.microsoft.com/en-us/windows/win32/shell/fa-intro)
[File Extension Key](https://docs.microsoft.com/en-us/windows/win32/com/-file-extension--key)
[DefaultIcon](https://docs.microsoft.com/en-us/windows/win32/com/defaulticon)
[Extending the new submenut](https://docs.microsoft.com/en-us/windows/win32/shell/context#extending-the-new-submenu)

**Comment by bclothier** [comment]
FWIW, I found out that there's a bonus with the above --- it also enables the use of recents for the application:
![image](https://user-images.githubusercontent.com/2367644/181917055-44ef2e6e-5258-44e9-97ff-79b678bad543.png)

Not sure which enables the feature but I do use the `Recent` list a lot. Much quicker than browsing to the right folder or opening the application and going through the list.

**Comment by WaynePhillipsEA** [comment]
This is now incorporated into the startup routine of the IDE as of BETA 149.   Thanks for sharing!
