### ISSUE TITLE
WinNativeForms : Control Property behaviour

### ISSUE THREAD

**Issue by AntsAntix** [twinbasic/twinbasic#1004]
**Describe the bug**
I experience significant frustration with WinNativeForms that could easily be result of ignorance on my part. It revolves around what should be working, and what isn't implemented. Those properties that have been implemented show up on the IDE. But sometimes, the property is only a 'shell' that does not implement the _getter_ and/or _setter_ logic.

**To Reproduce**
For example, I created a form to which a I added a WinNativeForms.Frame. This frame.BackColor was changed to DarkBlue on the property sheet. I then embedded a number of WinNativeForms.Label controls and set label.ForeColor to White and label.BackColor to DarkBlue. In UIDesigner, the frame BackColor stays White, but the embedded labels conform to the newly set colours.
I created another WinNativeForms.Frame and left it as a standard definition. I then embedded another WinNativeForms.Label into the frame. I set label.BackColor to LightGreen. In the UIDesigner, it displays as expected.
During form initialisation, I get the label.BackColor in order to implement label.MouseMove behaviour. The result of the assignment to a form variable is 0 (zero).
If you refer to the attached images, I show that UIDesigner view of the form and then the Preview of the form. 

**Expected behavior**
I am not sure what to expect, other than I would like the implementation to work. Because some Property get/set works, and other not, I am not sure how to tackle the problem. I suspect that the misbehaving label behaviour might be because the embedded controls adopt the same property values as the Parent control (I cannot explain the label loss-of-colour other than this).
I looked at the implementation of the WinNativeForms package, but I do not have enough background to try to make adjustments here.
I am not sure if I should be struggling. My mind goes back to early days of VisualStudio when I could develop applications in NotePad as long as I wired the application together correctly, it could compile and run.
But if I know how, I am willing to try piece it together.

**Screenshots**
In UIDesigner:
![image](https://user-images.githubusercontent.com/89644755/180262013-12cd55a2-39af-4c5d-97b1-85f8d84547aa.png)
In Preview:
![image](https://user-images.githubusercontent.com/89644755/180262186-f7665837-15d7-4a44-818e-fb2d1070af6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version: BETA . . . up to 79

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Thanks for your feedback.  I can appreciate that it's frustrating, but it's mostly expected at this stage, since the UI work is not yet complete.  In fact, container controls support was only added a couple of weeks ago... so yes, some bugs world most certainly be expected there.

The best thing to do is to report any issues you find here on GitHub, as you find them.  You will typically find they get fixed/implemented very quickly.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 82, thanks!
