### ISSUE TITLE
Variable structure alignment (#pragma pack(n))

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1007]
**Is your feature request related to a problem? Please describe.**
Some APIs require structs aligned at sizes other than the VB/TB enforced 4-bytes. 

**Describe the solution you'd like**
Implement an equivalent to `#pragma pack(n)` that changes the automatic alignment size.

**Describe alternatives you've considered**
Currently this must be done manually for higher values, and I'm unaware of possible solutions for lower values.

**Comment by mansellan** [comment]
Might be able to accommodate this with an attribute, [like .net does](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute.pack?view=net-6.0)

**Comment by WaynePhillipsEA** [comment]
A new attribute, `[ PackingAlignment(n) ]` is now supported for UDTs, equivalent to #pragma pack in MSVC.   Using `[ PackingAlignment(1) ]` above a UDT will ensure no alignment packing is added by the compiler.
