### ISSUE TITLE
Auto-indent frequently stops working

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1016]
**Describe the bug**
Title says it all

**To Reproduce**
It seems to mostly happen after Dim statements. Start typing, press enter to autocomplete (twice), and it stops working on all lines following that in the current procedure.
Also, after strings ending a line... Label1.Caption = "whatever" (typing last quote manually), press enter once, no more auto-indent.

**Expected behavior**
Should always auto-indent on enter.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSB 1809
 - twinBASIC compiler version: 0.15.80

**Additional context**
None

**Comment by WaynePhillipsEA** [comment]
I can only seem to repro this if I put something extra at the end of a line, e.g. a space.  So `Dim a As Long ` {ENTER} loses the indent position, but `Dim a As Long` {ENTER} does not.

**Comment by WaynePhillipsEA** [comment]
Ah OK... any auto-correction is triggering whitespace trimming of empty lines, so `dim a as long` {ENTER} loses the indent position due to the auto-correction that triggers the empty line trimming on the new line

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 82, thanks!
