### ISSUE TITLE
Check boxes truncate text rather than wrap to next line, even when height allows it

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1018]
**Describe the bug**
Title says it all. Applies to both IDE designer and runtime.

**To Reproduce**
Create caption longer than fits in control.

**Expected behavior**
BS_MULTILINE Or BS_VCENTER style should be set by default as in VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 1809
 - twinBASIC compiler version: 0.15.82

**Additional context**
Can be worked around by setting via API, support is there so should be a fairly quick fix.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 85, thanks!
