### ISSUE TITLE
TB exe DPI awareness

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1019]
**Describe the bug**
Windows detects TB exes as DPI-aware. This is not in the automatically included manifest. There does seem to be some dpi awareness; TB controls appear the proper size, and remain that way when system DPI scaling is applied by forcing it via compatibility settings. However, specifying pixels for actions done with APIs is not scaled

**To Reproduce**
Create an object on a form via API specifying pixels. It will not be scaled. 

**Expected behavior**
This is a major departure from VB6 projects; either it's not marked dpi aware in the manifest and system scaling works with both design-time based controls and API-created controls, or it is marked dpi aware in the manifest and nothing is scaled by the system.

**Screenshots**
![Screenshot](https://i.imgur.com/LBo2R2J.jpg)
The frame was created in the designer with height 180. The ListView was created via API at y=204. As you can see by looking at the small space between frames, it was not scaled, so is at 204 absolute pixels while the frame was scaled to 270 pixels. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise LTSC 1809
 - twinBASIC compiler version: 0.15.82

**Additional context**
[Project with issue in question.](https://www.vbforums.com/showthread.php?890181-TwinBasic&p=5574850&viewfull=1#post5574850)

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.  This is a known issue due to the tB form engine calling `SetProcessDpiAwareness` during initialization, whereas we should be leaving the choice up to the developer via a manifest.

**Comment by fafalone** [comment]
Closing since the option to set it manually was added a few versions ago.
