### ISSUE TITLE
Save doesn't save after Find In Project

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1022]
**Describe the bug**
Save doesn't save after Find In Project

**To Reproduce**
1. Start tB as admin.
2. Import a VBP.
3. Find In Project
4. Click the found item.
5. Change something
6. Try to save.

**Expected behavior**
Project gets saved to disk.

**Screenshots**
See video:
https://user-images.githubusercontent.com/88059532/180639042-99a4d985-2e54-427f-b3ad-1443d1700437.mp4

**Desktop (please complete the following information):**
 - Windows 10
 - beta 82

**Comment by WaynePhillipsEA** [comment]
I haven't seen any recent reports of this problem, so let's close this.  Thanks.
