### ISSUE TITLE
Strange return of a unwanted unicode string

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1027]
i have a function which beautifys numbers
[10:40] Rexxitall: Function Beauty(ByVal R As Double, Optional Stellen As Double = 4, Optional Length As Long = 0, Optional Roundit As Double = 0.0001) As String 'EXPORT
'#INFO: active author:tl timestamp:20220725133004 md5:1EDBC9E0ABFE85C9A3FCA808F9C50F9D
'
    Dim Rs As String
    Dim S As String
    Dim S2() As String
    S = Trim(Str(Roundto(R, Roundit)))
    S = Trim(Str(R))
    S = Replace(S, ",", ".")
    If InStr(S, ".") = 0 Then S = S & "."
    S2 = Split(S, ".")
    If Stellen < 0 Then S2(1) = Trim(Left(S2(1), Abs(Stellen)))
    Stellen = Abs(Stellen)
    Do While Len(S2(1)) < Stellen
        S2(1) = S2(1) & "0"
    Loop
    Rs = Trim(S2(0) & "." & S2(1))
    Rs = Replace(Rs, "-.", "-0.")
    If Left(Rs, 1) = "." Then Rs = "0" & Rs
    If Length > 0 Then

        If Len(Rs) < Length Then

            Do While Len(Rs) < Length
                Rs = " " & Rs
            Loop

        End If

    End If
    Beauty = Rs
End Function
[10:41] Rexxitall: i use a define to set them in the vba code
[10:41] Rexxitall: Declare PtrSafe Function Beauty Lib "\vba\ACAD-DLL\MATH_GEO.dll" (ByVal r As Double, Optional stellen As Double = 4, Optional Length As Long = 0, Optional roundit As Double = 0.0001) As String     '#SRCTOOL#
[10:41] Rexxitall: i call the function by using this
[10:41] Rexxitall: Sub testbeauty()
Debug.Print Beauty(Pi, 3, 3)

End Sub
[10:42] Rexxitall: and i get this in the immediate window back
[10:42] Rexxitall: 3 . 4 1 5 9 2 6 5 3 5 8 9 7 9 3
[10:42] Rexxitall: which is not the result i get in vba
[10:45] Rexxitall: which is 3.41592653589793
[10:45] Rexxitall: so how to get rid the additional unicode  chars ?
[10:46] Rexxitall: in VBA

Proposal:
There should be a compiler switch which disables or forces unicode character generation in both ways .
In my case it breaks existing code.

**Comment by WaynePhillipsEA** [comment]
Could you also provide the `Roundto` implementation

**Comment by WaynePhillipsEA** [comment]
Apologies, this is not a bug.  Your DLL export from twinBASIS is returning a unicode string (BSTR), but VBA treats the 'String' definition as ANSI in your DLL Declare.  So just change the last line in your tB implementation to match it:   `Beauty = StrConv(Rs, vbFromUnicode)`

**Comment by rexxitall** [comment]
Public Function Roundto(ByVal Dblnumber As Double, ByVal Dblroundto As Double) As Double 'EXPORT
'#INFO: active author:tl timestamp:20220725133004 md5:B6F824720AB34D8B68A0C17E082A9F2B
'
    On Error Resume Next
    Roundto = Round(Dblnumber / Dblroundto) * Dblroundto
    On Error GoTo 0
End Function

**Comment by rexxitall** [comment]
You "solution" require a massive amount of  manual code changes. A compiler directive would be more effective. In my eyes "StrConv(Rs, vbFromUnicode)" is not 100% compatible. This was not needed in the original source and will also break the code. After that Statement VBA will get confused. I guess its not the idea to be 100% compatible if you need hundreds of conditional defines, massive manual edit afford and finally breaking the original source. In this case i can also use another compiler which also needs a complete manual code rewrite. Anyhow thanks for the workaround. Same as with the [ DllExport ] statement. which ends up by something like that and which is also not nice.
 #If Dll = 0 Then '#SRCTOOL# DLL
#If Vba < 1 Then '#SRCTOOL#
[ DllExport ]
#End If '#SRCTOOL#
Public Function Roundto(ByVal Dblnumber As Double, ByVal Dblroundto As Double) As Double 'EXPORT
'#INFO: active author:tl timestamp:20220725133004 md5:B6F824720AB34D8B68A0C17E082A9F2B
'
    On Error Resume Next
    Roundto = Round(Dblnumber / Dblroundto) * Dblroundto
    On Error GoTo 0
End Function
#End If '#SRCTOOL# DLL

**Comment by WaynePhillipsEA** [comment]
DLL declares in VBx are inherently ANSI based, which is a lossy text format.  In general we don't want to encourage use of ANSI in 2022.  This is not technically a backwards compatibility issue, since VB6 cannot ordinarily create DLL exports without additional help anyway.

A much better solution would be to create a COM object (or multiple) to expose your functions to VBA.  That way, there's no lossy conversions.  You can even avoid having to prefix the calls with the class instance object by marking the classes as `[ AppObject ]`, which will expose the class members just like regular functions.

**Comment by rexxitall** [comment]
A com object needs to be created and the complete code has to be rewritten as well. Just to fill the com object variable inside. Also not a solution. Why its so hard just to convert the unicode things back to ascii if someones needs that. If you do not want to rewrite your string libs etc ? Its way more easy on the compiler thing then in thousends of user code lines.

**Comment by WaynePhillipsEA** [comment]
> A com object needs to be created and the complete code has to be rewritten as well.

Not true.  Again, please consider the `[ AppObject] ` attribute on a regular COM class;  it lets you write class members that are allowed to be used in much the same way as standard module functions *without* changing your code.  _(The underlying implementation is slightly different, but from a functional user perspective, they are very similar, and shouldn't require masses of code to be re-written)_

The solution you are asking for is nowhere near as simple as you make it sound.
