### ISSUE TITLE
No font size option in MonthView control

### ISSUE THREAD

**Issue by OldestCoderInTown** [twinbasic/twinbasic#1028]
When I use settings to reference MS Windows common controls, I get the MonthView control but the Font option is grey.

**Comment by WaynePhillipsEA** [comment]
Doesn't seem to be a problem in recent builds, so let's close this.  Thanks

**Comment by OldestCoderInTown** [comment]
The fontsize option is present but fails to affect the displayed control.

**Comment by fafalone** [comment]
I believe that's a Visual Styles issue. But it belongs in a new issue.

**Comment by OldestCoderInTown** [comment]
Every day is a school day. Thanks very much, issue now resolved.
