### ISSUE TITLE
Self-referential assignment fails for custom class variables

### ISSUE THREAD

**Issue by zeumai** [twinbasic/twinbasic#1030]
**Description**
A self-referential assignment statement like `Set x = AnyFunction(x)` fails if `x` was declared with a custom class as its type. Testing `x` after the attempted assignment reveals that its value remains unchanged.

**To reproduce**
Run the Main method in this code:
```
Class CustomObj
End Class

Module Tests

    Function ReturnNothing(DummyArg As Object) As CustomObj
    End Function
    
    Sub Main()
    
        Dim x As CustomObj
        
        Set x = New CustomObj
        Debug.Print x Is Nothing, ObjPtr(x) 'x has successfully been initialized
        Set x = ReturnNothing(x)
        Debug.Print x Is Nothing, ObjPtr(x) 'x should now be Nothing, but it is not
        
    End Sub

End Module
```

**Expected behavior**
`x` should have been set to `Nothing` by `Set x = ReturnNothing(x)`. Instead, `x` continues to refer to the new object instance created by `Set x = New CustomObj`. The expected behavior can be obtained by replacing `Dim x As CustomObj` with `Dim x As Object`.

**Desktop**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.82

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 86, thanks for reporting!

**Comment by zeumai** [comment]
Thank you!
