### ISSUE TITLE
IDE Feature: Copy/Paste or duplicate complete Forms/Modules/Classes

### ISSUE THREAD

**Issue by yogeshvachhani** [twinbasic/twinbasic#1033]
As the IDE is still under heavy development I requesting this feature if possible.

Add facility to copy a Forms/Modules/Classes and Paste it give facility in Project Explorer on right click menu to duplicate a Forms/Modules/Classes.

Here when user uses the Duplicate feature the IDE should ask for name.

Regards,

**Comment by fafalone** [comment]
Copy/Paste works with source files; new ones with " copy" in the file name are created and include the code of the original.
