### ISSUE TITLE
MsgBox shows wrong title

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1041]
**Describe the bug**
MsgBox shows wrong title when title is omitted.

**To Reproduce**
1. In Sub Main, place this:
```
md = "Blabla"
MsgBox md

```
2. F5
3. Look at the title.

**Expected behavior**
The title should show the project name.
MSDN:
title
Optional. String expression displayed in the title bar of the dialog box. If you omit title, the application name is placed in the title bar. 

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/181222976-381893c7-72ba-4766-a307-3cad5b688724.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 86

**Additional context**
I also wonder about the German word "Fehler" (= "Error").
Where does it come from?

**Comment by WaynePhillipsEA** [comment]
I believe this was fixed recently.  If this still persists, let me know and I will re-open.

**Comment by KarlSevenSeven** [comment]
1)
Not ok in beta 145.
Now the title is blank.
The title should be the project name if not set by the MsgBox command.

2)
```
        Dim md As String
        md = "-START-" & String$(120480, "Q") & "-END-"
        Debug.Print Len(md)
        MsgBox md
```
Silently fails, VB6 truncates the stupid long string and shows the MsgBox.

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven  for 1) please check your Application Title setting.  This was introduces recently, and should automatically import over if you're loading a VBP.

For 2) this is fixed in next release.

**Comment by KarlSevenSeven** [comment]
> Application Title setting
> ...
>  you're loading a VBP

Didn't load a VBP, made a new EXE project.

The Application Title setting was not touched and is set to 'New project' by default.
![image](https://user-images.githubusercontent.com/88059532/194846560-9bd10377-7d52-4fb1-bb45-b1c7af70b344.png)

When I edit the Application Title setting, then MsgBox shows it.
So in general it works, but not 100% right.

---

Thanks for 2).

**Comment by WaynePhillipsEA** [comment]
Issue 2 is fixed in BETA 146.  
I couldn't repro Issue 1, let me know if you have a sample twinproj file that demonstrates it.

Thanks for reporting :)

**Comment by KarlSevenSeven** [comment]
Here the sample, done with 145.
F5 and mouseclick the form.
No title in here.

[2022-10-11_MsgBox.zip](https://github.com/twinbasic/twinbasic/files/9758042/2022-10-11_MsgBox.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 147, thanks!
