### ISSUE TITLE
DateSerial and/or Format doesn't work when placed in module under x64

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1042]
**Describe the bug**
I've attached a demonstration project for this bug; it calls the GetLocalTime API and formats it. 

When the formatting code is placed in a Form, it works. When the same code is in a module, the data is corrupted and displays
Debug.Print DateVar, 1/1/0 -6699:0-14:0-8 AM 
Debug.Print Formatted DateVar, 27,0000-01-01 ᜫ7:ᧈ2:ᧈ8

**To Reproduce**
Download and open (confirm if in x64 mode, I don't recall if that's saved with the project settings)
Run, it will display the corrupted string above.
Cut and paste SystemTimeToDate and FormatTime from MyModule to Form1
Run again, it will display the correct and properly formatted time.

**Expected behavior**
DateSerial and Format should work regardless of whether they're in a Form or Module in x64 mode. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.85 (Edit: Confirmed still present in 0.15.86)
 
**Additional context**

[DTBug.zip](https://github.com/twinbasic/twinbasic/files/9197426/DTBug.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 102, thanks.
