### ISSUE TITLE
No menu for forms

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1044]
**Describe the bug**
There is no pulldown menu for forms.

**To Reproduce**
1. Nothing...

**Expected behavior**
Having a menu.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 82

**Comment by KarlSevenSeven** [comment]
When it comes to the menu, perhaps the 100% compatibility does not have to work **back** to VB.
The VB menu has some quirks, IMO not worth to copy them:
http://www.vbaccelerator.com/home/VB/Code/Controls/Menus/Icon_Menu_Control/article.html
To get this control to work would require major effort.
The control itself is also quirky.

Importing the menu defined in the *.frm file to a better system would be sufficient.
And if this better system could show icons in the menu, that would be great.

**Comment by EduardoVB** [comment]
It would be good to list the quirks, so we could discuss a way to fix them while still maintaining backward compatibility.

**Comment by KarlSevenSeven** [comment]
Now it's there - super!

When selecting a PNG file for the picture, there is no transparency.

**Comment by KarlSevenSeven** [comment]
Covered and solved by
https://github.com/twinbasic/twinbasic/issues/1299#issue-1422176642
