### ISSUE TITLE
Project not saving all things after a Control + S

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1045]
Hi, i might be wrong but ! In VBA or VB6 the whole project will be stored if i press STRG+S. Not just a bit or the actual file open in the editor no -  they store EVERYTHING. :) 
Even i do not compiles today or something "strange". I just add and edit files. Ane even i presst STRG a lot - i loose files and changes. Not one times, many times. So something IS wrong in the project management. There was no crash no warnings, nothing. I just got a "nice" surprise after reopen the project. Sometimes it works but often not. Can not track it down much better at the moment. I was busy with Adding var declarations or fixing minor bugs. Looks a bit same as the bug described if someone has opened two instances of TB. By that knowledge i was carefully avoid this. So there must be another issue. Thanks god i just refactor existing code today. But even by that it was anoying :/ Fixing the same BS again and again isnt that fun ;)

**Comment by bclothier** [comment]
Just curious - are you by any chance saving files to a network folder?

**Comment by WaynePhillipsEA** [comment]
Possibly related to #1022 ?

**Comment by EduardoVB** [comment]
> Hi, i might be wrong but ! In VBA or VB6 the whole project will be stored if i press STRG+S. Not just a bit or the actual file open in the editor no - they store EVERYTHING. :)

No, VB6 saves only the current code module.
PS: it would be a headache if tB saves everything.

**Comment by KarlSevenSeven** [comment]
This could be more verbose:
![image](https://user-images.githubusercontent.com/88059532/181477327-9605a48d-ce02-40ae-95e8-a5e821a4b8ac.png)

CTRL+S should save the current module only as in VB.
And tell it in the Debug pane.

CTRL+SHIFT+S would be nice for save whole project.
In VB it's annoying to have to use the menu or the icon to do so.

In VS Code there is the Hot Exit feature.
I didn't like it as it didn't ask - what if you don't want to save?
Q: It this Hot Exit available in the new IDE?

**Comment by WaynePhillipsEA** [comment]
I've not seen any recent reports of such a problem, so let's close this.  Thanks.
