### ISSUE TITLE
MsgBox doesn't show

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1047]
**Describe the bug**
MsgBox doesn't show.

**To Reproduce**
1. Load this:
[ExOrder1a.zip](https://github.com/twinbasic/twinbasic/files/9207405/ExOrder1a.zip)
3. Run
4. The debug pane shows the content the MsgBox should show.
5. In VB6 it's as expected.

**Expected behavior**
The MsgBox should show up.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 86

**Additional context**
I know the example is not good to measure the evaluation performance.
The missing MsgBox issue came up before I was finished.

**Comment by KarlSevenSeven** [comment]
https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/msgbox-function

My fault.
The string to display is simply too long (152158 > 1024).

On the other hand, when in VB6, the prompt gets truncated and the MsgBox shows up.

**Comment by WaynePhillipsEA** [comment]
This was fixed in more recent builds, so let's close this now.  Thanks.
