### ISSUE TITLE
History of visited places in the code

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1048]
**Is your feature request related to a problem? Please describe.**
Not a problem.

**Describe the solution you'd like**
A list of last visited places in the code would be nice.
Could work like this:
Once the cursor is in a place for 10 seconds, this place should be stored.
The list should show the procedure name and module.
A doubleclick on an item would restore the cursor position.
Error message if not found (deleted proc).

**Describe alternatives you've considered**
A bookmark system that can make bookmarks automatically.

**Additional context**
CodeSmart has such:
![image](https://user-images.githubusercontent.com/88059532/181475628-d785026f-b7dc-49ce-9f0e-331e72096384.png)

**Comment by mburns08109** [comment]
So, basically and IDE Auditor function?
(looked at this)
(deleted that)
(inserted these)
(looked at this other stuff)
(cut this) (moved over there) & (pasted that)...

sounds very doable, but will have the same navigation issues that we see in the Windows Event logs after a while - even if cleared between edit sessions.

One would presume that you'd want things like configurable options to auto-save/delete after N sessions or x days or yyy space used or somesuch? at least then you could go back looking for those "Oh yeah, I did code that a day or 3 back, but removed it before saving..." things.

**Comment by KarlSevenSeven** [comment]
> IDE Auditor function

Sounds good, but I mean a much simpler thing.
Just a simple list, updated in an interval.

**Comment by WaynePhillipsEA** [comment]
This sounds like a good idea, thanks.

**Comment by WaynePhillipsEA** [comment]
We've had the HISTORY panel available for some time now, so let's close this now.  Thanks.
