### ISSUE TITLE
BASE64 code forces endless loop in IDE

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1050]
How to reproduce
Create active X dll from scratch 
import code by copy and paste
scroll a bit or try to save. 
![image](https://user-images.githubusercontent.com/22050310/181522855-596b9542-2db3-48c1-8e03-0f0d93e15464.png)

**Comment by rexxitall** [comment]
Bas file can not imported and by try to insert via copy and paste it cretes endless loop
[BASE64.zip](https://github.com/twinbasic/twinbasic/files/9274666/BASE64.zip)
File attached. was exported from autocd vba7 64bit

**Comment by KarlSevenSeven** [comment]
Same in here.

**Comment by KarlSevenSeven** [comment]
The default member of the err object is not resolved correct.
https://docs.microsoft.com/en-us/office/vba/Language/Reference/User-Interface-Help/err-object

Therefore line # 530 in the source confuses tB.
`Select Case ERR`
Changing this to
`Select Case Err.Number`
before import/paste kind of solves the issue.

**Comment by rexxitall** [comment]
Sorry, that is some kind of *zensored* ,I totally disagree ! Even the code is not perfect or wrong, the IDE should be able to import the code. (Like any other IDE) If the code is perfect then i guess i do not need a IDE anymore :) That is what i usually await and can await from any stupid editor /IDE out in the world. Seem just according your words not from the TB IDE. Nice try to avoid work and fix the bug :D

**Comment by rexxitall** [comment]
But thank you very much for the workaround :)

**Comment by WaynePhillipsEA** [comment]
@rexxital, @KarlSevenSeven was only helping identify the problem, since I haven't yet managed to look into this for you.

The bug will of course be fixed.   All in good time.

Thanks @KarlSevenSeven.

**Comment by rexxitall** [comment]
Thanks you both :) And you may know - its a bit difficult to be a bit jokey in a foreign language :) Stupidly i like to joke. Life is hard enough :) BTW - i recognize also that i was a bit to strong in the wording. So the thanks for the workaround was not ironically :)

**Comment by WaynePhillipsEA** [comment]
No worries!  Yes, it's always difficult with languages... I've made that mistake before ;)

**Comment by rexxitall** [comment]
Well i was together and also married to a girl from Finland for 10 years. Fun Part She does never learns german and for sure i never learned suomi - the finish language. (Some kind of kisuaheli. Its old ukrisch and has no language roots by any other european language). All the time we use english. Now imagine how much fun we have had *laugh* :D

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 102, thanks.
