### ISSUE TITLE
IDE history pane

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1054]
**Is your feature request related to a problem? Please describe.**
Scrolling through the dropdowns to find code in medium to large codebases is time consumer, especially when work frequently involves large time blocks working on a set of related procedures.

**Describe the solution you'd like**
The VB6 CodeSMART addin provides a history pane listing the last 20 (or less depending on size) procedures, and it's a huge time saver. Something like this seems like minimal complexity for a big benefit.

**Describe alternatives you've considered**
Much longer term, ability to make addins like this by the community would provide even more flexibility. 

**Additional context**

**Comment by KarlSevenSeven** [comment]
Same idea:
https://github.com/twinbasic/twinbasic/issues/1048#issue-1320674872

**Comment by wqweto** [comment]
Btw, what is TB IDE equivalent of `Ctrl+Shift+F2` in VB IDE?

I know that `F12` goes to definition but `Ctrl+-` as in Visual Studio does not return to previous position.

**Comment by fafalone** [comment]
Missed the previous entry for this, sorry.
