### ISSUE TITLE
Logical Operators Unexpected Result

### ISSUE THREAD

**Issue by SlavWski** [twinbasic/twinbasic#1055]
**Describe the bug**
Logical operators are producing unexpected result when comparing String with Integer.
OrElse and AndAlso work ok and if check is done beforehand and pre-assigned to Bool

**To Reproduce**
Run following code:
        
        Public Sub TestRun()

        Dim X As Integer, Y As Integer, Z As String
        Dim bCheck1 As Boolean, bCheck2 As Boolean
        
        X = 1
        Y = 2
        Z = "39"

        bCheck1 = X = 0 'False
        bCheck2 = Y > Z 'False

        Debug.Print bCheck1 Or bCheck2  'False
        Debug.Print X = 0 OrElse Y > Z  'False
        Debug.Print X = 0 Or Y > Z      'True but False is expected

        Debug.Print bCheck1 And bCheck2 'False
        Debug.Print X = 0 AndAlso Y > Z 'False
        Debug.Print X = 0 And Y > Z     'True but False is expected

        End Sub

**Expected behavior**
Behaviour to Match VBX/VBA

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise; 10.0.19044 Build 19044
 - twinBASIC compiler Version: 0.15.71

**Comment by mburns08109** [comment]
uhm, shouldn't the Y > Z checks be throwing a type error? ...or have you re-created "Evil Type Coercion" here too?

**Comment by WaynePhillipsEA** [comment]
@mburns08109 No, that is allowed.  It doesn't throw.

@SlavWski this is fixed in BETA 88, thanks for reporting.
