### ISSUE TITLE
Splitters over popup menus

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1063]
**Describe the bug**
Pane splitters overwrite even popup menus.

**To Reproduce**
Right click towards the bottom on edit pane so that popup menu shows over debug console and without leaving the popup position the mouse vertically on the splitter.

**Screenshots**
![image](https://user-images.githubusercontent.com/987963/181889350-b424e696-15b3-4b8d-8f6d-228833b8ed78.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 87

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 89, thanks!
