### ISSUE TITLE
Join2D takes forever

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1065]
**Describe the bug**
In a test app the Join2D function performs not so well while it does in VB6.
http://dailydoseofexcel.com/archives/2015/01/28/joining-two-dimensional-arrays/

**To Reproduce**
1. Unzip this:
[2022-07-30_FastStore.zip](https://github.com/twinbasic/twinbasic/files/9227016/2022-07-30_FastStore.zip)

3. Run and click the 'ToVariant' command button.
4. Try the same in VB6 (also in ZIP)

**Expected behavior**
A t least same performance as in VB6

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 88

**Comment by WaynePhillipsEA** [comment]
This should be better in BETA 89.  I will await your confirmation before closing.  Thanks.

**Comment by KarlSevenSeven** [comment]
Join is better now, still VB6 EXE makes 'ToVariant' faster.
485 vs. 875 msec.

Also interesting is 'ToArray'.
16 vs. 296 msec.
This is a much simpler case; no type conversion, just Doubles.

**Comment by WaynePhillipsEA** [comment]
Looks like this was resolved but didn't get closed, so let's fix that now.
