### ISSUE TITLE
Infinite Do While loop

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1077]
**Describe the bug**
A Do While loop is never left.
Works fine in VB6.

**To Reproduce**
1. Load:
[2022-08-02_InfLoop.zip](https://github.com/twinbasic/twinbasic/files/9242155/2022-08-02_InfLoop.zip)
3. Run.
4. Try the same code in VB6.

**Expected behavior**
Basic loops and calculations working as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 89

**Additional context**
While I needed to give up on a large ActiveX project, I tried another one which is a lot smaller.
Every procedure makes output to a debug file.
Example (shortened:)
[TD.TXT](https://github.com/twinbasic/twinbasic/files/9242426/TD.TXT)
The idea is to find a general error faster and easier to explain.
This is the first obstacle I found.

Quite cumbersome to play with ActiveX sources because there are no real means for debugging in tB I know of.
Isolating errors takes hours and hours.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 90, thanks
