### ISSUE TITLE
WinNativeForms Property Issues

### ISSUE THREAD

**Issue by AntsAntix** [twinbasic/twinbasic#1078]
**Describe the bug**
Seems to be regression related to Frame Property handling. At least Property Let BackColor no longer works.

**To Reproduce**
Setting BackColor for a Frame no longer works. 
Setting BackColor in the IDE did not apply the colour to a Frame, but at some stage it did function in an EXEcutable.

**Expected behavior**
That BackColor can be set for a Frame and its 'child' controls can be set.

From a WinNativeForms perspective, Font.Bold and FontBold Property Let also do not action at runtime.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version: BETA-89

**Additional context**
I am sure that BackColor was working up until maybe BETA-87 or thereabouts

**Comment by WaynePhillipsEA** [comment]
Looks OK to me in recent builds, so let's now close this.  Thanks.
