### ISSUE TITLE
Outline indentation

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1081]
**Describe the bug**
In OUTLINE panel a member is indented.

**To Reproduce**
1. See pic.
2. 
[2022-08-04_OutlineIndent.zip](https://github.com/twinbasic/twinbasic/files/9257671/2022-08-04_OutlineIndent.zip)

**Expected behavior**
No indentation.
Or, if it's a feature, a short explanation.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/182790254-cdbbc052-6bd6-4a5f-a13b-73b46b0c9463.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 90

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 94, thanks for reporting!
