### ISSUE TITLE
Missing design propertys of controls

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1083]
A lot of the standard controls lack features to set foreground or background colors, fonts etc for ALL Design elements. In VBA i am for example not able to style the buttons of a multipage view. Even that would be handy in a lot of cases. So in simple words - if something is gray and you can not change this color you got such a candidate.

Proposal: add this kind of propertys in a way that in normal VB6/VBA it will ignored by on error resume next" :) For such enhancements in the IDE also a "warning" flag may be a good idea. Should appear if such statements are not inside a conditional defines rule. #if TB then ...

**Comment by WaynePhillipsEA** [comment]
Controls and their properties are based off VB6, not VBA/MSForms, therefore this is considered out-of-scope.  Thanks
