### ISSUE TITLE
Slow load time and flickering when opening forms

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#1084]
**Describe the bug**
I'm observing that it takes several seconds between the clicking of a ribbon button and before the tB form displays. Furthermore, I'm observing that when opening a 2nd form from that form via the ItemCheck event of a listbox, there's lot of flickering on the first form before the 2nd form open. 

I'm not sure what might be causing it to be so slow and finicky. I also observe that there's an unhandled exception when closing the Access application (which would then attempt to unload the add-in and fail). This only happens if I've opened the 2nd tB form. 

**To Reproduce**
1. Create an Office add-in project
2. Add a tb Window form
3. Add a listbox. Enable checkboxes on it. 
4. Add a ItemCheck event to open a 2nd tb Window form
5. Run the add-in and observe the slowdown/flickering.

**Expected behavior**
No flickering or delays in opening.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler BETA 90

**Comment by WaynePhillipsEA** [comment]
I believe this should be much improved in more recent builds, therefore I'm going to close this.  Thanks.
