### ISSUE TITLE
Outline pane wrong content

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1085]
**Describe the bug**
The outline panel shows numbers instead of the expected variable names.

**To Reproduce**
1. Load
[2022-08-05_Outline2.zip](https://github.com/twinbasic/twinbasic/files/9270362/2022-08-05_Outline2.zip)
3. Click on entries in the outline pane.

**Expected behavior**
Showing correct content.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/183122912-98819e4a-a7d7-4d3c-9bd0-89dacbe51679.png)

Also see the numbers changing:
https://user-images.githubusercontent.com/88059532/183125462-bb189ab0-fee1-4583-a818-e16082e48126.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 90

**Additional context**
I know the project is full of errors - doesn't matter for this issue.
In the real project w/o errors there are different numbers in outline pane.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 94, thanks for reporting!
