### ISSUE TITLE
Asc() returns wrong result

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1087]
**Describe the bug**
Asc("ä")  returns wrong result.

**To Reproduce**
1. Type `Print Asc("ä")` in the debug console.
2. See `-28` as the result.
3. Try the same in VB6.
4. See correct result `228`.

**Expected behavior**
Correct result

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC 90

**Comment by francescofoti** [comment]
Note: `Print AscW("ä")` does however yield the correct result.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 93, thanks!
