### ISSUE TITLE
Raised error from a class method does not bubble up to calling procedure

### ISSUE THREAD

**Issue by francescofoti** [twinbasic/twinbasic#1089]
**Describe the bug**
When calling a class method that raises an error from another method (of the same class in this test), does not reach the top of the stack calling method in a module.

**To Reproduce**
1. Create a new project (Standard EXE)
2. Add a new class file (TestClass.twin), with the following class code:

`
Class TestClass

	Public Sub MethodThatFails()
    	Err.Raise 5&, "TestClass2::MethodThatFails", "Error message that should display"
	End Sub

    Public Sub CallMethodThatBlindlyFails()
    	Me.MethodThatFails
    End Sub

    Public Sub CallMethodThatTrapsError()
        On Error GoTo CallMethodThatTrapsError_Err
    	Me.MethodThatFails
        Exit Sub
    CallMethodThatTrapsError_Err:
        Debug.Print "I confirm that calling MethodThatFails raises an error"
    End Sub
End Class
`

3. Add a new module file (MMain.twin), with the following code:

`
Module MMain

	Sub Main()
    	Dim oTestClass As New TestClass
        
        On Error GoTo Main_Err
        oTestClass.CallMethodThatBlindlyFails  'This should jump to Main_Err
        Debug.Print "Something's not right"
        
        Exit Sub
    Main_Err:
        Debug.Print "Error: " & Err.Description
	End Sub
`
`
  Sub Test2()
    Dim oTestClass As New TestClass
    oTestClass.CallMethodThatTrapsError 
    Debug.Print "Do we see the error message in the console ? - Unfortunately not"
  End Sub

End Module
`

5. In the debug window, invoke procedure Main
Output:
![image](https://user-images.githubusercontent.com/6288870/183465090-5e14958c-a0d4-4ac1-8b5a-d35421cae545.png)

6. In the debug window, invoke procedure Test2
Output:
![image](https://user-images.githubusercontent.com/6288870/183465112-b6146a55-c865-469b-a87e-4531c6b89728.png)

**Expected behavior**
At step 4, the raised error should bubble up into the error handler in Sub Main (Main_Err), so we should see the error displayed as "Error: Error message that should display" in the debug window.
At step 5, the error handler in member procedure CallMethodThatTrapsError should display the error in the debug console from its error handler.

**Desktop:**
 - OS: Windows 10
 - twinBASIC compiler version BETA 90

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 93, thanks!
