### ISSUE TITLE
Mid Statement does not populate strings in Variant Array

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1096]
**Describe the bug**
If I have a string in a variant array then the Mid statement does not write to the string in the array.

**To Reproduce**
```VB
Public Sub TestMidToStringInArray()
	
    Dim myArray As Variant
    ReDim myArray(1 To 4)
    myArray(1) = VBA.Space$(10)
    myArray(2) = VBA.Space$(10)
    myArray(3) = VBA.Space$(10)
    myArray(4) = VBA.Space$(10)
    Mid(myArray(2), 3, 1) = "x"
    Dim myString As String = "HellowWorld"
    Mid(myString, 6, 1) = " "
    Debug.Print "test output"
    Debug.Print myArray(2)
    Debug.Print myString
End Sub
```
![MidStatementNotWriting](https://user-images.githubusercontent.com/81257042/183665182-cf600b6b-e833-40b9-b58f-abd75182b288.jpg)

I have checked and the original string assigned to myArray(2) is being printed.
If I replace 
```
Dim myArray as Variant
```
with
```
Dim myArray() as string
```
Then the output is as expected

**Expected behavior**
The Mid statement should work on strings stored in an array of variants

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Beta IDE 90

**Comment by WaynePhillipsEA** [comment]
This was fixed in BETA 93.  Thanks
