### ISSUE TITLE
Mid statement using memmove instead of raw memcpy

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1097]
**Describe the bug**
```
    Public Sub TestMidStatement()
        Dim myString As String
        myString = "Hello" & Space$(100)
        Mid(myString, 6) = myString
        Debug.Print myString
    End Sub
```
This produces `HelloHello` in TB while in VBx it does not heed overlapped source/dest buffers and produce `HelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHelloHello` which is buggy but cute and fast way to replicate strings.

**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 87

**Comment by WaynePhillipsEA** [comment]
Nice find 👍 I'll get that fixed to match.

I'd love to know how many people are relying on that!

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 93, thanks!
