### ISSUE TITLE
VBA Loss of session and all logical sense during E&C

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/twinbasic#1098]
**Is your feature request related to a problem? Please describe.**
Can we somehow try and assure that when we get to implementing E&C for tB that the compiler WON'T "get lost" and fall into the stupid session-death-loop that VBA can get into when you DIM a new variable during E&C?
I'm referring to the "Duplicate declaration in current scope." error than can arise if you DO happen to enter a DIM statement that duplicates an existing (_local_) variable during an E&C session. In VBA (and I just got stymied in a complex debug session by this), this error can arise __incorrectly__. For one example, if that variable name had gotten "accidentally" shadow-DIM'd by first using it in the immediate pane __before__ actually going into the code and typing in the DIM statement (on a new, separate line, of course).

Of course, this little foible is most annoying when you _didn't_ actually accidentally pre-use the variable in question in the immediate window first (leaving you to wonder what the _he**_ VBA is talking about in the first dang place...can we manage to avoid _this_ too!?) (<-- this is the "loss of all logical sense" part)

When VBA gets into this issue, your debug session is fried because you're stuck between either stopping the run due to the duplicate declaration error - or the equally session-killing act of deleting the not-really-a-duplicate-at-all DIM statement line - which will also force the execution to stop.

**Describe the solution you'd like**
Have tB NOT lose its mind over an "accidental" duplicate DIM-in-scope somehow so the E&C session can still continue?
Either by throwing a smarter error message that ASKS you which variable instance you wanna keep/lose or, I dunno..._something_ better than falling into this stupid no-way-forward trap!?

**Describe alternatives you've considered**
same-old VBx same-old?

**Additional context**
I hope I described this annoyance well enough.
I'm unsure if this same situation arises in VB6, but I seem to recall having it happen there too.

**Comment by wqweto** [comment]
Yes, in VB6 this happens the same if you first write a statement with the new var and then move up the routine to dimension it. 

I always comment out the current new statement before moving out of current line so the parser does not try to add any new symbols from current statement to its local symbol table and then fail on dimension with duplicate declaration.

**Comment by mburns08109** [comment]
@wqweto 
yeah - makes sense.
Too bad that my fingers and brain aren't always operating with the same clock frequencies.
VERY annoying when this happens.

**Comment by WaynePhillipsEA** [comment]
As this is more of a VBA issue than a tB issue, I'm going to close this.  Thanks for the information though.
