### ISSUE TITLE
Issue with PANDA 360 Security

### ISSUE THREAD

**Issue by uwbwsvd** [twinbasic/twinbasic#1099]
Building a ComAddin.
Is there a possibilty on the side of TwinBasic to avoid this?:
![grafik](https://user-images.githubusercontent.com/41230018/183820495-dabdcb2d-8f85-43fd-a487-b5e69badcc44.png)
PANDA blocks the registry part.

**Comment by fafalone** [comment]
Did you try running it as administrator? Not a lot you can do in the registry without it these days.

**Comment by wqweto** [comment]
This is like running a server on your machine but the firewall is blocking inbound connections. Not a lot can be done by server authors but you can allow inbound ports on the firewall condig for the server to work properly.

**Comment by WaynePhillipsEA** [comment]
Unfortunately this is our of our control.  You'll have to configure your anti virus product appropriately to allow this behaviour.  As such, I'll close this issue.
