### ISSUE TITLE
Rounding error in integer division of LongLong

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1102]
**Describe the bug**
`A \ B` differs (correct) VBx impl for some `LongLong` variables.

The division seems to work in IDE debug console and with integer literals but fails only with variables somehow.

**To Reproduce**
```
        Dim lA As LongLong = 8209118002272571941^
        Dim lB As LongLong = 17179869184^
        Debug.Assert lA \ lB = 8209118002272571941^ \ 17179869184^
```
**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 87

**Additional context**
SHA-512 implementation in TB fails test vectors.

**Comment by WaynePhillipsEA** [comment]
Operations involving just literals get constant-folded before codegen.  It sounds like the constant-folded version is correct, and the codegen version is wrong here.  I will check and get it fixed.

**Comment by WaynePhillipsEA** [comment]
This bug only affects 32-bit builds.   Fixed in tomorrows update.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 93, thanks!
