### ISSUE TITLE
Image control does not respond to events!

### ISSUE THREAD

**Issue by Peter9Claudius** [twinbasic/twinbasic#1103]
Hello,

the image control does not react to any of the assigned events. For example, if I link the popping up of a "MsgBox" to a Click event, nothing happens. Likewise with the other events. However, if I link the click event for the "Form" with MsgBox, then the MsgBox appears as expected on mouse click. Surprisingly, the click event of the form triggers the action even if I click on the image control and not on the form. It is almost as if the image is not there. Is there a cause for this?

Thank you very much and kind regards,

Peter.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 146.  Thanks for reporting :)
