### ISSUE TITLE
DispCallFunc crash (CNamespaceWalk Demo)

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1105]
**Describe the bug**
The demo project https://www.vbforums.com/showthread.php?897328-VB6-VBA7-CNamespaceWalk-(Using-the-INamespaceWalk-interface) crashes in tB at a call to INamespace::Walk.
The demo project uses no tlb. So the crash happens in the VTableCall wrapper (DispCallFunc)

**To Reproduce**
Run demo project

**Expected behavior**
VB6 and VBA7 do run. (32 or 64 bit)
So I bet something tiny happens wrong in tB.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1111]

**Additional context**
The crash happens with or without a INamespaceWalkCB callback.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 92, thanks!

**Comment by Kr00l** [comment]
Just wanted to point out the crash below. It's not a big deal at all as it just happens when toggling between win32 and win64..
I re-open for that case. If it can't be fixed just close again.

![image](https://user-images.githubusercontent.com/33756666/185735283-5a1361ee-821d-4507-86c1-ae686b732f39.png)

So to replicate: (test.twinproj)
First open the below test project. Run it on win32 (important to run first) after that successfull run toggle to win64 (restart compiler if you want) then the error happens.
It won't happen if it get's toggled to win64 before any run before happened.
[test.zip](https://github.com/twinbasic/twinbasic/files/9386486/test.zip)

**Comment by Kr00l** [comment]
crash (toggling between win32 and win64) does not happen anymore in latest release. So close..
