### ISSUE TITLE
Old school commands lost in vbx

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1106]
Call me old school but one of the most sill things i missed always (also in Vbx) is the good old print using "+####.##" statement from the old dos basic variants. It makes creating tables, dialog and reports for an engineer a snap. And no the damn shitty FORMAT thing is not a option. :) I am mad to write own format  routines just to do the same thing i could do with a line of QBASIC. YES it might require a font supporting it. But engineers does not care bout a font as long they can read the values :) And by this - you may laugh even more - the old screen commands, print, color and locate, was also very time saving and easy to understand that days. :)

**Comment by bclothier** [comment]
I think this is a candidate for a community-developed package for building a text-based printer. I don't see a need to make it a language feature.

**Comment by FullValueRider** [comment]
This exists already (mostly)
https://codereview.stackexchange.com/questions/30817/a-csharpish-string-format-formatting-helper and https://github.com/Greedquest/VBA-Gems.

The important point for this facility would be that the language specific aspect  that twinBasic could introduce (without violating backwards compatibility), is the ability to embed variables in {} in strings.  As demonstrated by the above links, the formatting can be left to library functions.

**Comment by WaynePhillipsEA** [comment]
I agree with the above comments; this does not need to be something provided at the compiler level.  Thanks.
