### ISSUE TITLE
REXX parse

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1108]
The most missed statement from REXX which i really have learned to love was the parse statement. It separates a string by patterns and assign them to a single dimension array. So you can very easy do text parsing without hussle. Was a bit hard to find but that will give you a overview :) http://www.manmrk.net/tutorials/rexx/TCVM1/L3CH9.HTM

**Comment by mburns08109** [comment]
So, a lot like Split() does in VBx already?  or "by patterns" do you mean something more than what Split() does?

**Comment by Greedquest** [comment]
Regex capture groups do this sort of thing quite nicely? Otherwise glancing at that link it does look a bit like `Split`.

**Comment by WaynePhillipsEA** [comment]
Closing as out-of-scope.  Could be implemented in a package if necessary, but doesn't need to be a language feature.
