### ISSUE TITLE
Request for IDE - new project type: Console App

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/twinbasic#1110]
**Is your feature request related to a problem? Please describe.**
Basically I want the same features as a "standard EXE" project, but _without_ the starting Form class/object.
Just give us a Sub Main() module Window

**Describe the solution you'd like**
Console Project type added to the New project options list.

**Describe alternatives you've considered**
see above.

**Additional context**
n/a that is all.

**Comment by WaynePhillipsEA** [comment]
This is now available, as of BETA 95.  Thanks!

**Comment by fxl447098457** [comment]
but seems no fucntions for stdin/stdout,just like console.writeln/readline/read/write in .net.

**Comment by WaynePhillipsEA** [comment]
@fxl447098457 correct.  This issue was just for the template, not for any additional functionality.

**Comment by WaynePhillipsEA** [comment]
Note: The template that ships for this in BETA 95 does not have the 'Is Console Application' flag set in the settings.  This will be fixed in tomorrows update.
