### ISSUE TITLE
Implement native typedef statement

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1111]
**Is your feature request related to a problem? Please describe.**
Sometimes it hurts readability quite a bit to have such a limited selected of variable types to work with. This is improved by a feature VB (and tB) supports already, if in a typelib... for instance,
`typedef [public] long BOOL;`
is one of the aliases I've added to my oleexp typelib, since it's a lot more clear where that type of boolean is used instead of a VB boolean, and using a Long instead hurts readability. This allows having `Dim b As BOOL` in VB.

**Describe the solution you'd like**
It would be nice to have a native language keyword to do this. I believe any argument such a thing doesn't belong in BASIC isn't persuasive given that, as mentioned, VB and tB already supports this, just in a less convenient way.

While I'd be fine with just reusing the typedef keyword, perhaps as TypeDef A As B to match normal VB keyword capitalization patterns, I wonder whether something like Public Alias A As B might be friendlier, since there's already a native concept of Alias in API declares. 

**Describe alternatives you've considered**
Continuing to have to use a typelib.

**Additional context**
Scope would have to be considered; could we have Private TypeDef, and Public TypeDef, with the same scope as those statements usually imply?

**Comment by WaynePhillipsEA** [comment]
There's an open issue for this: https://github.com/twinbasic/lang-design/issues/32

I'm all for it, and it's a simple addition. Once we can agree on syntax, it can be implemented.  Thanks.

**Comment by fafalone** [comment]
Ah I searched issues and discussions here but not lang design, my bad.
