### ISSUE TITLE
Highlighting of Compiler errors can be overenthusiastic

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1114]
**Describe the bug**
The updated codegen can give rise to overenthusiastic highlighting of the error making determination of the error a bit more work than it needs to be.
The code below has a " missing just before Thing in the last underlined line.  The omission of the " means that the previous 182 lines are highlighted.

![ExcessiveErrorHighlighting](https://user-images.githubusercontent.com/81257042/185701661-807f1632-15eb-4b51-9e48-42c3dab3cea5.jpg)

**Expected behavior**
To at least limit the error highlighting to the start of the current method

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Ide beta 95

**Additional context**
For information.  I'm assuming this will go away as you continue to polish the current codegen

**Comment by WaynePhillipsEA** [comment]
This should hopefully be fixed in BETA 96, but there still may be a couple of edge cases not yet discovered that are doing similar.   Thanks for reporting.
