### ISSUE TITLE
Intellisense showing wrong list for types with enums in some circumstances

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1117]
**Describe the bug**
I noticed this when filling out LVITEM structs. The .Mask and .State members are tied to an enum, but the only time it shows the list of enum values is `.Mask = .Mask Or ...`. Other times, it shows a list of keywords I don't can't see where it got them from.

**To Reproduce**
-Have a Public Type with a member being a Public Enum in a module.
-Declare a variable of Type and attempt to fill out members.

**Expected behavior**
Intellisense should allways be populated with the enum members.

**Screenshots**
![Situation 1](https://i.imgur.com/HjZl8rq.jpg)
![Situation 2](https://i.imgur.com/lANRXGn.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.96

**Additional context**
Definitions in SS:

```
Public Enum LVITEM_mask
  LVIF_TEXT = &H1
  LVIF_IMAGE = &H2
  LVIF_PARAM = &H4
  LVIF_STATE = &H8
  LVIF_INDENT = &H10
  LVIF_GROUPID = &H100
  LVIF_COLUMNS = &H200
  LVIF_NORECOMPUTE = &H800
  LVIF_DI_SETITEM = &H1000   ' NMLVDISPINFO notification
  '6.0
  LVIF_COLFMT = &H10000
End Enum
Public Enum LVITEM_state
  LVIS_FOCUSED = &H1
  LVIS_SELECTED = &H2
  LVIS_CUT = &H4
  LVIS_DROPHILITED = &H8
  LVIS_GLOW = &H10
  LVIS_ACTIVATING = &H20
 
  LVIS_OVERLAYMASK = &HF00
  LVIS_STATEIMAGEMASK = &HF000
End Enum
Public Type LVITEM 'LVITEMW
  Mask As LVITEM_mask
  iItem As Long
  iSubItem As Long
  State As LVITEM_state
  StateMask As LVITEM_state
'remaining items omitted
End Type
```

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 99, thanks!
