### ISSUE TITLE
Repeated whitespace characters are not visible in the Variables window

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1123]
**Describe the bug**
Whitespace characters are collapsed at the start and end of strings when viewed in the 'Variable' window.

**To Reproduce**
Steps to reproduce the behaviour:
1. Declare a string variable as "&nbsp; &nbsp; &nbsp; &nbsp; Hello World&nbsp; &nbsp; &nbsp; &nbsp; "
2. View the variable in the 'Variables' window
3. The displayed value is " Hello World ".  
4. The behaviour of the variable is as "&nbsp; &nbsp; &nbsp; &nbsp; Hello World&nbsp; &nbsp; &nbsp; &nbsp; "

This is slightly confusing from a debugging perspective.

**Expected behaviour**
The variables window should show the exact content of strings.

**Screenshots**
![CollapsedWhitespace](https://user-images.githubusercontent.com/81257042/186479017-b4646266-519c-44b1-ad40-102a24a021f5.jpg)

**Desktop (please complete the following information):**
 - OS: Windows11
 - twinBASIC compiler version Ide Beta 97

**Additional context**
Not an urgent issue for me.

**Comment by FullValueRider** [comment]
OK, now with nbsp; to mark individual spaces !£@!!! Markdown.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 99, thanks!
