### ISSUE TITLE
Error highlight over procedure name hard to read

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1125]
**Describe the bug**
In the default light mode, the error highlight on a procedure name (`GetScheduleType`) is very hard to read:

![image](https://user-images.githubusercontent.com/18285074/186664220-0054dfe8-b063-49ff-80c9-c525114a9b6b.png)

But in dark mode its OK:

![image](https://user-images.githubusercontent.com/18285074/186664116-8bafa0e6-51b9-40e7-92bf-881735d746a1.png)

At least on my monitor the first was very hard to make out.

**To Reproduce**
I loaded a VB6 VBP and clicked on one of the errors in the "problems list"

**Expected behavior**
Better contrast

**Desktop (please complete the following information):**
 - OS: Win10
 - tB beta 99

**Comment by WaynePhillipsEA** [comment]
This has been tweaked in BETA 101.  If you think it's still an issue, please just let me know.

**Comment by DaveInCaz** [comment]
Just looked in beta 103, and the contrast is much improved. It looks good in both dark + light. Seems like the approach was to not use the colorized text in this case, but IMO readability is important enough this is worth it.
