### ISSUE TITLE
ALT+TAB engages the default IDE menu

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1126]
**Describe the bug**
Have the tB IDE in the foreground / active.
Press ALT+TAB which on Windows lets you switch to other applications.
The tB File menu opens and the tB screen dims -- this is not standard behavior.

**Expected behavior**
Other than "lost focus" type events normally the foreground program doesn't react to ALT+TAB at all.

**Desktop (please complete the following information):**
 - Win10
 - tB beta 99

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 101, thanks for reporting.

**Comment by DaveInCaz** [comment]
Confirmed fixed in beta 103. Thanks!
