### ISSUE TITLE
API declares with ByVal <locally defined interface> can't be validated

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1128]
**Describe the bug**
In my [VB6 DragDrop project](https://www.vbforums.com/showthread.php?808125-VB6-Register-any-control-as-a-drop-target-that-shows-the-Explorer-drag-image), I use:
`Private Declare Function RegisterDragDrop Lib "ole32" (ByVal hwnd As Long, ByVal DropTarget As IDropTarget) As Long`

Where IDropTarget is in a TLB. In twinBASIC I'm trying to use a locally defined interface, fully qualified with project name because WinNativeForms exposes it's own version I can't implement,
`Private Declare PtrSafe Function RegisterDragDrop Lib "ole32" (ByVal hwnd As LongPtr, ByVal DropTarget As DragDropDemo.IDropTarget) As Long`

This produces the error 'validation of call to RegisterDragDrop failed. Argument for 'DropTarget' cannot coerce type 'Long' to '_IDropTarget'

**To Reproduce**
Project attached.

**Expected behavior**
This is allowed VB6 syntax and this is a finnicky API that doesn't work with the normal ByRef, and I get a runtime error trying ByVal LongPtr with ObjPtr instead.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.99
 - 
**Additional context**
I thought locally defined interfaces would be a solution to my midl nightmare but this is proving equally problematic with things like this and the conflicts with built-in versions (issue #1082 applies to interfaces as well). 
[DragDropProject.zip](https://github.com/twinbasic/twinbasic/files/9425684/DragDropProject.zip)

**Comment by WaynePhillipsEA** [comment]
Unless I'm missing something, this looks correct to me.   

```
If RegisterDragDrop(m_hWnd, ObjPtr(Me)) = DRAGDROP_E_ALREADYREGISTERED Then
```
`ObjPtr` returns a `LongPtr` (so `Long` on x86), therefore you can't pass that to your `RegisterDragDrop` `DropTarget` argument that is defined as `IDropTarget`.
