### ISSUE TITLE
 IsNumeric wrong from variant

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1129]
**Describe the bug**
 IsNumeric() should be true not false in the example.

**To Reproduce**
1.
```
Sub main()

Debug.? "Correct", IsNumeric("0")

Dim ObjData As String

Dim i As Integer

ObjData = vbNullString
For i = 0 To 16
ObjData = ObjData & "0" & vbTab
Next
ObjData = ObjData & "0"

    Dim v2 As Variant
    v2 = Split(ObjData, vbTab)
    
'Debug.? ObjData

Debug.? "v2:" ; UBound(v2)

    If UBound(v2) <> 17 Then Exit Sub

Debug.? "v2(0): >" ; v2(0) ; "<"
Debug.? "IsNumeric(v2(0)): ", IsNumeric(v2(0))

Dim m As String
m = v2(0)
Debug.? "IsNumeric(m): ", IsNumeric(m)

End Sub

```
2. Run and read debug output.

**Expected behavior**
Correct result

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC 99

**Additional context**
Came up on my other large AX project.
Edit: Must be a regression, in earlier tB's it was ok.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 101, thanks for reporting.
