### ISSUE TITLE
Can you add support for SKIA by Google?

### ISSUE THREAD

**Issue by yogeshvachhani** [twinbasic/twinbasic#1132]
Recently Google has released a powerful graphic library called SKIA. https://skia.org/

It is cross platform and it is also works in Android and iOS.

Would it be possible to add support for SKIA.

I feel in the long run it will be helpful at every level as well for loading and handling SGV graphics.

Do check it out and if you feel interested please integrate it into tB.

One way to integrate it on Windows is to build a DLL. A few developers have already build DLL and released under MIT license. https://github.com/skia4delphi/skia4delphi

Please do check its documentation also. https://skia.org/docs/user/modules/skottie/

**Comment by mburns08109** [comment]
as an add-on library, perhaps? I could see that, but as an intrinsic form engine...? mmmnope.

**Comment by WaynePhillipsEA** [comment]
I'm going to close this as out-of-scope.  Could be a community based package, but unlikely to be a native language feature.  Thanks
