### ISSUE TITLE
FOR EACH destroys loop-object on exit

### ISSUE THREAD

**Issue by AntsAntix** [twinbasic/twinbasic#1133]
**Describe the bug**
tB statement For Each seems to destroy the loop-object much the way C++ and C# do on Exit from the loop 

**To Reproduce**
This type of code:
```
  Dim select    As CElement
  ...
  For Each select In Elements
    If StrComp(select.Tag, "requiredtag") = 0 Then Exit For  
  Next
  ...
```
After Exit For, the value of _select_ is Nothing, regardless of whether it exited via Exit For or not.

**Expected behavior**
That the value of a variable declared in the Dim statement will persist after leaving the For-loop 

**Screenshots**
![image](https://user-images.githubusercontent.com/89644755/187215982-5f7980db-f275-4e29-a82b-4182c9fe6813.png)

![image](https://user-images.githubusercontent.com/89644755/187216212-f4d83bca-4e99-4fb8-b0b2-113149eeb22d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version BETA-99 and later

**Additional context**

**Comment by mburns08109** [comment]
> That the value of a variable declared in the Dim statement will persist after leaving the For-loop

Yup and that IS a backwards-compatibility issue! I have relied on that behavior many times.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 103, thanks for reporting!
