### ISSUE TITLE
Different behavior of CByte in TwinBasic VS VBA

### ISSUE THREAD

**Issue by francescofoti** [twinbasic/twinbasic#1134]
TwinBasic: CByte(True) --> overflow
VBA: CByte(True) --> 255

**To Reproduce**
1. Go to the debug window (CTRL+G)
2. Type: ?CByte(True)
3. See error

**Expected behavior**
Should yield 255 as in VBA.

**Screenshots**
![image](https://user-images.githubusercontent.com/6288870/187396179-3705e68e-4258-4c38-88b1-fa964f1edb16.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler BETA 102

**Comment by WaynePhillipsEA** [comment]
Thanks!  Annoyingly this was covered by tests, but a group of tests had been left disabled at some point, and this was in that group.  Fixed in tomorrows update.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 104, thanks!
