### ISSUE TITLE
Duplicate 'datatype has not been explicitly declared..' errors for the same line

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1135]
**Describe the bug**
I brought in some VB6 code which included this:

`Public Function Exists(ByVal sIdentifier) As Boolean`

which causes a "datatype has not been explicitly declared so will default to Variant" error (fine in itself).

But for some reason that error is listed twice:

![image](https://user-images.githubusercontent.com/18285074/187455877-642029f2-7e6f-4a0e-9f77-1b910bdc3f02.png)

It shows up this way in the PROBLEMS pane also.

**Expected behavior**
It should only be shown once.

**Desktop (please complete the following information):**
 - OS: Win10
 - twinBASIC compiler version beta 103

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 116, thanks!
