### ISSUE TITLE
Close tabs using standard hotkeys

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1136]
**Is your feature request related to a problem? Please describe.**
While in the tB IDE (beta 103) I had several tabs of source files open.

It seems that neither CTRL+F4 nor CTRL+W will close the current focused tab. The former switches to/from full screen (unexpectedly) while the latter doesn't do anything.

I'm used to F11 being used for fullscreen (from Chrome maybe?) but I'm not sure how standard that is.

**Describe the solution you'd like**
Use these keystrokes in the standard/expected ways (per OS, I guess).

**Describe alternatives you've considered**
Clicking the X on the tab works, but is slow.

**Comment by WaynePhillipsEA** [comment]
CTRL+F4 and CTRL+W now close the active tab as of BETA 104.  Thanks!
