### ISSUE TITLE
First time opening a file from the PROBLEMS pane - file is blank

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1137]
**Describe the bug**
I opened a VB6 VBP in tB and of course it generated a bunch of errors (as expected).

After that, from the PROBLEMS pane it seems that for **most** files, double clicking on an error will create a tab for the file but will show nothing in the contents of the tab:

![image](https://user-images.githubusercontent.com/18285074/187457380-3aeb98ad-b5b1-4e89-a96e-11f4a88cf3ba.png)

At first I thought it was just being slow. But I think its more of a refresh issue. Switching to/from another tab and then back will show the tab's contents immediately.

These files are on the large side ... 3000+ lines.

**Desktop (please complete the following information):**
 - OS: Win10
 - twinBASIC compiler version beta 103

**Comment by WaynePhillipsEA** [comment]
Not seen any recent reports of this, so let's close.  Thanks
