### ISSUE TITLE
Crash with codejock activex tabcontrolpage inside of tabcontrol

### ISSUE THREAD

**Issue by wopag** [twinbasic/twinbasic#1139]
Adding a codejock tab control causes crash(registered 15.1.2)

Add a TABcontrol  - runs fine
Add a tabcontrolpage - runs fine

Move tabcontrolpage into TABCONTROL  (so tabcontrol become a container)  -   crash  - error below 

    Public Property Get Ambient_BackColor() As OLE_COLOR
        Log("Ambient_BackColor")
        Return Me.RootWindowElement.Container.BackColor
^^^^^ Run-time error -2147352570 (80020006)    - Description  Unknown Name.
    End Property

Even removing the tabcontrolpage from the screen - still crashes - add any control into the tabcontrol and it crashes.  Have to restart 
 TB to clear the error

**Comment by WaynePhillipsEA** [comment]
Couldn't reproduce the problem with v23 of the CodeJock controls.  However, I've added some error handling around the Ambient properties that will hopefully fix this for you.  Please try BETA 104 and let me know if that's fixed it for you.

**Comment by rboeckka** [comment]
I made the test with v13.4 of Xtreme Suite Controls; here it worked without crash.

**Comment by WaynePhillipsEA** [comment]
@rboeckka thanks!  Would you mind just confirming if prior versions of tB (e.g. BETA 103) did have the same problem for you?  If it did, I will then close this issue.   Thanks!

**Comment by rboeckka** [comment]
My older version of tB is 102; here i could not reproduce the problem of wopag.

**Comment by wopag** [comment]
Tested with 107,    now working !!!!!
