### ISSUE TITLE
Save fails if folder is moved/deleted while open; goes into infinite retry loop

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1140]
**Describe the bug**
If the folder the .twin file that's open is moved/deleted,  save will fail and it will go into a loop retrying.... well I'm still watching it and it's up past 200 times so I don't think it's stopping. 

**To Reproduce**
-Open project
-Move/delete folder .twin file is in
-Try to save

**Expected behavior**
This should be handled more gracefully. Ideally IMO bring up a box asking if the user wants to retry or to bring up a 'Save As...' dialog, but at least giving a one time error rather than trying over and over in an infinite loop (if try 2 fails, try 200 is certainly going to fail too). 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.103

**Additional context**
When this first happened accidentally, it had a popup that locked the IDE 'Please wait...'

I was able to reproduce the infinite retry loop, but this time the IDE remained responsive and I could continue typing, and eventually restarting the compiler ended the loop without exiting/killing the process, but there is some circumstance where this doesn't happen.

**Comment by WaynePhillipsEA** [comment]
I'm not currently able to reproduce this.  I created a new Standard EXE project, created a new folder and created a twin file inside it, and then tried renaming the folder under different conditions. 

When the twin file is open but not dirty, the twin file gets closed upon renaming the folder.   When the twin file is open and dirty, the rename fails and a modal error message informs you of the problem.

**Comment by fafalone** [comment]
What does dirty mean? I open the IDE, open an existing project, start editing it, and if the folder containing the .twin is gone, it goes into the below loop.

I can reliably reproduce it every time (the infinite loop at least, haven't figured out how to get 'Please wait...' back)

```
[PROJECT] twinBASIC project saving to disk...
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT]   -- errorCode: 3
[PROJECT]   -- file:      C:\tbproj\RamdiskDriver\rdDriver.twinproj
[PROJECT]   -- detail:    The system cannot find the path specified.
[PROJECT] twinBASIC project saving to disk... [RETRY 1]
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT] twinBASIC project saving to disk... [RETRY 2]
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT] twinBASIC project saving to disk... [RETRY 3]
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT] twinBASIC project saving to disk... [RETRY 4]
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT] twinBASIC project saving to disk... [RETRY 5]
[PROJECT] twinBASIC project saving to disk [FAILED]
[PROJECT] twinBASIC project saving to disk... [RETRY 6]
```

**Comment by WaynePhillipsEA** [comment]
> What does dirty mean? 
Just that there are unsaved changes.

Thanks for the extra info, I'll try to get this fixed in tomorrows update.

**Comment by WaynePhillipsEA** [comment]
> If the folder the .twin file that's open is moved/deleted, save will fail and it will go into a loop retrying.... 

It seems the misunderstanding here was that you meant the '.twinproj' file here, right?   When trying to reproduce the problem, I was trying to rename the _virtual folder_ inside the project file explorer (i.e. where the 'twin' source file resides), not the actual real folder where the project 'twinproj' file resides.  With that now cleared up, I can reproduce the problem, thanks.

**Comment by fafalone** [comment]
Oh sorry, yeah I meant the folder on the hard drive containing the .twinproj file.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 106.  Thanks for reporting!
