### ISSUE TITLE
Magic tabs

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1141]
**Describe the bug**
It looks random how a tab is opened and closed from clicking in the project explorer.
Or I don't understand it.

**To Reproduce**
1. Load a project.
2. Click in the project explorer.
3. Watch the tabs.

**Expected behavior**
No voodoo tabs.

**Screenshots**
https://user-images.githubusercontent.com/88059532/187865848-73b7810b-0a7c-4cf6-b9c5-2507a1fce57b.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 GERMAN
 - twinBASIC 104

**Additional context**
Thanks for CTRL+Tab and CTRL+F4.

**Comment by WaynePhillipsEA** [comment]
This behaviour is copied from VS Code.   Single click opens a file in preview mode.  Only one tab can be open in preview mode, so single-clicking on another file will close the last 'preview' tab before opening the new preview tab.   A tab opened in preview mode will have its caption in the tab in italic font.

If you edit a file that is opened in preview mode, it will be promoted to a normal tab (you will see the italic font removed).  

Double-clicking on a file in the explorer will instead open the tab as a normal (non-preview) tab.

You can change this behaviour in the IDE options > `File Explorer: Single-Click Preview` ... turn it off to not use the preview feature.

**Comment by mwolfe02** [comment]
> Then it's easy to understand und no need to be adjustable.

Unless you are coming from the VS Code universe and then it's different behavior.  I believe full-blown Visual Studio uses this file preview feature by default, too.

One idea for a post-v1.0 release would be to add support for two or more "IDE modes".  These would basically be some predefined settings for shortcut keys, File Explorer behavior, IntelliSense behavior, etc. that would mimic other popular IDEs, such as: the legacy VB6 IDE, VS Code, etc.
