### ISSUE TITLE
TreeView nodes can't expand - "Unable to find DLL entry point"

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1146]
**Describe the bug**
```
    Public Function IsKeyPressed(ByVal KeyCode As KeyCodeConstants) As Boolean
        Return USER32_GetAsyncKeyState(KeyCode) And &H8000&
    End Function
```
In TreeViewConsts.twin throws Run-time error -353703418 (EAEAEA06) - Unable to find DLL entry point when clicking an expando button.

**To Reproduce**
Add TreeView, leave all defaults
```
    Private Sub Form_Load() Handles Form.Load
        Dim hNode As Node
        Set hNode = TreeView1.Nodes.Add(, , , "Node1")
        TreeView1.Nodes.Add hNode, tvwChild, , "ChildNode1"
        TreeView1.Nodes.Add hNode, tvwChild, , "ChildNode2"
        TreeView1.Nodes.Add hNode, tvwChild, , "ChildNode3"
    End Sub
```
Run, click expando.

**Expected behavior**
No error here.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.110
 
**Additional context**

**Comment by fafalone** [comment]
Note: Only effects x86. Nodes expand as expected on x64.

**Comment by WaynePhillipsEA** [comment]
Well, that was a silly one!  Fixed in BETA 111, thanks for reporting!
