### ISSUE TITLE
Combobox black

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1148]
**Describe the bug**
When click happens on the combobox, the dropdown list appears black. and if you move the mouse over it , then the items appear.

**To Reproduce**
1. Go over a combobox
2. Click on it
3. See error
4. move mouse over the dropdown list to show items

**Expected behavior**
When clicking on a combobox, the dropdown list should appear normally and show the visible items.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version [ 0.15.112]

![combo1](https://user-images.githubusercontent.com/113173954/189317866-b546ed3c-ae2d-4a09-9db9-2bff44f003b0.png)
![combo2](https://user-images.githubusercontent.com/113173954/189317875-843d04c2-8fe5-463a-8924-8a6373f356ed.png)
![2022-09-10_16-20-52](https://user-images.githubusercontent.com/113173954/189485359-266410df-df6f-4ae2-b516-bb620c3baf16.gif)

**Comment by WaynePhillipsEA** [comment]
I don't seem to be able to reproduce this problem here (on Windows 10 also).

**Comment by fafalone** [comment]
It's black for me too; both x86 and x64, both if items added at runtime and design time.

**Comment by WaynePhillipsEA** [comment]
Thanks - I will try a few other systems to see if I can repro

**Comment by sokinkeso** [comment]
> I don't seem to be able to reproduce this problem here (on Windows 10 also).

Hi, I 've added a gif animation with the problem.
I have tested on 2 different machines (with windows 10 x64) and on a VMware virtual machine with windows 10 x64,
and I had the same problem on all of them.

**Comment by WaynePhillipsEA** [comment]
Ah I bet this doesn't repro for me because I have animations turned off when I log in to my machines via RDP.

**Comment by WaynePhillipsEA** [comment]
Yes, that was it.  If I login via RDP with the 'menu and window animation' setting ON, I do now see the black dropdown.

**Comment by sokinkeso** [comment]
> Yes, that was it. If I login via RDP with the 'menu and window animation' setting ON, I do now see the black dropdown.

Nice. If you need anything else from me, that will help you, please contact me.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 117, thanks for reporting it!
