### ISSUE TITLE
TreeView add Error

### ISSUE THREAD

**Issue by uwbwsvd** [twinbasic/twinbasic#1152]
Who is wrong?
I or TwinBasic?
![grafik](https://user-images.githubusercontent.com/41230018/189492532-72a73adc-9842-418e-8620-495149b77d32.png)

**Comment by WaynePhillipsEA** [comment]
We can't tell from the screenshot.  We need to see what is happening earlier.   As you are passing 5 for the relative, that will be treated as an index into the collection, so as long as you've added 5 items to the treeview before that call, it should work.

**Comment by wqweto** [comment]
Worst king of issue reports. 

Is this some kind of riddle we should marvel?

**Comment by uwbwsvd** [comment]
Here is projektfile. The error occurs not every time you run it. Don't have the power to find it out, what is wrong.
Run the form, press "Button".
[testlist.zip](https://github.com/twinbasic/twinbasic/files/9541787/testlist.zip)
![grafik](https://user-images.githubusercontent.com/41230018/189512985-d3137e95-09d8-49c3-a3c2-12b5c7324786.png)

**Comment by WaynePhillipsEA** [comment]
Here is the full relevant snippet that we need to see:
```
        TreeView1.Nodes.Add , , "town", "town"
        'Streets of the town
        TreeView1.Nodes.Add "town", tvwChild, "s1", "First Street"
        TreeView1.Nodes.Add "town", tvwChild, "s2", "Second Street"
        TreeView1.Nodes.Add "town", tvwChild, "s3", "Third Street"
        
        'Houses of the streets
        'First Street
        TreeView1.Nodes.Add 5, , "s1h1", "1First house"
        TreeView1.Nodes.Add 6, , "s1h2", "1Second house"
        TreeView1.Nodes.Add 7, , "s1h3", "1Third house"
```

As you can see, you've only added 4 nodes prior to the "1First house" node, and so passing an index of 5 for the relative is most definitely wrong.  This is not a problem of tB.  An error would occur here in the MSCOMCTL version of the treeview.

BTW, I would generally advise passing around Node objects instead of using indices for the relationships.  Something like this:
```
Dim town As Node = TreeView1.Nodes.Add( , tvwFirst, , "town")
Dim firstStreet As Node = TreeView1.Nodes.Add(town, tvwChild, , "First Street")
TreeView1.Nodes.Add(firstStreet, tvwChild, , "First house")
TreeView1.Nodes.Add(firstStreet, tvwChild, , "Second house")
TreeView1.Nodes.Add(firstStreet, tvwChild, , "Third house")
```

**Comment by fafalone** [comment]
VB6 gives a much more helpful "index out of bounds" error. It's best to try the code there first; if it doesn't work in VB either it's not a tB problem.

**Comment by WaynePhillipsEA** [comment]
Just FYI, at the end of the month, I'm hoping to go through all the UI controls and improve the error handling to match VB6 as close as possible.
