### ISSUE TITLE
MousePointer property not working

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1158]
**Describe the bug**
MousePointer property is not working on any control.

**To Reproduce**
Change the MousePointer property value from default to any other value from the drop-down menu.
run your app, and hover the mouse over the control with the MousePointer changed property.

**Expected behavior**
The Mouse pointer should change according to the selected value.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC BETA 120

![20220915_154445](https://user-images.githubusercontent.com/113173954/190407541-8a399d6a-742e-4279-8702-cb664727cd5a.gif)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 122, thanks!
