### ISSUE TITLE
Single constant missing causes hundreds of unrelated errors

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1159]
**Describe the bug**
I was fixing renamed constants after the update fixing and came across a bug where a single constant being undefined resulted in hundreds of 'error occurred in evaluating constant expression' errors-- none of them involving the missing constant.

**To Reproduce**
I've tried to reproduce this in a simpler project without success. But it's very easy to reproduce in an existing project of mine:

-Grab latest version of TBEventTrace [from here](https://github.com/fafalone/EventTrace/blob/main/twinBASIC/TBEventTrace.twinproj).

-Open project, open modSubclass.twin

-Comment out the first constant (on line 2), `Public Const BCM_FIRST = &H1600`

**Expected behavior**
Only errors involving the undefined constant.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.121

**Additional context**
Hovering over the constants producing the error shows their value, so it seems one part of the program is seeing them but another is not.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 122, thanks!
