### ISSUE TITLE
ReleaseCapture+WM_NCLBUTTONDOWN, HTCAPTION does not work on PictureBox

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1160]
**Describe the bug**
I use the following code to create mini-dialogs with PictureBoxes in VB6:

```
    Private Sub Picture1_MouseMove(Button As Integer, Shift As Integer, X As Single, Y As Single) Handles pbOptions.MouseMove
        If Button = 1 Then
            Call ReleaseCapture
            Call SendMessage(Picture1.hWnd, WM_NCLBUTTONDOWN, HTCAPTION, 0&)
        End If
    End Sub
```

This allows a control to be dragged around the form. While this works with the Frame control in tB, when I replaced the frame I had substituted for a PictureBox with the new PictureBox control, it did not work with that.

**To Reproduce**

Demonstration project attached. 

Or,

-New Standard EXE

-Add PictureBox (change BackColor for visibility), add Frame for comparison

-Add the following code,

```
Private Declare PtrSafe Function SendMessage Lib "user32" Alias "SendMessageA" (ByVal hWnd As LongPtr, ByVal wMsg As Long, ByVal wParam As LongPtr, lParam As Any) As LongPtr
Private Declare PtrSafe Function ReleaseCapture Lib "user32" () As Long
Private Const WM_NCLBUTTONDOWN = &HA1
Private Const HTCAPTION = 2

    Private Sub Picture1_MouseMove(Button As Integer, Shift As Integer, X As Single, Y As Single) Handles Picture1.MouseMove
        If Button = 1 Then
            Call ReleaseCapture
            Call SendMessage(Picture1.hWnd, WM_NCLBUTTONDOWN, HTCAPTION, 0&)
        End If
    End Sub
    
    Private Sub Frame1_MouseMove(Button As Integer, Shift As Integer, X As Single, Y As Single) Handles Frame1.MouseMove
        If Button = 1 Then
            Call ReleaseCapture
            Call SendMessage(Frame1.hWnd, WM_NCLBUTTONDOWN, HTCAPTION, 0&)
        End If
    End Sub
```

-Run. Drag Frame. Drag PictureBox. Former works, latter does not.

**Expected behavior**
This works in VB6 so should work in tB.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.121

**Additional context**
[CaptureTest.zip](https://github.com/twinbasic/twinbasic/files/9577799/CaptureTest.zip)

**Comment by fafalone** [comment]
Ironically I just checked VB6 and this does not work on a Frame at all.

Should this be considered a bug? Or just an extra feature? I'm not sure.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 122, thanks for reporting.    

FYI, I wouldn't rely on this feature working for Frames, as that will likely stop working as the implementations get closer to their VB6 counterparts.
