### ISSUE TITLE
controls do not capture the mouse while mouse button is pressed

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1162]
In VB6, when you press a mouse button on a control  or form, this happens:
   1) mouse button down
   2) ctrl_mouse_down event fires
   3) control gets mouse capture
   4) moving the mouse around (with the mouse button pressed) EVEN OUTSIDE of the control, ctrl_mouse_move event fires
   5) releasing the mouse button EVEN OUTSIDE of the control,   ctrl_mouse_up event fires
   6) mouse capture release from the control

In TwinBasic, I think that the control does not get the mouse capture,  so the above sequence cannot happen.

I have  a sample project in which you can move a picturebox with the mouse, and in tB if you move the mouse jerkily and the mouse pointer gets out of the control, the control stops moving.
In VB6 the control does not stop moving.
   
[test_move_ctrl.zip](https://github.com/twinbasic/twinbasic/files/9579502/test_move_ctrl.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 123, thanks!
