### ISSUE TITLE
"Open VB6 project" menu item

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1163]
**Describe the solution you'd like**

The FILE menu in the IDE should get a new item "OPEN VB6 PROJECT", which opens VB6 project directly. Practically the same function which is now in the NEW PROJECT -> IMPORT FROM VB6 -> files page, but it would be faster and easier, when you change  beetween VB6 projects.

(Now then Open Poject menu item doesnt load VB6, gives ERROR_BAD_FILE_FORMAT error)

**Comment by DinyaZ** [comment]
(Beta124)

Thank you! :)

**Comment by WaynePhillipsEA** [comment]
Oh yes, I forgot to reference this issue in the release notes.  I assume the new support for this within the existing Open Project menu option is an acceptable solution, so I'll close this.  Thanks 👍
