### ISSUE TITLE
Unsupported document 'Form1.frm' type 'Form' message, error

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1164]
**Describe the bug**

First of all, I want to thank you for your really fantastic work with TWB development! :)
-
When will TWB be able to import .frm files from VB6 project? I tried to test today, to load in a very simple VB6 project with only one form, which contains 2 labels, a timer, a commandbutton, and some simple code.
The result now in TWB, the items in Project explorer are empty, and the import log is:

"Import from Visual Basic VBP file 'C:\MEDICOMP\Visszaszamol\Project1.vbp'...
   successfully set project.buildType to 'Standard EXE' at line #1
   ***FAILED*** unsupported document 'Form1.frm' type 'Form' at line #2
   successfully added project.reference 'OLE Automation' at line #3
   successfully set project.name to 'Visszaszamol' at line #8
   successfully set project.versionMajor to '1' at line #11
   successfully set project.versionMinor to '0' at line #12
   successfully set project.versionRevision to '0' at line #13
   successfully set project.versionCompanyName to 'Medi-Comp 2D Kft.' at line #16
IMPORT FINISHED WITH 1 ERRORS/WARNINGS

![Image1222](https://user-images.githubusercontent.com/94013032/190846466-fbd4de5a-2fc5-4333-9e83-5742791a9781.jpg)

![Image12221](https://user-images.githubusercontent.com/94013032/190846616-1bcf348e-9491-4092-9260-daa3146f4f16.jpg)

**Desktop (please complete the following information):**
 - OS: Win7 64bit
 - twinBASIC compiler version beta122

**Comment by WaynePhillipsEA** [comment]
Thanks.  See my comments [here](https://github.com/twinbasic/twinbasic/issues/938#issuecomment-1242929623).  Although the PictureBox work went a little over time, importing of VB6 forms is literally next on the list, and should be available early next week.

**Comment by fafalone** [comment]
Forms importing added shortly after last comment in 2022.
