### ISSUE TITLE
IDE tabs issue

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1175]
**Describe the bug**
Tabs in IDE do not open correctly
- with single click on a project explorer element, if no tab is open then it opens. if tab is open, its contents replaced with the new element clicked
- with double click , if tab is open, its contents replaced with the new element clicked,  but with the next single click new tab is opened.
- there is also a weird behavior while clicking and double-clicking in which an open tab closes while selecting a new one to open

**To Reproduce**
Add two-three forms in a new project and try to open each form or it's code panel

**Expected behavior**
When clicking on an element in Project Explorer panel, if it's not open it will open. If it's already open it must get the focus
normally , the same behavior should have the double-click, but an alternative would be to use it for closing the tabs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [beta 123]

**Comment by KarlSevenSeven** [comment]
See here:
https://github.com/twinbasic/twinbasic/issues/1141#issuecomment-1233953877

**Comment by sokinkeso** [comment]
> See here: [#1141 (comment)](https://github.com/twinbasic/twinbasic/issues/1141#issuecomment-1233953877)

Thank you for your comment. I haven't seen that post.

**Comment by KarlSevenSeven** [comment]
For me it's strange as well.
IMO the option should be OFF by default.

**Comment by sokinkeso** [comment]
I'm ok with the option "File-explorer: single click preview", so I'm closing this issue..
