### ISSUE TITLE
.ActiveControl is missing (Me and Form1)

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#1179]
![Me_ActiveControl](https://user-images.githubusercontent.com/33807881/191427615-f464c016-d721-421a-9691-1b5673a4ba89.jpg)

![Form1_ActiveControl](https://user-images.githubusercontent.com/33807881/191427634-8a45afa5-37df-43fa-9e25-93b70b829673.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version BETA 123

**Comment by WaynePhillipsEA** [comment]
Thanks @camomille22003 .   To try to keep down the individual reports of missing properties & methods in the UI controls, I've opened #1188.  Therefore I'm now closing this issue.  Thanks!
