### ISSUE TITLE
Strange Array declaration allowed.

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1180]
Its a bit a question if bug or feature :)
....
Private Sub DHPSRT(ByVal k As Long, ByVal N As Long, ByVal LDA As Long, a As Double(), ByRef MAP As Long())
'-----------------------------------------------------------------------------------------------^ 
...

In Twinbasic it seems to be allowed to have "a AS DOUBLE()  Declaration
VB6/VBA do not enjoy it.

For backward comatibility i would prefer to just allow the VB6 syntax.
Or at least mark it somehow or add some kinmd of STRICT switch.
I just generated it by a search and replace action. 

![image](https://user-images.githubusercontent.com/22050310/191531251-8e94132c-c3a0-464c-a0aa-5d60e4842995.png)

**Comment by mansellan** [comment]
Caveat: I'm not sure of the specific cause of this particular issue,

But in general terms, the removal of artificial restrictions in twinBASIC is expected, and to be encouraged insofar as it doesn't compromise any design guidelines.

This sounds like a forwards-compatibility item - something that wouldn't compile in VBx but can compile in twinBASIC. There's no prohibition to that, and indeed plenty of legal twinBASIC code will not compile in either VB6 or VBA. The non-negotiable is backwards-compatibility; that all intrinsic VBx code must compile and function as previously in twinBASIC, and anything that doesn't is a bug.

There's a suggestion to implement an Option Legacy directive, which would limit in-scope code to only the VBx subset and disallow anything new. Option Strict is a little different, in that it would disallow bad coding practice like default-to-Variant and default member dereferencing.

**Comment by fafalone** [comment]
Not an issue.
