### ISSUE TITLE
Label - BackStyle parameter is missing

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1182]
First of all, Beta124 is a very good step forward again, thank you for your work, Wayne!
Now I could load my little demo app with form and code, and it seems to be working mainly.
.
A bug report, or is it a feature request? The Label control in VB6 has a useful feature, the BackStyle, which is missing in TWB. 
BackStyle can be:
0 - Transparent
1 - Opaque

(By the way, another missing feature with all TWB controls: ToolTipText)

**Comment by WaynePhillipsEA** [comment]
Thanks @DinyaZ.   To try to keep down the individual reports of missing properties & methods in the UI controls, I've opened #1188.  Therefore I'm now closing this issue.  Thanks!
