### ISSUE TITLE
Controls do not inherit Form font

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1189]
**Describe the bug**
I noticed this when importing forms... The Form Font properties are not listed as unimplemented (and I think they were, for Print?) and it correctly lists the values from VB, but these are not applied to controls that do not have their own Font properties defined.

I checked and also noted that in a new tB project, if you change the Form font, it is also not inherited by new controls. 

**To Reproduce**
Import form from VB with a default font used for controls different from tB's default font, or change a tB Form font then add controls.

**Expected behavior**
Controls should be presumed to inherit the parent Form font in imports, and new controls definitely should inherit. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.125
 - 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Guess what was already at the top of my list to sort out next week? 😉

Thanks for creating the issue, this will be resolved v. soon

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 156, thanks!
