### ISSUE TITLE
Control array error

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1190]
**Describe the bug**
Today I have tested TWB with a more complex VB6 app, and find a few issues. The first is the control arrays, for example Label1(0), Label1(1) gives error message, TWB thinks that they are duplicated definitions. 

![Image3wsws](https://user-images.githubusercontent.com/94013032/192034443-3c5aa281-d78b-4ef7-b234-c60bab79c2d1.jpg)

(Another issue: 
- when TWB loads in a form, which have controls in front of or behind each other, the TWB cant keep the original arrangement. With "bring to front", "Send to back" I can rearrange them, but it would be better to be able to load in the original setting.)

**Comment by WaynePhillipsEA** [comment]
Control arrays are not yet supported in tB, see #909.   Support for them is coming next week.  The import actually handles them correctly, it is the lack of support for control arrays in the tB engine that causes the problem.

The Z-ordering issue is also known, and will be fixed early next week.  I don't think there's an open issue for that one.  Thanks!
