### ISSUE TITLE
"Invalid Picture" error if Picture property is not set in an "Image" control

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1191]
**Describe the bug**
If we add an "Image" control and do not define the picture property on it, an "Invalid Picture" runtime error will occur in the HandleCreate() sub of Image.twin.

**To Reproduce**
1. Open a new standar EXE project
2. Add an Image control to the Form1
3. Run the program

**Expected behavior**
A normal execution without errors.

**Desktop:**
 - OS: Windows 10 Pro 21H2
 - twinBASIC BETA 126 (this problem also happens with previous versions)

I suppose that it would be necessary to check that there is picture data before LoadPicture.
I would like to congratulate and encourage the whole team for the great work!

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 127, thanks!.  

> I would like to congratulate and encourage the whole team for the great work!

Thanks for your support :)
