### ISSUE TITLE
Transparent Frame, Listbox

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1193]
Easier to show the problem. The same form in Vb6 and with TWB :

![screen orig01](https://user-images.githubusercontent.com/94013032/192099380-349a0465-1d7a-410d-8202-e10de674557a.jpg)

![screen twb01](https://user-images.githubusercontent.com/94013032/192099384-abcb142b-82eb-4c28-85ca-9aa5c67c86b2.jpg)

You see, that the frames, and listboxes in TWB bacame transparent, which is very confusing.

(By the ways the the "dots" on the forms background in TWB are perhaps too big. Much smaller dots and with a lighter, perhaps dark gray color instead of black should be better, now the dots take too much focus.)

**Comment by WaynePhillipsEA** [comment]
If the `Visible` property of a control is False, then the form designer halves the opacity.  I personally find this useful as it is clear that the control is invisible.  Perhaps the opacity reduction is too much?

I agree about the dots... I will look at adjusting them.

**Comment by DinyaZ** [comment]
"If the Visible property of a control is False, then the form designer halves the opacity."
.
.
Huh, Wayne, I dont know, I think it is very confusing, specially when you have a complicated form with many controls. The original VB6 solution is better, much cleaner for me........

**Comment by DinyaZ** [comment]
> "If the Visible property of a control is False, then the form designer halves the opacity." . . Huh, Wayne, I dont know, I think it is very confusing, specially when you have a complicated form with many controls. The original VB6 solution is better, much cleaner for me........
.
.
Or can this "half opacity" feature be a setup option?

**Comment by wqweto** [comment]
> The original VB6 solution is better, much cleaner for me........

Which "original VB6 solution"? VB6 form designed does not do anything to Visible=False controls which is sub-optimal to say the least.

An idea might be for opacity to be restored to 100% on the invisible control becoming currently selected in the form designer.

**Comment by rexxitall** [comment]
A dotted frame could show completely invisible or hidden things. If you see nothing, like also in VB6 sometimes if a thing is in the back, has same colors etc. , you do not know where to click to  activate :)

**Comment by WaynePhillipsEA** [comment]
Just checked and the opacity was being double-reduced (50% in normal CSS property plus 60% in CSS filter), so 30%.   I agree that's too much.  I'll tweak this in the next release and see if we can come to a compromise.

**Comment by rexxitall** [comment]
Should becomes a user setting. It depends on the color cheme in the application. A game designer might not use gray... It depends what you need. Should be impossible to make things totally invisible in the editor. But as long as you can guess that there is something it would be fine.  Good values for me was around 70 percent. But as said that depends also on the contect of the form.

**Comment by WaynePhillipsEA** [comment]
I'm generally not in favour of adding masses of settings.  If we can come to a compromise, all the better IMO.

**Comment by rexxitall** [comment]
In my web editor i run also in this kind of transparency issues. Could becomes a part of the color settings. I also think a bit at handycapt peoples. If you hardcode it, it might be a no go for some. But in general i agree. I "love" apache config files :D (nightmare)

**Comment by WaynePhillipsEA** [comment]
It could indeed become part of the IDE 'theme', once we support custom themes.

**Comment by WaynePhillipsEA** [comment]
Actually, you can do this via CSS right now by editing the `ide\styles-twinbasic-dark.css` (or `style-twinbasic-light`) file, adding this at the bottom:

```
.baseControl
{
   filter: none !important;
   opacity: 1 !important;
}
```

Naturally, you would need to readjust that file each time you download an update, but it demonstrates how we can have it as part of the customizable CSS theme in the future.

**Comment by rexxitall** [comment]
In this case you can also do the css settings by a JS file. In this case a user provided file could overule the settings if needed. But more afford then needed. And for sure not all are able to deal with css or js. Put it it in the custom themes some days where it belongs perfectly. I guess you has enough to do :)

**Comment by fafalone** [comment]
See that's the right way to do it... not to many front-end options right in the IDE where too many might be overwhelming when first starting with the software, but lots of options possible behind CSS and/or config files.

**Comment by bclothier** [comment]
Just as a consideration --- there is a related issue about having a separate section for non-visible controls (#911). If the controls are permanently invisible, putting them in that section means less clutter on the form. Doesn't help if they are only invisible sometime and therefore should be on the form somewhere when they are made visible. 

I'm usually of opinion that it's better to disable than to make invisible; otherwise the jack-in-the-box effort makes for a fun tech support session; "click that button", "where?!?" but that's a UX issue rather than form designer issue. YMMV.

**Comment by DinyaZ** [comment]
As I think: invisible controls without transparency as default (and as is in VB6), and transparency possibility for everybody who like it with config file.

**Comment by rexxitall** [comment]
@Fafalone hidden config files are also not a gift. Will make the program like for Linux Users. Noone want to act like a linux user ;)  Gnome has tried it - was not a success. In this case its best to act like VLC or KODI. They have config level for beginner novice, expert.

**Comment by fafalone** [comment]
Who said hidden?

**Comment by DinyaZ** [comment]
> @fafalone hidden config files are also not a gift. Will make the program like for Linux Users. Noone want to act like a linux user ;) Gnome has tried it - was not a success. In this case its best to act like VLC or KODI. They have config level for beginner novice, expert.

Maybe community can develop a config manager, with easy UI....? :)

**Comment by rexxitall** [comment]
@Fafalone it is not a freeware ;). The annual fee is currently near 500 Euros... To be honest for that money i await a bit more then fiddeling byselv with config files. I wann have a yacht, 20 well shaped girls a island .... (endless list)  *laugh* I guess to make this config entry in the custom settings will be later on just a few lines of JS code :) No need for long discussions :)

**Comment by rexxitall** [comment]
If i remember right wayne is thinking to release the code for the IDE and the controls as well.  .oO( Best he can do to get rid this boring stuff and nagging anoying user requests) *hmpf*

**Comment by WaynePhillipsEA** [comment]
The reduced change in opacity is now active in BETA 128.

**Comment by DinyaZ** [comment]
> The reduced change in opacity is now active in BETA 128.

Thank you, that is much better and useable now, although I'm still not sure if it's necessary to have 20%. Have you tested with 10%?

Another diverse details: 
- when I change a clickable item on the properties page, for example this "Visible", the properties list jumps up to the first properties item, and doesnt stay down on changed.
- the timer control on the TWB panel is unnecesariliy too big
- the background dots are much better now in Beta128. But to go further: when I click on controls, the blue dots on the corners of the control are also too big.

**Comment by WaynePhillipsEA** [comment]
> Have you tested it with 10%?

Of course.  I was not happy with that, so I settled on 20%.

> when I change a clickable item on the properties page, for example this "Visible", the properties list jumps up to the first properties item, and doesnt stay down on the changed item.

Yes, I've noted this.

> the timer control on the TWB panel is unnecesariliy too big

I will adjust it so that it matches VBx.

>  the background dots are much better now in Beta128. But to go further: when I click on controls, the blue dots on the corners of the control are also too big.

I will look into it.  They don't look overly big to me, but I will test it a fraction smaller.

**Comment by WaynePhillipsEA** [comment]
These have now been tweaked, so I'm marking this as complete.  Thanks.
