### ISSUE TITLE
ListBox.AddItem not working when passed vbNullString

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1194]
**Describe the bug**
In vb6 , the vbNullString constant is equal to an empty string (""). In tB vbNullString is an "empty" varialble.
In vb6 if a string variable s , assigned the vbNullString and check its value you will see a zero length string ""
in tB with the same check you will see as a value = vbNullString.
In tB  when vbNullString assigned as value to a textbox.text or label.caption it is automatically converted in "", but if you try to add an item to a listbox with a value= vbNullString (list1.additem vbNullString) the app hangs.

**To Reproduce**
Add a textbox, a label and a listbox on a form and try to pass the value of vbNullString

**Expected behavior**
All controls should have as a value = "" , after passing vbNullString

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC BETA 127 (and all previous versions)

**Comment by WaynePhillipsEA** [comment]
> In vb6 if a string variable s , assigned the vbNullString and check its value you will see a zero length string ""
> in tB with the same check you will see as a value = vbNullString.

I can see no difference in behaviour between VB6 and tB in this regard.  You can test if a string is actually a vbNullString by checking the value with StrPtr:

```
   Dim s As String
   s = ""
   Debug.Assert StrPtr(s) <> 0
   s = vbNullString
   Debug.Assert StrPtr(s) = 0
```

> but if you try to add an item to a listbox with a value= vbNullString (list1.additem vbNullString) the app hangs.

Yes, that is the only bug I see here, as the general handling of vbNullString seems fine.

**Comment by WaynePhillipsEA** [comment]
I've fixed this ready for tomorrows release, including several other places in the UI controls implementations which also weren't handling vbNullString appropriately.

**Comment by sokinkeso** [comment]
> I've fixed this ready for tomorrows release, including several other places in the UI controls implementations which also weren't handling vbNullString appropriately.

That's why I mention it as "possible bug with the vbNullString"  :)
I'm glad that you found the real issue of vbNullString handling in some controls.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 128.  Thanks!
