### ISSUE TITLE
Infinite compiler restart loops in newer versions

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1196]
**Describe the bug**
I started working on my shell interface def projects in 126 and got an infinite compiler restart loop doing nothing out of the ordinary; upgrading to 128 did not resolve the issue. 

**To Reproduce**
These are hard to simplify so I'll attach my project. Open it, it should open to the slInternet.twin module, then start adding members to IInternetSecurityMgrSite. Sometimes I can break it out of the endless restart loop that starts, other times I have to kill it from a task manager.

**Expected behavior**
No restart loop.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.128

**Additional context**

[tbsl-bugcheck.zip](https://github.com/twinbasic/twinbasic/files/9640978/tbsl-bugcheck.zip)

**Comment by fafalone** [comment]
This appears related to a duplicate definition; but duplicates shouldn't be throwing it into a restart loop.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 129, thanks!
