### ISSUE TITLE
debug.print/assert causes runtime error in compiled (.exe)

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1198]
**Describe the bug**
If the parameter of debug.print or debug.assert , causes an error in the IDE, this error also occurs in the compiled app. In vb6 the evaluation of debug.print/assert is ignored outside the IDE. 

**To Reproduce**
add command button on a form, and in the click event the following code:
Debug.Print Mid$("abc", 0, 1)

compile/build the app.

run the program in the IDE, a runtime error will occur.
run the compiled exe,   a runtime error will occur too.

**Expected behavior**
in the compiled app , the error should be ignored.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE_BETA_129

**Comment by WaynePhillipsEA** [comment]
This line does actually throw an error in a compiled VB6 application:
`Debug.Print Mid$("abc", 0, 1)`

Do you have the VB6 edition of vbWatchdog installed, by chance?  On VB6, vbWatchdog has a side-effect that removes all  `Debug.Print` statement evaluations in compiled EXEs.   Disabling the developer addin and then restarting the VB6 IDE will restore the original behaviour.

**Comment by sokinkeso** [comment]
> 

You are right! In the pure vb6 IDE if compiled this line throws exception in compiled too. Very strange...(a vb6 bug maybe??)
I have tested in an IDE where I have the Codesmart addin.
Nevertheless,  in normal situation the debug commands should be ignored in the compiled.
I have tested also:
dim a(5)
debug.print a(6)     ' <====  this throws exception in IDE but not in the compiled.

debug.print  1/0    ' <====  this throws exception in IDE but not in the compiled.

**Comment by wqweto** [comment]
Ouch! This will be a PITA to emulate.

It appears w/ `Debug.Print` the VB6 compiler checks expression for potential side-effects (function calls included) to decide if to emit code to evaluate expression whose result is never going to be used.

**Comment by WaynePhillipsEA** [comment]
Yes, I was just about to say that it's not quite that simple.    For example, using your example:

`Debug.Print a(6) + Something()`

`Something` does get called... yet the `a(6)` part of the expression is not evaluated.

**Comment by sokinkeso** [comment]
> Yes, I was just about to say that it's not quite that simple. For example, expanding on your example:
> 
> `Debug.Print a(6) + Something()`
> 
> `Something` does get called... yet the `a(6)` part of the expression is not evaluated... or at least: does not throw. Errors occurring in `Something()` do throw, confirming that it's not errors just generally being ignored here. So yes... this will be a PITA.


I agree with both of you... after testing again I cannot end up to a conclusion about how this is handled. 
Exceptions with the same error number, do not have a stable action...
Here are my tests:

'--------------- these throw exception in compiled
Debug.Print Mid$("abc", 0, 1)  'invalid procedure call or argument  error-5
Debug.Print a.Name ' without defining a   ' object required error-424
Debug.Print Day("gggg")   'type mismatch error-13

Dim mcol As Collection
Set mcol = New Collection
Debug.Print mcol(1)  'without adding items in the collection   'invalid procedure call or argument  error-5
Debug.Print mcol(2)  'after adding one item in the collection   'subscript out of range error-9


'--------------- these do not throw exception in compiled

Debug.Print CBool("ggggg")   'type mismatch error-13
Debug.Print CByte("hhh")    'type mismatch error-13
Debug.Print CDbl("gggg")   'type mismatch error-13
Debug.Print CByte("gggggg")   'type mismatch error-13
Debug.Print CInt("fff")   'type mismatch error-13
Debug.Print CDate("fffff")  'type mismatch error-13
Debug.Print CLng("gg")   'type mismatch error-13
Debug.Print 1 / 0    'divizion by zero  error-11
Debug.Print Abs("hh")  'type mismatch error-13
Debug.Print (-1) ^ (1 / 2) 'invalid procedure call or argument  error-5

Dim a(5)
Debug.Print a(6) 'subscript out of range error-9

**Comment by fafalone** [comment]
Just to note, I found an issue where this occurs *without* an error in the IDE.

`Debug.Print App.LastBuildPath`

It's a simple string print that works fine without error when from the IDE.

(I closed the duplicate I opened about this, so wanted to add it here).

**Comment by WaynePhillipsEA** [comment]
@fafalone `App.LastBuildPath` currently throws an error at runtime when built into an executable.  That is probably not desirable, and we could simply return an empty string for that case instead.

**Comment by WaynePhillipsEA** [comment]
>> Why are these statements being left in anyway? That goes for VB6 too apparently. Is there some way to access their output?

The actual output string is not formed in the final executables, but functions that are called as part of the expression evaluation do still get executed (and any results discarded).  But as noted in this thread, it's a little more complex than that in reality.

**Comment by fafalone** [comment]
Still curious though why is *anything* called; why wouldn't the entire Debug.Print statement be stripped at the preprocessing level? There must be some reason if both VB6 and tB aren't doing that I'd think? Well I guess tB would be doing it to match VB6, though that kind of straddles the line between what's included with compatibility; replicating behavior that occurs with error-triggering code and replicating undocumented VB internals.

**Comment by jpbro** [comment]
I guess it gets compiled in because you can call methods in Debug.Print, and those methods can change variables. For example:

`Option Explicit

Private Sub Form_Load()
   Dim x As Long
   
   Debug.Print DoSomething(x)
   
   MsgBox x
End Sub

Private Function DoSomething(ByRef x As Long) As String
   x = x + 1
   DoSomething = "ABC"
End Function
`

If you don't compile Debug.Print statements into the executable, then you will get different results for MsgBox x depending on whether or not you are running the compiled code.

**Comment by WaynePhillipsEA** [comment]
Indeed, tB does it to try to match compatibility with VB6.  I vaguely remember a case on here that was reported for pretty much the exact reason @jpbro mentioned, where the output differed due to not executing the side-effecting functions.

**Comment by jpbro** [comment]
FWIW I think the original VB6 devs made the "least-worst" choice here. Different execution between the compiled/non-compiled versions of the same code are a nightmare.

That said, it has always bothered me that Debug.Print statements are compiled. I only use Debug.Print for in-IDE logging, and I would prefer that those strings never leak into the EXE. Maybe an option to not compile Debug.Print would be a good feature for tB?

**Comment by sokinkeso** [comment]
I agree with jpbro, and I believe this area may be one case where compatibility with vb6 should be reconsidered. In the end, the Debug object is for debugging despite of the fact that many programmers use it also as a workaround trick for a "RunInIDE" function.
So if tB provide a build-in RunInIDE function, then Debug.Print/Assert don't have to be compiled.
This compatibility break, is very minor.

**Comment by WaynePhillipsEA** [comment]
`App.LastBuildPath` now returns an empty string in built executables as of BETA 373.  Thanks

**Comment by mwolfe02** [comment]
> This compatibility break, is very minor.

I disagree.  I could easily imagine a scenario where a developer changed a side-effect-producing `Sub` into a `Function` that returns a string as a quick and dirty way to add some debug logging to an application.  The returned string would be some sort of message for the developer's benefit.

More importantly, the difference between 99% and 100% backward compatible is way more than 1% in terms of the development effort to migrate from VB6 to twinBASIC.  I concede that this is a corner case, but the difference between 99.999% and 100% is way more than 0.001%, too.  What's worse, this is the sort of breaking change that could result in a logic error.  That is, it would alter the program's _behavior_ without raising any kind of explicit error (either at compile time _or_ runtime).

I think you need to be _really_ careful about intentionally foregoing backward compatibility whenever you can help it.  

In my opinion, a much better approach would be to introduce a new method to the Debug class that would act just like the Print method except that it would not get compiled into any binaries.
