### ISSUE TITLE
Form is non extensible object 

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1202]
**Describe the bug**
I have a public function "XTest" on a Form (FormX)

In VB6 I can do this:.................

dim x as long
dim F as Form

Set F = FormX.
x = F.Xtest

It might not be nice but it works in VB6.
In tB it gives an error "unrecognised member Xtest on type  _Form [non extensible object]

**To Reproduce**
See above.

**Expected behavior**
I would like it to work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win11]
 - twinBASIC compiler version:   all versions, including the most recent

**Additional context**
I appreciate that this sort of thing is resolved at runtime and that I can't really expect itellisense stuff to work but I do it quite a lot.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 132, thanks!
