### ISSUE TITLE
Properties sheet behavior

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1204]
**Describe the bug**
I have noticed these (3) little issues about the properties sheet: 
1) the info area at the bottom of the property sheet, stucks with the same message.

2) property sheet's properties disappear when mouse_down event occur on form

3) properties sheet auto-scroll to the top always

**To Reproduce**
"play" selecting different controls on a form

**Expected behavior**
1) the info message should show help about the selected property*
2) should not disappear
3)  if the previous selected property exists in the new selected control then
         if the control is the same type, then 
             do not scroll the property sheet
         else 
             scroll to find/show the same property
     else 
         scroll to the top

**Screenshots**
no screenshots... :(

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC compiler version BETA_IDE_131

**Additional context**
It will be good to highlight the selected (last changed)  property

**Comment by WaynePhillipsEA** [comment]
2 & 3 should be somewhat better in BETA 139.  Thanks.

**Comment by sokinkeso** [comment]
It is ok in BETA_140. Thnx!!!
