### ISSUE TITLE
Duplicated event

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1206]
**Describe the bug**
I click on the textbox multiple times, and TWB creates a new Text1_Change() event again and again

**Expected behavior**
Dont duplicate the empty event, but jump to the existing

 - twinBASIC compiler version BETA131
 
![Image23434](https://user-images.githubusercontent.com/94013032/193121514-d6ba4edc-f32e-4632-b1d5-808d85e9c941.jpg)

.
PS: Isnt it possible to have event name without the "handles Text1.Change" extension? (as in the VB6)

**Comment by sokinkeso** [comment]
I want to add an extra notice here, when we double click on a control anytime after the first time the cursor must go to the first line under the event declaration (as in the first time that the declaration is created). Right now the cursor goes at the begging or the declaration line.

**Comment by sokinkeso** [comment]
Good morning [DinyaZ], I think it is ok in BETA_140

**Comment by WaynePhillipsEA** [comment]
I haven't looked into this yet, but I suspect this bug only surfaces when there are particular compilation errors already in the project (probably in the form class).  So I'm guessing this issue might still be current.

**Comment by WaynePhillipsEA** [comment]
Haven't seen any recent reports of such problems, so let's close this now.  Thanks.
