### ISSUE TITLE
Window designer - add border to labels while editing

### ISSUE THREAD

**Issue by mika76** [twinbasic/twinbasic#1207]
**Is your feature request related to a problem? Please describe.**
This is a feature request to add some kind of border to labels while designing. Currently it can be hard to see the sizes and dimensions of labels on a form. VB6 has always also had this issue. 

**Describe the solution you'd like**
I would like some sort of design-time border (or background color would work too I guess - maybe not for color-blind people) to be added to make it more visually clear of the label dimensions. It could be a thing that can be switched on and off like the grid maybe? Could be this is added to all the controls without borders? Maybe a dotted/dashed border which is a different color? I dunno - just something make things a little more clear while designing.

**Describe alternatives you've considered**
The only alternative I know is to actually add a border or a background color to the label but that is changing the actual property which is not only design time.

**Additional context**
![Screenshot 2022-09-30 at 09 53 38](https://user-images.githubusercontent.com/229311/193220294-1101ddcd-2e10-4b84-8e57-cc1d1d521f13.png)

**ℹ️ See how when selected the label dimensions are far clearer.**

**Comment by WaynePhillipsEA** [comment]
In BETA 132 I've added a dotted box around all controls when the CTRL key is held down.  Let me know what you think.

**Comment by mika76** [comment]
It does not seem to work for me very well. The form only really refreshes when I click something else (seems to be happening with the grid toggle too).

Also I hope you make it a toggle. When moving things around I don't think having to hold down the control key sounds like much fun.

Visually it looks good once enabled.

**Comment by WaynePhillipsEA** [comment]
"Show outlines" is now an option available via the grid options drowdown (just hover over the grid icon in the form designer) in BETA 133.  Thanks!
