### ISSUE TITLE
unsupported document  type 'PropertyPage' 'ResFile32'

### ISSUE THREAD

**Issue by foolonthedesk** [twinbasic/twinbasic#1209]
**Describe the bug**
__IMPORT_LOG.txt is
Import from Visual Basic VBP file 'D:\hokanko\MyData\src\VB6\aicAlphaImage\Project1.vbp'...
   successfully set project.buildType to 'Standard EXE' at line #1
   successfully added project.reference 'OLE Automation' at line #2
   successfully imported USERCONTROL '..\Common\aicAlphaImage\aicAlphaImage.ctl' at line #3
   *****FAILED*** unsupported document '..\Common\aicAlphaImage\ppgSourceImage.pag' type 'PropertyPage' at line #4**
   successfully imported CLASS '..\Common\aicAlphaImage\cGIFparser.cls' at line #5
   successfully imported CLASS '..\Common\aicAlphaImage\cCDECL.cls' at line #6
   successfully imported CLASS '..\Common\aicAlphaImage\cPNGparser.cls' at line #7
   successfully imported CLASS '..\Common\aicAlphaImage\cPNGwriter.cls' at line #8
   successfully imported CLASS '..\Common\aicAlphaImage\cBMPparser.cls' at line #9
   successfully imported CLASS '..\Common\aicAlphaImage\c32bppDIB.cls' at line #10
   successfully imported CLASS '..\Common\aicAlphaImage\cICOparser.cls' at line #11
   successfully imported CLASS '..\Common\aicAlphaImage\cGDIplus.cls' at line #12
   successfully imported FORM 'Form1.frm' at line #13
   successfully imported MODULE '..\Common\aicAlphaImage\modParsers.bas' at line #14
   *****FAILED*** unsupported document '"Sample.RES"' type 'ResFile32' at line #15**
   successfully set project.startupObject to 'Form1' at line #16
   successfully set project.name to 'Project1' at line #20
   successfully set project.versionMajor to '1' at line #23
   successfully set project.versionMinor to '0' at line #24
   successfully set project.versionRevision to '0' at line #25
   successfully set project.versionCompanyName to 'LaVolpe' at line #28
IMPORT FINISHED WITH 2 ERRORS/WARNINGS

**Desktop (please complete the following information):**
 - OS Windows 10
 - twinBASIC compiler version 133

**Comment by fafalone** [comment]
These are now recognized by the importer; other implementation issues and separate imports have their own issues.
