### ISSUE TITLE
Support MDI forms

### ISSUE THREAD

**Issue by JBEJBE** [twinbasic/twinbasic#1213]
1. (Experimental) VB6 Project Import does not detect menu items with array syntax.

Example: 2 text boxes from a form "Form1" with names "box(0)" and "box(1)" will be imported as "box" and "box", giving "duplicate definition in Form1" errors in code. TwinBasic then gets confused with its internal workings, leaving the form in a mess. Sometimes with errors, othertimes no messages. After manual rename to "box(0)" and "box(1)", the array-centric code for "Form1" still does not work.

2. Imported MDI Forms always have blank class name, invalidating all following code.

Errors can be replicated by importing code from this application:
https://github.com/Gagniuc/Diabetes-prediction-2.0

**Comment by WaynePhillipsEA** [comment]
Control arrays are not yet supported, so this is expected behaviour at this point.   There will be an update this coming week to support them.

MDI forms are also not yet supported in tB, so this is to be expected.

**Comment by dmrvb** [comment]
More exciting stuff. Will you also support run time loading of new elements into a control array?

**Comment by WaynePhillipsEA** [comment]
> More exciting stuff. Will you also support run time loading of new elements into a control array?

Absolutely.  Probably not this week, but definitely soon!

**Comment by WaynePhillipsEA** [comment]
Menu arrays are now supported as of BETA 141.

**Comment by JBEJBE** [comment]
Great, thank you for your usual "high speed support". Seems to work in first tests with the above mentioned application. MDI support will be available in a few weeks?

**Comment by WaynePhillipsEA** [comment]
Thanks.   MDI forms hopefully this month.

**Comment by JBEJBE** [comment]
Wow, that's fast. Microsoft would need a year or so...

**Comment by dmrvb** [comment]
I found a bug ("feature") in the Basic compiler (BC) in 1985. I reported it, Microsoft would not fix it as users might be working with it, instead they produced a modified compiler just for me, in less than a week. How things have changed.

**Comment by JBEJBE** [comment]
Great work, thank you Wayne. Your VB6 project import is really a milestone and game changer.
 
Best regards
Jens Becker

**Comment by JBEJBE** [comment]
Wayne, I've switched to SDI, couldn't wait for MDI implementation.

**Comment by VB6-Programming** [comment]
> 

Others of us are still waiting

**Comment by fafalone** [comment]
I've got a great stress test in mind for tB as soon as MDI forms are available:

https://github.com/smbx/smbx-legacy-source

Super Mario Bros X... Gameplay identical to smb 3, in pure VB. Why something like that uses so many MDI forms who knows, but I'm looks forward to it 😄

**Comment by wqweto** [comment]
Do you have the graphics? It calls `LoadPicture(App.Path & "\graphics\mario\mario-" & A & ".gif")` to load all the sprites.

**Comment by fafalone** [comment]
Haven't tried it in VB6 yet but I presumed I could use the assets from the binary distro? It's got the \graphics folder with \mario\mario-... and thousands of others.

https://github.com/Wohlstand/smbx-experiments/releases

**Comment by WaynePhillipsEA** [comment]
BETA 537 is out, with MDI support -- see sample 19.     When reporting bugs relating to MDI, it would be most helpful if you can post a minimal project based off Sample 19 to demonstrate the issue(s).
I wouldn't dive in trying to load complex MDI projects just yet until the dust settles 🙂

**Comment by JBEJBE** [comment]
OK Wayne, thank you.

Actually working on Excel-64-Programs with TwinBasic sans MDI. 
Runs flawless, great job in that aera  😉

Best regards
Jens Becker

-----Original Message-----
