### ISSUE TITLE
VBA.ConvertIconToBitmap optional BackColor argument

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1215]
**Is your feature request related to a problem? Please describe.**
The tB VBA.ConvertIconToBitmap function is very convenient.
However, an optional BackColor (OLE_COLOR) argument would be nice.

**Describe the solution you'd like**
I guess the icon is drawn into a memory bitmap (using DrawIconEx ?) then the `hbrFlickerFreeDraw` argument can be used to pass a HBRUSH which contains the passed BackColor.
If nothing is passed to the optional BackColor, then it contains a 0 color which is just black. So matching current behavior.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
This is now implemented in BETA 139.  Thanks!
