### ISSUE TITLE
COM references decompile some [Description] attributes with double-double-quotes

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1217]
**Describe the bug**
I imported an older VB6 project and started clicking through the references. I noticed that a few of them contained description attributes with an extra set of double quotes.  Most descriptions are fine, just a few of them come out like this.

Examples:

From MSXML2:
```
    ' Original type library: ..\..\..\..\Windows\System32\msxml6.dll
    ...

    [ Description (""Constants that define a node's type"") ]
    Enum tagDOMNodeType
        NODE_INVALID = 0                                     ' &H00000000&
        NODE_ELEMENT = 1                                     ' &H00000001&

```

From DAO360:
```
    ' Original type library: C:\Program Files (x86)\Common Files\Microsoft Shared\DAO\dao360.dll
    ...

    [ CoClassId ("00000101-0000-0010-8000-00AA006D2EA4") ]
    [ Hidden, COMCreatable, COMLicensed]
    [ Description (""DAO 3.0 DBEngine (private)"") ]
    CoClass PrivDBEngine
        [ Default ] Interface DAO._DBEngine
    End CoClass
```

The OLEView version of these don't have the same issue:

```
    typedef [helpstring("Constants that define a node's type")]
    enum {
        NODE_INVALID = 0,
        NODE_ELEMENT = 1,
```

and

```
 [
      uuid(00000101-0000-0010-8000-00AA006D2EA4),
      helpstring("DAO 3.0 DBEngine (private)"),
      licensed,
      hidden
    ]
    coclass PrivDBEngine {
        [default] interface _DBEngine;
    };

```

Also noteworthy is that there was some weird coloration problems in the syntax highlighting just after the MSXML example of this. I don't really know if that is related or not, but it seemed sensible that if the syntax parsing was going wrong this could happen:

![image](https://user-images.githubusercontent.com/18285074/193882097-e087bda8-7e77-4a23-81c4-c1e519fce72f.png)

**To Reproduce**
1. Add MSXML6.dll as a reference
2. Visit it in the References node
3. Scroll down to 'Enum tagDOMNodeType'

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 137

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 139.  Thanks for reporting!
