### ISSUE TITLE
missing IDE option: spaces per tab

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/twinbasic#1218]
**Is your feature request related to a problem? Please describe.**
My standard is to change the IDE option for spaces per tab to 2 always because of the way I code (very functional-style with MANY possible levels of indentation). I learned this style writing AutoLisp many years ago, and it serves quite well.

**Describe the solution you'd like**
Retore to us the VBIDE option of setting an arbitrary number of spaces per tab-indent (additional settings options - as in other editors - to encode them as tabs or spaces would be nice, too, but unnecessary.

**Describe alternatives you've considered**
never using a tab again?

**Additional context**

non-sequiter here, but for inherited/converted VBx projects, could you make the default setting be Monaco:Render Whitespace = Trailing ("All" as a default is just - ICK! where "Trailing" is a VBIDE option we don't have that is good: "see this extra stuff here you don't need?")

**Comment by WaynePhillipsEA** [comment]
This feature has been available in the IDE settings for some time now, so let's close this.  Thanks.
