### ISSUE TITLE
Internal error trapping msgbox with "6660" text pops up

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1221]
**Describe the bug**
An unexpected error message pops up, see attached screenshot. If I click ok, the msgbox pops up again and again. This started to happen when I open the simplest helloworld demoapp, and tried to add a form to it. I cant reproduce it, but I hope you will find this internal errormessage in the code.

![Image233](https://user-images.githubusercontent.com/94013032/194281154-ca9bc09e-fb12-4203-aa29-9103f163605a.jpg)

**Comment by DinyaZ** [comment]
PS: I can reproduce it now. When I added the new form to the demo app, as an unintended mistake I changed the form name to only a "," symbol, and then the form adding process became a neverending circle, and this 6660 pops up again and again.

**Comment by WaynePhillipsEA** [comment]
Thanks, that helps a lot

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 141, thanks!
