### ISSUE TITLE
Can TwinBasic support Office Custom Task Pane ?

### ISSUE THREAD

**Issue by AlanSkyNet** [twinbasic/twinbasic#1222]
We had to use strange Office object to load a custom task pane designed as a .dob file in VB6.

How can we port that to TwinBasic ?

Private Sub _
    ICustomTaskPaneConsumer_CTPFactoryAvailable _
    (ByVal CTPFactoryInst As Office.ICTPFactory)
End Sub

<img width="542" alt="vbuserdocuments" src="https://user-images.githubusercontent.com/37843466/194341726-920316dc-0755-444e-8221-9a9fd7d54691.png">

**Comment by WaynePhillipsEA** [comment]
It's been a while, so I'm assuming you've moved on from this by now.  Additionally this is neither a bug report nor a feature request, so for general support you'll get a better response over on our discord server.
