### ISSUE TITLE
Optimize formulas

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1224]
By some lazy coding, or by reading reasons or copy and paste you find very often that e value is calculated again and again

Weak example:
x=(x-3) * (X+5)
y=(x-3) + (X+5)

Desired: The compiler should optimize it internally to

VAR1=(x-3)
VAR2=(x-5)

x=VAR1+VAR2
y=VAR1*Var2

**Comment by WaynePhillipsEA** [comment]
For general optimization such as this, LLVM will handle it, and will handle it well.  There are specific cases where we need to look at front-end compiler optimizations, but this is not one of them.  As such, to keep the issue count down, I'm going to close this one.  Thanks.
