### ISSUE TITLE
optimize Math in general

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1225]
Based on the fact that the IDE is js based and there are a lot of CAS libs out
it should be possible to use them to simplify calculations before get compiled

To use those CAS libs while editing could also be a great gift.
 Desired Behaviour:
automatic 
[optimize math auto]
x=(x+1)+(x+1)+(x+1)+(x+1)+(x+1)+(x+1)
'optimization x=6*(x+1)
[Stopoptimize math auto]

While  editing 
mark some calculation code and get it converted in a CAS edit window

fiddle there with the math and cas
press save
Original code will be comented out
OPtimized code will be filled in

**Comment by WaynePhillipsEA** [comment]
For general optimization such as this, LLVM will handle it, and will handle it well. There are specific cases where we need to look at front-end compiler optimizations, but this is not one of them. As such, to keep the issue count down, I'm going to close this one. Thanks.

**Comment by rexxitall** [comment]
You should keep this open. 
You should let it open. The GUI part is interesting. I a quite sure LLM Will not handle thing like drive, solve formulas, isolate variables in a formula and so on.

see
https://github.com/aantthony/javascript-cas
var y = M('x^2 + 3');
// Differentiate with respect to x
var dy = y.differentiate(y.unbound.x);
// Compile a javascript function
var fn = dy.compile('x');
// now evaluation of the deriviative is fast:
var x = fn(3.1); // Returns a javascript number.

Things like that i am talking on. 
That goes a few steps further then LLVM is able

Its more a kind of code refactoring

>ou will add a lof of mathematics to your customers which are now not forced to run first mathlab and freinds and then rewite that to basic code...

**Comment by rexxitall** [comment]
Maybe this sample is better due it does not do it numerical
from math.js - as told there are some libs of that type 

[](https://mathjs.org/docs/expressions/algebra.html)

// work with an expression tree, evaluate results
const h = math.parse('x^2 + x')
const x = math.parse('x')
const dh = math.derivative(h, x)
console.log(dh.toString())        // '2 * x + 1'                 <---------------------------THINGS LIKE  THAT I WANT SyBoLiC
console.log(dh.evaluate({x: 3}))  // '7'

**Comment by wqweto** [comment]
Maybe symbolic calculus is outside the scope of any compiler.

Everything beyond what LLVM already does is outside of compiler's optimization capabilities.

External library for symbolic math - yes. Doing this in compiler advanced optimizations - not feasible.
