### ISSUE TITLE
Setting editing not possible

### ISSUE THREAD

**Issue by uwbwsvd** [twinbasic/twinbasic#1226]
- open a Standard EXE project
- goto settings
- editing settings fails
- closing the editing tab
- open it again.
- it is blank
- got a messagebox with "33330" without title

Version 15.141

https://user-images.githubusercontent.com/41230018/194565331-19a3a870-b3f1-4453-a949-0730ab6cf310.mp4

**Comment by DinyaZ** [comment]
I have tried it on my machine now, but it worked well here without this run-time error. (Beta141, Windows7)

**Comment by uwbwsvd** [comment]
At least I deleted all IDE files and extracted them again. Everything is working fine.

**Comment by WaynePhillipsEA** [comment]
Perhaps it's now time for me to go through these cryptic message box numbers and give more sensible error descriptions ;)

**Comment by uwbwsvd** [comment]
At least to know it is a TwinBASIC error and nothing unexpected else.
