### ISSUE TITLE
Some sample demos stopped working in BETA 141

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1227]
**Describe the bug**
Sample 6 & 8: Ambiguous error "9403".

**To Reproduce**
Run any of the sample projects listed above.

**Expected behavior**
It should work as in previous versions.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/2956806/194578176-f29c7f94-e429-4d20-bbf0-5bf56f8b7a6b.png)
![imagen](https://user-images.githubusercontent.com/2956806/194577328-66f5e08e-bd2b-4259-b2a0-e645a13a676f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - twinBASIC BETA 141

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting!  Fixed in BETA 142
