### ISSUE TITLE
Overview of all controls regadless if visible or not

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1229]
Sometimes you "loose a control. Either it becommes hidden ovy overlapping, or you has made aunwanted copy and paste action. Anyhoe the control ist "lost".. Same by making ist invisible by same color as the background.  Whatever

Suggestion. some Hotkey which shows all control names and a frame with the control dimensions.
While hotkey is pressed you can select the hidden control. It will show up in the property box and this frame will be shown also if you release the key. Now you can bring it to front or do whatever. The temporary frame will get destroyed by loosing focus.

**Comment by WaynePhillipsEA** [comment]
We already have the drop-down list in the form designer which should be sufficient for this, so let's close this now.  Thanks
