### ISSUE TITLE
Cant pass control as argument if its a control array

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1231]
Implementing control arrays is exciting stuff and another big step forward, The list of errors from my big app is rapidly reducing. Will it compile for Christmas!
a little bug:.......
.
I have a function that takes a textbox as an argument.
This does not work if I pass a textbox that is in a control array

Function Tvalue(tx as textbox) as long
..............
end function

xxx = Tvalue(mytextbox(1))

gives errors:
This property is read only
Unable to take a reference to a withevents array element pass as byval instead.

**Desktop (please complete the following information):**
 - OS: [ Windows 11]
 - twinBASIC compiler version..... the latest one that almost supports control arrays.

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 143, thanks!
