### ISSUE TITLE
[TextBox()] does not contain 'Text', or it is inaccessible in this context

### ISSUE THREAD

**Issue by flaviofornazier** [twinbasic/twinbasic#1233]
[TextBox()] does not contain 'Text', or it is inaccessible in this context

Just put any value on index property.

=)

![twinbasic_142](https://user-images.githubusercontent.com/50641373/194678882-ac849f0a-d027-4e4e-b660-cc8e1bf05568.PNG)

**Comment by WaynePhillipsEA** [comment]
When you change a control into a control array, you must also change any code that references that control to include the index. For example, `MyTextBox.Text = "Hello"` needs to be updated to `MyTextBox(0).Text = "Hello"` (assuming an index of 0).  

Unless I'm missing something, this error is correct, so I'll close this issue.

**Comment by flaviofornazier** [comment]
Thank you Mr.Wayne. My mistake. The "zero" was already in my daily release test project, before control index implementation.
