### ISSUE TITLE
Multi-selection issues

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1235]
**Describe the bug**
Case-1: When trying to select multiple controls including simple controls and controls that belong to an array, by dragging a selection rectangle on the form,  the selection procedure "hungs" and the selection rectangle stays visible.
If we do it by holding the Ctrl and clicking on the controls, selection handles appear for each control, but cannot move or copy them. We can only delete them.

Case-2 : When selecting multiple controls (different types) the property sheet shows the properties of the last selected control.

**To Reproduce**
On a form, add a control array of 2 buttons, a textbox and a checkbox
Case-1: try to select a button and a textbox (by pressing left mouse button and dragging the mouse)

Case-2: Select the textbox and the checkbox either by pressing left mouse button and dragging the mouse  or holding ctrl and selecting one-by-one

**Expected behavior**
Case-1: 
The normal behavior is to be able to select multiple controls (mixing single and array-controls) by dragging the selection rectangle,  or by holding Ctrl and clicking on each control.
Also, for compatibility reasons with VB6, when we have multiple controls selected (including controls that belong to an array) , the default copy-paste action should be to paste the array-controls increasing the array index, and for the single controls ask the user if a control array should be created (like in vb6)

Case-2:
When we have multiple controls selected, in the property sheet should appear only the properties that the selected controls have in common.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC IDE_BETA_143

**Comment by WaynePhillipsEA** [comment]
Is this still an issue?

**Comment by sokinkeso** [comment]
The "hung" issue of multi-selection has been fixed.
The following are not fixed yet:

1) For compatibility with VB6, when we have multiple controls selected (including controls that belong to an array) , the default copy-paste action should be to paste the array-controls increasing the array index, and for the single controls ask the user if a control array should be created (like in vb6)

2) When we have multiple controls selected, in the property sheet should appear only the properties that the selected controls have in common.

**Comment by WaynePhillipsEA** [comment]
1.  I think this is covered better by #1486
2. Not sure I agree.  It could still be useful to still set properties against all selected controls, even if not all controls offer the property.  For example, using the select-all feature instead of selecting only specific types of controls.  However, perhaps the properties sheet should indicate that not all selected controls do support the property.

**Comment by sokinkeso** [comment]
I hadn't tried to change a property when multi selecting controls. I've just tested , and yes you are right, changing a property can be done even if in the selection exist a control that does not support it.
So you can close this issue , since #1486 , covers the number (1).
Thank you!

**Comment by WaynePhillipsEA** [comment]
Thanks!
