### ISSUE TITLE
Unrecognized member 'QueryInterface' on unrestricted TLB-defined IUnknown

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1237]
**Describe the bug**
Noticed this when loading oleexp.tlb projects. oleexp.IUnknown is an unrestricted version I use for, e.g.,

```
                            Dim psf As oleexp.IShellFolder
                            Dim pidlPar As Long, pidlRel As Long
                            upi.GetParentAndItem pidlPar, psf, pidlRel '(upi->IShellItem)
                            Dim pUnk As oleexp.IUnknown
                            Dim pIcon As oleexp.IShellIcon
                            Dim hr As Long
                            Set pUnk = psf
                            hr = pUnk.QueryInterface(IID_IShellIcon, pIcon)
```
Note that it doesn't matter if I do `pUnk.QueryInterface(IID_IShellIcon, pIcon): hr = Err.LastHResult`

The new Object Viewer shows it's seeing it correctly in oleexp.tlb:

```
    [ InterfaceId ("00000000-0000-0000-C000-000000000046") ]
    Interface IUnknown Extends Nothing
        [ PreserveSig ]
        /* voffset &H0000*/ Function QueryInterface(ByRef riid As oleexp.UUID, ByRef ppvObject As Any) As Long
        [ PreserveSig ]
        /* voffset &H0004*/ Function AddRef() As Long
        [ PreserveSig ]
        /* voffset &H0008*/ Function Release() As Long
    End Interface
```
But note that it doesn't matter if I do `pUnk.QueryInterface(IID_IShellIcon, pIcon): hr = Err.LastHResult`

**To Reproduce**
I'm attaching a simplified demo. It references [oleexp.tlb](https://www.vbforums.com/showthread.php?786079-VB6-Modern-Shell-Interface-Type-Library-oleexp-tlb).

**Expected behavior**
These methods should be available via this unrestricted def, as they are in VBx.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.143

**Additional context**
Possibly similar to the IDispatch special handling by IID issue?

[UnkTest.zip](https://github.com/twinbasic/twinbasic/files/9739706/UnkTest.zip)

**Comment by WaynePhillipsEA** [comment]
Yeah, this is most likely the same issue as the IDispatch one, so should be an easy fix.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 144, thanks!
