### ISSUE TITLE
Anchors-property (possible bug)

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1242]
**Describe the bug**
When a control has negative coordinates on the form, then resizing the form the control moves until left and top go to zero.
Also there is strange behavior if top_anchor=false
Watch the attached videos.

**To Reproduce**
open the included project, run it and resize the form slowly from the bottom and from the right edge.
[anchors_test1.zip](https://github.com/twinbasic/twinbasic/files/9743406/anchors_test1.zip)

**Expected behavior**
the controls should stay to their position

**Screenshots**

https://user-images.githubusercontent.com/113173954/194800705-9872bb58-0661-4ccb-9f0f-ff16847f62f9.MP4

https://user-images.githubusercontent.com/113173954/194800706-07ef7ee0-5454-4e32-a744-0fa3bc802d3b.MP4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC IDE_BETA_145

**Comment by WaynePhillipsEA** [comment]
I think this should be fixed in BETA 146.  Let me know if you're still experiencing issues here.

**Comment by sokinkeso** [comment]
Yes it's OK in BETA_146. Thank you!!!
