### ISSUE TITLE
"Fixed Single" effect does not have the perspective effect like VBx

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#1243]
just a picture to compare

![Fixed_Single](https://user-images.githubusercontent.com/33807881/194814824-071b649a-303a-4ef0-af82-4af4500570ea.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 145

**Additional context**

**Comment by WaynePhillipsEA** [comment]
By default, tB applications include a visual styles "theme" manifest (see the #1.xml file in your project Resources > MANIFEST folder).

If you want non-themed forms, you can delete that file, and once you've restarted the compiler, the controls will appear like in VB6.

Alternatively, you can change the `VisualStyles` property of any control to `False` in order to do the same thing on a per-control basis.

**Comment by mburns08109** [comment]
Whoa - that's going to HAVE to be called out in the documentation very clearly.

**Comment by WaynePhillipsEA** [comment]
When importing a VB6 project, I expect we'll want a popup dialog to ask A) do you want themed controls, and B) do you want to turn on high-DPI support

(since high-DPI support can cause issues if you've written code that doesn't account for it)

**Comment by camomille22003** [comment]
Excuse me, I had not seen this "Visual Styles" option which does not exist in VBx.
Thanks

**Comment by wqweto** [comment]
> Excuse me, I had not seen this "Visual Styles" option which does not exist in VBx.

It's weird in 2022 to compile/produce Windows applications without comctl6 (VisualStyles) enabled in app manifest. These would definitely look like a blast from the past for the end-users :-))

@WaynePhillipsEA Btw, implementing VisualStyles in TB being ON by default is most appreciated. This is long overdue and TB's mission in this regard is dragging VBx devs into 21-st century for which everyone will be very thankful in the end.

**Comment by WaynePhillipsEA** [comment]
I agree, defaulting to ON is to be the default setting.
