### ISSUE TITLE
Too many problems, will only show first 1000, frequently displays 0

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1247]
**Describe the bug**
When importing some large projects using unimplemented features, you get the message
"WARNING: too many problems.  The PROBLEMS pane will only show 1000 entries, and so is now FROZEN to prevent sluggish IDE behaviour.  After fixing problems, restart the compiler to refresh the PROBLEMS pane. (This is a temporary fix)"

However, quite often, all entries under 'Problems' get removed, and you can't get them back without entirely exiting and restarting, just restarting the compiler doesn't help, nor does closing the editor window and reopening.

**To Reproduce**
I can't find exactly what triggers the list clearing, but it happens often enough it won't be hard to miss if you do something like import my shell browser control, copy a large typelib like oleexp that has numerous things like [ PreserveSig ] and Aliased types from the viewer into a module, or anything else that will trigger thousands of errors.

**Expected behavior**
It should always display at least the first 1000 problems like it says it's doing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.145

**Additional context**
Large projects like these take quite a long time to prepare for x64 compatibility, so I don't care if certain features are unimplemented so far, and for many things I can do a workaround but it needs to be done by hand.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in BETA 149.  A custom virtual treeview is now used for the OUTLINE and PROBLEMS panel, eliminating the performance problems encountered when the trees contained thousands of nodes.  The new virtual treeview is tested with 1 million nodes, and the performance is excellent.

**Comment by dmrvb** [comment]
That looks good,.
I dont think I will ever get a million errors.
However I do still have quite a lot of errors and navigating that treeview to examine them is Not easy. It does not respond to the keyboard up/down arrow keys.
I would like to repeat an earlier rant:...............
The scroll bars (throughout the IDE) are rubbish, but I think this is outside of your control?
A click above/below the "scroll cursor" should move up/down one page.
A click on the scrollbar buttons should move up/down one line.
Scroll bar buttons were really good but have gone a bit out of fashion.
End Rant.

**Comment by WaynePhillipsEA** [comment]
With the new virtual treeview, we do have complete control over the scrollbar behaviour.   So it can be changed there.  However, it makes no sense to do that unless we do it everywhere for consistency.

The plan is for me to change over the remaining panels to use the virtual treeview because the performance is so much better, but that will take a little time.   Once that is done, then yes I think we should look at changing all the scrollbars behaviour.

For the keyboard entry, yes I'm aware and it's on the list 👍

**Comment by dmrvb** [comment]
Thats nmore good news, thanks again.
Could we have "proper" scroll bars in the code editing window too?

**Comment by WaynePhillipsEA** [comment]
Yeah that's the place that will need a bit of extra work, since it's controlled by Monaco... but we'll sort it.
