### ISSUE TITLE
Label backstyle cant show 'opaque'

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1249]
**Describe the bug**

Easier to show it on screenshots:

![TWB screen002](https://user-images.githubusercontent.com/94013032/195170956-54576926-84bf-4f77-bd30-5031b8cae36d.jpg)

![TWB screen002 vb6](https://user-images.githubusercontent.com/94013032/195170962-1a497069-dd20-43ee-a973-78c8a440b160.jpg)

TWB can't show the yellow backcolor of the label, and as backstyle says Transparent, but ot was opaque in the original VB6 version

**Comment by WaynePhillipsEA** [comment]
Thanks @DinyaZ.  If you set the BackStyle and BackColor manually, does it then work correctly?  If so, it sounds like it's just an import issue, so should be an easy fix.

**Comment by DinyaZ** [comment]
Yes, it works manually, I think also that it is an import issue. The backcolor comes correctly, only the backstyle import is the problem.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 147, thanks!

**Comment by Kr00l** [comment]
I didn't check the new release. But the defaultvalue for Label's BackStyle property was vbFSTransparant. But it should be Opaque, was that fixed as well?

**Comment by WaynePhillipsEA** [comment]
I will check.  I think that was missed.  Thanks

**Comment by WaynePhillipsEA** [comment]
The default is now correct in BETA 148.  Thanks.
