### ISSUE TITLE
DrawStyleConstants.vbInvisible should safe a GDI handle

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1251]
**Describe the bug**
Currently a DrawStyle property of DrawStyleConstants.vbInvisible creates a PS_NULL pen.
VB6 simply safes a GDI handle here and does not create a pen at all.

**To Reproduce**
n/a

**Expected behavior**
to match VB6 behavior. (no pen at all in that case)

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [BETA 148]

**Additional context**
Saving a GDI handle is a nice thing.

**Comment by WaynePhillipsEA** [comment]
Thanks @Krool.  Indeed, there's a few places in the controls where I want to add caching of handles etc.  Thanks for opening the issue.

**Comment by Kr00l** [comment]
@WaynePhillipsEA I think I was wrong here. I guess PS_NULL returns always the same handle, regardless of how many times it is created.

So, maybe it was a false alarm ...

**Comment by Kr00l** [comment]
I will close for now. Sorry..
Should have tested PS_NULL before. It seems windows is clever here and returns a cached pen already.
