### ISSUE TITLE
IDE Paren-match highlighting

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/twinbasic#1259]
**Is your feature request related to a problem? Please describe.**
Would it be possible to get the tbIDE to do some parentheses-match highlighting ala NotePad++?

**Describe the solution you'd like**
When the cursor sits on/immediately-behind (depending on editor's current overwrite or insert keyboard mode) a parenthesis character ('(' or ')') it would be marvelous to see the matching parenthesis highlighted in the IDE. In NP++ it gets shown in a different color, and underlined+italicized - until the cursor moves elsewhere, so something similar would be great.
(As the cursor moves off/away from the paren, the match-highlighting is cleared automatically.)
Both ends of the matching pair get the highlight.

**Describe alternatives you've considered**
current - no paren-match highlight and guessing-via-eyeball whether we have them balanced in given lines/expressions or not

**Additional context**
In some editors, I've also seen mouse-hovering cursor do the highlighting also, but I'll not ask for the moon, here.
Important note: DO NOT INDUCE SCROLLING in the Window to show the matching paren.

I sorely miss this feature in the VBIDE/VBA sometimes!

**Comment by WaynePhillipsEA** [comment]
tB already does this.  It shows a box around the current matching pair when the cursor is at the start/end position.

Perhaps the current box is too subtle?   I know in recent versions of VS Code they now use color highlighting of them, so perhaps we can look at that.

**Comment by WaynePhillipsEA** [comment]
Highlighting of bracket pairs is now an option available via the IDE settings (IDE > Tools menu > IDE Options) in BETA 155.  Thanks!
