### ISSUE TITLE
Cls statement caused Run-time error 91 (0000005B)

### ISSUE THREAD

**Issue by leadron** [twinbasic/twinbasic#1263]
Bug :
Me.Cls
Me.Line (PointX, PointY)-(CenterX, CenterY), vbBlack
I guess statements above caused Run-time error 91 (0000005B)
I put em in a Sub and called it from Command1_Click and Form_Resize which looks something like this :

```
Private Sub Command1_Click()
    rotateVector PointX, PointY, 1, CenterX, CenterY
    ReDraw
End Sub

Private Sub Form_Resize()
    CenterX = Me.ScaleWidth / 2
    CenterY = Me.ScaleHeight / 2
    ReDraw
End Sub

Private Sub ReDraw()
    Me.Cls
    Me.DrawWidth = 1
    Me.Line (PointX, PointY)-(CenterX, CenterY), vbBlack
End Sub 
```

OS :
Windows 10 Pro
Version 21H2
OS Build : 19044.1620
Windows Feature Experience Pack 120.2212.4170.0

Compiler version :
twinBASIC_IDE_BETA_148
COMPILER[Win32]v0.15.148

Screenshots :
https://discord.com/channels/927638153546829845/927641542150197288/1030694710005727252
https://discord.com/channels/927638153546829845/927641542150197288/1030700321535692842
![001_Callstack](https://user-images.githubusercontent.com/31407323/195969661-7dfd39c2-edff-442c-970a-ba5d93ab1ada.PNG)

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  Where were these being called from? (e.g. button click event, Form_Load event etc).   A snapshot of the callstack panel might be useful in this instance.

**Comment by WaynePhillipsEA** [comment]
Is this still an issue?

**Comment by leadron** [comment]
I think it's no longer a problem now, thanks for fixing it ;)
