### ISSUE TITLE
Do While statement on local interface members has invalid Intellisense

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1264]
**Describe the bug**
If you have an interface IFoo, and start a loop with Do While IFoo. when you type the . Intellisense just shows a general list of completely unrelated stuff. Further, when you do type the member name and ( the argument list isn't found; it's just a blank rectangle for Intellisense. 

**To Reproduce**
Define interface with functions
Attempt to use with Intellisense

**Expected behavior**
It should be able to identify the interface names and arguments like when used in other situations.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.148

**Additional context**
At first I thought this might  be related to [ PreserveSig ], but I confirmed it was the same for interfaces without any PreserveSig members (that still had at least one Function from returning the last parameter).

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 155, thanks!
