### ISSUE TITLE
Show method accepts only 1 argument

### ISSUE THREAD

**Issue by leadron** [twinbasic/twinbasic#1265]
**Describe the bug**
Show method accepts only 1 argument, while in VB if Modal = vbModal, we pass additional argument (Owner)

**To Reproduce**
1. Create 2 forms (Form1 and Form2) and 1 Button (Command1)
2. Call Form2.Show with argument vbModal
```
Private Sub Command1_Click()
    Form2.Show vbModal, Me
End Sub
```

**Expected behavior**
Form2 should appear and Form1 cannot respond to the user until Form2 is closed.

**Screenshots**
![002_Show](https://user-images.githubusercontent.com/31407323/195970938-953750fc-1c0c-491c-ab0a-e4ea462a03cc.png)

**Desktop (please complete the following information):**
OS :
Windows 10 Pro
Version 21H2
OS Build : 19044.1620
Windows Feature Experience Pack 120.2212.4170.0

Compiler version :
twinBASIC_IDE_BETA_148
COMPILER[Win32]v0.15.148

**Comment by WaynePhillipsEA** [comment]
Indeed, this is a known issue in that the Show method is only partially implemented. 

As the Show method is listed in the big UI thread (#1188), I'll close this in favour of that.   This will be worked on soon.  Thanks!
