### ISSUE TITLE
FileListBox.Pattern doesn't support multi filter

### ISSUE THREAD

**Issue by leadron** [twinbasic/twinbasic#1266]
**Describe the bug**
I'm not sure if this is a bug or not yet implemented, but apparently FileListBox.Pattern doesn't support multi filter

**To Reproduce**
1. Create a FileListBox
2. Put `*.bmp;*.jpg` on Pattern property
3. Navigate the path to the folder containing both types of files (bmp and jpg)
4. The list doesn't show anything

**Expected behavior**
The list should display both bmp and jpg file types

**Desktop (please complete the following information):**
OS :
Windows 10 Pro
Version 21H2
OS Build : 19044.1620
Windows Feature Experience Pack 120.2212.4170.0

Compiler version :
twinBASIC_IDE_BETA_148
COMPILER[Win32]v0.15.148

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 150, thanks for reporting.
