### ISSUE TITLE
'Minimum size' code works to limit Form size in VB but not tB

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1267]
**Describe the bug**
I typically use this quick and ugly method to limit Form size;

```
Private Sub Form_Resize()
        If Me.Height < (582 * Screen.TwipsPerPixelX) Then Me.Height = (582 * Screen.TwipsPerPixelX)
        If Me.Width < (348 * Screen.TwipsPerPixelY) Then Me.Width = (348 * Screen.TwipsPerPixelY)
```

I use the similar 

```
    Private Sub Form_Resize() Handles Form.Resize
        If Me.Height < 582 Then Me.Height = 582
        If Me.Width < 348 Then Me.Width = 348
```

in tB. This result in heavy flickering in either case, but in VB it always winds up correctly limiting the Form size to the given values. In tB, it does not.

**To Reproduce**
Use code above. Continually resize Form, moving mouse slowly once you're in the flickering stage.

**Expected behavior**
I know this is far from the ideal method (but you need to subclass for that), but it serves it's purpose.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.148

**Additional context**
It has to be dropping some resize messages; with the simple code above unless you move it into the negatives and trigger an error it should never not execute that code.

**Comment by sokinkeso** [comment]
I think that is better for this situation to have extra properties for the form, in A property group named "constraints". 
The property names could be:
MinWidth, MaxWidth, MinHeight, MaxHeight.
This would be a nice enhancement for tB

**Comment by fafalone** [comment]
That would certainly be ideal yes. Currently you have to subclass and respond to WM_GETMINMAXINFO to do it effectively.

**Comment by dmrvb** [comment]
I found the flicker much worse on some VB forms than others, I expect it relates to the number and type of controls.
Subclassing is the way to fix this.
Additional form properties would be great, but once again if we have nice safe easy subclassing that would be good enough for me.

**Comment by fafalone** [comment]
No longer an issue.
