### ISSUE TITLE
Fixed single Forms allow Maximize

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1268]
**Describe the bug**
In  VB, Forms with the Fixed Single border style do not have a minimize/maximize button in the titlebar. In tB, they do, and worse, it actually allows maximizing, resizing forms not meant to be resized.

**To Reproduce**
New StdExe with fixed single border.

**Expected behavior**
No Min/Max, like VB.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.148

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 150, thanks for reporting.

**Comment by fafalone** [comment]
This issue has recurred in recent versions.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 411.  Thanks
