### ISSUE TITLE
Space chars (at beginning) are not displayed in label controls.

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1269]
**Describe the bug**
Space characters are not displayed at the beginning of the text assigned in the "Caption" property of label controls (at design time and at run time).
I think this happen since recent implementation of lightweight controls.

**To Reproduce**
1. Add a label control to the form.
2. Set Alignment property to vbLeftJustify (for a better visualization of the problem).
3. Enter a text in the Caption property.
4. Add one or more space characters at the beginning of this text, you will see that the added spaces do not affect the text displayed in the control.

**Expected behavior**
The text should be displayed in the control as in his caption property.

**Desktop (please complete the following information):**
 - OS:  Windows 10 21H2 x64
 - twinBASIC compiler version 0.15.149

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 150, thanks for reporting.
