### ISSUE TITLE
twinBASICloader

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1270]
I have created a simple twinBASIC loader, see it attached in .zip format. If you unzip it, it contains two files  
-TWBloader.exe
-setup.ini
.
Simple app, doesnt need installation, and without UI. It find the newest twinBASIC_IDE_BETA_xxx folder in the "downloads" folder, and run the newest twinbasic.exe.
Place a shortcut icon of the TWBloader to the Windows desktop.
.
It can check if a newer twinBASIC version exist on the GitHub (twinBASIC_IDE_BETA_xxx + 1) and if so, then opens the GitHub releases page on the browser.
.
In setup.ini you can select (true/false):
- delete twinBASIC_IDE_BETA_xxx.zip files
- delete older twinBASIC_IDE_BETA_xxx folders, except for the new, actual one of course. :)
default selection false, false now.
.
[ download link removed by @WaynePhillipsEA ]

**Comment by WaynePhillipsEA** [comment]
@DinyaZ 

Thanks for sharing, and I appreciate your efforts, but please only post source code for anything you share on here.  No EXEs or any other binary files.

In addition, this is the wrong place to post this.  GitHub "Issues" are for bug reports and feature requests only.  If you'd like to post this in the "Discussions" area, or on Discord, with source code and no binary files, that would be much appreciated.
