### ISSUE TITLE
With IDE Beta 149 parsing of edits in an existing project has become very slow.

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1271]
**Describe the bug**
Parsing of code in an existing project has become slow with edits taking 10s of seconds to be fully parsed. This issue does not occur in Beta 148 or Beta 141, the two previous versions I have tested.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the project
2. edit the code

**Expected behaviour**
parsing of the edits should take 1-2 seconds ish.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Beta IDE 149

**Additional context**
Here is the project file.
[Lib.zip](https://github.com/twinbasic/twinbasic/files/9794142/Lib.zip)

**Comment by fafalone** [comment]
It does seem a little laggier for me, but 2-3s, not 10s of seconds, even in ucShellBrowse project that's 50k lines and hundreds of errors from unimplemented features. (I'm working on preparing it for x64, which will take weeks, I want to have it ready to go as soon as we can use .ctls).

**Comment by FullValueRider** [comment]
Here's a screen recording of entering the following
```
Public Function Test() as Long
End Function
```
Takes from +15 sec to + 2 min.


https://user-images.githubusercontent.com/81257042/196126416-d3085d59-4f6b-4914-b786-1e547c86f57d.mp4

**Comment by WaynePhillipsEA** [comment]
It's fixed in todays release later today.

**Comment by FullValueRider** [comment]
Your productivity ans responsiveness to issues never ceases to amaze me ;-)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 150, thanks for reporting.
