### ISSUE TITLE
Function return types show Long/LongLong instead of LongPtr; sometimes don't show type at all. 

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1273]
**Describe the bug**
I find myself constantly rechecking if I declared something right when the info popup for a function either shows Long/LongLong instead of LongPtr; and for some APIs, it doesn't show the return type at all. 

**To Reproduce**
Look at info popups for APIs.

`Private Declare PtrSafe Function DefSubclassProc Lib "comctl32.dll" Alias "#413" (ByVal hWnd As LongPtr, ByVal uMsg As Long, ByVal wParam As LongPtr, ByVal lParam As LongPtr) As LongPtr`

is one that won't show the return type. 

**Expected behavior**
It would be very helpful to see LongPtr when it's the return type, especially since it shows that for arguments.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.149

**Additional context**
I could have sworn I was seeing another place it did the Long/LongLong instead of LongPtr but now I can't find it... will update if I do.

**Comment by WaynePhillipsEA** [comment]
The missing return type is fixed in BETA 150, thanks for reporting.

If you have repro steps for the Long/LongLong vs LongPtr issue, I'll gladly look at it also.

**Comment by fafalone** [comment]
I'm still looking for the APIs I saw doing it but if you open up e.g. my TBEventTrace project and look in Form1.InitLV, you'll see the CreateListView function right above it returns a LongPtr but the help shows Long/LongLong.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 154.  Thanks!
