### ISSUE TITLE
SendKeys function missing

### ISSUE THREAD

**Issue by mika76** [twinbasic/twinbasic#1274]
**Describe the bug**
[SendKeys](https://learn.microsoft.com/en-us/office/vba/language/reference/user-interface-help/sendkeys-statement) is not implemented.

**To Reproduce**
Use `SendKeys"{tab}"` in any vb6 code

**Expected behavior**
To be recognised

**Screenshots**
![Screenshot 2022-10-18 at 11 01 13](https://user-images.githubusercontent.com/229311/196386252-dc92fff5-d598-4e0b-bf4e-deafae1db61e.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC IDE Beta 150

**Comment by Kr00l** [comment]
I find this [SendKeys source code](https://github.com/lallousx86/SendKeys) quite good.

**Comment by Kr00l** [comment]
Or, for the time being, include a quick solution for the VBA lib
```
Public Sub SendKeys(ByRef Text As String, Optional ByRef Wait As Boolean)
CreateObject("WScript.Shell").SendKeys Text, Wait
End Sub
```
Until you have the resources to provide an independent cross-platform solution..

**Comment by WaynePhillipsEA** [comment]
That's a great idea @Kr00l!

**Comment by WaynePhillipsEA** [comment]
Suggestion from @Kr00l is now implemented in BETA 291.  Works also on X64, so I'll consider this done for now.  Thanks all
