### ISSUE TITLE
too few arguments, even though enough arguments are specified.

### ISSUE THREAD

**Issue by foolonthedesk** [twinbasic/twinbasic#1276]
**Describe the bug**
win32 API MultiByteToWideChar has 6 arguments as below.

 Private Declare Function MultiByteToWideChar Lib "kernel32" (ByVal CodePage As Long, ByVal dwFlags As Long, ByVal lpMultiByteStr As Long, ByVal cbMultiByte As Long, ByVal lpWideCharStr As Long, ByVal cchWideChar As Long) As Long

But twinBASIC IDE insists that too few arguments, even though enough arguments are specified as next screenshot. 

**Screenshots**
![image](https://user-images.githubusercontent.com/114799657/196635523-fc2f01b3-2129-4f3a-b81a-6e746ac4d375.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 151

**Additional context**
This module is in an impoted vb6 project.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 154.  Thanks!
