### ISSUE TITLE
Public and private declare statements get mixed up - at least in the GUI

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1278]
**Describe the bug**
I have some declares public and same ones declared as private in some different modules
In VB6 they do not conflict and work like designed. In twinbasic some get not recogniced or shows up as ambigious which will produce a error.

**To Reproduce**
Create a few modules with declare statements.
Some as public, some without private or public declarations and some as private with the same name in another module. 
Call the declared functions in a sub or function.
Use Vb6 to be sure that the declares are fine.

Import to TB 
See whats get mixed up

**Comment by WaynePhillipsEA** [comment]
I'd appreciate if you could provide a VB6 project for demonstrating the problem here.

**Comment by WaynePhillipsEA** [comment]
Further information was not provided, so closing this.  Thanks.
