### ISSUE TITLE
Input in console mode

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1279]
Input in standard basic is very limited in console mode. Some kind of textinput box would be nice where you has the normal cursor functions availeable to input any data. Even this will open a wide range of wishes wich ends up in implement something like VB 1.0 :) Would make some youngsters jelous whats been possible with a plain text console like in the good old days ;)

**Comment by sokinkeso** [comment]
Good morning, I'm writing here because your "wish" is similar to a discussion I had with Wayne about console. 
So , only as a reminder to Wayne, about a console class with methods and properties, that will be automatically included in console apps, I'm adding this comment.
