### ISSUE TITLE
Popup help shows static arrays as undimmed variable arrays

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1280]
**Describe the bug**
If you have a Type with a static array, the info popup for that type will show it as Var() instead of Var(2) etc.

**To Reproduce**
```
Private Type Foo
    Bar(0 To 3) As Byte
End Type

Private Sub Test()
Dim t As Foo
End Sub
```
Hover on the Foo in t As Foo. It will show "Bar As Byte()". This also applies to API declarations and Sub/Function arguments using the Type. 

**Expected behavior**
It should show the dimensions when static. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.152

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 154.  Thanks!
