### ISSUE TITLE
ComboBox/DriveListBox CloseUp Event (CBN_CLOSEUP)

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1281]
**Is your feature request related to a problem? Please describe.**
Counterpart of already existing DropDown event is the CloseUp event.

**Describe the solution you'd like**
CloseUp Event in response to CBN_CLOSEUP

**Describe alternatives you've considered**
n/a

**Additional context**
This event does not exist in VB6, but it's a low hanger and quickly added.

**Comment by WaynePhillipsEA** [comment]
Yep, that's a good one. Thanks

**Comment by Kr00l** [comment]
added DriveListBox, doesn't harm to add CBN_CLOSEUP here as well since it has also CBN_DROPDOWN.

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 154.  Thanks!
