### ISSUE TITLE
controls disappear when "re-showing" a form

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1283]
**Describe the bug**
When we show a form (in the example, Form2 with a picturebox and a label), everything works fine until we close it and show it again, which is when some controls visually disappear (the label) and others seem to be destroyed being unable to access their properties.

**To Reproduce**
Run the attached project.

**Expected behavior**
The form should be displayed every time with no problem.

**Screenshots**

https://user-images.githubusercontent.com/2956806/201890739-19a8be1b-e9fa-4b4e-8c43-4d954aac1a4a.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - twinBASIC compiler version 0.15.153
 

[reshowing_form_bug.zip](https://github.com/twinbasic/twinbasic/files/9839498/reshowing_form_bug.zip)

**Comment by marcoslm** [comment]
Update: 
It works correctly if we destroy Form2 after it is closed. May be tB is not destroying all controls/objects when closing the form.

`Private Sub Command1_Click()
        Form2.Show vbModal
        Set Form2 = Nothing
End Sub`

**Comment by marcoslm** [comment]
I tested it on Beta 273 and this bug no longer occurs. I don't know from which release it was fixed, but I suppose this issue can be closed now, so with your permission, I'll close it.

**Comment by WaynePhillipsEA** [comment]
Great! Thanks for the update
