### ISSUE TITLE
Form MaxHeight property is not working alone

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1284]
**Describe the bug**
If MaxHeight is set to a value<>0 and MinHeight =0 then MaxHeight is not work as size limit.

**To Reproduce**
Set MaxHeight to a value<>0 and leave MinHeight =0

**Expected behavior**
To work as max limit

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC BETA_154

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 155, thanks!
