### ISSUE TITLE
Used Memory of the running process shown

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1287]
**Is your feature request related to a problem? Please describe.**
I guess al ot of problems arise cause peoples do not get aware that the program they develop has a memory hole.

**Describe the solution you'd like**
Showing used memory during debug time (titlebar, status line)

**Describe alternatives you've considered**
Seekeing endless in a big project to find the memory leak even it could be detected on first sight

**Comment by WaynePhillipsEA** [comment]
There is an option in the IDE settings for monitoring the memory and resource usage in recent builds, therefore in closing this now.  Thanks
