### ISSUE TITLE
Registry entry cannot be read

### ISSUE THREAD

**Issue by AWSMunich** [twinbasic/twinbasic#1288]
**Describe the bug**

.RegRead("HKLM\" & aP_Section & "\" & aP_Key & "\")  is not working and run into an error Err.number = -2147352567
aP_Section="SOFTWARE\Microsoft\Office\ClickToRun\Configuration"
aP_key="Platform"

.RegRead("HKLM\" & aP_Section & "\") is working fine.

**To Reproduce**

**Expected behavior**
X86 or X64 expected

**Screenshots**
![Twinbasice_2022-10-23 183723](https://user-images.githubusercontent.com/116510151/197405995-b43d07f1-dbfb-4b10-b1f7-7fb2d82a31c3.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version [e.g. 0.15.0155]

**Additional context**

**Comment by fafalone** [comment]
Probably going to need see what the RegRead function is doing, which call is actually raising the error.

**Comment by WaynePhillipsEA** [comment]
From what you've posted so far, it looks like you're missing delimiters, e.g. between "HKLM" and aP_Section.   It would be much better if you could provide a complete example routine to demonstrate the problem.  It's probably also worth checking that the same example also fails on VB6 or VBA, just to be sure that this is a twinBASIC issue.

**Comment by AWSMunich** [comment]
You are right. I copied the command from VB.net project where it works and not from a VBA code where it si NOT working to,
Issue is solved.

Thank you.

**Comment by wqweto** [comment]
@AWSMunich Btw, the way I see is that this issue tracker is for bugs in TB compiler and/or IDE only.

I cannot see how can one connect an error in some `RegRead` method (which ever object this is on) with some problem with the TB compiler to raise an official issue here.

You might better try creating a [[discussion](https://github.com/twinbasic/twinbasic/discussions) in the repo about troubles with porting some code of yours to TB or even better chime in to [TB's Discord server](https://discord.gg/UaW9GgKKuE) to chat freely with other follow developers and Wayne in particular.
