### ISSUE TITLE
Color panel positioning problem

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1290]
**Describe the bug**
If I click on the color selector (backcolor, fillcolor, forecolor), the panel comes up with wrong positioning, out from the display.

![Image2](https://user-images.githubusercontent.com/94013032/197477511-8820ee17-cafa-4e5a-b056-0fad60ae0651.jpg)

**Expected behavior**
if colorpanel.left+colorpanel.width>me.width then colorpanel.left=me.width-colorpanel.width

**Comment by WaynePhillipsEA** [comment]
I'm pretty sure this got fixed since time ago, so let's close this now.  Thanks
