### ISSUE TITLE
Add TextBox property "Numbers only"

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1295]
**Is your feature request related to a problem? Please describe.**
This is a commonly used feature, and it's a low hanging fruit that's very simple to add.

**Describe the solution you'd like**
Add a 'Numbers only' option that toggles the ES_NUMBER flag on a textbox.

**Describe alternatives you've considered**
Doing it via API, not friendly to beginners.

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 157, thanks!
