### ISSUE TITLE
Ambiguities between packages and project/packages not resolved

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1296]
**Describe the bug**
If something, e.g. constants/enums, is defined in multiple packages, you're unable to use both packages as they're treated as ambiguous. Further, local definitions should take precedence over references and not be marked ambiguities. 

**To Reproduce**
Define same const/enum/etc in project and packages added as references.

**Expected behavior**
These ambiguities should be permitted and resolved according to the existing ruleset: Local project takes first priority, then packages are processed according to the order in the reference list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.156
 
**Additional context**
As tB grows, allowing packages to be mutually exclusive over constants etc could be a significant problem; people will likely want some packages that have at least 1 conflict with others.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 161, thanks!
