### ISSUE TITLE
Infinite compiler restart loop after typing Private Type ... (unknown circumstances)

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1297]
**Describe the bug**
I was working on a new project and everything was going fine. But I reached a certain point and it now goes into an infinite restart loop after I type in 'Private Type whatever', at least until I can get it commented out or deleted again between restarts. I've tried exiting tB completely, as well as exiting all tB instances completely, and restarting, but it just does it again, so it's not just a random fluke. I also tried some previous versions and it happens as far back as I checked (142). 

**To Reproduce**
UPDATE: I've tracked the cause down and it's a weird one. Simply having StrPtr in code triggers it. I can't figure out what is it about the syntax here that's problematic, because obviously this isn't happening in most projects using StrPtr. Even in the same way. But this is reliably happening in every version of tB I try, in every new form (but not existing ones?)

1) Create new standard EXE

2) In Form1, add

```
Class Form1
' private type fkhf
    Sub New()
    what(StrPtr(a))
    End Sub

End Class
```
Uncomment the `Private Type` or attempt to add a new one.

**Expected behavior**
No restart loop :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.156

**Additional context**

**Comment by fafalone** [comment]
Some more experiments:

```
' Private Type wtf
    Sub New()
    Dim a As String
    If StrPtr(a) Then
    	MsgBox "..."
    End If
    End Sub
```
Does *not* trigger it. But
```
' Private Type wtf
    Sub New()
    Dim a As String
    If b(StrPtr(a)) Then
    	MsgBox "..."
    End If
    End Sub
```
does, regardless of whether b is defined. 

I'd love to know the details behind this when you solve it :)

**Comment by WaynePhillipsEA** [comment]
Already fixed ready for next release.   In trying to resolve the UDT members, on encountering what it has determined to be an array member, the compiler tries to resolve the array bounds, so it tried to evaluate `StrPtr(s1)`.  But during this process there was a missing error flag check, and so it overlooked the important detail that `s1` wasn't resolved.  This led to bad codegen which got executed and trashed the stack.

**Comment by fafalone** [comment]
But this was occurring whether or not there were any unresolved symbols; originally, s1 was declared, and in the 2nd example, adding

```
Function b(c As LongPtr) As LongPtr
b = c
End Function
```
still leaves it happening?

i.e. I can paste the error-free code

```
' Private Type wtf
    Sub New()
    Dim a As String
    If b(StrPtr(a)) Then
    	MsgBox "..."
    End If
    End Sub

Function b(l As LongPtr) As LongPtr
b = l
End Function
```
into a brand new project, and it will go into the loop when I uncomment the type.

**Comment by WaynePhillipsEA** [comment]
The compiler has to interpret everything following the `Type` header as part of the UDT... so it's not parsing 'code' at that point... it's trying to parse everything that follows as UDT fields (since the UDT was not closed)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 157, thanks!
