### ISSUE TITLE
Menu Editor

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1299]
**Describe the bug**
1)
The current Menu Editor doesn't allow to shift menu items from one main menu to another.

2)
When selecting a PNG file for the picture, there is no transparency.

**Expected behavior**
A text or list Menu Editor would be handy.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 157

**Comment by WaynePhillipsEA** [comment]
I note that transparency for PNGs in menu items is now working since the changes in BETA 159 for PNGs support.  You'll need to reset the Picture property to the PNG file in the designer, as the PNGs were converted to bitmaps in earlier versions.

**Comment by WaynePhillipsEA** [comment]
Movement between menus is now possible using Cut/Copy/Paste as available in BETA 160.   In future you'll be able to drag'n'drop them around, but for now this should work acceptably.

With the transparency issue seemingly already now fixed, I'll close this.  Thanks!
