### ISSUE TITLE
INTEGER and LONG can not be given to a double by reference

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1300]
**Describe the bug**
Function d2s(d As Variant) As String
    d2s = Trim(str(d))
End Function

or 
Function d2s(d As as double) As String
    d2s = Trim(str(d))
End Function

shoud be able to consume integers or longs without need to convert explicit using  CDBL(). The type conversion from integer or long should be done automatically like in VB6

Add the code in some module and try to get a string from a integer without using CDBL in that call

**Comment by WaynePhillipsEA** [comment]
This looks perfectly correct to me.  The DOUBLE version is invalid in VBx also.  The VARIANT version is allowed, same as VBx.

```
Function d2s(d As Double) As String
        d2s = Trim(Str(d))
    End Function
    
    Public Sub Test()
        Dim ALong As Long
    	d2s ALong
    End Sub
```

Above fails in VB6 with compile error of `ByRef argument type mismatch`.   I'm closing this, since the information given is either wrong or incomplete.

**Comment by rexxitall** [comment]
I just wonder why that code works perfect in vb6 without issues, it works for years in VB7 and you think a integer can not be put into a double without Cdbl.

**Comment by WaynePhillipsEA** [comment]
You haven't provided an example that works in VB6 and doesn't work in tB.   I've provided example code that shows, given the minimal information provided, that it is disallowed in both VBx and tB.

Please provide a full example that demonstrates it working in VB6 and failing in tB, and then of course I will re-open the issue.

**Comment by rexxitall** [comment]
Not true you  has the whole thing as zip file :) Ther you can also see and reproduce all the other bugs i mentioned today

**Comment by rexxitall** [comment]
I  send it to you via discord few seconds ago

**Comment by WaynePhillipsEA** [comment]
Just for reference, the real issue here is now covered by #1305
