### ISSUE TITLE
Message boxes should apear in middle of the screen

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1301]
Any message boxes of the IDE which tells the user something should be apear centered in the application like in VB7 not in the lower  right corner.

**Comment by WaynePhillipsEA** [comment]
It depends on the context.  Not all messages need to be modal.  Some are just notifications, and displaying less prominently in the lower right corner works fine IMO.

If you see a message appear in the notification window that you think should be a more prominent, modal dialog, please open a specific issue for that issue.  Thanks!
