### ISSUE TITLE
Form name not recognized

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1302]
The name of the form is not given to the compiler

![image](https://user-images.githubusercontent.com/22050310/197768570-cdc409f5-a847-42c0-97e7-19621a6d0e94.png)

[SURF.zip](https://github.com/twinbasic/twinbasic/files/9860083/SURF.zip)

**Comment by WaynePhillipsEA** [comment]
The name of the form given by the form property is not currently authoritative.   Actually, it is currently ignored, and only the name of the Class declaration currently matters.

It is a known bug discussed elsewhere, but I don't see an issue on here for it.  However, I'm going to merge with #1303 as it's more or less the same issue.  Thanks.
