### ISSUE TITLE
ReDim statement ignores datatypes suffixes

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#1305]
**Describe the bug**
`ReDim` statement ignores datatype suffixes.

**To Reproduce**
`ReDim Foo&(123)`

**Expected behavior**
`Foo` should be interpreted the same as `ReDim Foo(123) As Long`.  It currently gets interpreted as `ReDim Foo(123) As Variant`, as well as issuing a Variant warning.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 158

**Comment by mburns08109** [comment]
Wait a sec...I'd always thought that the data type of a given array variable was set ONLY on the initial DIM statement defining the array, and that ReDIM was limited to resizing the array, and not anything like changing the type of the array contents.

Is this true, or have I missed something significant like this for the last 3 decades or so?

**Comment by wqweto** [comment]
When `Dim Foo As Variant` then `ReDim Foo(0 To 100) As String` and `ReDim Foo(0 To 100) As Long` are both valid.

**Comment by mburns08109** [comment]
Oh! So, because "as variant" on a Dim implies that _it **may** be an array_, the redim can do "whatever it wants" later then, eh? That is a subtlety that I have indeed missed on knowing about over the years, then. Hmrph. learn something new every day indeed.

**Comment by mburns08109** [comment]
Actually, thinking a bit more on that...I'm wondering if the;
`Dim X as variant
...
ReDim X(whatever) as MyClassTypeHere
`
could ever be considered as a "Good Idea"(TM) in actual use, or something more prone to be an invitation to abuse by unscrupulous hacker-types (and therefore something to be avoided)?

**Comment by wqweto** [comment]
There is no problem using Variant variables/params to store SAFEARRAYs, no hacking possible.
