### ISSUE TITLE
Hang on Import VBP 

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1307]
**Describe the bug**
Attempt to import a VBP fails.
tB is busy but no result.
tB has to be killed then.

**To Reproduce**
1. Unzip the project
[2022-10-26_ImportFail.zip](https://github.com/twinbasic/twinbasic/files/9868212/2022-10-26_ImportFail.zip)
2. In tB, try to import the project.
3. Please wait spins forever.

**Expected behavior**
Import should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 157

**Additional context**
I very know that the project is crappy.
Variants where strings should be etc..
Nevertheless it does it's job in VB6.

**Comment by WaynePhillipsEA** [comment]
Could you check if it still fails in BETA 158 released yesterday, as I suspect this was already fixed?  Thanks

**Comment by KarlSevenSeven** [comment]
So sorry I didn't check in the current version.
And yes, works in 158.
Thank you.
