### ISSUE TITLE
New menu button behavior

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1309]
**Is your feature request related to a problem? Please describe.**
A small enhancement for the form menu would be to add new item when the green button [+] is clicked.
Now when we click for new item after editing the existing, like in the picture:
![Screenshot 2022-10-28 201528](https://user-images.githubusercontent.com/113173954/198695037-ef41e1a8-c253-4b6b-afd0-77ecacf05678.jpg)
the edited item is saved and we have to click again on the button for the next item.

**Describe the solution you'd like**
IMO it would be better behavior if when clicking on the add button [+] , then current item is saved and a new item is created.

**Describe alternatives you've considered**

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 162, thanks!
