### ISSUE TITLE
Windowless controls resize problem with anchors enabled

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1310]
**Describe the bug**
The label and image controls (windowless) flip horizontal and/or vertical when resizing a form and anchors left&right or top&bottom are enabled.

**To Reproduce**
Add a button and a label on a form, enable all anchors in both controls run the project and resize the form.

**Expected behavior**
To resize as the normal windowed controls

**Screenshots**

https://user-images.githubusercontent.com/113173954/198715931-2474392a-a1d5-4d3e-b158-15004a19c42d.MP4

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - twinBASIC IDE_BETA_161

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 162, thanks!
