### ISSUE TITLE
Web View has problems with encoding special chars

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1311]
**Describe the bug**
Add a weg view and enter a url in the url property
Run it to see the Web page. In my case the dot was the problem. 

![image](https://user-images.githubusercontent.com/22050310/198733087-ad669d44-3898-49cb-919e-9760ef09a896.png)

**Comment by WaynePhillipsEA** [comment]
It looks like you incorrectly entered a comma, not a dot.   i.e.   `https://google,de`.   So, the comma getting URI encoded is correct behaviour.

**Comment by rexxitall** [comment]
I need bigger screens or better glases :) Sorry i get too old :D
