### ISSUE TITLE
Checkbox Forecolor

### ISSUE THREAD

**Issue by animalnitrate** [twinbasic/twinbasic#1312]
**Describe the bug**
Unable to change Checkbox ForeColor in IDE or at runtime.

**To Reproduce**
1. Code run at startup: CheckAppTask.ForeColor = &H999999

**Expected behavior**
Expect text color of the Checkbox to be light-gray.

**Screenshots**
Screen shot of IDE change included.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version beta-x-0161 

![tmp](https://user-images.githubusercontent.com/116934988/198814162-9cd45c1d-ffca-4673-9cb9-29e1baad5f19.png)

**Comment by WaynePhillipsEA** [comment]
When VisualStyles are in effect, this is normal correct behaviour.

To turn off VisualStyles for the individual control, set the VisualStyles property of the control to False in the property sheet.     Or, to turn off VisualStyles for the whole application, you can delete the `#1.xml` file in the `Resources\MANIFEST\` folder of your project.
