### ISSUE TITLE
Web view backround transparency

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1313]
To get rid of user control issues or rapid prototyping it would be useful to set the veb view control backround and border color to some kind of transparency. Which would help game developers as well a lot. On this case custom styled controls could be more easy to implement. Like floating dialogs over the game world fitting to the design.

**Comment by WaynePhillipsEA** [comment]
If we allow the new Opacity and TransparencyKey properties on child controls as discussed on Discord (via a project OS-target setting of Windows 8+), then you will get your wish.

However, note that every instance of WebView2 creates several external processes to handle rendering and JavaScript execution in isolation etc, and as such the idea of having individual controls each running WebView2 instances could require a beefy PC.

I'm going to close this for now in favour of the more general discussion of allowing child controls to have Opacity/TransparencyKey, which I will open a new issue for shortly.

**Comment by WaynePhillipsEA** [comment]
See #1317
