### ISSUE TITLE
Multiline tooltip text

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1318]
**Is your feature request related to a problem? Please describe.**
I think that a multiline tooltip text would be a nice improvement for tB

**Describe the solution you'd like**
I imagine something like this in the picture:

![tooltiptext_multiline](https://user-images.githubusercontent.com/113173954/198876946-d15aae6c-73e6-4022-810f-94f7b59c3572.png)

**Additional context**
In the future , it could also has title, border, and RichText (bold, italics ..etc).
But for now I think that just multiline is already a step forward from VBx

**Comment by rexxitall** [comment]
Love it :) And also if the tooltip apears on the screen where the control is visible. This is in VBx not the case. And for sure the colors should be able to set as property. At least in the code :) White tips on a dark UI might not be what a designer wants :) Just as idea multiline text in the propertys and a tooltip custom control where you can specify the global settings until they are overidden by code for ultimate flexibility ;)

**Comment by WaynePhillipsEA** [comment]
Multi-line tooltips now supported as of BETA 567.  Thanks

**Comment by rexxitall** [comment]
:) Thanks, after fighting cancer two years i hope i am in a better mood now. So i hope we can have a friendly restart.
