### ISSUE TITLE
IDE resets/hangs when writing code statements

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1322]
**Describe the bug**
IDE is constantly restarting as we write in the code editor. It even hangs.

**To Reproduce**
Just write some code in the editor.

**Expected behavior**
A normal behavior ;-)

**Screenshots**

https://user-images.githubusercontent.com/2956806/199034230-4e7cf48a-143a-4eae-bc73-3468b952b060.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - twinBASIC compiler version v0.15.164

**Comment by FullValueRider** [comment]
I'm noticing this as well.  In addition, it has become impossible to rename a .cls file to .twin and then edit it.

**Comment by WaynePhillipsEA** [comment]
Apologies.  This is now fixed in BETA 165.  Thanks for reporting!
