### ISSUE TITLE
Form_Resize erasing API-created controls

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1323]
**Describe the bug**
I have a form with an API created ListView and a couple DateTime controls. When the form resizes, they're erased, and don't redraw until mouseover. If the control is disabled, it will not redraw on mouseover. 

**To Reproduce**
Load a project with (user) API-created controls, such as my Event Tracer. For convenience, I'm attaching a build with the admin check and wow64 check disabled, with a prior version (see additional context). This happens both IDE and fully compiled, 32bit and 64bit. This also happens to externally created windows from COM components, such as IExplorerBrowser.

**Expected behavior**
Controls not being erased.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.165

**Additional context**
This is a regression; TBEventTrace did not display this problem in the past. This seems to have happened quite a while ago; I just hadn't noticed til now since I hadn't tried resizing forms with API controls. This problem begins in Beta 125. My guess is "fixed: added PictureDpiScaling property to Form/PictureBox/Image controls, default True, when False image is rendered as stored" could be related (although setting to False does not resolve it), or "added: all graphical members to Form class to match PictureBox (e.g. Circle, Print, etc)" if other changes were made to implement that.
(Note that while the attached project resizes the API control, on the project I'm developing where I first noticed this, all API controls were erased, including ones not resized or that went into/out of the visible area).

[TBEventTrace22dbg.zip](https://github.com/twinbasic/twinbasic/files/9907639/TBEventTrace22dbg.zip)

**Comment by fafalone** [comment]
If it's easier I've made a minimal reproduction just creating a very simple DateTimePicker control with nothing else on the Form.

[APICtlBug.zip](https://github.com/twinbasic/twinbasic/files/9978981/APICtlBug.zip)

**Comment by WaynePhillipsEA** [comment]
Apologies for not rushing to fix this.  The whole controls refresh/repaint system needs a little bit of refinement, and so this will be looked into at the same time as that.

**Comment by fafalone** [comment]
It's no problem, whenever that is will be fine. I have a temp fix where resize sets a timer to call RedrawWindow a few ms after the resize ends, so it's barely noticeable with that in place.

**Comment by WaynePhillipsEA** [comment]
I'm fairly confident this was resolved in the recent releases, so I'll close this now. Thanks.
