### ISSUE TITLE
VB.Form not supported in tB

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1326]
**Describe the bug**
VB.Form is not supported and gives error [VB] does not contain 'Form'

more generally the members of VB. are very different between VB and tB.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [151]

**Additional context**
I have always used "as Form" and have never used "as VB.Form" myself. I noticed this issue when looking at some code from Krool.

**Comment by WaynePhillipsEA** [comment]
Yes, at the moment most of the UI classes are under `WinNativeForms`, e.g. `WinNativeForms.Form`.  It's about time this got sorted out.  Thanks.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 166, thanks!
