### ISSUE TITLE
Combobox Change event does not work (TB 165)

### ISSUE THREAD

**Issue by haplox** [twinbasic/twinbasic#1327]
**Describe the bug**
The Change event in the Combobox, does not works and is not fired
**To Reproduce**
Simply create a nuew form, populate the combobox in the initialize event, and in the change event put a simple MsgBox

**Expected behavior**
The change event in the combobox to work correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windos 10 Pro x64
 - Versión: 21H2
 - Compilation: 19044.1586
 - twinBASIC compiler version: BETA 165 - License COMMUNITY

**Additional context**
![GIF 03-11-2022 9-51-52](https://user-images.githubusercontent.com/10757873/199680108-2a10934c-02d1-42c2-851a-a28d409c62e2.gif)

**Comment by fafalone** [comment]
The Change event does not fire in VB6 either unless you type in it.

**Comment by haplox** [comment]
Thanks fafalone, The option is to use the Click event, as I have read in tne net

**Comment by sokinkeso** [comment]
@fafalone, is correct, but the is a small difference in behavior between VB and tB.
with this code:

Private Sub Combo1_Click()
MsgBox Combo1.Text
End Sub

VB6 fires the click event after update the text property of combobox, and tB fires the click event BEFORE update the text property. I think this needs fixing for compatibility reasons.

A nice improvement could be a new event (eg  SelectionChange(byval Index as integer)   )

**Comment by haplox** [comment]
@sokinkeso is right. Using the Click event I have to Choose twice the option I want to fire the click event

**Comment by haplox** [comment]
I suspect tha is the same for the click event in listbox... So if the change event does not work and the click event is fully different to VB6, it is a trully problem

**Comment by fafalone** [comment]
You can subclass it for the `CBN_SELCHANGE` and/or `CBN_CLOSEUP` messages.

**Comment by sokinkeso** [comment]
> 

subclass which one? combobox or listbox, and why?
Right now there is an issue with combobox..it is not working like in VBx.
And as I mentioned above, a new event for combo would be an improvement for tB.
Of course subclassing can give much more control, but if some features can exist internally I think it would be much more efficient and convenient for the majority of the users.

**Comment by Kr00l** [comment]
MSDN remarks on CBN_SELCHANGE
`To get the index of the current selection, send the CB_GETCURSEL message to the control.`

So, tB shall send CB_GETCURSEL upon CBN_SELCHANGE and change the text. To be compatible to VB.ComboBox.

In VBCCR I did:
```
Case CBN_SELCHANGE
    Dim SelIndex As Long
    SelIndex = SendMessage(lParam, CB_GETCURSEL, 0, ByVal 0&)
    If Not SelIndex = CB_ERR Then
        If PropStyle <> CboStyleDropDownList And ComboBoxEditHandle <> 0 Then SendMessage ComboBoxEditHandle, WM_SETTEXT, 0, ByVal StrPtr(Me.List(SelIndex))
        Call CheckTopIndex
        RaiseEvent Click
    End If
```

Other side note: tB calls `CheckTopIndexChanged()` **after** the Click event. However, I think it would be better to have the synced top index available upon Click event.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 166, thanks!

**Comment by Kr00l** [comment]
in ListBox/FileListBox/DirListBox you may also move the `CheckTopIndexChanged()` above the Click event.

```
Case ListBoxNotifications.LBN_SELCHANGE
    RaiseEvent Click()
    CheckTopIndexChanged()
```

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l that's also sorted in BETA 167

**Comment by dmrvb** [comment]
The events in the combo are still different to VB6, and wrong.
for a dropdowncombo, if I click on the arrowbox I get: 
gotfocus/lostfocus/gotfocus/dropdown.
if I close and click again (without moving the mouse) I get:
closeup/lostfocus/gotfocus/lostfocus/gotfocus/dropdown

so there is some spurious got/lostfocus going on
Note that VB6 does dropdown Before gotfocus....your tB sequence is better but not compatible.

also, if I select an item from the dropped list I get
closeup/change/click    
in VB I only get click, not change. In VB change only comes from user editing in the textbox field.

The Combobox control is horible to program. Maybe we can make it better in tB.
