### ISSUE TITLE
GetSetting and DeleteSetting partially broken due to not handling Missing optional args properly

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1337]
**Describe the bug**
I originally thought the 'type mismatch' was implicit number to string related, but I've since found it raises a type mismatch on pure string input as well.

**To Reproduce**
New StdExe

Code:
```
Dim sPath As String
sPath = GetSetting("Test", "Name", "Key")
Debug.Print "sPath="
```

**Expected behavior**
This works in VB6, so should work in tB. Currently it raises a 'Type mismatch' error on the GetSetting line.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.169

**Additional context**

**Comment by fafalone** [comment]
This appears to be a more serious bug as CStr(i + 1) also raises a type mismatch.

**Comment by WaynePhillipsEA** [comment]
GetSetting is broken because it is incorrectly handling the Default argument when it is Missing.

**Comment by fafalone** [comment]
Ah yes that would explain it. I didn't know, hence just "completely broken" 👍

**Comment by fafalone** [comment]
Ah yes partially, sorry 😇

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 171, thanks!
