### ISSUE TITLE
Bilding the EXE file in tB170 is reported as virus in Windows 10

### ISSUE THREAD

**Issue by haplox** [twinbasic/twinbasic#1342]
**Describe the bug**
Bilding the EXE file in tB170 is reported as virus in Windows 10. It is reported as **"Trojan:Win32/Wacatac.H!ml (severe)"**
**To Reproduce**
Build you EXE fron you Project

**Expected behavior**
EXE Not to be reported as a virus

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10 Pro x64 - Version 21H2 - Compilation 19044.1586
 - twinBASIC compiler version 170
**Additional context**
![Sin título](https://user-images.githubusercontent.com/10757873/200784173-fd0ab551-4bb1-491e-9a24-57bf58278f01.png)

**Comment by haplox** [comment]
Thanks @WaynePhillipsEA , but... Why is this the first version with which I get my EXE as a virus? I could build my EXEs with previous version without this issue.

**Comment by rexxitall** [comment]
Virus scaner are stupid like hell. By some heuristic magic i got same problem when i wrote something which is using a internet connection or some "special" api calls or just a suspicious var name . I never figured it totally out. Happens also sometimes after they update the virus database.

**Comment by fafalone** [comment]
If you go back to the previous version and compile a new exe from the same code, does that get flagged? 

It's not impossible there's something it finds particularly suspicious. 

But it's still likely something from your code. For comparison, my event tracer forces running as admin, calls a bunch of kernel apis, digs into the memory of other processes, and still is only flagged by 1/71 on VirusTotal, just checked a version built with 170.

**Comment by haplox** [comment]
Right now, with new tB172, the first time I build the exe, the windows antivirus **needs to check it on the net**, and make it sucessfully. The next times I build it, it does it withou any advertisement from the antivirus. showing the folder in the exe in the debug console

In tB163, it makes it without problem, showing the folder in the exe in the debug console.

It seems that something goes on changing in tB with the new versions,

**Comment by WaynePhillipsEA** [comment]
Nothing has changed with regards to the build process. 
 
Many of the decisions anti virus software make, are guesses, usually based on heuristics.  Unfortunately, we have no control over any of it.

**Comment by rexxitall** [comment]
just as q tip avira does not has that issue that often and a nice setup to ignore files. It might not be the best and most secure solution but at least it keep you developing.
