### ISSUE TITLE
TwinBasic Toolbox

### ISSUE THREAD

**Issue by MC67000** [twinbasic/twinbasic#1343]
Hi,
When do think than i can use my own OCX with thinBasic.
I have a big project with a lot of OCX, today i can open my controls, it's very greeat but my own used control are recognized as a picture box. When I add My .dll or .ocx, TwinBasic accept my dll, but my control not appear in the toolbox.
Is it not yet available to use our own ocx? or I have something to do?

**Comment by marcoslm** [comment]
As far as I know, the OCX implementation is one of the pending things in tB. OCX/User Controls is a very important feature that will be a big step forward.
I don't know how the roadmap is currently going, but the development is constant and fast. Wayne is a machine! xD

**Comment by dmrvb** [comment]
I think you can use an OCX now by setting a COM  reference in settings. Ive just tried it and the control appears in the controls pane.
What does not work is importing things as a VB project import, and some intrinsic contriols progressbar for example) also do not yet import (set as picturebox).
