### ISSUE TITLE
Imported VB6 `Return` statement (from GoSub) produces "internal error"

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1344]
**Describe the bug**
I imported some VB6 code which uses Gosub/Return.

tB reported that the final "n" in `Return` was an internal error:

![image](https://user-images.githubusercontent.com/18285074/200847491-6e66bbfd-4d3f-419a-adeb-4ed80ab7ecf3.png)

Full context:

![image](https://user-images.githubusercontent.com/18285074/200847038-d5cafc3f-f4e0-48cc-9627-a4d6acd3e5a1.png)

Text equivalent:

```
    GoSub Cleanup
    Exit Sub

Cleanup:
    Close #nFileHandle
    Return

Handler:
    SaveError
    GoSub Cleanup
    ForwardError LIBRARY_NAME, CLASS_NAME, METHOD_NAME
End Sub
```

---

This error came up on similar lines in a few different places. I noticed though that other cases of `Return` produced a different error - "expected an expression" instead. In fact, these produced TWO errors for the exact same line/char position. The second error was "Sub procedure does not return a value".

These latter cases were from blocks that looked like this:

```
Cleanup:
   Return
```

Something about having multiple lines after the label maybe?

**Expected behavior**
Some more specific / sensible error was expected. And highlighting the entire keyword.

**Desktop (please complete the following information):**
 - OS: Win10
 - twinBASIC compiler version: IDE beta 170

**Comment by Kr00l** [comment]
That's ok for the moment. 
See issue 639 missing syntax GoSub
#639

**Comment by DaveInCaz** [comment]
@Kr00l  aha! Thanks!
