### ISSUE TITLE
Label Contol does not have a Refresh Method

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1347]
**Describe the bug**
Missing functionalirty
No Refresh method on Label control    (it does in VB6).

I have mentioned this before but deep inside another topic, so I thought I should give it its own report.

**Comment by WaynePhillipsEA** [comment]
Thanks.  Yes, this method went missing with the change to making Label a lightweight control.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 180, thanks!
