### ISSUE TITLE
No Move Method

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1348]
**Describe the bug**
Missing Functionality.
VB6 supports a MOVE method for Forms and Controls, tB does not have this.

Move allows resizing a form or control in a single method rather than individual calls to Top,Left,Width,Height.
This can avoid multiple firing of the Resize event so can be useful.

**Comment by WaynePhillipsEA** [comment]
Oops... this was commented out when I was working on the ScaleMode.   Prior versions did support the Move method.

**Comment by AntsAntix** [comment]
At one stage, it seemed that MOVE that had not been implemented (or so I thought). A prompt from Camomille22003's spreadsheet indicated that all 4 parameters are required for Form.Move method. The MOVE method then worked for a Form. But, this was not the implementation in VB6 where only Left and Top properties are required, and Height and Width are optional.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 174, thanks
