### ISSUE TITLE
Label control not scaled properly in design mode when dpiaware = none

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1349]
**Describe the bug**
![image](https://user-images.githubusercontent.com/7834493/201189547-c18cb297-3b0e-454c-bdb4-f681071e68c2.png)

The label, checkboxes, frame, and command button are all size 8 font, but the label is abnormally small. It should scale the same as the others. This only impacts design mode, it's fine during runtime.

**To Reproduce**

-Create a label and other controls

-Set dpi aware to NONE. 

**Expected behavior**
Same scale.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.171

**Additional context**

**Comment by WaynePhillipsEA** [comment]
This was fixed in recent builds.  Thanks.
