### ISSUE TITLE
Screen Flicker during VB Import

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1351]
**Describe the bug**
During import of VB project the white "Please Wait" box has some flicker, it looks like it transiently gets bigger (bottom edge goes lower) before returning to its normal size.

This is a Trivial Cosmetic issue (though these things can detract from new user confidence) but I am reporting because I have only observed it in the latest release (174) so the cause might be fresh in your memory.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 177, thanks!
