### ISSUE TITLE
DEBUG.CLS and friends - make more from the immediate window :)

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1362]
The classical VB6 immediate windows has some features i always missed since DOS times ;)

DBEUG.CLS - clear the debug window by code
DEBUG.COLOR foreground background - Sets output fore and background
DEBUG.LOCATE Xscreen position ,Y screen position - put the cursor to some screen position
DEBUG.INPUT "MESSAGE"; VAR - set some new variable content

**Comment by wqweto** [comment]
Btw, colorful debug output would be a first -- I've never seen anything remotely similar in other IDEs :-))

**Comment by mburns08109** [comment]
Put this in as an actual feature request, then.

**Comment by rexxitall** [comment]
i put it into a feature reques...

**Comment by WaynePhillipsEA** [comment]
`Debug.Cls` (or `Debug.Clear`?) sounds like a reasonable request.

`Debug.Color`   I can see some uses for this, but I'm not really sure that it would be worth the effort to implement.   Anyone else have thoughts on this?  Would you use it?

`Debug.Locate`   I would think it's unlikely we'd go for that one.  The use case is too limited.
`Debug.Input`  Same as above, unlikely.

**Comment by KDGundermann** [comment]
For Logging and Debug outputs I have written a very flexible [Logger](https://github.com/Gugro0/VBA-Logger) 
Maybe I find some time to port it to TB

**Comment by KarlSevenSeven** [comment]
`.Cls` could be really helpful.
`.Color `, is not what I miss today, but I can imagine several uses.
```
If a < 1 then Debug.Color = vbRed
Debug.Print a
```
If you ever should decide to implement `.Color`, please reset it to default after next `Debug.SomeThing`.

**Comment by rexxitall** [comment]
The debuf.input would comes in handy if you want to create a GUI app and fiddling with something like in my PIPELAB. There are data structures you want t change for testing purposes. The current way around is either to write a testing console app. Which is waste f time. Or to add a debug form like PIPELAB is and wasting even more time. :/  In this case such a thing like debug.input comes in handy. 
`
Public Type PIPE_TYPE
    OL As OVERLAPPED 'not implemented
     
    PIPE_INSTANCES_MAX As Long
    PIPE_MODE As Long
    PIPE_MODE_FILE As Long
    PIPE_MODE_MESSAGE As Long
    PIPE_MODE_OPEN As Long
    PIPE_MODE_WAIT As Long
    PIPE_NAME As String
    PSD As SECURITY_DESCRIPTOR
    READ_BUFFER_AS_LONG As Long
    READ_BUFFER_SIZE As Long
    READ_BYTES As Long
    SA As SECURITY_ATTRIBUTES
    TIME_OUT_MS As Long
    WRITE_BUFFER_SIZE As Long
    WRITE_CONTENT_SIZE As Long
    WRITTEN_BYTES As Long
    CONTENT_MODE As Long
    CONTENT() As Byte
    REQUEST() As Byte
    REQUEST_LENGTH As Long
    CONTENT_LENGTH As Long
    DATA_MODE As Long

end type

'a lot of useless stuff for the testing purpose

Sub NAMED_PIPE_SETUP(PIPE As PIPE_TYPE)
'this here fetch all the form input fills the PIPE data structure
    With Form1
    
    
        'SERVER
        '-------------------
        'Pipename
        PIPE.PIPE_NAME = Form1.PIPENAMEFULL.Caption
        'Pipe timeout
        If IsNumeric(.TIMEOUT.Text) Then PIPE.TIME_OUT_MS = Val(.TIMEOUT.Text)
        If IsNumeric(.MaxInstances.Text) Then PIPE.PIPE_INSTANCES_MAX = Val(.MaxInstances.Text)
        
        'Pipe buffer sizes
        If IsNumeric(.BUFFERSIZEREAD.Text) Then PIPE.READ_BUFFER_SIZE = Val(.BUFFERSIZEREAD.Text)
        If IsNumeric(.BUFFERSIZEWRITE.Text) Then PIPE.WRITE_BUFFER_SIZE = Val(.BUFFERSIZEWRITE.Text)
        
        '--------------------------------------------------------
        'Pipe open mode
        Dim ITEM As Long
        Dim LISTSTRING As String
        PIPE.PIPE_MODE_OPEN = PIPE_ACCESS_DUPLEX
        ITEM = .READWRITE.ListIndex
        If ITEM = -1 Then
            LISTSTRING = .READWRITE.Text
        Else
            LISTSTRING = .READWRITE.List(ITEM)
        End If
        Select Case LISTSTRING
        
            Case "Duplex"
                PIPE.PIPE_MODE_OPEN = PIPE_ACCESS_DUPLEX
            Case "Read"
                PIPE.PIPE_MODE_OPEN = PIPE_ACCESS_INBOUND
            Case "Write"
                PIPE.PIPE_MODE_OPEN = PIPE_ACCESS_OUTBOUND
        End Select
    
        PIPE.DATA_MODE = DATAMODE_ENUM.VB6_SAMPLE
        If ITEM = -1 Then
            LISTSTRING = .DATAMODE.Text
        Else
            LISTSTRING = .DATAMODE.List(ITEM)
        End If
        Select Case UCase(LISTSTRING)
        
            Case "VB6 SAMPLE" 'uses one long
                PIPE.DATA_MODE = DATAMODE_ENUM.VB6_SAMPLE
            Case "STRING"
                PIPE.DATA_MODE = DATAMODE_ENUM.STRING_SAMPLE
            Case "BYTE ARRAY"
                PIPE.DATA_MODE = DATAMODE_ENUM.BYTE_ARRAY_SAMPLE
        End Select
    
        
        'Pipe file mode
        If .WriteTrough.Value = 1 Then PIPE.PIPE_MODE_FILE = PIPE.PIPE_MODE_FILE Or FILE_FLAG_WRITE_THROUGH
        If .NoBuffering.Value = 1 Then PIPE.PIPE_MODE_FILE = PIPE.PIPE_MODE_FILE Or FILE_FLAG_NO_BUFFERING
        
        '--------------------------------------------------------------
        'NOT IMPLEMENTED yet - That will take "some" more afford ... *sigh* !!!
        'If .Overlapped.value=1 Then PIPE_MODE_FILE = PIPE_MODE_FILE Or FILE_FLAG_OVERLAPPED
        '--------------------------------------------------------------
        PIPE.PIPE_MODE_OPEN = PIPE.PIPE_MODE_OPEN Or PIPE.PIPE_MODE_FILE
        
        '--------------------------------------------------------
        'Pipe wait mode
        If .WAIT.Value = 1 Then
            PIPE.PIPE_MODE_WAIT = PIPE_WAIT
        Else
            PIPE.PIPE_MODE_WAIT = PIPE_NOWAIT
        End If

        'Pipe Message mode
        If .PIpeModeMessage.Value = 1 Then PIPE.PIPE_MODE_MESSAGE = PIPE.PIPE_MODE_MESSAGE Or PIPE_TYPE_MESSAGE
        If .PipeModeMessageRead.Value = 1 Then PIPE.PIPE_MODE_MESSAGE = PIPE.PIPE_MODE_MESSAGE Or PIPE_READMODE_MESSAGE
        
        PIPE.PIPE_MODE = PIPE.PIPE_MODE_WAIT Or PIPE.PIPE_MODE_MESSAGE
        
        'CLIENT
        '-------------------

        PIPE.PIPE_NAME = .PIPENAMEFULL.Caption
        'If IsNumeric(.BYTESREQUESTED.Text) Then PIPE.WRITE_BUFFER_AS_LONG = Val(.BYTESREQUESTED.Text)
        If IsNumeric(.BUFFERSIZEREAD.Text) Then PIPE.READ_BUFFER_SIZE = Val(.BUFFERSIZEREAD.Text)
        If IsNumeric(.BUFFERSIZEWRITE.Text) Then PIPE.WRITE_BUFFER_SIZE = Val(.BUFFERSIZEWRITE.Text)
        If IsNumeric(.TIMEOUT.Text) Then PIPE.TIME_OUT_MS = Val(.TIMEOUT.Text)
        ReDim PIPE.CONTENT(PIPE.READ_BUFFER_SIZE)
    End With
    

End Sub
....
'some useful stuff
....

'so the whole form or the console thing could be replaced  by something short like this:
'which can be written fast from the typedef by mostly copy and paste

'                      input message                    Var to be filled                Default value
debug.input  "PIPE.PIPE_MODE_OPEN",  PIPE.PIPE_MODE_OPEN   , PIPE_ACCESS_DUPLEX
debug.input   "PIPE.PIPE_MODE_WAIT" , "PIPE.PIPE_MODE_WAIT" , PIPE_WAIT
debug.input   "PIPE.WRITE_BUFFER_SIZE" , PIPE.WRITE_BUFFER_SIZE, 2000
'and so on ...
...`



To the debug.color thing i disagree with Carl even i inderstand hwy he want to have it.
He think about single lines to colorize in exeptional cases.

Is not my opinion the whole thing should be really act like in a console mode program.

But  no need for war

debug.color foreground, optionmal  background, optional singleline as boolean 
would make us both happy
I propably would makr coordinates chunks colorfula all each lines or that.
Thats i am not the big fan of a suzide debug,color version ;)


The debug.locate thing ;)

The trick by this 4 comands would be that you are able to also design a console version on the fly from it.
Or rapid prototyping something where you have no glue yet how it woould be look in a form...

Copy and paste debug.input lines is faster then creating the gui Version
(create a buttonm name a button, caption a button, move a button, make a button click event ...)

After you are happy with all the GUI stuff or other way around - if you are happy with your console stuff you can paint your gui and waste there a lot of time with ;)

the magic would be a simple REPLACE "debug." with ""
and your console program has been done as well ;)

And to make it a bit more fun and accurate you might have also the need for debug.locate ;)
Its also handy just for debugging. now you can have a variable output always on top while other output below scrolls.

I know all are crazy for GUI stuff. I am not that big fan of.
Very often i write fire and forget things.
Used once for one specific problem in a project - usually waste of time to write a big gui.
The gui stuff usually takes longer then the worker routines.

'---------------------------------
DEBUG.ON     DEBUG.OFF
'---------------------------------

Also handy ones. Switching debug output on and off :)
No need anymore to find all the debug lines or waste a "if debug then" construct  :)

So maybe let you fantasy a wild ride and imagine how it could work and what could be done with it instead to insist
that there is no use for ;)

On cars was same - until a guy from germany invent ones ;)

Have fun
Thomas

**Comment by KDGundermann** [comment]
Hi Thomas,
reading your thread I assume what would be helpfull for you is using a testing framework.
So in setting up yor test you will fill the PIPE As PIPE_TYPE struct with the proper values, call your procedures with PIPE as param and test for the results. No need to have a GUI for unit tests. (And no need to enhance the VBA LANGUAGE for this)

**Comment by rexxitall** [comment]
It is just a example how i would use it. There are no testing frameworks out i could use or want to. :) Especially not if you can do it with a few debug.input lines :) In VBa and VB6 you can fake it by stop at a debug point and add some code to change the value you want to change. This is possible at runtime.  In VBx you can change the code as well til some point even during runtime.  So you can act on the open heart of the living program *laugh* . Its a time saver like hell. But by a fully compiled exe you can not act like this. But with debug.input you can at least change values.  I am wndering why all peoples tell me that its a stupid idea to have something that silly simple. I am not writing programs since yesterday. And very often i have had the whish to have a simple input like 1980. Or a colorful output both while and during debugging. Imagine you are civil engineer and has a strange calculation routine which act as a pure number cruncher. There is no funny gadget on the screen where you can see "Oh it has the worng color - i got to fix it...".  Somewhere in the data mess a engineer produce is a wrong number... "Pure fun" to find... And you can not even imagine how such a type structure looks like.  Otherwise i wont ask for it and wasting peoples time and energy :) I do not want to play i want to do my job a bit more easy and faster and more colorfull - i love colors. By brain works better with colors. *grin* I am that old that ive wasted a few years of my life watching on a green monochrome screen with a hercules grapic card and a fast 8088 cpu at 5Mhz  (in hardware).  :D

**Comment by rexxitall** [comment]
BTW the debug console has already a color output ... Lacks the input which VBA has in the itermediate window. There you can also calculate things...

**Comment by fafalone** [comment]
Debug.Clear - absolutely. Virtually everyone looks for workarounds to add that VB at some point.

Colors - Yes; twinBASIC itself uses at least 3 different colors, so it's no surprise we'd want to as well. It's great for critical vs information distinction, for example. Rather than 2 separate calls (and worrying about whether to automatically set it back or not); maybe a .PrintColor where the first argument specifies the color, and then follows the regular Print syntax from there? Or maybe even just a couple options; PrintRed/PrintYellow, since I'd imagine the vast majority of people just want a few different options rather than a full RGB rainbow.

Instead of specialized features like Locate or Input, how's about something simpler- Debug.Contents that just returns the full contents of the debug window? Then anyone who wants more complex features can implement it themselves, and this feature itself should be easy to implement.

**Comment by Greedquest** [comment]
`Debug.Color/Locate`: Since Windows 10 and on Linux and Mac it is possible to use ANSI escape sequences in the terminal. I've been using this in python for colourful logging. You just add some special colour sequences to your string before sending it to stdout.

Here's a minimal example in python, including the check for Windows version support:

https://github.com/pre-commit/pre-commit/blob/1f59f4cba8241ed7e572a1b5818bba74c6f31181/pre_commit/color.py#L59-L78

And here is an article in much more detail
https://stackoverflow.com/a/33206814/6609896
Escape sequences also allow you to shift the "virtual cursor" position - although that's maybe more complication then desired.

---

All that is to say, it would be very useful if the `Debug` window supports the colour escape sequences rendering because then I could `Debug` my console command line app without compiling to exe and losing the debugger. Unless tB runs hosted like VBA does, the Debug window won't be accessible to the end user of any code, only the programmer so scope for user interaction is quite limited, which is why I'm putting emphasis on consistency with the console output, so I can print the exact same string to either.

**Comment by KDGundermann** [comment]
> I am that old that ive wasted a few years of my life watching on a green monochrome screen with a hercules grapic card and a fast 8088 cpu at 5Mhz (in hardware). I think that's enough monochrome :D

Hi Thomas, yes I am old too, Started with an Commodore PET 2001 (6502 with 1 Mhz and 8k RAM) and developing software for now 45 years. And one thing I learned for sure: writing tests for my software leads to testable software which means: smaller functions, dedicated classes with an clear API,  [CLEAN CODE](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29)

**Comment by WaynePhillipsEA** [comment]
`Debug.Cls` was a no-brainer, so that is now available as of BETA 180.

For the color support, I would want a proposal in twinbasic/lang-design repo.   I do not like the suggested `Debug.Color rgbForeColor, rgbBackColor` syntax.  Perhaps seperated;  `Debug.ForeColor = rgbForeColor` and `Debug.BackColor = rgbBackColor`, but then we also have the single line vs continuous issue... so it would be best discussed over in lang-design more formally.

Sorry, I don't see us offering `Debug.Locate` nor `Debug.Input`, as I consider them to be too specialized.
