### ISSUE TITLE
Make more from a text box

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#1363]
Text boxes are nice but a bit stupid :)
Would be nice to set the scroll position, get and set the cursor position 
and get and set marked text :)
This would remove the need for some workarounds.

Same for the RhichText edit box.

Usually used as a editor replacement.

There is the monaco thing yes, but its usually overkill for simple purposes.

**Comment by mburns08109** [comment]
sounds like a job for an extended control, then - TextBoxEx if you will, if you want those added features.

**Comment by rexxitall** [comment]
more for adding a few subs and functions  to the existing ones no need to write a completely new control i guess.

**Comment by DinyaZ** [comment]
You can set cursor position in Vb6 textbox with selstart and sellenght=0
Does it work in Twb?
