### ISSUE TITLE
Compiler error for `Scale` property

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#1367]
**Describe the bug**
It appears that tB is treating the `Scale` property as a reference to the `Scale` keyword, causing an error.

**To Reproduce**
1. Add the following code:

```
    Private Type DecimalAttributes
    	Precision As Byte
        Scale As Byte
    End Type
    
    Public Sub Demo()
        Dim f As DecimalAttributes
        With f
            Debug.Print "(" & .Precision & ", " & .Scale & ")"
        End With
    End Sub
```

2. Observe the compiler highlighting ` &` after the `.Scale` as a syntax error. 
3. If you try to type something after the `.Scale`, the intellisense shows the hint for the `Scale` keyword rather than the property.

**Expected behavior**
The compiler should not confuse the property with the keyword.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC IDE 178

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 180, thanks!
