### ISSUE TITLE
PictureBox "Line" doesn't like dash first

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#1368]
- OS: [e.g. Windows 10]
 - twinBASIC compiler version 180
![Image3](https://user-images.githubusercontent.com/33807881/202748916-0bdad3f7-31c6-4a9d-9fdd-678415cdc80e.jpg)
![Image4](https://user-images.githubusercontent.com/33807881/202748939-67d62667-baa7-426f-897c-7169b03c0142.jpg)

**Comment by WaynePhillipsEA** [comment]
Yes, this is a regression in the latest release.  I'll get it fixed tomorrow.  Thanks

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 181, thanks

**Comment by camomille22003** [comment]
Works perfectly.
Just to point out that a syntax error in the Vbx help which has been copied into Tb is that when you use "index", the dash must be in front of the second "index" and not in front as the intellisense indicates
![Image2](https://user-images.githubusercontent.com/33807881/202845511-b5a0c01a-c900-454c-bc88-73ecedb2d78f.jpg)
![Image1](https://user-images.githubusercontent.com/33807881/202845515-5d9649f9-e3f8-46ac-baa1-47981dc9ffb6.jpg)

**Comment by WaynePhillipsEA** [comment]
<img width="392" alt="tbLineIntellisense" src="https://user-images.githubusercontent.com/25738109/202888266-9e91159d-c3c3-4e2d-8fca-e46a57de4be2.png">

Nope, I'm not seeing a problem there.  Our intellisense looks correct.

**Comment by camomille22003** [comment]
sorry to see bugs where there are none.
Excuse me for wasting time.
