### ISSUE TITLE
Form Gets lost (goes behind other apps/windows) when closing modal Form.

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1373]
**Describe the bug**
I have a test app where the main form (Form 1) shows a second Form (Form2) Modally

Command1_Click
 Form2.Show 1 
end Sub

When I close the modal Form2 by clicking its control box then Form2 closes correctly but Form1 becomes lost behind any other windows.

If I close Form2 with "Form2.visible=false" then it works as expected

**To Reproduce**
as above

**Expected behavior**
Form1 should remain visible (and be activated)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g.182]

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 183, thanks!
