### ISSUE TITLE
Form will not close reliably if shown with API ShowWindow 

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1374]
**Describe the bug**
If I show a second form with an API call to "ShowWindow (4)" then that form will not close reliably.

It will close with a visible = false
It will NOT close reliably from its control box.
Sometimes it will close on the first use, but not on subsequent uses.

ShowWindow is useful because it gives extra show modes such as showing a form without activating it. (ncmdshow = 4)

**To Reproduce**
I can supply test code if required

**Expected behavior**
It works ok in VB6.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [182]

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 183, thanks!

**Comment by dmrvb** [comment]
Thank you again for your rapid response.
