### ISSUE TITLE
Form.show fires resize event several times

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1376]
**Describe the bug**
Showing a New Form causes that form to fire its resize event 6 times.
.
**To Reproduce**
In a command button on the main form do:
Form2.show

in the resize event on Form2 do this:

Static n As Long
  n = n + 1
 Label1.Caption = Format$(n)
 
**Expected behavior**
Resize should fire only once.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [183]

**Additional context**

**Comment by sokinkeso** [comment]
To be more specific, this is the sequence of events at Form loading:

--- VB6 ----
load
resize
activate
paint  (if auto_redraw=FALSE)


--- tB ---
resize
resize
resize
load
activate
resize
resize
paint  (if auto_redraw=FALSE)

So, except that the Resize event fires several times, it also fires in wrong order (before load, and after activate)

**Comment by WaynePhillipsEA** [comment]
I'm fairly confident this was resolved in the recent releases, so I'll close this now. Thanks.
