### ISSUE TITLE
SSTab and Flexgrid are flamingo fields

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#1383]
since version 186 my SSTab and Flexgrid controls are all pink.

![Image1](https://user-images.githubusercontent.com/33807881/203918283-0575cc1a-1bf3-404a-9d75-0e6f65f73bc6.jpg)

 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 186 & 187 & 188

**Additional context**

**Comment by WaynePhillipsEA** [comment]
The flamingos have flown away to a far away land, in BETA 189.  Thanks!
