### ISSUE TITLE
To stop app with END doesnt work, infinite loop.

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1384]
**Describe the bug**
Beta189. If I try to exit from the app with END (as in VB6, and there it works), the app freezes, see this on the screenshot.

![Image244443](https://user-images.githubusercontent.com/94013032/204088005-1daf8e7e-499a-423c-a760-009797dff62d.jpg)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 193.  Thanks for reporting!
