### ISSUE TITLE
Simplification of Control Type change when control converted due to "not yet being supported for migration"

### ISSUE THREAD

**Issue by LewisUD** [twinbasic/twinbasic#1387]
Currently controls are converted to a PictureBox when they're "not yet being supported for migration":

`***WARNING*** converted control 'dlgDest' of type 'MSComDlg.CommonDialog' to 'PictureBox' due to control not yet being supported for migration`

 Once references are resolved the original control type often works, but there is no easy way to convert the PictureBox back to its original type - there's no "Control Type" in the .tbform and there doesn't appear to be a way to manually change it back either; you need to delete and re-add.  If you search for the PictureBox or the original ID in the project it appears in the search results, but clicking the result takes you back to the tbform, where you can't change it.

**Comment by WaynePhillipsEA** [comment]
Thanks for the suggestion.   However, the import process is being upgraded to support ActiveX controls for the next release, so this won't be needed.
