### ISSUE TITLE
Name as not implemented

### ISSUE THREAD

**Issue by axisdmx** [twinbasic/twinbasic#1391]
**Describe the bug**
'Name as' vb function not implemented 

**To Reproduce**
use name as to rename a file:
Name (App.Path & "\Sequences\" & originalName) As (App.Path & "\Sequences\" & Text1.text & ".ASQ")

**Expected behavior**
rename file

**Desktop (please complete the following information):**
 - windows 7
 - twinBASIC 193

**Additional context**
Not major, did not even remember using this function but might be good for backward compatibility

**Comment by fafalone** [comment]
Looks like it's just a parsing issue where the parentheses are making it invalid syntax... if you remove them it should work (for now; I'm sure the issue will get fixed by Wayne to match it being valid in VB).

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 199, thanks for reporting.
