### ISSUE TITLE
Not a single issue!

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1392]
**Is your feature request related to a problem? Please describe.**
Not a problem, only good news!

Today I finished a small UI project in VB6.
Then imported in tB.
Runs without a single change.
Cool!

**Describe the solution you'd like**
Continue the good work...

**Additional context**
The size of the EXE is quite big.
The project uses MSCOMCTL2 for a DTPicker.
You once said that the interfaces are compiled into the EXE (don't remember the exact wording).
1) Can that be the reason?
2) Will that effect go away when it comes to LLVM?
3) Regarding the roadmap, when will that be?

**Comment by WaynePhillipsEA** [comment]
Nice!  That's cool.  Thanks for your feedback.

With regard to the EXE size... yes, at the moment all control implementations gets compiled into the EXE.  So for example, when you reference MSCOMCTL2, you're linking in all the ActiveX wrapper class implementations for UpDown, MonthView etc, regardless if they are used or not.  Same for all of the internal controls... even if they're not used, the implementations are linked in to the final EXE, currently.

LLVM will also definitely help.  All the implementations and the ActiveX wrappers are written in tB, and the tB compiler currently generates code quickly without giving much consideration to the code size or optimization.  LLVM will help massively in both of those areas.

I'm planning to update the roadmap this weekend, so hopefully you'll get a better idea after that.

**Comment by dmrvb** [comment]
I'm still just a liitle way off, three errors plus Zorder and OLEdrag, but its a fairly big project. I expect there will be a fair few run time issues when it does compile, but it feels like tB is getting very close to quite a huge milestone.
