### ISSUE TITLE
PathGetArgsW-SysReAllocString crashes in tB but not VB6

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1394]
**Describe the bug**
This came up after resolving the previous bug and trying to get my RunAsTI program to work... I call PathGetArgsW on a string input containing a path, then my standard LPWStrToStr function to dereference the string pointer it returns. This works in VB6, but is crashing in tB, using the unmodified direct import version.

**To Reproduce**
 I've distilled it down to a fairly minimal reproduction (30 lines). Project is attached; run, enter a path in the ComboBox (the one I've been testing with is "C:\Program Files\Process Hacker 2\ProcessHacker.exe" -- including quotes), and click command button.

**Expected behavior**
Should not crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.197

**Additional context**
The pointer returned by PathGetArgsW is non-zero. The LPWStrToStr function itself is a common function used in numerous projects I've ported to tB (and in dozens of VB6 projects), so in general that part works. Passing sCommandLine ByVal does not help. Actually specifying arguments in the path string so a non-blank string is expected does not help.

[strcrash.zip](https://github.com/twinbasic/twinbasic/files/10146441/strcrash.zip)

**Comment by fafalone** [comment]
Some additional info: It looks like the attached demo crashes only in the IDE. However when adjusted to x64, it does crash in both:

```
Private Declare PtrSafe Function PathGetArgsW Lib "shlwapi" (ByVal pszPath As LongPtr) As LongPtr
Private Declare PtrSafe Function SysReAllocString Lib "oleaut32.dll" (ByVal pBSTR As LongPtr, Optional ByVal pszStrPtr As LongPtr) As Long
Private Declare PtrSafe Sub CoTaskMemFree Lib "ole32.dll" (ByVal pv As LongPtr)
    
    Private Sub Command1_Click() Handles Command1.Click
        LaunchAsTI Combo1.Text
    End Sub
Public Function LaunchAsTI(ByVal sCommandLine As String, Optional PriorityClass As Long = 0) As Long
    Dim sArg As String
    Dim sTx As String
    Dim lpArg As LongPtr
    
     sTx = "C:\temp\ProcessHacker.exe /m /n" 'sCommandLine
    Debug.Print "sCommandLine=" & sTx
    lpArg = PathGetArgsW(StrPtr(sTx))
    sArg = LPWSTRtoStr(lpArg)
    MsgBox "did we crash? sArg=" & sArg & ",sTx=" & sTx
End Function

Private Function LPWSTRtoStr(lPtr As LongPtr, Optional ByVal fFree As Boolean = True) As String
SysReAllocString VarPtr(LPWSTRtoStr), lPtr
If fFree Then
    Call CoTaskMemFree(lPtr)
End If
End Function
```

**Comment by WaynePhillipsEA** [comment]
The return value given by PathGetArgs is just an offset into the string.  So you shouldn't be calling CoTaskMemFree on it.  It falls into the undefined-behaviour bracket.... sometimes it'll crash straight away, and others it might take time, but it will very likely crash eventually.

**Comment by fafalone** [comment]
Thanks... seems to work, guess the documentation is just really misleading...

```
LPCWSTR PathGetArgsW(
  [in] LPCWSTR pszPath
);

Return value

Type: PTSTR

Returns a pointer to a null-terminated string that contains the arguments portion of the path if successful.
```

I think what threw me off is that this has *never* crashed or caused a call to fail in VB, and I've been regularly using it every time I restart for 8 months now.

**Comment by WaynePhillipsEA** [comment]
Yes, luck is a funny thing ;)

BTW you can check the value returned sits inside the middle of the original BSTR (that you took with StrPtr).  It most definitely doesn't return a new string.  I agree, the docs could be more clear though.
