### ISSUE TITLE
`VBA` library qualifier not recognised

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1395]
**Describe the bug**
tB throws a compiler error when using vba color constant syntax VBA.vb[color] and VBA.ColorConstants.vb[color]

**To Reproduce**
```vba
    Debug.Print vbBlue 'recognized by both vba and tB
    Debug.Print VBA.vbBlue 'recognized by only vba
    Debug.Print VBA.ColorConstants.vbBlue 'recognized by only vba
```
**Expected behavior**
tB should recognize all of the alternative color constant syntaxes (?)

**Screenshots**
none

**Desktop:**
 - OS: Windows 11
 - Excel 360 (64-bit)
 - twinBASIC compiler version IDE Beta 195

**Additional context**
The work-around is obvious and trivial - just use vb[color] without parent prefixes, but thought I should report since you are aiming for backward compatibility. Thanks - this project is awesome!

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  It's the VBA qualifier that's the problem, I think.  I'm sure we use `ColorConstants.vbBlue` syntax inside the WinNativeForms package.  I'll get it fixed.

**Comment by Kr00l** [comment]
Don't fix it. We stick to the enum of VBRUN.ColorConstants for VB6 back-compat instead of the module constants of VBA.

**Comment by WaynePhillipsEA** [comment]
That's true, it might cause more harm than good.   We can look to allow the VBA qualifier later, perhaps via a separate package.  I'll leave this open so that we look at it later, but I'll tag it as won't-fix for now

**Comment by mburns08109** [comment]
Wasn't there mention of a Mode VBA type of switch earlier? if so, would not this functionality seem to be a good candidate to be covered by that same switch?

**Comment by WaynePhillipsEA** [comment]
@mburns08109 I don't recall such a discussion, no.

It is most likely that it will be done via package choice, as it will also involve offering MS Forms (UserForm) compatible controls, rather than the VB6 controls.
