### ISSUE TITLE
VBA Specification of VbVarType Constant Not Recognized (sort of)

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1396]
**Describe the bug**
tB throws a compiler error when using vba VbVarType constant syntax VBA.vb[variable type]

**To Reproduce**
```vba
    Debug.Print vbString 'recognized by vba and tB
    Debug.Print VBA.vbString 'recognized by only vba
    Debug.Print VBA.VbVarType.vbString 'recognized by vba and tB
```
**Expected behavior**
tB should recognize all of the alternative VbVarType constant syntaxes (?)

**Screenshots**
none

**Desktop:**
 - OS: Windows 11
 - Excel 360 (64-bit)
 - twinBASIC compiler version IDE Beta 195

**Additional context**
The work-around is obvious and trivial - just use vb[variable type] without VBA prefix, but thought I should report since you are aiming for backward compatibility. Thanks - this project is awesome!

**Comment by WaynePhillipsEA** [comment]
See #1395
