### ISSUE TITLE
MSHTML Library - Different Behavior between Excel VBA and tB

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1397]
**Describe the bug**
tB throws several runtime errors when attempting to execute the sub below that manipulates objects in MSHTML (Microsoft HTML Object Library). The sub executes without error in Excel VBA7 (64 bit). 

**To Reproduce**
```vba
Sub main()
    Dim table As MSHTML.HTMLTable, doc As MSHTML.HTMLDocument
    
    Set doc = New MSHTML.HTMLDocument

    'VBA prints "<html><head></head><body><p>&nbsp;</p></body></html>"
    'tB throws Run-time error 91 (0000005B) - Object variable or With block variable not set
    Debug.Print doc.DocumentElement.outerHTML
    
    Set table = doc.createElement("table") 'this works in both VBA and tB...
    
    'Both VBA and tB print "<table></table>"
    Debug.Print table.outerHTML
    
    'tB throws "Run-time error 600 (00000258) - Internal OFS status codes indicating how an allocation operation
    'is handled. Either it is retried after the containing onode is moved or the extent stream is converted to
    'a large stream. "
    'VBA runs fine...
    table.innerHTML = "<tbody><tr><td></td></tr></tbody>"
    
    'vba prints "<table><tbody><tr><td></td></tr></tbody></table>"
    Debug.Print table.outerHTML
End Sub
```
**Expected behavior**
tB should execute the above sub with same results as Excel VBA...

**Screenshots**
none

**Desktop:**
 - OS: Windows 11
 - Excel 360 (64-bit)
 - twinBASIC compiler version IDE Beta 195

**Additional context**
VBA and tB "indicate" that both are referencing the same C:\Windows\System32\mshtml.tlb file path on disk...

**Comment by WaynePhillipsEA** [comment]
The first error is now resolved in BETA 198.

However, the 600 error happens for me in all environments... VB6, VBA and tB, on both 32 and 64-bit architectures.  As such, I don't believe it to be a tB problem.

Thanks!

**Comment by GCuser99** [comment]
Thanks Wayne - fixing the COM class initialization issue allowed me to move forward with a workaround for the 2nd roadblock.

FYI, I just tried that sub in VBA on two different Windows 64-bit machines and it worked fine (referencing C:\Windows\System32\mshtml.tlb). I then tried it on a Windows 32-bit setup (referencing C:\Windows\SysWOW64\mshtml.tlb) and it failed in VBA. Head scratcher...
