### ISSUE TITLE
Form resize is buggy

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1398]
**Describe the bug**
In VB6, resizing is smooth and when you resize a form, it never goes out of sync with controls you resize in the Form_Resize event. But with tB, the resize event doesn't seem to be firing quite correctly, and if you resize too fast, it can result in controls not being properly resized.

**To Reproduce**
Create a new project with a Form and a TextBox that takes up the whole form. Add:

```
    Private Sub Form_Resize() Handles Form.Resize
        Text1.Width = Me.Width - 120
        Text1.Height = Me.Height - 120        
    End Sub
```
Start and resize it very quickly

**Expected behavior**
Resizing should be as smooth and accurate as VB6.

**Screenshots**
![image](https://user-images.githubusercontent.com/7834493/205498383-a569cb37-1d41-46ab-b0d5-02da614a810d.png)

That's a much larger gap than 8 pixels (120 twips). It's not possible to get out of sync like this with VB6.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.197

**Additional context**

**Comment by WaynePhillipsEA** [comment]
There's quite a few related issues in this area (e.g. multiple resize events firing, resize event in wrong order, flickering of controls etc).  This is all due to be reworked very soon.

**Comment by WaynePhillipsEA** [comment]
Btw, if it's a new project, using the control right/bottom anchors might be easier than doing it in code.

**Comment by fafalone** [comment]
Using anchors it's staying in sync, thanks. At least solves it with the built in controls for now.

**Comment by dmrvb** [comment]
Just out of interest, VB6 can do some untidy things with resizing.
Create a smallish second form (with windowstate = normal)
A run timw set windowstate = 2 (maximised), then set visible = true.
The form will transiently show as the small form but magnified up to full screen with big controls and even a big title bar before correctly resizing itself.  
It works fine in tB and a hope Wayne does not feel a need to replicate VB6 here :smiley:

**Comment by WaynePhillipsEA** [comment]
I'm fairly confident this was resolved in the recent releases, so I'll close this now.  Thanks.
