### ISSUE TITLE
ListView embedded in a Frame on a form does not instantiate

### ISSUE THREAD

**Issue by AntsAntix** [twinbasic/twinbasic#1404]
**Describe the bug**
A ListView that is embedded in a Frame on a Form isn't instantiated in normal processing. It needs to be 'woken' in the IDE to function normally.

**To Reproduce**
1. Import the VB6 project . . .
2. Replace the PictureBox that has been substituted for the ListView with a Frame
3. Add the Reference for MSComCtlLib 
4. Embed a ListView in the Frame and set Attributes
5. Compile the Project
6. Run the compiled program - it fails.
7. Run the program within the IDE - it fails.
8. Step thru the program in the IDE to point of failure ... 
9. Reference the ListView in Variables Window - Form builds normally . . . 
>> Please refer to Additional Context below for further information

**Expected behavior**
I expect the Form to load completely.

**Screenshots**
Both compiled version and when run from the IDE, this message pops up when I try to add ColumnHeaders to the ListView.
![image](https://user-images.githubusercontent.com/89644755/205685043-b0e4079e-5360-4587-b782-47f12f4dd0d6.png)
From within the IDE, when I set breakpoints at the point of failure and I use the Variables Window to navigate to the ListView and then to ColumnHeaders, execution proceeds without failure:
![image](https://user-images.githubusercontent.com/89644755/205685802-6afcc336-ce84-481e-9d24-c752797049e6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version BETA 199 

**Additional context**
I have been poking at this problem for a number of versions.
I also noticed in the .VBP that this Reference for MSComCtlLib was listed as an "Object" and not as a Reference. I think that might be because in the original project, I had used the ToolBar to activate the ListView and not by adding a Reference to the library. 
The "Import From VBP" in TwinBASIC IDE did not detect this entity when it loaded the VBP.

**Comment by AntsAntix** [comment]
I will put it together for you - might take a few minutes.

**Comment by fafalone** [comment]
I tried importing a VBP with a mscomctl reference + ListView on form inside frame and it worked fine.

**Comment by AntsAntix** [comment]
@fafalone: the original form did not have the ListView embedded in a Frame. I changed that in the TwinBASIC version.
But it had this in the .vbp:
Reference=*\G{420B2830-E718-11CF-893D-00A0C9054228}#1.0#0#..\..\..\..\..\..\Windows\SysWOW64\scrrun.dll#Microsoft Scripting Runtime
Object={831FDD16-0C5C-11D2-A9FC-0000F8754DA1}#2.0#0; MSCOMCTL.OCX
Form=..\Common\Forms\Splash.frm
and this in the Form:
VERSION 5.00
Object = "{831FDD16-0C5C-11D2-A9FC-0000F8754DA1}#2.0#0"; "MSCOMCTL.OCX"
Begin VB.Form MainForm 
   Appearance      =   0  'Flat

**Comment by AntsAntix** [comment]
More: scratching in the Settings of the project, I see that MSCOMCTL is version 2.2 and I am sure it will object to the 2.0 in the declaration for the Object.
I will close this Bug and change that entry in the .VBP to see what happens.

**Comment by fafalone** [comment]
Yup that's how the references are for my project too. Although the other reference, for scrrun, looks weird, there should only be . or .., not ...........

e.g. when I added it,
`Reference=*\G{420B2830-E718-11CF-893D-00A0C9054228}#1.0#0#..\..\Windows\SysWOW64\scrrun.dll#Microsoft Scripting Runtime
Object={831FDD16-0C5C-11D2-A9FC-0000F8754DA1}#2.0#0; MSCOMCTL.OCX`

**Comment by AntsAntix** [comment]
BTW, the _IMPORT_LOG made no reference to the MSCOMCTLLIB reference at all - nothing that it had failed.
The other references are 'fluff' ... I included them only to give context to the line that said: Object
But the other References in the VBP were 'discovered' without problem.

**Comment by AntsAntix** [comment]
@WaynePhillipsEA : You are correct about loading the ListView - I changed the version of the Object for MSComCtlLib to be 2.2 in the .VBP to match the version on this machine. It then created the Form with the ListView - no problem.
