### ISSUE TITLE
Collapsing inside a function or subroutine makes the syntax coloring stop working

### ISSUE THREAD

**Issue by mika76** [twinbasic/twinbasic#1407]
**Describe the bug**
If I collapse an if condition or a while loop or pretty much anything within a function, the rest of the code after the collapsed section is just gray and does not display syntax coloring.

**To Reproduce**
1. Collapse a while loop which has some code after it.

**Expected behavior**
Syntax coloring should always be showing for visible lines.

**Screenshots**
![Screenshot 2022-12-06 at 18 21 32](https://user-images.githubusercontent.com/229311/205979572-4a4843ac-a209-4f62-ad2c-d0236b56f9d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version [e.g. 0.9.1111] IDE Beta 201

**Comment by WaynePhillipsEA** [comment]
I'm pretty sure we fixed this at some point a while ago. If you're still encountering it, just add a comment and we'll reopen this issue.
