### ISSUE TITLE
Project explorer is wrapping the file names to the next line and jumping around when it's too narrow

### ISSUE THREAD

**Issue by mika76** [twinbasic/twinbasic#1408]
**Describe the bug**
Project explorer is wrapping the file names to the next line and jumping around when it's too narrow

**To Reproduce**
1. Resize the project explorer until the names start wrapping.

**Expected behavior**
The lines should not change. If you can't fit something it should cut it off (maybe show ellipsis)

**Screenshots**
![Screenshot 2022-12-06 at 18 25 10](https://user-images.githubusercontent.com/229311/205980264-200e0ae0-68e9-48da-af41-ea1083f6612b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - twinBASIC compiler version [e.g. 0.9.1111] IDE BETA 201

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 205.  Thanks!
