### ISSUE TITLE
ActiveX  expression is neither used nor assigned

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1413]
**Describe the bug**
When I call a funcion as a subroutine on an ActiveX control I get the error "expression is neither used nor assigned".

**To Reproduce**
The Active X control contains a function that returns a boolean status but I am calling it as if it were a subroutine.
This error occurs on a third part ActiveX control.
I have not replicated this on other axtiveX controls
Adjusting my code to do a correct function call solves the problem.

I have not reproduced this on other controls

**Expected behavior**
VB6 allows functions to be called as subs..

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [201]

**Additional context**
This is probably a low priority issue unless other users also see it, but as ActiveX is currently a work in progress i thought it was worth reporting.
I can supply a copy of the control if required.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 205.  Thanks!
