### ISSUE TITLE
IDE Version number

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1419]
**Describe the bug**
Only on my PC ? After the update to Beta202, it shows IDE BETA 201 in the caption.

**Comment by dmrvb** [comment]
I see this too, I suspect an easy mistake to make, but I also suspect that 203 will be along before very long.

**Comment by WaynePhillipsEA** [comment]
Yes, apologies.  I have to manually bump the IDE number, and sometimes I forget, particularly when it has been a few days between releases.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 203, thanks.
