### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1420]
**Describe the bug**
![222d2d](https://user-images.githubusercontent.com/94013032/207601327-662190f1-f1ae-4f93-8da0-3fc05939e03a.jpg)

**Comment by WaynePhillipsEA** [comment]
You've got compilation errors.  See line #137 - error "expression is neither used nor assigned".   Therefore, I think this is the same as https://github.com/twinbasic/twinbasic/issues/1413, so I'll close this.  Thanks.
