### ISSUE TITLE
UserControl auto-generated event prototypes change LongPtr to Long/LongLong

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1425]
**Describe the bug**
If you have a UserControl event with LongPtr arguments, when the prototype is autogenerated by the IDE, it will use Long when in 32bit mode, LongLong when in 64bit mode, then give the error that it doesn't match when you switch modes.

**To Reproduce**
Have UserControl with event with LongPtr (attached). 

Place on form then select event from dropdowns to autogen prototype.

**Expected behavior**
Should preserve LongPtr so as to not need manual correction.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.207
 - 
**Additional context**
Changing it to LongPtr manually does seem to work as a temporary mitigation.

[evtptrtest.zip](https://github.com/twinbasic/twinbasic/files/10241350/evtptrtest.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 208, thanks.
