### ISSUE TITLE
Can not save licence key info in TB (IDE Beta 210)

### ISSUE THREAD

**Issue by GioKia** [twinbasic/twinbasic#1428]
I can't save the license key: I enter it, but it doesn't save. 

If I try to insert it I can't save anything anymore. 
I have to wait for it to time out (error saving), close (without saving) and restart the IDE; after restart, IDE is not registered. 

Compiling projects, nag screen disappear, but can not save anything; restarting IDE I have to reinsert the key, and problem restart.

I tried running TB in administrator mode but it didn't solves the problem.

 - Laptop  i7, Win 10 PRO, 22H2
 - IDE Beta 210

Thanks :)

**Comment by GioKia** [comment]
SOLVED.
Downloaded and installed an old version (a beta 201): registration went well. 
After, I try to use the BETA 210, and registration remained.
So *maybe* it's a problem of version 210 and new registrations. 

Thanks anyway.
Gio

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting the problem, and for the fix.    I will look into this.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 211, thanks
