### ISSUE TITLE
Controls moved via API do not recognize they've moved

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1429]
**Describe the bug**
I use the the following to create draggable mini-dialogs and sizing bars:

```
    Private Sub Picture1_MouseMove(Button As Integer, Shift As Integer, X As Single, Y As Single) Handles Picture1.MouseMove
        If Button = 1 Then
            Debug.Print "PreReleaseCaptureTop=" & Picture1.Top
            Call ReleaseCapture
            Call SendMessage(Picture1.hWnd, WM_NCLBUTTONDOWN, HTCAPTION, 0&)
            Debug.Print "PostReleaseCaptureTop=" & Picture1.Top
        End If
    End Sub
```

You can click and drag the PictureBox to move it around. In VB6, it realizes it moves, and the PostReleaseCapture top will be different. In tB, it doesn't recognize it's moved, ever, even if you click a button to show the new position even after the above sub exits. This breaks sizing bars and other position-based features.

**To Reproduce**
Project attached, Click the button to show the initial top, drag it around, you'll see it reports the original top both after the ReleaseCapture routine returns and when you click the button again.

Then run the same in VB6, and you'll see it gives the new top both in the PostReleaseCapture message and when you click the button again.

**Expected behavior**
It should recognize it's been moved like in VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.210

**Additional context**

[CaptureTest.zip](https://github.com/twinbasic/twinbasic/files/10263606/CaptureTest.zip)

**Comment by fafalone** [comment]
This problem is more widespread than I thought. I tested moving a CommandButton with `SetWindowPos`, and it also did not recognize it had moved.

At this point I expect this issue applies to most or all of the controls.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 214.  Thanks
