### ISSUE TITLE
Infinite restart loop while typing DLL declare

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1430]
**Describe the bug**
Seems to be a regression as this would have been noticed much earlier otherwise, but when there's not much on a form in a new project and you type a DLL declare, it goes into an infinite compiler restart loop, or hangs, when you start the name, which persists until you finish the name and move onto 'Lib' in the event it doesn't hang outright.

**To Reproduce**
-New Standard Exe
-Open Form code
-Start typing in area between Class Form1 and Sub New() 'private declare ptrsafe sub ab' and pause.

**Expected behavior**
...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.210

**Additional context**
I did this over and over, FullValueRider reproduced it, but after like the 10th IDE restart, it stopped... so it's possible it may not reproduce immediately, but it is there.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 211, thanks
