### ISSUE TITLE
Closing a browser makes the application screen redraw three times.

### ISSUE THREAD

**Issue by OldestCoderInTown** [twinbasic/twinbasic#1432]
This is weird. 

I have 288 Labels on my screen and when I close the last instance of a browser (Chrome, Edge or IE) my application has a screen redraw meltdown.

Every label gets redrawn three times, causing a ripple down the screen.

This happens in the IDE and in a compiled version of the application, regardless of whetehr the IDE is running or not

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  Redrawing/flickering of controls is a known issue, see related issue #1084.  There are a few issues covering this already, so I'll close this dupe, thanks.
