### ISSUE TITLE
DrawText API does not draw in ForeColor

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1434]
**Describe the bug**
I noticed some color differences while working on my ShellBrowse control... In VB6, when you use the DrawText API to draw text onto a control with an hDC (Form, PictureBox, UserControl), the text is drawn in the ForeColor of the control as set in the standard properties interface. In tB, the ForeColor is ignored and it always draws in black. 

**To Reproduce**
Minimal example projects (VB6 and .twinproj that imported it) attached; run and click button. 

**Expected behavior**
It should draw in the ForeColor like VB6.

**Screenshots**
![image](https://user-images.githubusercontent.com/7834493/209912622-1b83399c-1a25-4ecd-af6a-24f8229403e9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.215

**Additional context**
This seems to be part of a recurring, larger issue where VB control properties and APIs interact normally, but in tb, they don't see eachother.

[DrawTextBug.zip](https://github.com/twinbasic/twinbasic/files/10317939/DrawTextBug.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 216, thanks
