### ISSUE TITLE
Import from VB - Load Object statement Error.

### ISSUE THREAD

**Issue by claudio052** [twinbasic/twinbasic#1436]
-VB Project:
On a form create a command1, and a label1(0) 
code:
Private Sub Command1_Click()
Load Label1(1)
Label1(1).Top = Label1(0).Top
Label1(1).Left = Label1(0).Left + 1000
Label1(1).Caption = "OK"
Label1(1).Visible = True
End Sub

The statement ' LoadLabel1(1) ' gives an error: Run-timer Error-340(0000154)
   
TwinBasic (IDE beta 213)
VB6(sp6)
Win10

**Comment by WaynePhillipsEA** [comment]
Unfortunately the Load statement is not implemented fully yet.  This is a known issue, but I don't believe we've got an open issue for it, so we can leave this issue open.

In particular, we don't support adding control array elements at runtime.   This will be fixed in the next week or two.

**Comment by claudio052** [comment]
Thank you for the response.Very good project. I wish you a great success.
Claudio
    Il venerdì 30 dicembre 2022 09:08:11 CET, WaynePhillipsEA ***@***.***> ha scritto:  
 
 


Unfortunately the Load statement is not implemented fully yet. This is a known issue, but I don't believe we've got an open issue for it, so we can leave this issue open.

In particular, we don't support adding control array elements at runtime. This will be fixed in the next week or two.

**Comment by LastJasonNext** [comment]
Load statement (adding control array elements at runtime) still producing Error. That and form and picturebox Image property implementation I think are all that's stopping an import of VBP, but of course that's an unknown until until compiler can get past the Errors. I do hope you're getting enough sleep! Really great work. A lot of us have dreamed of this. You're actually getting it done.
