### ISSUE TITLE
ActiveX DLL - DoEvents hangs when used in tB

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1440]
**Describe the bug**
VBA's DoEvents hangs when used in a tB ActiveX DLL.

**To Reproduce**
Open tB and initialize an ActiveX DLL project.
Make a MyClass.cls in tB like below:
```vba
Attribute VB_Name = "MyClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True

' add your member fields and procedures here
Sub DoDoEvents()
    DoEvents
    MsgBox "Done"
End Sub
```
Compile the DLL in tB.
In Excel, reference the DLL and run the following Sub:
```vba
Sub Test_DoEvents()
    Dim mc As New MyClass
    mc.DoDoEvents
End Sub
```
The sub hangs in Excel VBA and does not show message "Done".

**Expected behavior**
Running the sub in VBA should return message "Done".

**Screenshots**
none

**Desktop:**
 - OS: Windows 11
 - Excel 365 (64-bit)
 - twinBASIC compiler version IDE Beta 201

**Additional context**
The sub Test_DoEvents works fine in tB's IDE from MainModule.twin.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 220.  Thanks!

**Comment by WaynePhillipsEA** [comment]
You're welcome.  You can use the latest version.  The latest versions are not building ActiveX controls at the moment, but that doesn't affect ActiveX libraries.
