### ISSUE TITLE
[DllExport] on a function with optional arguments fails silently

### ISSUE THREAD

**Issue by Greedquest** [twinbasic/twinbasic#1442]
When compiling a standard DLL (and calling it from vba with the LoadLibrary function), this signature is successfully included and can be called:
```vba
[ DllExport ]
Public Function StdModuleAccessor(ByVal moduleName As String, ByVal vbProj As VBProject, ByVal projectName As String, ByRef outModuleTypeInfo As ITypeInfo, ByRef outITypeLib As LongPtr) As Object
```

This one cannot (see last 2 optional args)
```vba
[ DllExport ]
Public Function StdModuleAccessor(ByVal moduleName As String, ByVal vbProj As VBProject, ByVal projectName As String, Optional  ByRef outModuleTypeInfo As ITypeInfo, Optional ByRef outITypeLib As LongPtr) As Object
```

Both instances appear to compile successfully. There should be
 - The possibility of optional args in the compiled standard dll
 - **OR** an error if a signature is incompatible with [DllExport] rather than silently leaving it out

**Comment by WaynePhillipsEA** [comment]
I cannot reproduce any problem here.   Here is my test project:

```
Interface VBProject
End Interface

Interface ITypeInfo
End Interface

Module MainModule
    [ DllExport ]
    Public Function StdModuleAccessor(ByVal moduleName As String, ByVal vbProj As VBProject, ByVal projectName As String, Optional ByRef outModuleTypeInfo As ITypeInfo, Optional ByRef outITypeLib As LongPtr) As Object
        MsgBox "Hey there from twinBASIC!"
    End Function
End Module
```

StdModuleAccessor appears to get exported fine, and can be called from VBx without any problem.

**Comment by Greedquest** [comment]
I think this was to do with the way I was calling it, cannot repro. There was some weirdness going on but I can't figure out what. Just whenever I renamed the function or changed the arguments it works occasionally be omitted from the compiled dll
