### ISSUE TITLE
Transition from Beta 209 to Beta 219 is giving Memory Locked error

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1443]
**Describe the bug**
I'm using Olaf Scmidt's cHashD.  After installing Beta IDE 219 (jumping from Beta IDE 209) I'm seeing memory locked messages when trying to enumerate Keys/Items or Pairs.  The following code works as expected in IDE 209.
```
Sub testforeach()

    Dim myC As cHashD = New cHashD
    
    myC.Add "One", 1
    myC.Add "Two", 2
    myC.Add "Three", 3
    
    Dim myKey As Variant
    For Each myKey In myC.Keys
        Debug.Print myKey
    Next
End Sub
```

In IDE 219 I see the following
![MemoryLocked](https://user-images.githubusercontent.com/81257042/210215336-7ade30eb-c5be-4fc0-9950-b0ee97c4053c.jpg)

**To Reproduce**
1. In the attached twinproj
2. goto Module Pootle
3. execute testforeach

**Expected behavior**
No memory locked message

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Beta IDE 219

**Additional context**
The twin proj file
[Lib.zip](https://github.com/twinbasic/twinbasic/files/10330866/Lib.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 220.  Thanks!
