### ISSUE TITLE
Error Compilation

### ISSUE THREAD

**Issue by mencoxx** [twinbasic/twinbasic#1444]
![image](https://user-images.githubusercontent.com/51709552/210340043-78a01034-c760-4a45-bf8d-cdcb6ab8b531.png)

there is nothing else

**Comment by fafalone** [comment]
There's no issue calling a function with that prototype that I can reproduce, so presumably there is indeed something else.

```
Public Sub CalcolaGrafico_T(G As Object, sql As String, lVis As Boolean, Dta1 As Date, DtaF As Date, LimIcas As Integer, LimS As Integer, etl As Integer, et2 As Integer, Titolo As String, tp As Integer, vEt As Boolean)

    On Error GoTo Grafico_Errore
	MsgBox sql, vbOKOnly, Titolo
    
    Exit Sub
    Grafico_Errore:
End Sub

Private Sub Command1_Click() Handles Command1.Click
    CalcolaGrafico_T Nothing, "hi", True, Now, Now, 1, 2, 3, 4, "sup", 5, True
    
End Sub```

**Comment by WaynePhillipsEA** [comment]
@mencoxx are there any compilation errors in your project?  (In particular, inside `CalcolaGrafico_T`)

**Comment by mencoxx** [comment]
I found the error, if as I had to rewrite the calls to the function
specifying the type of variable for each parameter (VBA Access has lazy me)
I should have written: 'LimI As Integer' instead of: 'LimIcas As Integer.

Sorry--however, I'm slowly getting used to it.

Il giorno mar 3 gen 2023 alle ore 14:09 WaynePhillipsEA <
***@***.***> ha scritto:

**Comment by WaynePhillipsEA** [comment]
Ah, so it was a typo.  No problem, I'll close this then, thanks.
