### ISSUE TITLE
Multiple Interface Inheritance

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#145]
Given:
```
Public Interface Foo
  Public Sub DoIt()
End Interface

Public Interface Bar
  Public Sub DoIt()
End Interface
```

We should be able to do something like this:

```
Public Class Both
  Implements Foo
  Implements Bar

  Public Sub DoIt() Implements Foo.DoIt, Bar.DoIt
  End Sub
End Class
```

Currently, this is not allowed, which requires one to implements the other interface's method. Considering that sometimes it is necessary to implement for multiple interfaces for backward compatibility, being able to specify multiple compatible `Implements` on same sub would be a great help in reducing the boilerplate.

**Comment by mansellan** [comment]
Would also be nice to be able to declare the class's inherited types more concisely:

```
Public Class Both Implements Foo, Bar
```

**Comment by bclothier** [comment]
I have to agree - implicit inheritance is usually the case. Explicit inheritance is great when you need it but it also makes it for quite verbose class definition if you have to add `Implements ...` to each method.

**Comment by bclothier** [comment]
I came across this issue again, and noticed that this issue wasn't tagged so bumping in case it might have gotten missed.

**Comment by WaynePhillipsEA** [comment]
Thanks Ben, will look at it very soon

**Comment by bclothier** [comment]
I think that issue was already resolved sometime ago, so closing.
