### ISSUE TITLE
Wrong parsing of keywords after `!` (bang) operator

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1450]
**Describe the bug**
This does not parse well
```
        Dim rsData As ADODB.Recordset
        Dim MyNum As Long
        MyNum = rsData!Width.Value
        MyNum = rsData!Error
        MyNum = rsData![Error]         '<--- works
```

It looks like the parser keeps on distinguishing language **keywords** after `!` (bang) operator although these look like identifiers but act like keys/strings i.e. single "word" with no spaces or [square brackets with spaces].

**Expected behavior**
Special-case identifiers after `!` and don't trip up on `Error` and other language **keywords**.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version: BETA 222

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 223.  Thanks!
