### ISSUE TITLE
ActiveX DLL - With Err on single line crashes Office Application

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1454]
**Describe the bug**
Rogue code line crashes MS Excel when referencing tB ActiveX Dll. Does not fail in tb IDE. Took me hours to find this needle in the hay stack... :-)

**To Reproduce**
1. Make a tB ActiveX Dll
2. Create a class as below:
```vba
VERSION 1.0 CLASS
BEGIN
    MultiUse = -1  'True
    Persistable = 0  'NotPersistable
    DataBindingBehavior = 0  'vbNone
    DataSourceBehavior  = 0  'vbNone
    MTSTransactionMode  = 0	'NotAnMTSObject
END
Attribute VB_Name = "MyClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True

' add your member fields and procedures here
Sub MyMethod()

    On Error GoTo ErrHandler
    MsgBox "this is an ActiveX dll"
    Exit Sub

ErrHandler:
    'this crashes office application
    With Err: Err.Raise .Number, .Source, .Description, .HelpFile, .HelpContext: End With

    'this does not crash office application
    'Err.Raise Err.Number, Err.Source, Err.Description, Err.HelpFile, Err.HelpContext

End Sub
```
5. Compile
6. Open Excel, reference the tB ActiveX Dll, then execute this snippet in VBA:
```vba
Sub test()
    Dim o As New MyClass
    o.MyMethod
End Sub
```
**Expected behavior**
Should show message "this is an ActiveX dll."

**Desktop (please complete the following information):**
OS: Windows 11
Excel 365 (64-bit)
twinBASIC compiler versions IDE Beta 211 through 226

**Additional context**
The rogue code line does not crash using tB compiler versions 201-210. After 210, the crashes occur.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 227, thanks!
