### ISSUE TITLE
Function compatibility problem?

### ISSUE THREAD

**Issue by dj-make** [twinbasic/twinbasic#1458]
Function compatibility problem?
![QQ截图20230113043206](https://user-images.githubusercontent.com/122567615/212175808-65f18d3e-33d1-4862-a35d-91f230a2c17e.jpg)
![QQ截图20230113043231](https://user-images.githubusercontent.com/122567615/212175811-c6561c15-6500-4676-8265-a180f8a4ace1.jpg)

**Comment by mburns08109** [comment]
Aren't you using the # Doub le data type suffix as a prefix there? VBA should barf at that too

**Comment by mburns08109** [comment]
PLUS - isn't InputB$() a holdover from the (now truly ancient) Access-Basic (i.e. PRE-VBA Access code)!?  ...and if so, may not be covered by the 100% VBx back-compat goal...?

**Comment by dj-make** [comment]
> 您不是在那里使用 # Double 数据类型后缀作为前缀吗？VBA也应该对此吠叫



This is to import a normal vb6 project file. vb6 is running normally.
Ps. Explain that there is still a lot of work to be done to be compatible with vb6.
![QQ截图20230113052505](https://user-images.githubusercontent.com/122567615/212184794-9bc9c511-116a-4636-927c-ac5005c5e7b3.jpg)

**Comment by wqweto** [comment]
This must ba a simple parser issue with `#` prefix for the second parameter of the `InputB` function although I'm not sure the actual file format `InputB` reads/persists to is supported (if different than regular VBx cludge) and it looks scary ancient.

**Comment by WaynePhillipsEA** [comment]
The `#` file number prefix is a pain.  Depending on the statement syntax... sometimes it is absolutely required, sometimes it is completely disallowed, and other times it is entirely optional.  But it is what it is, and this will be fixed in the next release.

**Comment by WaynePhillipsEA** [comment]
Compilation error fixed in BETA 230.  Thanks for reporting.
