### ISSUE TITLE
Activation of this event is invalid

### ISSUE THREAD

**Issue by dj-make** [twinbasic/twinbasic#1459]
Activation of this event is invalid
![QQ截图20230113044731](https://user-images.githubusercontent.com/122567615/212178125-7c90febf-3517-4aae-8d3d-bcb01f790a21.jpg)

**Comment by wqweto** [comment]
If you hover over the yellow squiggles it explains that this is yet unsupported property so it's planned to be implemented some time later before v1 release.

IMO this issue can safely be closed!

**Comment by WaynePhillipsEA** [comment]
Agreed, this is known to be unimplemented as listed in #1188, so I'll close this duplicate.
