### ISSUE TITLE
Unload Me will cause the IDE to reload. Me. Close is normal.

### ISSUE THREAD

**Issue by dj-make** [twinbasic/twinbasic#1460]
Unload Me will cause the IDE to reload. Me. Close is normal.
![QQ截图20230113051145](https://user-images.githubusercontent.com/122567615/212182351-64b33b4a-b5a6-427c-96eb-2416e43eae93.jpg)

**Comment by wqweto** [comment]
According to #783 `Unload` is supported since BETA 72 so this might be an actual issue.

**Comment by WaynePhillipsEA** [comment]
This should be fixed as of BETA 234.d  Thanks.
