### ISSUE TITLE
UserControl Visible property not working

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1462]
**Describe the bug**
It's not marked as unimplemented, but setting a control to Visible = False during design time is ignored and it's visible, and setting a visible one to False during runtime is ignored.

**To Reproduce**
Minimal reproduction attached.

**Expected behavior**
Either working or marked unimplemented

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.232

**Additional context**

[UCVisDemo.zip](https://github.com/twinbasic/twinbasic/files/10420028/UCVisDemo.zip)

**Comment by AntsAntix** [comment]
I am quite taken with Mathieu Guindon's MVVM OOP 'framework'. In his implementation of Validators and ErrorFormatters, there is a function where an actual screen object (an image) is meant to be made Visible or Not Visible when an exception has occurred. In that section of code, the Class-wide 'Target' item is declared as an Object. In an 'Apply' procedure, a Procedure level variable is declared as Control (I think the automatic import of the .VBP changes it to type: VB.Control) that has 'Target' assigned to it.
At a point in the logic. Control.Visible is set to either True or False.
But, during execution, this assignment is ignored.
Does this relate in anyway to this bug that has been reported? If not, I will try to reduce the logic down to something that can be used to demonstrate the problem.
The logic works in the VB6 version of the program.

**Comment by WaynePhillipsEA** [comment]
This is working in latest builds, so lets close this.  Thanks
