### ISSUE TITLE
Power Operator

### ISSUE THREAD

**Issue by M2000Interpreter** [twinbasic/twinbasic#1465]
Which symbol used for power operator?
I wish to check what result return this -2^2 but ^ not recognized as operator.

**Comment by WaynePhillipsEA** [comment]
That's a parser bug.   `^` is not only the power operator, but also the LongLong datatype suffix (in VBA64 and tB), so the parser is incorrectly interpreting that expression.  You can use `-(2)^2` to workaround it until fixed.

**Comment by WaynePhillipsEA** [comment]
Actually, just adding the appropriate space is sufficient:   `-2 ^2`

BTW, VBA64 also has the same problem, so this is a difficult problem to solve due to the overloaded use of power operator.

**Comment by M2000Interpreter** [comment]
I use && for long long types in M2000, but I think you want tour language to be compatible with VBA64. But maybe you have a option to change the ^ symbol to && for long long (signed long long)
