### ISSUE TITLE
Import from VB6 Project error   

### ISSUE THREAD

**Issue by wopag** [twinbasic/twinbasic#1467]
Importing an exiting project

'Load Png to Picture Control
 Sub PngPictureLoadSize(PathFilename As String, PictureControl As PictureBox, w As Long, h As Long)     
   Dim Token    As Long
    Token = InitGDIPlus
    PictureControl = LoadPictureGDIPlus(PathFilename, w, h)
    FreeGDIPlus Token
End Sub

Where   function looks correct (part of XLibrary)

' Loads the picture (optionally resized)
Public Function LoadPictureGDIPlus(PicFile As String, Optional Width As Long = -1, Optional Height As Long = -1, Optional ByVal BackColor As Long = vbWhite, Optional RetainRatio As Boolean = False) As IPicture
    Dim hDC     As Long
    Dim hBitmap As Long
    Dim Img     As Long
        
    ' Load the image

Error is 

LoadPictureGDIPlus:   (compile error: too few arguments, expected at least 1 in call to 'LoadPictureGDIPlus')
unable to bind to reference; this is a ReadOnly binder
unable to resolve call as no suitable default (DISPID_VALUE) member found on type 'IUnknown'

I presume type iPicture is at fault ?

**Comment by WaynePhillipsEA** [comment]
Could you try `PictureControl.Picture =` instead of just `PictureControl =`?    It sounds like Picture is not set as the default member, so I will check that later.

**Comment by wopag** [comment]
Sub PngPictureLoadSize(PathFilename As String, PictureControl As PictureBox, w As Long, h As Long)
   Dim Token    As Long
    Token = InitGDIPlus
    PictureControl.Picture = LoadPictureGDIPlus(PathFilename, w, h)         <<<<<<<<<<<<<<<<<<<<<<<
    FreeGDIPlus Token
End Sub

Run-time error 91 (0000005B)
Object variable or with block variable not set

**Comment by bahbah** [comment]
@wopag, might need to be

 **Set** PictureControl.Picture = LoadPictureGDIPlus(PathFilename, w, h)

**Comment by wopag** [comment]
Still the same error message.

**Comment by wopag** [comment]
[XLibrary.zip](https://github.com/twinbasic/twinbasic/files/10484419/XLibrary.zip)

if it helps...

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 246, thanks!

**Comment by swiler** [comment]
Hi, I am using a Chilkat plugin and I am getting the following error:

twinBASIC VB6 Run-time error 91 (0000005B) Object variable or With block variable not set but it works in native VB6 IDE.

```
    Option Explicit
    Dim glob As New ChilkatGlobal
    Dim success As Integer

        ' Unlocks the component.
        success = glob.UnlockBundle("xxxxxxx")
```

It is blowing up on this line:  success = glob.UnlockBundle("xxxxxxx") 

Thanks.

**Comment by fxl447098457** [comment]
chilkat is running fine in twinbasic.
![2024-12-12_082720](https://github.com/user-attachments/assets/e5627233-717b-4e4f-adfc-c56cfedd3e78)

**Comment by fafalone** [comment]
Might be an early vs late binding issue? Is the reference correctly added in tB? If the Use ActiveX controls box is checked, try unchecking it. you have to scroll the references  list horizontally to see it.

The need for that in some cases should be fixed soon.

**Comment by swiler** [comment]
@fafalone , the issue seems to have been the ActiveX controls box.  Thank you.
