### ISSUE TITLE
RaiseEvent event names not case corrected

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1468]
**Describe the bug**
Function names, sub names, etc, are all automatically case corrected automatically, however event names following RaiseEvent are not.

**To Reproduce**
Open UserControl with event
Type RaiseEvent (eventname) in the wrong case

**Expected behavior**
Case correction to be consistent with it being done for everything else.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.237

**Additional context**
Very minor super low priority, much more important things to worry about now but hopefully this gets revisited at the appropriate time :)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 246, thanks!
