### ISSUE TITLE
VBE Addin sample broken in latest release

### ISSUE THREAD

**Issue by Greedquest** [twinbasic/twinbasic#1471]
**Describe the bug**
Using the VBE addin sample project, saving as "test.twinproj" in my downloads folder but otherwise changing nothing, the build and Registry registration succeed, but I get the error on startup:

![image](https://user-images.githubusercontent.com/25348920/215324665-128c5b7c-b3bc-4b99-97f2-6c48a2c18ff2.png)

**To Reproduce**
1. Create & Build addin sample (64 bits)
2. Open VBE

**Desktop:**
 - OS: Windows 11
 - twinBASIC version: BETA 237
 - 64-bit VBE

**Additional Information**
I use Rubberduck also, but no other VBE addins

Is there some logging I can perform?

**Comment by WaynePhillipsEA** [comment]
Noted in the release notes in all recent versions building ActiveX controls is known to bed broken in these releases.  The next release is a major release for ActiveX support, and so this will be working again very soon.

**Comment by Greedquest** [comment]
Oh sorry I didn't know that's what ActiveX controls were, thanks for clarifying👍

**Comment by WaynePhillipsEA** [comment]
No worries.  Addins themselves aren't; it's the toolwindow that's an ActiveX control.
