### ISSUE TITLE
Dinamically load control

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1478]
hello , as i promised yesterday today i post a problem about dynamic loading of controls , i have this simple code
command1  have index 0 already
`    
Sub LoadButton()
        Dim k As Long
        
        For k = 1 To 10
            Load Command1(k)
            Command1(k).Move Command1(k - 1).Left, Command1(k - 1).Top + Command1(k - 1).Height, Command1(k - 1).Width, Command1(k - 1).Height
            Command1(k).Visible = True
        Next
    End Sub
    Private Sub Command2_Click()
        LoadButton
    End Sub`
![immagine](https://user-images.githubusercontent.com/124681792/217542981-3e99147e-5bf1-4025-bbf3-14f245144cbe.png)

the code become in this error , i dont know if it is a know problem , I tried to search but couldn't find , in vb6 thiscode work.

![immagine](https://user-images.githubusercontent.com/124681792/217543296-89f7401a-25f7-40a8-9ced-fa419139c82b.png)

best regards

**Comment by sokinkeso** [comment]
Hi, there is already an open issue for this.
https://github.com/twinbasic/twinbasic/issues/1436

**Comment by bodrusG** [comment]
sorry ... I didn't search well

**Comment by sokinkeso** [comment]
> sorry ... I didn't search well

It's ok...it can happen to anyone 🙂
You can close this issue, and we will wait until the Load statement is implemented. I think Wayne has this in his mind.

**Comment by WaynePhillipsEA** [comment]
Closing this duplicate.  Thanks.
