### ISSUE TITLE
Setting Picturebox Scalemode via Comand Button Click causes Error

### ISSUE THREAD

**Issue by bcelestia** [twinbasic/twinbasic#1479]
**Describe the bug**
The following code causes an Error in Graphics.twin

Class Form1
   
    Private Sub Command1_Click()
        Picture1.ScaleMode = vbPixels
    End Sub

End Class

**To Reproduce**
1. Create a standard Exe
2. Add a picturebox and command button
3. Add the above code.
4. Click the button

**Expected behavior**
The picturebox scalemode is set to vbPixels

**Screenshots**
![image](https://user-images.githubusercontent.com/101827535/217626551-d5401281-02bd-47bf-a60c-9e6bae92474a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [Beta 245]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Hmm yes, this is a regression.  Thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 246, thanks!
