### ISSUE TITLE
Error message details

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1482]
**Is your feature request related to a problem? Please describe.**
Not too important, only a few minor ideas to the error messages:

Now:

![Error message 001](https://user-images.githubusercontent.com/94013032/218059497-41381741-116a-4c72-aee3-1c35caf1b0d2.jpg)

How I think:

![Error message 002](https://user-images.githubusercontent.com/94013032/218059634-ee1005b2-9d31-42c9-9970-2d26e49eb601.jpg)

Can you show the importance of the message with special icons? Error message with a yellow ! icon or something else, but not with a standard info icon.
I think it should be better to begin the text with the error itself.

**Comment by fafalone** [comment]
'text not in the center'? what is it off by 1 or 2 pixels? or that it shouldn't be centered in the button? (that i'd disagree with, text centered in the button, buttons on the right is the standard UI design and should be followed)

**Comment by DinyaZ** [comment]
The main idea was to change to text, and the error message comes first to show the problem, and only then the additional info, for example the filename. 
And an icon which shows better that this is an error message.
.
.
And the button was only a very minor, cosmetic issue, absolut not important now, but if you ask it, I have meant this:
.
![Image447](https://user-images.githubusercontent.com/94013032/218095323-c5ea18c3-83ab-4903-968d-d51abf8fe58e.jpg)

**Comment by WaynePhillipsEA** [comment]
Sorted in BETA 247, thanks
