### ISSUE TITLE
TB  can't  recognized   Printer ？

### ISSUE THREAD

**Issue by forliny** [twinbasic/twinbasic#1485]
**Describe the bug**

![image](https://user-images.githubusercontent.com/44160049/218246276-98aaf73b-4a2e-4d6d-8a48-1fca69216bc2.png)

 PrinterName = Printer.DeviceName  ' Current printer
 hPrtDC = Printer.hdc              ' hDC for current Printer

TB can't  recognized   Printer

![image](https://user-images.githubusercontent.com/44160049/218246265-b64ffd44-f719-4a97-a52f-44819f6675bf.png)

**Comment by sokinkeso** [comment]
Hi, the printer object is not implemented yet.
There is already an open issue for this. See:
https://github.com/twinbasic/twinbasic/issues/893
