### ISSUE TITLE
Runtime error in TypeOf statement

### ISSUE THREAD

**Issue by Kumpel62** [twinbasic/twinbasic#1488]
**Describe the bug**
This is my first attempt at testing twinBasic - the "Read SMBIOS" project on VBForums. Compilation was successful, but I got an runtime error "Object Reguired" when running the application. The development environment indicated the following problem:

![image](https://user-images.githubusercontent.com/101055155/218514078-1b67cc38-66b4-46ca-971a-0bae798755f7.png)

Replacing "NypeOf" with "IsObject" helped to get around this error, the application works.
In any case, twinBASIC impressed me :)

**Desktop (please complete the following information):**
 - OS: WINDOWS 7
 - twinBASIC compiler version IDE Beta 249

**Comment by WaynePhillipsEA** [comment]
Welcome @Kumpel62!   Thanks for the bug report.  I will look into this one, and hopefully have a fix issued tomorrow.

If at all possible, could you send the screenshot again, but include the VARIABLES panel, with the `Item` node visible (and with the node expanded)?

**Comment by Kumpel62** [comment]
![image](https://user-images.githubusercontent.com/101055155/218526160-beaf094d-0aec-4b2d-9f4b-f677392342ad.png)

**Comment by Kumpel62** [comment]
Might be useful
![image](https://user-images.githubusercontent.com/101055155/218541727-d07aa9fc-b50f-4577-97d4-1cee8976214b.png)

**Comment by wqweto** [comment]
@Kumpel62 You cannot use `TypeOf` on a Variant holding `False` i.e. non-reference type and this is consistent with VBx behavior.

You have to test first with `IsObject`, then check the reference is not `Nothing` and only then you can type-check with `TypeOf` operator.

**Comment by Kumpel62** [comment]
I agree with you. But this is not my code, but a finished project from VBForums. Of course, I had to add some exception handlers to the project, but not in this place. VB6 had no problem with this line of code. The error occurs only in twinBASIC. Compatibility is certainly amazing, but not perfect yet :)

**Comment by bclothier** [comment]
Just to verify - is this a case of an `Variant` containing an `Object` that contains a default member? Resolution can get ambiguous in this case.

**Comment by Kumpel62** [comment]
@bclothier  This variable may or may not contain an object, as in this case. The reason is in the FetchAndBrowseSMBiosData method of the SmbiosInformation class, where is the line of code that provokes the exception

`AddByteBooleanValue "Used20CallingMethod", 0`

But it looks like VB6 first checks the content for an Object and then for a Collection. That is, in VB6, a runtime error does not occur.

**Comment by WaynePhillipsEA** [comment]
Hmm yes, `TypeOf` on a `Variant` appears to just return `False` for non-Object types, despite the same throwing compilation errors for the explicit (non-Variant) types.  This has been overlooked, and will be fixed in the next tB release.  Thanks.

**Comment by WaynePhillipsEA** [comment]
Not sure why this was closed.  I'll re-open until the fix has been released.  Thanks.

**Comment by WaynePhillipsEA** [comment]
This is now fixed in BETA 251, thanks!
