### ISSUE TITLE
Memory is locked

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1492]
**Describe the bug**
Spurious run-time error `Memory is locked` on locked array inside a UDT.

**To Reproduce**
In Std-EXE project's Form1
```
    Private Type MyItem
    	Value As Long
    End Type
    
    Private Type MyUDT
    	Data() As MyItem
    End Type

    Private m_uCtx As MyUDT

    Private Sub Form_Load()
    	Dim uEmpty As MyUDT
        ReDim m_uCtx.Data(10)
        With m_uCtx.Data(5)
            m_uCtx = uEmpty
            .Value = 42
        End With
    End Sub
```
The same error I get with a synthetic (FADF_AUTO) overlaying byte-array w/ `SAFEARRAY.cLocks = 1` on purpose (cannot contrive sample code to lock a byte-array).

**Expected behavior**
Works in VB6.

Used to work in BETA 223 and probably later ones though might be a case of swalled error from oleaut call so this used to leak (in VB6 too).

Not sure which behavior is buggy but surely current BETA prevents legacy VBx code from running here.

**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 250

**Comment by WaynePhillipsEA** [comment]
Indeed, I can see the leak in the VB6 version.  SafeArrayDestroyData is first called, which erases the data, but doesn't delete the array itself and returns DISP_E_ARRAYISLOCKED which is completely ignored.  Then SafeArrayDestroyDescriptor is called, again failing with error code DISP_E_ARRAYISLOCKED, which is again completely ignored.

For compatibility, I will change tB behvaiour to match here, but at some point we'll want a stricter compilation mode which doesn't ignore such runtime errors (and causes leaks).

**Comment by wqweto** [comment]
Yes, this is quite unfotunate VBx impl. Allowing leaks at compiler level is the antithesis of software development IMO, so this better error out in TB so code can actually be fixed and then even backported to VB6.
