### ISSUE TITLE
Duplicate Hex Literal warning

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1495]
There is a new warning on possible misuse of headecimal literal notation.

A single line of code generates **4 identical warnings**.
**This is a trivial issue but looks a bit concerning on first sight.**

The offending line (in a function) is:

Const b24 As Long = &HFF00

win 11
tB 248

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 252, thanks!
