### ISSUE TITLE
TreeView Run Time Error adding and setting node

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1497]
**Describe the bug**
A run time error    -2147467262 (80004002) "No such Interface supported" when setting a node and adding a node in a TreeView

To replicate:
Put a TreeView and command button on a form.
In the command button:

Dim nod As Node
Dim newkey As String
newkey = "K1"
Set nod = TreeView1.Nodes.Add(, , newkey, "New-Node")

The Set nod line gives the runtime error.

Works ok in VB6

**Expected behavior**
No crash and the new node appears in the Treeview

note:   built the test project in VB6 and imported into tB

Win 11 tB251

**Comment by fafalone** [comment]
Could it be that since you imported it, it's referencing [MS]ComCtlLib.TreeView, but `Dim nod As Node` resolves to WinNativeForms.Node for the tB-native TreeView as that's a higher priority?

**Comment by dmrvb** [comment]
It could be, but its still a VB6 compatability issue.
But, not sure this is the cause as I normally see an error message if there are ambiguous references.
I will investigate.

**Comment by dmrvb** [comment]
You are correct, 
Dim nod As MSComctlLib.Node
fixes the problem.
So how can this be handled to give VB6 compatability without a whole load of code editing?.

**Comment by fafalone** [comment]
I believe the native common controls that are in the OCXs should have their code qualified automatically, to make it possible to simply move the OCX higher in the reference list.

However, unless you're using both controls, e.g. ocx TreeView *and* tB TreeView in the same project, you should already be able to do that now without issue. But you'd have to stick to using all controls from the OCX where applicable, otherwise you'd have to qualify everything yourself.

**Comment by WaynePhillipsEA** [comment]
The plan is, to move our native TreeView and Progress at it into a separate package, rather than them being so bundled in WinNativeForms.  That way, the native versions won't conflict with the ActiveX ones in an imported project.

**Comment by dmrvb** [comment]
Thanks
As said before, I try to be a high level programmer so am not expert in some of the low level details of COM and compiler design, Can you explain why bugs like this can't be detected at edit/compile time rather than waiting for run time failures?
More generally I sometimes get a "type missmatch" runtime error in VB6 and thought that this could be spotted at compile time???

**Comment by WaynePhillipsEA** [comment]
At compile time it is not known whether an object instance actually implements a requested interface.  The type information from the library can give you a clue, but the type library information is not authoritative.  For example, the type library might state that class `Foo` only implements interface `IFoo`, but the implementation of Foo actually perhaps might also implement `IBar` as well (but has chosen not to expose that information publicly in the type library).  The only way to know is to let it run at runtime and the `IUnknown::QueryInterface` call will either succeed or fail for the requested interface.

**Comment by wqweto** [comment]
> (but has chosen not to expose that information publicly via the type library)
Esp. when `IBar` is private this happens automatically.

**Comment by dmrvb** [comment]
Thank you, thats a good clear explanation.
I like fast code, does this give a significant time penalty? Is the same check required on subsequent calls or does the compiler remember than an interface exists?  If the object is created by myself in the same project does the QueryInterface still happen or does the compiler know what interfaces/methods are available? 
Its good to know these things because then I can avoid putting object references in big loops etc

**Comment by wqweto** [comment]
> So how can this be handled to give VB6 compatability without a whole load of code editing?.

This is not possible in VB6 too. If you add a form from one project to another project the source code might not compile depending on the **order** of target project references which is very unfortunate. To be future-proof modules have to use `LibName.TypeName` fully qualified format for every inteface `Dim`ed and every class `New`ed.

This only shows how dated the language is because modern languages prevent ambiguities at file level by requiring to either use fully qualified names like `System.Controls.MSComCtl.Node` or explicitly declare which namespaces will be assumed with `using System.Controls.MSComCtl` so that `Node` identifier is searched in only an explicit list of namespaces defined at file level not like in VB6 in all references at project level and in some obscure order.

**Comment by dmrvb** [comment]
Yes, I have been caught out by this before.
I am going through the project right now to sort this out.
I am happy to make some small mods to get my code to run in tB, indeed tB is highlighting quite a few things that need improving. However if we really want 100% compatability, especially for new users, then this is a potential problem.
Is it possible to give a warning at compile time that there is a possible ambiguity? I have found the other tB warnings to be really useful.

**Comment by WaynePhillipsEA** [comment]
The fix is already mentioned...

>  The plan is, to move our native TreeView and ProgressBar into a separate package, rather than them being bundled in WinNativeForms. That way, the native versions won't conflict with the ActiveX ones in an imported project.

**Comment by wqweto** [comment]
> However if we really want 100% compatability, especially for new users, then this is a potential problem.

This will fix by itself the moment built-in WinNativeForms is modelled after VB's physical components/DLLs i.e. separate  ComCtls library (or couple of libraries) which can be reordered separately than WinNativeForms library.

**Comment by bclothier** [comment]
> This only shows how dated the language is because modern languages prevent ambiguities at file level by requiring to either use fully qualified names like System.Controls.MSComCtl.Node or explicitly declare which namespaces will be assumed with using System.Controls.MSComCtl so that Node identifier is searched in only an explicit list of namespaces defined at file level not like in VB6 in all references at project level and in some obscure order.

Agreed; it would be nice if there was a warning & quickfix given for ambiguous references.  The ambiguity problem will become bigger once the concept of twinpack takes off. 

For reference, we have issue on this discussion: 
https://github.com/twinbasic/lang-design/issues/21

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 254 as discussed.  Thanks!
