### ISSUE TITLE
Forms do not close correctly so will not redisplay

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1499]
**Describe the bug**
Run Time Error or fail to display if form closed and then shown again.

**To Reproduce**

command button on Form1.
In command button:
Form2.show 1

This will display Form2 modally
Close Form2 with its control box and then click the Form1 command button again.

This gives run time error 400, "Form Already displayed, can't show modally"

works ok in VB6

win11 tB251

**Additional context**
Actually have three command buttons on Form1 to do
Form2.show 1
Form2.show 0
Form2.visible = true

plus a command button on Form2 to execute Form2.visible = false.

various incorrect behaviour but probably related to above

**Comment by WaynePhillipsEA** [comment]
Thanks.  Confirmed regression from BETA 235 onwards.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 252, thanks!
