### ISSUE TITLE
Some minor IDE QOL improvements

### ISSUE THREAD

**Issue by adakordev** [twinbasic/twinbasic#1504]
**1)**
When you now press enter the "End Sub" will not be added, but the "private" and "sub" will now begin with capital letters. Could we make it work so when we do not use Capital letters, the "End Sub" will be added automatically as well? Right now both of them have to begin with a capital letter, otherwise it will not add "End Sub"
![grafik](https://user-images.githubusercontent.com/31490758/221196045-2ebcec29-65f0-425c-bd73-d0fb3a107adb.png)

**2)**
My caret is after test(). When I now press Enter...
![grafik](https://user-images.githubusercontent.com/31490758/221198164-0107e4ad-a33d-4577-976f-1c8721fc2dcc.png)

...my caret will be here, but I would like to automatically add a tab in such case...
![grafik](https://user-images.githubusercontent.com/31490758/221198341-7d965823-3227-4693-9b90-3647faf5a57c.png)

...so it would appear here. 
![grafik](https://user-images.githubusercontent.com/31490758/221198600-6eba9908-966b-43c0-92db-ea0fc17844a2.png)

**3)**
When I have something to paste, the first pasted line is always indented in a false way. Even when I set the caret to the correct position, see 2) picture 3. It comes out this way:
![grafik](https://user-images.githubusercontent.com/31490758/221199743-f40f78fe-6967-4fb5-acbe-3c0fdd8f9a3f.png)

Only when I set the caret here and paste afterwards, it will be correct, but this shouldn't be the way.

![grafik](https://user-images.githubusercontent.com/31490758/221200166-360b7329-6e57-4d6c-a221-8c604995ac64.png)

**4)**
Could we please make Print the first option here, so I can just Tab. The intellisense option I need is never the first one, but the second.
![grafik](https://user-images.githubusercontent.com/31490758/221200895-bf435c7a-6925-4d5c-9770-221b29f25644.png)

**Comment by WaynePhillipsEA** [comment]
1st issue should now be resolved as of BETA 420.

**Comment by adakordev** [comment]
4) issue should now be resolved as of BETA 422.

**Comment by adakordev** [comment]
First issue 1) does not work in 429 again. 
Try "if true then" for example.

**Comment by WaynePhillipsEA** [comment]
Fixed again in BETA 430.   Thanks!
