### ISSUE TITLE
Error in importing items with user controls

### ISSUE THREAD

**Issue by dj-make** [twinbasic/twinbasic#1507]
[Demo.zip](https://github.com/twinbasic/twinbasic/files/10832946/Demo.zip)
Error in importing items with user controls
![1](https://user-images.githubusercontent.com/122567615/221391869-a9ee2690-77a8-4f58-9461-72fdb2291d01.jpg)
![2](https://user-images.githubusercontent.com/122567615/221391870-847a2abd-737f-4790-a8a5-90cc2e2c500e.jpg)

**Comment by sokinkeso** [comment]
The error occurs if the first letter of the project name is not a character of the Latin alphabet. 
I tried naming a project with greek leters (name: δοκιμή) , and got the same error while importing to tB.
Setting the name (in VB6) :  xδοκιμή   (the first letter is now the english x),  it works ok, and the import done normaly.

**Comment by dj-make** [comment]
> 发生这种情况是因为 vb6 中的项目名称是中文的。如果项目名称的第一个字母不是拉丁字母的字符，则会发生此错误。我尝试用希腊语 leters（名称：δοκιμή）命名一个项目，但在导入到 tB 时遇到了同样的错误。设置名称（在 VB6 中）：xδοκιμή（第一个字母现在是英文 x），它工作正常，导入正常完成。



> It happens because the name of the project in vb6 is in chinese. The error occurs if the first letter of the project name is not a character of the Latin alphabet. I tried naming a project with greek leters (name: δοκιμή) , and got the same error while importing to tB. Setting the name (in VB6) : xδοκιμή (the first letter is now the english x), it works ok, and the import done normaly.
![1111](https://github.com/twinbasic/twinbasic/assets/122567615/f99f31de-c152-4bce-a730-3797c1d1190d)
![2222](https://github.com/twinbasic/twinbasic/assets/122567615/7ca304dc-f7d0-4e56-9f29-08dfddeb1265)

It's strange that importing a regular VB project without user controls doesn't have any problems.

**Comment by sokinkeso** [comment]
It's not so strange...if you see inside the .frm file of your project, default controls have the prefix vb. , and usercontrols have as prefix the project name...so there is something happening when parsing the .frm file..I think it is an easy fix..
We will wait for Wayne to check this..

**Comment by WaynePhillipsEA** [comment]
Nice catch, @sokinkeso!

Fixed in BETA 325.
