### ISSUE TITLE
picturebox forecolor and picture textheight  dont' work

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1508]
Hi I think there is a problem in the ForeColor property of the picturebox when it is set from code, also there is another problem in the TextHeight function and maybe also in TextWidth
I attach a simple example to replicate the situation in twinbasic and in vb6

[TestForeColorAndTextHeight.zip](https://github.com/twinbasic/twinbasic/files/10834619/TestForeColorAndTextHeight.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 269, thanks for reporting.
