### ISSUE TITLE
The `App` object no longer recognized

### ISSUE THREAD

**Issue by joyfullservice** [twinbasic/twinbasic#1513]
**Describe the bug**
In (at least) the last couple releases of twinBASIC the `App` object is not recognized. (Worked fine in v129)

**To Reproduce**
1. Open a project that uses the App object. (Such as [this one](https://github.com/joyfullservice/msaccess-vcs-integration/tree/dev/Ribbon))

**Expected behavior**
The `App` object should be recognized.

**Screenshots**
![image](https://user-images.githubusercontent.com/7254992/222260652-6ad6cdfc-8c8c-4b76-8231-76f0309398b1.png)

![image](https://user-images.githubusercontent.com/7254992/222260708-5e77c727-fe0d-4138-81e4-1b0ee65d1973.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 257, 256, etc...

**Additional context**
I assume this object is still supported in the latest compiler versions...  🤔

**Comment by dmrvb** [comment]
and App.Startmode is still not supported.

**Comment by GCuser99** [comment]
FYI, I only get the "Unrecognized symbol" error in the IDE - I'm still able to compile and my code (using App) seems to work fine.

**Comment by fafalone** [comment]
Looks like the App object still requires a reference to WinNativeForms. (`[COMPILER PACKAGE] WinNativeForms Package` right up top of references). 

If you add that, the error will go away.

**Comment by joyfullservice** [comment]
Thanks! Adding the reference as suggested by @fafalone seems to have resolved the problem, and I am able to compile the project now. I guess that must have been a change somewhere along the way, since version 129 didn't require the reference to compile the same project.

**Comment by bclothier** [comment]
IIRC it'd be around the version when support for creating kernel mode drivers was introduced since it had to be possible to build without any references to the VB objects (just like in VB6, AIUI).

**Comment by fafalone** [comment]
My kernel mode driver project works in Beta 95 or newer, don't blame me for that :P

If you didn't use the App object, it's code wouldn't get incorporated.
