### ISSUE TITLE
bad json

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1515]
Hi , i have this bug qune i try to write the code in te parameter or if th mouse is on the keyword 

![immagine](https://user-images.githubusercontent.com/124681792/222781108-ffc89c69-c209-442d-973c-5521f02bb878.png)

twinbasic 259
win 10 64

**Comment by WaynePhillipsEA** [comment]
Could you use the copy to clipboard option, and paste it into a TXT file, and attach the TXT on here?  Thanks

**Comment by bodrusG** [comment]
shure

'''
{"jsonrpc":"2.0","id":"6","result":{"contents":{"kind":"markdown","value":"AddFormatoColonnaTitolo ( ByRef Testo As String, Optional ByRef Width As Long = 100%, Optional ByRef ColoreInizio As Long = vbWindowBackground, Optional ByRef ColoreFine As Long = vbWindowBackground, Optional ByRef VersoRiempimento As eVersoRiempimentoCella = eVersoRiempimentoCella.None, Optional ByRef AllineamentoH As eTipoAllineamentoH = eTipoAllineamentoH.Left, Optional ByRef AllineamentoV As eTipoAllineamentoV = eTipoAllineamentoV.Center, Optional ByRef FontName As String = "Consolas", Optional ByRef FontSize As Integer = 10%, Optional ByRef FontBold As Boolean = False, Optional ByRef FontUnderline As Boolean = False, Optional ByRef FontItalic As Boolean = False )\r\n___\r\n## **AddFormatoColonnaTitolo**\r\n>`in _ActiveXControlExtender`\r\n\r\n*no further information available. &nbsp; to add documentation here, add `[Description(\"\")]` annotation above the procedure.*"},"range":{"start":{"line":9,"character":19},"end":{"line":9,"character":42}},"selectionRange":{"start":{"line":9,"character":19},"end":{"line":9,"character":42}}}}
'''

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 261.  Thanks for reporting!
