### ISSUE TITLE
bug in graphics methods compared with vb6

### ISSUE THREAD

**Issue by bodrusG** [twinbasic/twinbasic#1516]
Hi , I think there are some problems in the graphical methods of TwinBasic compared to vb6.
I created an example in vb6 and then imported it into Twinbasic, the code of the two examples is identical.
As you can see in the attached image, after scrolling a few times the grid lines are not drawn correctly in Twinbasic.
I am also attaching the project in both vb6 and Twinbasic

![immagine](https://user-images.githubusercontent.com/124681792/222900262-166fd721-9177-4629-a058-ab023cde4781.png)

![immagine](https://user-images.githubusercontent.com/124681792/222900273-17c982fd-a802-4110-ab19-a89fc47ec3d3.png)

[TestGrid.zip](https://github.com/twinbasic/twinbasic/files/10888280/TestGrid.zip)

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting it.   This looks like a simple GDI objects leak:

<img width="603" alt="tbGDILeak" src="https://user-images.githubusercontent.com/25738109/222907040-3ce4d313-e1c6-470f-b911-ac84d2acdcfd.png">

The GDI objects count is going up 900+ each time you scroll.   It's probably a font handle leak.  I'll look into it further and get back to you.

**Comment by bodrusG** [comment]
Thanks, I think this issue is also related to Issues 1508 and 1509.
At the beginning I had used a picturebox but there was often an error on WindowRootElemnt = nothing so I tried to use the device context of the usercontrol and the error on WindowRootElement doesn't happen anymore

**Comment by WaynePhillipsEA** [comment]
GDI font leak is now fixed in BETA 262, and from preliminary tests, that fixes this issue, so I'll close this.  Thanks!
