### ISSUE TITLE
Turn off the splash screen

### ISSUE THREAD

**Issue by dragokas** [twinbasic/twinbasic#1517]
When I run compiled console app, the splash screen "twin Basic" is appearing.
Is it adjustable, to turn off?

**Comment by FullValueRider** [comment]
Easy.  Just buy a license.  The 64 bit community version has the sspash screen.

**Comment by dragokas** [comment]
I see. Thanks.

**Comment by GaryMiller** [comment]
How many seconds is the Splash screen up for?

**Comment by FullValueRider** [comment]
Five

**Comment by dragokas** [comment]
5 sec. on Windows 7 / 11.
No splash screen on Win XP.
Also, first 3 sec. the taskbar is locked.
-
Where the license can be bought?

**Comment by WaynePhillipsEA** [comment]
https://twinbasic.com/preorder.html

Note that if you compile to 32-bit (Win32 target), then you will avoid the splash screen altogether.

**Comment by dragokas** [comment]
I see, thanks for info. I was need x64.

Good luck on project!
Very well done.

**Comment by fafalone** [comment]
IMO it would be a good idea to put a link to the preorder page in that enter license window.
