### ISSUE TITLE
DriveListBox .drive property

### ISSUE THREAD

**Issue by doctmn** [twinbasic/twinbasic#1520]
Hi guys :)
I'm not really sure it's a bug, but I don't understand.

A form with a DriveListBox.

    Private Sub Form_Load()
        DriveListBox.Drive = "d:"
    End Sub

Why on startup iI see always "c:" drive in DriveListBox? 
Yes, after I can change, but I would like to start app in another unit.

I tried with other parameters and syntaxes: nothing to do.

 - Windows 10 PRO
 - twinBASIC IDE BETA 257

In VB and the .drive property of DriveListBox works just like that.

Thanks :)

Doc

**Comment by fafalone** [comment]
Definitely a bug. Confirmed/reproduced in 263.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 265.  Thanks!
