### ISSUE TITLE
Shall twinbasic support cdecl dll some time later?

### ISSUE THREAD

**Issue by loquat** [twinbasic/twinbasic#1523]
how about this?
Declare PtrSafe Function wtoi64 CDecl Lib "msvcrt" Alias "_wtoi64" (ByVal psz As LongPtr) As Currency

**Comment by bclothier** [comment]
It already exists.

See https://github.com/twinbasic/lang-design/issues/25

**Comment by loquat** [comment]
but it seems do not support Cdecl callbacks?

**Comment by bclothier** [comment]
Correct. That is why it's still open so this can be tracked.

**Comment by loquat** [comment]
Thanks, will be in track.
