### ISSUE TITLE
Label Control does not fully instantiate on a form

### ISSUE THREAD

**Issue by AntsAntix** [twinbasic/twinbasic#1525]
**Describe the bug**
The Font object does not instantiate along with its parent control, in this case a Label. If you refer to the attached screenshot, in the Variables panel, you will see that DragIcon, MouseIcon, and Font are still set to 'Nothing'. Other than that, the Label has been instantiated. 

**To Reproduce**
As an aside: I have taken Mathieu Guidon's MVVM pattern from VBA and have attempted to implement it into twinBASIC. Generally, this code works in VBA. 
I originally built this project in twinBASIC from 'scratch'. In other words, I manually created the project in TB along with each class/module and then copied the required code from each class/module into TB. But the form was completely new.
The project compiled successfully, but I when I ran it from the IDE, it reached this point in the execution.
I then took this project back to VB6 and rebuilt it as a VB6 project. This to make sure that I had not corrupted anything. In that IDE, it executes as expected.
I then imported that VBP back into TB. The result was the same (similar).
  
**Expected behavior**
I expect that form controls would fully instantiate when they are created.

**Screenshots**
![image](https://user-images.githubusercontent.com/89644755/224626560-4104a62e-afb3-4c8a-be97-9354cdb549a3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [BETA 268] . . . but started with earlier versions

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Difficult to be 100% sure with not having the twinproj to test, but I think this is now fixed in BETA 269.  If not, just let me know and I'll re-open.  Thanks.
