### ISSUE TITLE
Form designer - font sizing issue

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1527]
See screenshots, or test with the TbLoader source code in Tb! 
In VB6 is looks ok, but in Tb form editor the same font sizes became microscopically small!
.
Another question: the dotted background of the form is now almost invisible in Tb
.
(One more thing: I think, the Tb new and nice toolbox icons are perhaps a bit too big....? And perhaps that is why they seem to be too colorful, and catching the eyefocus too much.)

**Desktop (please complete the following information):**
 - OS: Win10
 - twinBASIC compiler version: beta270
 
![Image6TB](https://user-images.githubusercontent.com/94013032/224842911-58840ffa-c561-4655-84ad-83b82d6de0df.jpg)

![Image6](https://user-images.githubusercontent.com/94013032/224842932-0e9eb49a-3ff6-4af6-b8ac-4bafab441bef.jpg)

**Comment by WaynePhillipsEA** [comment]
The font issue is now fixed in BETA 271.     The dots are not yet DPI-aware, but will be soon.   And there will be further improvements to the toolbox icons in the next release.   Thanks.
