### ISSUE TITLE
`App` object not ready upon calling `Sub Main`

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#1529]
**Describe the bug**

Trying to set `App.Title` in `Sub Main` and I get this:

```
16:34:45.765  (runtime error -2147467259: NATIVE EXCEPTION: ACCESS_VIOLATION)
16:34:45.810  0001 14:34:45.765 NATIVE EXCEPTION: ACCESS_VIOLATION /MyModule.twin LINE 000004
```

**To Reproduce**

In project setting set `Sub Main` as startup object and try this code
```
    Private Sub Main()
         App.Title = "Test"
    End Sub
```
**Desktop (please complete the following information):**
 - OS: Win11
 - twinBASIC compiler version: BETA 278

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 290, thanks!
