### ISSUE TITLE
Bug Importing vb6 Project Containing a Microsoft Script Control on a  Form

### ISSUE THREAD

**Issue by bcelestia** [twinbasic/twinbasic#1533]
Create a VB6 project containing a Microsoft Script Control on a form
Import into Twinbasic
Run the Project

Twinbasic Internal Error message Appears as below (Error 9405 Failed to deserialize form)

 - twinBASIC compiler version 292

![image](https://user-images.githubusercontent.com/101827535/230692030-8f2fda24-fa76-4263-9927-a2dd71f63946.png)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 296, thanks
