### ISSUE TITLE
For Next using Array element generates 2 errors

### ISSUE THREAD

**Issue by LastJasonNext** [twinbasic/twinbasic#1536]
When assigning an Array element [ie m(2)] to a For Next, and adding that element to the Next statement, the loading of a VBP file generates two errors per instance:
1. Syntax error.  No handler for this symbol
2. Control variable does not match the opening For statement

**To Reproduce**
For m(2) = 0 to x
     'operations
Next m(2)           [error: ie. m(2) does not match m(2)]

**Expected behavior**
The "Next m(2)" steps the Array element without generating the two errors.

**Work Arounds**
1. Placing a non-array element with the Next statement appears to operate correctly
2. VB6 recognizes the Next determinant as an optional entry, and in current twinBASIC using Next without a determinant avoids the error and appears to operate the For Next normally.

**Screenshots**
DNA

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - twinBASIC IDE_BETA_292

**Additional context**
A couple of unrelated observations:
1. While the Compiler creates a SUCCESS executable with the above For Next Array element work arounds, it also creates a SUCCESS executable with unimplemented items, such as Form.Image, PictureBox.Image and the Load statement.
2. The imported VBP contains several in process UserControls (compile SUCCESS), which successfully present in Form view as Index 0.

On a personal note, VB6 compiles the VBP with several hundred of these UserControls ala the Load statement, so a Load workaround is a practical no go. As VB6's control Index is actually a key to an object (unlike arrays), one can only imagine the complexities of incorporating them into twinBASIC, while VB6 Collections of UserControls with alphanumeric keys also have to be a consideration. The irony is not lost. What a wondrous project is twinBASIC!

**Comment by WaynePhillipsEA** [comment]
This issue is fixed in BETA 293, thanks.

For the other unrelated comments; please create separate issues/discussions in order to keep things organized, or consider coming over to our Discord server (#629) for general discussion.  Thanks.
