### ISSUE TITLE
Behaviour: Text box not scrolling down using SelStart/SelLength

### ISSUE THREAD

**Issue by RZulu54** [twinbasic/twinbasic#1540]
**Describe the bug**
Behaviour:  in VB6 the following code scrolls down a text box - twinbasic is not scrolling

**To Reproduce**
1. Create form with text box (MultiLine=true, ScrollBars=vbVertical)  and a button
Code:
>>>>>>>>
Class Form1

    Private Sub Command1_Click()
        Dim i As Long
        Text1.Text = "Top"
        For i = 1 To 100
          AddLine "Line " & i
        Next
    End Sub
    
    Private Sub AddLine(isLine As String)
        If Len(Text1) > 64000 Then Text1.Text = ""
        Text1.Text = Text1.Text & vbCrLf & isLine
        Text1.SetFocus
        Text1.SelStart = Len(Text1)
        Text1.SelLength = 0
        DoEvents
    End Sub
    
End Class
<<<<<<
2. Click on 'button
4. See error:  Text box not scrolling down
 
**Expected behavior**
Last line in text box should be visible using Selstart/SelLenght

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17248753/231775889-207cbc8a-51a5-45d0-aca9-0e63ba935dea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 294

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 295, thanks for reporting!

**Comment by Kr00l** [comment]
Good bug report. Just noticed that in VBCCR this bug is as well.. so gonna fix it also :)
