### ISSUE TITLE
Checkbox Value Property Does Not Work

### ISSUE THREAD

**Issue by jlegg05** [twinbasic/twinbasic#1542]
**Describe the bug**
When using checkboxes inside of Microsoft Access, the value property always returned its state inside of the project itself. For example, if the value is set to unchecked, it will always be unchecked, and if it is set to checked, it will always be checked

**To Reproduce**
1. Create a new tbControl, and add a checkbox
2. Make sure the checkbox value is set to vbUnchecked
3. Create a button that prints the value of the checkbox
4. Build the file and run it in Microsoft Access
5. Click on the checkbox, ensuring it is checked
6. Click the button that prints the value of the checkbox

**Expected behavior**
It will create a pop up window that reads "vbUnchecked"

**Desktop:**
 - OS: Windows 11
 - twinBASIC IDE BETA 292

**Comment by WaynePhillipsEA** [comment]
Sorry, I can't reproduce any such problem here.  Tested on both 32-bit and 64-bit versions of Access.   The checkbox Value property returns the correct 0/1 value as given by its visual state.

**Comment by WaynePhillipsEA** [comment]
Please provide the exact code being used, or (even better) provide the twinproj file.

**Comment by jlegg05** [comment]
it wouldn't send the twinBASIC file as it was too large so I uploaded it to
the github issue

**Comment by jlegg05** [comment]
It won't let me link the .twinproj as it is not a supported file type, so I'm not quite sure how to provide it, but I would be happy to. I took fafalone's ExplorerHost project and was importing it as a control to Microsoft Access, and I got it working using a workaround, but the checkboxes themselves were not functioning correctly

**Comment by fafalone** [comment]
You can attach twinproj files inside a zip.
