### ISSUE TITLE
Error evaluating constant expression and array dimensions issue when const used in Static

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1545]
**Describe the bug**
Imported a VB6 project and this error came up; the code works fine in VB6... the syntax is legal and it successfully prints the expected '0'

**To Reproduce**
The following code in any method:

```
    Const message_length = 62
    Static t(0 To message_length - 1) As Byte
    Debug.Print t(22)
```
This shows 2 two errors: 
 {ERROR} /NewProject/Sources/Form1.twin [8,19]: Error occured in evaluating constant expression

 {ERROR} /NewProject/Sources/Form1.twin [9,17]: Wrong number of dimensions for this array [given 1, expected 0]

**Expected behavior**
It's not the *best* syntax but it works in VB6, so should work in tB.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.297

**Additional context**
Does not occur with `Dim t` instead of `Static t`.

**Comment by fafalone** [comment]
Ok this is bizarre; I pasted that code into 2 other existing projects, and 2 new projects (beta 296 then confirmed still present in beta 297), and the error always came up right away. But now I can't get it to come up *anywhere* except the original project...

**Comment by bclothier** [comment]
FWIW, it looks like it's fine in a module but not in a form or a class.

**Comment by wqweto** [comment]
Order of evaluation of consts/enums has been showing intermitten errors i.e. in some cases errors can be "fixed" by adding a new module to the project.

**Comment by fafalone** [comment]
Issue resolved at some point, closing.
