### ISSUE TITLE
Incorrect error message when Array is the name of a UDT member

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1546]
**Describe the bug**

The error behaviour of twinBasic appears to be the reverse of VBA when using the name Array as a member of a UDT or Enum.

Using 'Array' as the name of a UDT members gives an unexpected error and the error message appears to be incorrect.
The same code in VBA does not generate an error.

```
public Type ArrayMemberTest
    Array as Collection
end type
```

![ArrayTypeMember](https://user-images.githubusercontent.com/81257042/232697265-3a8339fe-bf29-465a-9de8-8cc018d2b07a.jpg)

An enum containing the member name Array does not present any errors in twinbasic but does in VBA

**Expected behavior**
the behaviour of twinBasic should match VBA with a stong preference for array to be allowed in both cases if 'option strict' is not in force.

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version beta IDE 297

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 301.  Thanks!
