### ISSUE TITLE
Mouse hover over string variable with backslash characters shows wrong value

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1550]
**Describe the bug**
When I hover the mouse during a breakpoint over a string variable containing certain backslash character combinations, the IDE displays the wrong value as if it has interpreted some of the backslashes as special character escapes.

However, the variable itself appears to contain the intended characters, so it may just be an IDE hover issue?

**To Reproduce**
```
Sub testBug()
    Dim s As String
    s = "a\b\}\\"
    'locals shows s = "a\b\}\\"
    'but hover mouse over s above and it displays "a\b}\"
    Debug.Print s 'this prints "a\b\}\\"
End Sub
```
**Expected behavior**
Expecting the hover to display the actual string contents.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version 297

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 298, thanks!
