### ISSUE TITLE
ListView1.SelectedItemIndex   1. Row give no Feedback

### ISSUE THREAD

**Issue by GitHubUserEH** [twinbasic/twinbasic#1553]
**Describe the bug**
In a ListView Feld the first Row gives noch action if You click in it.

**To Reproduce**
Open New Project. Just with one ListView Field

Use this simple code to test:

Class Form1
   
   Dim a As String = "1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            
    Private Sub Form_Load()
     Dim x As Integer

     With ListView1
    
      .ColumnHeaders.Add , , "Header Test", 800
            
      .View = lvwReport
      
      For x = 1 To 50
        .ListItems.Add , , "Row " & x & "  " & a
      Next x
   
     End With
    End Sub
    
   Private Sub ListView1_Click()
       MsgBox(ListView1.SelectedItemIndex)
   End Sub
         
End Class

1. run the app
2. Click on first, second row....

**Screenshots**

Mouse-Klick in 1. Row. No alert message with the row number is displayed.

![image](https://github.com/twinbasic/twinbasic/assets/69893688/af170a70-c547-418d-aa23-393187cb6f24)

Mouse-Klick in 2., 3., 4. ... Row. Alert message with the row number is displayed.

![image](https://github.com/twinbasic/twinbasic/assets/69893688/72114860-ccf6-4d28-a671-f29f8a532da7)

**Desktop 
 - OS: [Windows 11]
 - twinBASIC compiler version [IDE Beta 301]

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 306, thanks!
