### ISSUE TITLE
E_NOINTERFACE when setting Image by def property when *not* in array

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1556]
**Describe the bug**
This is a nice switch in that usually additional bugs would crop up when a control is in an array, but this bug is only occuring when the Image control is *not* in an array.

This is all legal syntax VB6:

```
        Set Image1(0) = VB.LoadPicture(AppPath & "Plus.ico")
        Set Image1(1) = VB.LoadPicture(AppPath & "Minus.ico")
        
        Set Image2 = VB.LoadPicture(AppPath & "Pause.ico")
```
(AppPath is App.Path with a guaranteed backslash)

The first two succeed, the third fails in tB with `E_NOINTERFACE`.

**To Reproduce**
1) New StdExe

2) Add Image control array and stand-alone Image

3) Set graphic via the default property as per above.

- or -

Run attached minimal reproduction demo, which includes test icons to use in controls.

**Expected behavior**
Shouldn't matter whether it's in an array or not, and should show picture since VB6 does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.303
 
**Additional context**
[ImgBug.zip](https://github.com/twinbasic/twinbasic/files/11499260/ImgBug.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 306, thanks!
