### ISSUE TITLE
Consolidate Currentxxx into a UDT

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1560]
This request may become mute when vbWatchdog components are added to twinBasic.

**Describe the solution you'd like**
At the Moment twinBasic provides five 'current' variables that provide project name, component name etc at runtime.

Would it be possible to consolidate these five variables into a single 'object' to facilitate passing all items to a error handling routine.

e.g. rather than currentcomponentname we'd have current.componentname

**Comment by WaynePhillipsEA** [comment]
No, that's not easily done.  The compiler quite literally turns `CurrentComponentName` (etc) into a literal string, e.g. `"MyClassName"`.  Better to wait for vbWatchdog :)
