### ISSUE TITLE
Can't set default properties on control array member on Form from Module

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1562]
**Describe the bug**
Another bug brought to us by Lemmings, this time from the level editor. 

When you have a control array, here, of TextBoxes, and want to set the text through the implicit default property via an implicit conversion, it fails, with 'Does not support this property or method' in the full project and 'automation error' in the minimal reproduction. Both work in VB6.

**To Reproduce**
1) New StdExe, add new module

2) Create Text1(0) and Text1(1) on Form

3) Form code:

```
Private Sub Form_Load()
Assign
End Sub
```
4) Module code:
```
Public Type foo
    bar As Byte
End Type
Public Sub Assign()
Dim bt1 As foo
bt1.bar = 1
With bt1
    Form1.Text1(0) = .bar
End With
End Sub
```

5) Run.

**Expected behavior**
Text1(0).Text should be set to 1, as it is in VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.309
 
**Additional context**
I'm not sure if some of the parts like in a With block or implicit conversion are neccessary, but wanted to keep the minimal reproduction close to the real world bug.

Attached is the minimal reproduction, real world project, and a working VB6 version of the min repro:

[defpropbug.zip](https://github.com/twinbasic/twinbasic/files/11544430/defpropbug.zip)

**Comment by taishan1** [comment]
I'm starting to feel immense empathy and sorrow for Wayne. We love you man.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 324.  Thanks!
