### ISSUE TITLE
KeyDown event not firing for up, down, left and right keys.

### ISSUE THREAD

**Issue by Mo-Lo** [twinbasic/twinbasic#1564]
**Describe the bug**
Form_KeyDown event doesn't work for up, down,  left and right keys.

**To Reproduce**
See file attached.

**Expected behavior**
Should fire.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.314

**Additional context**

[KeyDownNotWorking.zip](https://github.com/twinbasic/twinbasic/files/11570740/KeyDownNotWorking.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 323, thanks!
