### ISSUE TITLE
Project from V129 doesn't work in V314

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#1566]
**Describe the bug**
I have a source for an AX DLL that worked fine in beta 129.
Now 'some' versions later (beta 314) I can no longer build the DLL.

**To Reproduce**
1. I would have to send the project in private, but perhaps the screenshot tells enough?

**Expected behavior**
Working of course.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/88059532/ae088367-f33c-4bb1-ae31-2b5c4df837a2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC beta 314

**Comment by KarlSevenSeven** [comment]
Similar issue with another project.

I get
`0001 09:40:36.615 NATIVE EXCEPTION: ACCESS_VIOLATION  {no-basic-code}`

In this case there is no hint in the problems panel.

**Comment by WaynePhillipsEA** [comment]
Sure, if you can share the project privately with me on discord, I suspect I'll be able to get that fixed quickly.

**Comment by KarlSevenSeven** [comment]
_privately with me on discord_

Sorry for my ignorance: How do I have to do it?

**Comment by WaynePhillipsEA** [comment]
No problem, I have just messaged you privately on discord.  Or you can send via email if you prefer (I think you have my address already)

**Comment by KarlSevenSeven** [comment]
Should be at your hands now.
Thank you!

**Comment by KarlSevenSeven** [comment]
Got an error message from Outlook when replying with an attachment.
Sent other mail now to the known address.

**Comment by WaynePhillipsEA** [comment]
Thanks, got it.  This is a regression caused by the project description being blank.  I'll get this fixed in the next release.

I'll also fix the unrelated issues involving having a variable named 'Line'.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 315, thanks!

**Comment by KarlSevenSeven** [comment]
Works again, thank you!
