### ISSUE TITLE
Paste into search box broken as of Beta 315

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1567]
**Describe the bug**
Starting in Beta 315, if you open the search box (Ctrl+F) from a code window, and use Ctrl+V to paste, it pastes directly into the code window instead of the search box, ignoring the focus and going where you don't want it.

**To Reproduce**

Open code editor

Ctrl+F

Ctrl+V

**Expected behavior**
...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version: Confirmed in 315-318

**Additional context**
Ctrl+X (cut) and Ctrl+C will also operate directly on the code window if text is selected. Suspect connection to `fixed: 'Paste' code editor context menu option not showing the 'Ctrl+V' shortcut hint [ Tecman, discord ]`

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 321.  Thanks
