### ISSUE TITLE
TypeName(Object->UserControl or Me (UserControl)) incorrect

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1569]
**Describe the bug**
In VB6, if you create a variable of type `Object`, and assign a UserControl to it, `TypeName(Object)` returns "UserControl1" or whatever the name of your control is. In twinBASIC, it's continuing to return "Object".

**To Reproduce**
-New StdExe; create new UserControl within.

-UserControl code:

```
Dim pObj As Object

Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" ( _
    lpvDest As Any, lpvSource As Any, ByVal cbCopy As Long)

Private Sub UserControl_Initialize()
    CopyMemory pObj, Me, 4
    Debug.Print TypeName(pObj)
    Debug.Print TypeName(Me)
End Sub
```
-Place UserControl on Form.

Following these steps results in VB6 printing "UserControl1" twice while twinBASIC prints "Object" twice where it should be printing "MyUserControl" twice.

**Expected behavior**
Behavior should match VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.320

**Additional context**
At first I thought this was just an issue with an `Object` variable that had been reassigned, but thanks to a typo discovered it's actually broader, so added `TypeName(Me)` which is also UserControl1 in VB6 and Object in tB.

Code assumes 32bit in tB to match VB6 for the purposes of replication.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 323, thanks!
