### ISSUE TITLE
ListView ColumnHeader missing Width property let

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1575]
**Describe the bug**
It has the property get so you can retrieve the width, but both the 5.0 and 6.0 controls for VBx have a let to change the width, which tB currently does not.

**To Reproduce**
1. New StdExe with WinNativeCommonCtls
2. Add ListView
3. Code:
```    
Private Sub Form_Load() Handles Form.Load
    ListView1.View = lvwReport
    ListView1.ColumnHeaders.Add , , "Colum 0"
    ListView1.ColumnHeaders.Add , , "Colum 1"
    ListView1.ListItems.Add , , "Item 1"
    ListView1.ColumnHeaders(1).Width = 4200
End Sub
```

**Expected behavior**
Matching VBx by implementing.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version: 0.15.324
 - 
**Additional context**
Original tlb:

```
[id(0x00000008), propget, helpstring("Returns/sets the width of an object."), helpcontext(0x000335e7)]
HRESULT Width([out, retval] single* pflWidth);
[id(0x00000008), propput, helpstring("Returns/sets the width of an object."), helpcontext(0x000335e7)]
HRESULT Width([in] single pflWidth);
```

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 332.  Thanks!
