### ISSUE TITLE
After Declaring API with PtrSafe, 64 bit AddressOf generating "Cannot coerce longlong to long" error. 

### ISSUE THREAD

**Issue by LastJasonNext** [twinbasic/twinbasic#1581]
**Describe the bug**
This may not qualify as a bug, more of what must be a common 64 bit problem when dealing with API declarations. Also fairly sure its common enough to be a requested Feature if that's appropriate. I've posted this to both.

After Declaring API with PtrSafe, 64 bit AddressOf generating "Cannot coerce longlong to long" error. 

**To Reproduce**
Private Declare PtrSafe Function EnumDisplayMonitors Lib "user32.dll" (ByVal hDC As Long, ByRef lprcClip As Any, ByVal lpfnEnum As Long, ByVal dwData As Long) As Boolean

EnumDisplayMonitors &H0, ByVal &H0, AddressOf MonitorEnumProc, &H0
Produces:
{ERROR} /Fader/Sources/modMonitorData.bas [161,45]: Validation of call to 'EnumDisplayMonitors' failed.  Argument for 'lpfnEnum': cannot coerce type 'LongLong' to 'Long'
Fairly sure a CLng() can't take care of 64 bit expecting a 64 bit address

**Expected behavior**
I'm sensing that 64 bit use of API Declarations require replacement with other type of API object reference, ala VB.NET's reference protocol.

**Desktop (please complete the following information):**
 - OS: Latest Windows 11
 - twinBASIC IDE BETA 326

**Additional context**
This may well be a feature that is really a responsibility of the programmer when dealing with 64 bit. After some degree of searching twinBasic material and discussion, I haven't found any direct reference to a twinBasic 64 bit API addressing protocol. Apologies if posting this to both Bug and Feature is overdoing things, especially if I'm simply missing something obvious.

**Comment by WaynePhillipsEA** [comment]
For of #1582
