### ISSUE TITLE
After Declaring API with PtrSafe, 64 bit AddressOf generating "Cannot coerce longlong to long" error. 

### ISSUE THREAD

**Issue by LastJasonNext** [twinbasic/twinbasic#1582]
**Is your feature request related to a problem? Please describe.**
This may not qualify as a bug, more of what must be a common 64 bit problem when dealing with API declarations. Also fairly sure its common enough to be a requested Feature if that's appropriate. I've posted this to both.

After Declaring API with PtrSafe, 64 bit AddressOf generating "Cannot coerce longlong to long" error. 

Private Declare PtrSafe Function EnumDisplayMonitors Lib "user32.dll" (ByVal hDC As Long, ByRef lprcClip As Any, ByVal lpfnEnum As Long, ByVal dwData As Long) As Boolean

EnumDisplayMonitors &H0, ByVal &H0, AddressOf MonitorEnumProc, &H0
Produces:
{ERROR} /Fader/Sources/modMonitorData.bas [161,45]: Validation of call to 'EnumDisplayMonitors' failed.  Argument for 'lpfnEnum': cannot coerce type 'LongLong' to 'Long'

Fairly sure a CLng() can't take care of 64 bit expecting a 64 bit address

**Describe the solution you'd like**
A way to deal with VB6 32 bit declarations in a twinBasic 64 bit compile that solves the AddressOf error "Cannot coerce longlong to long" error.

**Describe alternatives you've considered**
I'm sensing that 64 bit use of API Declarations require replacement with other type of API object reference, ala VB.NET's reference protocol. I'm not sure how that might be addressed in twinBasic code.

**Additional context**
This may well be a feature that is really a responsibility of the programmer when dealing with 64 bit. After some degree of searching twinBasic material and discussion, I haven't found any direct reference to a twinBasic 64 bit API addressing protocol, beyond Declaration use of PtrSafe. Apologies if posting this to both Bug and Feature is overdoing things, especially if I'm simply missing something obvious.

**Comment by WaynePhillipsEA** [comment]
It's not enough to just add `PtrSafe` to a `Declare` statement.  There are often changes needed for the parameter data types in the declare statement, and then there are also often changes needed at the callsites too.

Here's a decent explanation of the most common changes you'll need to make, written for VBA64, but all applicable to twinBASIC:

https://codekabinett.com/rdumps.php?Lang=2&targetDoc=windows-api-declaration-vba-64-bit

There's plenty of other information online for upgrading VBA declare statements appropriately, and so I don't feel we need a specific issue here for it.   As you rightly say, this is not a bug nor a feature request, but we will cover it the documentation when we reach that point.
