### ISSUE TITLE
Importing packges: Only one package can be active

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1583]
I'm exploring splitting down a large library into a number of packages.  I'm experiencing a few problems when importing the local packages into a new project

1. Its not possible to  set the selection of imported packages, you get all or none.
2. Not all of the selected packages appear in the enabled  references pane in settings, although they do appear in the Project Explorer packages list
3. If the package is not in the enabled references it cannot be referenced even though it appears in the packages section in the project explorer
![ImportedPackages](https://user-images.githubusercontent.com/81257042/235875939-ab24f844-d442-45b6-a4de-78c40f8279e4.jpg)

WIndows 11
TwinBasic beta Ide 297

**Comment by fafalone** [comment]
Transferred from lang-spec\issues to twinbasic\issues, more on topic and more visibility anyway. 

---

I'm not sure what you mean here... you can filter the All Available References/Packages list; and of course the enabled ones only shows the ones in your project... do you mean you want a new function where they're added to your project but not enabled?

**Comment by FullValueRider** [comment]
@Wayne has resolved this issue.  It was caused by copying the main package and then deleting out what I didn't need.   This meant that I generated a set of smaller packages with the same Guid.
