### ISSUE TITLE
control arrays - runtime error when copying value to internal array

### ISSUE THREAD

**Issue by JBEJBE** [twinbasic/twinbasic#1596]
**Describe the bug**
Copying a value from a control array to an internal array gives runtime error 5. 

**To Reproduce**
1. Define control array in form (Me.Such)
2. Define internal array in form code: 
   Private Suche() As Variant
4. Copy value  
    Private Sub Such_Change(Index As Integer)
         If Right(Me.Such(Index), 1) = "*" Then
             Suche(Index) = Me.Such(Index)

tb seems to suspect a call to procedure "Suche"? 

5. Using "!" instead of "."
    Private Sub Such_Change(Index As Integer)
         If Right(Me!Such(Index), 1) = "*" Then
             Suche(Index) = Me!Such(Index)

throws other errors, but works in VB6 too

**Expected behavior**
Runs perfectly in VB6 and worked in some previous tb releases to my knowledge

**Screenshots**
![grafik](https://github.com/twinbasic/twinbasic/assets/102333747/fb56ad1e-d50c-424e-92b2-2aa90ba5dad7)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version last release

**Additional context**
-

**Comment by wqweto** [comment]
This works ok with Labels conrol array in BETA 587

```
Private Suche() As Variant

Private Sub Form_Load()
    ReDim Suche(0 To 10)
End Sub

Private Sub Label1_Click(Index As Integer)
    If Right(Me.Label1(Index), 1) = "*" Or True Then
        Suche(Index) = Me.Label1(Index)
    End If
End Sub
```
Might be a problem if control array members do not have default property but then it would fail in VBx so not that plausible.

**Comment by WaynePhillipsEA** [comment]
Indeed, as far as I can see this is working in recent builds.   I'll close for now - @JBEJBE if you're still experiencing a problem, please provide an example twinproj file.
