### ISSUE TITLE
Warning for implicit array creation

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1601]
**Is your feature request related to a problem? Please describe.**
Elroy on VBF mentioned this, and I thought it was a good idea... having arrays created by ReDim should really be counted as the kind of implicit creation that violates Option Explicit, and it's just generally a bad practice prone to being used accidentally.

**Describe the solution you'd like**
tB should have a compiler warning for this, so users can choose how to handle it (ignore/warning/error).

**Describe alternatives you've considered**
Not having such a warning.

**Additional context**
Currently `ReDim x(0)` would hit a warning for implicit variant use, but `ReDim x(0) As Long` wouldn't, and these should be handled separately.

**Comment by WaynePhillipsEA** [comment]
Yes, that is definitely worthy of a warning.

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 349.  Thanks!
