### ISSUE TITLE
Regression: Invalid types in interface definitions not flagged

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1604]
**Describe the bug**
Starting in Beta 343, invalid types aren't flagged as not existing, they just stay white rather than get the red squiggle and an error entry.

**To Reproduce**
1) New StdExe

2) 
```
[ InterfaceId ("BDFE5FE3-4988-4CB7-B674-2873E8033F57") ]
Interface IFoo Extends IUnknown
	Sub Bar(arg As DoesntExist)
End Interface
```

**Expected behavior**
'DoesntExist' should be flagged as in invalid type is it is prior to 343. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.347

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 349, thanks!
