### ISSUE TITLE
Array infotip is resolving LongPtr

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1607]
**Describe the bug**
Found one more situation where it's still showing Long/LongLong instead of LongPtr.

![image](https://github.com/twinbasic/twinbasic/assets/7834493/9f565574-dfc4-46c7-9568-ce6ecf3f7ea0)

**To Reproduce**
```
Private foo() As LongPtr
Sub bar()
	ReDim foo(1)
End Sub
```

Hover over foo.

**Expected behavior**
Show declared type of LongPtr.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.349

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 350.  Thanks
