### ISSUE TITLE
Autocomplete inserts $0 in some circumstances

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1609]
**Describe the bug**
Normally when you hit tab, you expect to be able to then enter arguments. I noticed in some circumstances, it instead sets arguments as ($0) and places the caret after ).

**To Reproduce**
New StdExe
In Form, `Public Event OLEDragDrop(foo As Long)`
Then create a sub and start typing RaiseEvent OLEDr... and hit tab.

**Expected behavior**
No $0 and caret inside ().

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.350
 - 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 356, thanks.
