### ISSUE TITLE
Wrong error text for misuse of hexadecimal literal notation

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1613]
**Describe the bug**
When defining a LongLong (or LongPtr in x64) variable and set it to `&H80000000` (not `&H80000000^`) then a wrong misuse message appears.

**To Reproduce**
```
Dim i As LongLong
i = &H80000000
```

**Expected behavior**

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/33756666/570e8187-5583-4929-963e-fb9f2c5f4fe9)

![image](https://github.com/twinbasic/twinbasic/assets/33756666/d290d1c6-33de-4b38-978b-0d0164c357a2)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. BETA 351]

**Additional context**
n/a

**Comment by bclothier** [comment]
I believe this is correct. In a `LongLong`, it would be converted to `&HFFFFFFFF80000000^` which wouldn't be the same thing as `&H000000080000000^`.  The error message could be more clear, though.

**Comment by wqweto** [comment]
Btw, `&H80000000^` is `2147483648` although using decimals instead of hexidecimals in the error message brings no value to me.

**Comment by fafalone** [comment]
How would you express the difference between negative and positive interpretations here if not with decimal?

**Comment by wqweto** [comment]
I might try using words :-)) i

> Literal type mismatch. This literal has negative value of -32768 (&HFFFF8000) because its type is `Integer` while constant type is `Long`. Use `&H8000&` to force literal type to `Long` and prevent unwanted side-effects.

**Comment by WaynePhillipsEA** [comment]
<img width="641" alt="misuseOfHex1" src="https://github.com/twinbasic/twinbasic/assets/25738109/284c4da6-61dc-4a73-be7a-ca41c5861371">
 (in next release)

**Comment by WaynePhillipsEA** [comment]
(the obvious 'Integer' error in the above screenshot will be correct 😉)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 356, thanks.
