### ISSUE TITLE
SW_SHOWNORMAL

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#1615]
**Describe the bug**

![TWBImage3](https://github.com/twinbasic/twinbasic/assets/94013032/929fd7a2-eeb9-4c73-962f-1034f1894243)

Twb beta356

SW_SHOWNORMAL is missing in Tb, working in VB6.

**Comment by Kr00l** [comment]
Shouldn't use vbShowNormal ?

**Comment by DinyaZ** [comment]
> Shouldn't use vbShowNormal ?

{ERROR} /twinBASICloader/Sources/Module1.bas [217,92]: Unrecognized symbol 'vbShowNormal'

**Comment by WaynePhillipsEA** [comment]
I think @Kr00l meant `vbNormalFocus`. 

Have you got `Option Explicit` set at the top of the module?  If you haven't, then that is why the error is not showing in VB6.  When you import a VB6 project into twinBASIC you have the option to turn ON/OFF the project-wide `Option Explicit` behaviour, and by default it is ON.

**Comment by DinyaZ** [comment]
> vbNormalFocus

Ok, yes, but SW_SHOWNORMAL is not existing ? 

https://www.vbforums.com/showthread.php?830829-Using-ShellExecute-in-VB-6-0

**Comment by WaynePhillipsEA** [comment]
SW_SHOWNORMAL is not a built-in constant.

You need to define it.
