### ISSUE TITLE
byref values are not passed from parameters of subs or functions to properties of an object

### ISSUE THREAD

**Issue by IvanPausich** [twinbasic/twinbasic#1619]
byref values ​​are not passed from parameters of subs or functions to properties of an object,
![16894412681134998548778519159051](https://github.com/twinbasic/twinbasic/assets/63315610/cd7852e2-22b3-4945-9bff-046b9fafa0e4)
![16894413156054382022530577629563](https://github.com/twinbasic/twinbasic/assets/63315610/887fe68d-0504-4277-afb7-38c1e8b40ff5)

**Comment by WaynePhillipsEA** [comment]
Are you expecting the property-let of `Binario` to be called, due to the updating of the ByRef parameter in the `ADD` routine?   If so, that's not how it works in VBx.

**Comment by IvanPausich** [comment]
forgive me, thanks, but maybe I'm too used to freebasic, which allows you.  updates the property value to you, as if it were a normal pointer using byref

**Comment by WaynePhillipsEA** [comment]
No problem, I'll close this since we can't consider changing that behaviour for back-compatibility reasons.

**Comment by IvanPausich** [comment]
sorry, but if I use the label object, with its let caption property, in byref the value is passed in both directions, it should also work with a property created on an abstract object such as a class, if not, how could I go about doing it , without using passing variables
