### ISSUE TITLE
Questions on extensions for files

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#162]
In version 0.10.220, we are able to add files. Using the add component, it will create a module or a class, both with extension `.twin`. In my test, I can create an extensionless file or a file with any other extension. 

That makes me wonder whether extensions has any meaning. Given that this is a virtual filesystem, I would expect it to list only the module names without extensions. In VB6 PE, we usually see something like `Class1 (Class1.cls)` where the former is the code name of the module and the latter is the actual file name. Because a file can contain multiple components, this no longer makes sense. However, I'd rather see just `Module1` and `Class1` rather than `Module1.twin` and `Class1.twin` if the extensions has no meaning. 

I also observe that without `.twin` extension, the intellisense doesn't apply. I'm not sure if we have plans to support `.bas` or `.cls`. 

Thank you in advance for the clarification on this!

**Comment by WaynePhillipsEA** [comment]
You can create (or drag 'n' drop from a Windows folder etc) any files in the project, with any file extension.  

The compiler currently only recognizes files with the '.twin' extension as source files.  So for example, if you create an extensionless file, the compiler will just ignore it (and you won't get semantic highlighting etc).

During my early testing I couldn't find a way to reliably get VS code to associate an extensionless filename with a language type (tB language), so unfortunately we had to drop that idea, as I agree it would've been cleaner without.

.BAS and .CLS files will be supported soon.

**Comment by bclothier** [comment]
Just a thought: if a `.bas` or `.cls` file is used, it could be treated as a single module / class respectively for backward compatibility, possibly as a part of supporting the legacy mode. That way, changing to `.twin` to enable tB feature is an explicit decision. OTOH, some may want the tB features even in a `.bas` file but want it to be a single module nonetheless.

**Comment by WaynePhillipsEA** [comment]
@bclothier yup, that's the plan

**Comment by mansellan** [comment]
@WaynePhillipsEA just wondered what the plan is for the legacy file types. `.cls`, `.frm` and others have a preamble not visible in the VB6 IDE - will tB preserve these for situations where the file must continue to work in both tB and legacy IDEs?

**Comment by bclothier** [comment]
Closing this because this is both answered and also now moot (new IDE)
