### ISSUE TITLE
Intellisense unneccessarily wrapping enum selections in brackets

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1622]
**Describe the bug**
The brackets aren't needed 99% of the time, and really shouldn't be added unless they are.

**To Reproduce**
```
Private Enum TestEnum
    foo = 0
    bar = 1
End Enum

Private Sub Test()
 Dim x As TestEnum
 x =
End Sub
```

Bring up the Intellisense for `x =` then select a value with the tab key or mouse. You wind up with ` x = [foo]` instead of `x = foo`.

**Expected behavior**
No brackets unless mandatory.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.361
 - 
**Additional context**

**Comment by bclothier** [comment]
Just FYI - though this is addressing enum members, caution may be needed for enum names.

This is valid VBx code:
```
Public Enum hi there
    totallyok
    [this is fine]
End Enum

Public Sub perfectlyfine()
    Debug.Print [hi there].[this is fine]
    Debug.Print [this is fine]
    Debug.Print [hi there].totallyok
    Debug.Print totallyok
End Sub
```

Note: To create the `hi there` enum, type `Public Enum [hi there]` and watch as compiler gobbles up the brackets, leaving the code with a naked `hi there`. O, joy! 

To really wreck the parser:
```
Public Enum just an enum with a ' comment
    [chillax, dude it's just a comment]
End Enum

Public Sub ohdear()
    Debug.Print [just an enum with a ' comment].[chillax, dude it's just a comment]
End Sub
```

tB is a bit more rational in that it refuses to subscribe to the insanity of gobbling up the brackets and somehow adding it to the symbol table though that may mean this particular VBx code won't be importable without modifications. For the record, I say, "Good! You deserve it for writing horrid code like those!" :)

**Comment by fafalone** [comment]
Issue fixed at some point, no longer an issue. Thanks!
