### ISSUE TITLE
Assigning empty byte array to String crashes

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1623]
**Describe the bug**
Assigning empty byte array to String crashes hard.

**To Reproduce**
```
Dim B() As Byte, MyStr As String

MyStr = B()

MsgBox MyStr
```

**Expected behavior**
That a "vbNullString" is assigned. (like in VB6)

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/33756666/6cf76c75-2d3b-4722-ac52-434b24f0c1ea)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. BETA 362]

**Additional context**
This bug happens in the RichTextBox control of VBCCR in tB.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 367.  Thanks
