### ISSUE TITLE
Questions on folders

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#163]
With compiler version 0.10.220, we can create folders. However in an existing twinBASIC project we already have `Resources`, `References` and `Sources` folders. In my quick test, I can create a file in any of those folder.

Are those folders special? Do they have any meaning to the compiler or am I free to reorganize it whatever I please? Can I for example delete the `Resources` folder? 

I also observer that I can move files any where but I cannot move it into the root. Doing so ~seems to put it in `Sources` subfolder~ seems to not actually move the file which implies at least that the folder has meaning. Can you confirm?

Addendum: I just confirmed that I cannot create new folders at the root; only within one of existing folders and deleting one of the existing root folder (e.g. `References`) causes an "unknown" error.

Thanks in advance!

**Comment by mansellan** [comment]
Really looking forward to the References node / browser!

Just a quick question on Resources - will it be compatible with the VB6 `.Res` format?

**Comment by bclothier** [comment]
Closing this because this was a question that was answered.
