### ISSUE TITLE
Recent IDE versions start in windowed state but think they're maximized...

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1634]
**Describe the bug**
...so when you first click on the titlebar to move it, it 'restores' to different size; resize is disabled until you do this.

**To Reproduce**
Open IDE after having exited while not maximized; try to resize; click and drag title bar.

**Expected behavior**
Normal window behavior.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/74cc74a5-e530-4c45-9668-52c394de276b)

This is a freshly opened IDE; you can see the middle button is the 'Restore' button, indicating a maximized window you can click to restore, instead of a 'Maximize' button like after the first click/drag:

![image](https://github.com/twinbasic/twinbasic/assets/7834493/1f662460-93f0-4a01-b31d-9c353d06b9e9)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.362

**Additional context**

**Comment by fafalone** [comment]
Very likely related-- when you do actually maximize the window, the Restore button doesn't work; you have to click and drag to trigger a restore.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 397.  Thanks!
