### ISSUE TITLE
Can't go to definition of consts in at least some circumstances

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1647]
**Describe the bug**
Title says it all

**To Reproduce**
```
Private Const foo = 1

Private Type bar
    fizz(foo) As Long
End Type
```
Right click foo, try to go to definition.

**Expected behavior**
Going to... somewhere... hmmm 🤣 

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/172c4bb5-9690-4418-a0d3-28a8b39d0400)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.367
 - 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 387.  Thanks.
