### ISSUE TITLE
Both auto-indent for caret and for paste missing on ElseIf

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1648]
**Describe the bug**
No indent is added, next line appears same as ElseIf

**To Reproduce**
```
    If True Then
    ElseIf True Then
    End If
```
Press enter on 2nd then, observe, paste code indented to a different width, observe.

**Expected behavior**
Incremented tab count.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.368

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 387.  Thanks.
