### ISSUE TITLE
Show name of enum for enum values

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1649]
**Is your feature request related to a problem? Please describe.**
The hover info for an enum member tells us it's value and that it's an enum member, and what module it's defined in, it should also provide the name of the enum to avoid having to go to definition for it.

**Describe the solution you'd like**
Include enum name.

**Describe alternatives you've considered**
Go to definition.

**Additional context**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/218ce47a-dc6c-4ea2-8113-9b0351ed48dd)
Perhaps e.g. "in tbShellLibApi.slAPI.GdiPenStyles" for the above?

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 387.  Thanks.
