### ISSUE TITLE
TLB viewer fails to completely parse Win32Api.tlb

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1650]
**Describe the bug**
There's a few VB6 programmers that are using this TLB, which is similar to oleexp in containing many interfaces and API calls. I added it to a tB project to copy some APIs and found the viewer cut off about 13k lines through before any of the APIs started. There's a few unsupported things, but I suspect it's due to not handling whatever kind of line break is a helpstring, since it cuts off at:

```
    [ InterfaceId ("AFA0DC11-C313-11D0-831A-00C04FD5AE38") ]
    [ OleAutomation(False) ]
    Interface IUrlHistoryStg2 Extends Win32Api.IUrlHistoryStg
        [ Description ("Adds an URLS" & vbCrLf & "                    IOleCommandTarget *poctNotify
                    IShellFolder *punkISFolder
```

where the decompiled ODL source continues,
```
        [helpstring("Adds an URLS
					IOleCommandTarget *poctNotify
					IShellFolder *punkISFolder")]
        HRESULT _stdcall AddUrlAndNotify(
                        [in] LPWSTR pocsUrl, 
                        [in] LPWSTR pocsTitle, 
```

**To Reproduce**

Zip with tlb and decompiled source attached. Add to tB and open in viewer.

**Expected behavior**
Loading entire tlb. VB6 loads it all into it's object viewer without issue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.368

**Additional context**
It does apparently read it ok as far as the compiler goes... I can get Intellisense for the entire thing, just then 'go to definition' takes me to the last line if it's past there.

[Win32Api.zip](https://github.com/twinbasic/twinbasic/files/12269223/Win32Api.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 375.  Thanks
