### ISSUE TITLE
Regression: Line continuation syntax and With causing parsing error

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1652]
**Describe the bug**
```
    With PropCellFont
    If .Name <> OldFont.Name Or .Size <> OldFont.Size Or _
    .Bold <> OldFont.Bold Or .Italic <> OldFont.Italic Or _
    .Strikethrough <> OldFont.Strikethrough Or .Underline <> OldFont.Underline Or _
    .Charset <> OldFont.Charset Then
        Set Me.CellFont = PropCellFont
    End If
```
This was part of the 64bit VBFlexGrid port. In version 365 and earlier, this syntax is accepted, in 366-368, it causes\
`{ERROR} : Two operators encountered, without an operand between them`\
 `{ERROR} : Unrecognized symbol 'Bold'`\
 `{ERROR} : Unrecognized symbol 'Strikethrough'`\
 `{ERROR} : Unrecognized symbol 'Charset'`

This error does not seem correct.

**To Reproduce**
Copy of project attached.

**Expected behavior**
No error here.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.368
 
**Additional context**
Suspected: (fixed: correction to handling when dot operator is split via a line continuation [ uiwoow, discord ])

[VBFlexGridDemo64.zip](https://github.com/twinbasic/twinbasic/files/12284482/VBFlexGridDemo64.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 371.  Thanks
