### ISSUE TITLE
Issue with DAO Objects

### ISSUE THREAD

**Issue by jlegg05** [twinbasic/twinbasic#1654]
**Describe the bug**
DAO object cannot be used as a reference in 64-bit.

**To Reproduce**
1. Create a new StdExe
2. Ensure the project is set to 64-bit
3. Go to Settings -> COM References
4. Click on Microsoft DAO 3.6 Object Library [v5.0]
5. See error

**Expected behavior**
A working DAO Object Libaray for 64-bit twinBASIC

**Screenshots**
![2023-08-09 15_15_15-• NewProject twinproj](https://github.com/twinbasic/twinbasic/assets/64992414/dc752e6a-8563-401b-a3e0-abbf9007f44a)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC BETA 365

**Additional context**
In 32-bit the reference works fine, so I'm thinking it's most likely just a compatibility issue with 64-bit

**Comment by bclothier** [comment]
This isn't a twinBASIC issue but rather wrong library being used. DAO 3.6 is 32-bit only. You want the library named "Microsoft Office Access Database Object Library", which is a newer version of DAO and is 64-bit if you have 64-bit Office installed.

**Comment by WaynePhillipsEA** [comment]
Plus, if you don't have Office installed, you can just download the database engine here:
https://www.microsoft.com/en-US/download/details.aspx?id=54920
