### ISSUE TITLE
Subscript out of range 

### ISSUE THREAD

**Issue by forliny** [twinbasic/twinbasic#1657]
**Describe the bug**
Run-time error '9'

Subscript out of range 

**To Reproduce**
1. New Project
2. Standard EXE (plus VBCCR)
3. add CommandButtonW1 Control
4. Build WIN64 
5. open NewProject_win64.exe

 
![81938678-cc34-45eb-8577-03c48765fd82](https://github.com/twinbasic/twinbasic/assets/44160049/8ae2d1d1-7f17-4deb-bf3c-3a278ce5dbe8)

**Comment by fafalone** [comment]
I get an even funner one:

![image](https://github.com/twinbasic/twinbasic/assets/7834493/f40d20ac-d008-4363-81df-03248f4a5272)

Works from the IDE though, so I'm not sure if it's a tB bug or VBCCR bug.

**Comment by WaynePhillipsEA** [comment]
I think this was fixed in recent builds.  Please confirm

**Comment by fafalone** [comment]
Yup appears to be fine now, recompiled the test project I had for this. 

@forliny feel free to reopen if you still have this issue but it seems fixed.
