### ISSUE TITLE
PictureBox.Scale isn't working

### ISSUE THREAD

**Issue by sunsetandlabrea** [twinbasic/twinbasic#1666]
Scaling in a PictureBox doesn't work. ScaleHeight and Width appear to be correct when viewed, but the drawing is correct.

In VB6 this code creates a diagonal line from the top left to bottom right.

Picture1.ForeColor = vbBlack
Picture1.Scale (50, 50)-(100, 100)
Picture1.Line (50, 50)-(100, 100)

Setting the ScaleLeft, Width, Top, and Height independently works.

In TwinBasic:

![image](https://github.com/twinbasic/twinbasic/assets/1923572/9888553a-e6ea-4952-825f-d6d32579055d)

In VB6:

![image](https://github.com/twinbasic/twinbasic/assets/1923572/1f7900eb-1de0-4115-a981-39caf00180ef)

**Desktop (please complete the following information):**
 - OS: Window 11
 - twinBASIC beta 382

Thanks!

**Comment by fafalone** [comment]
Confirmed here on direct import from VB6, dpi aware=none, picturedpiscaling->False, no effect.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 365.  Thanks!
