### ISSUE TITLE
Error occured in evaluating constant expression

### ISSUE THREAD

**Issue by bradPeg** [twinbasic/twinbasic#1668]
In beta 382 converted vb6 project 

Const message_length = 62
Static t(message_length) As Byte 

I'm getting Error occured in evaluating constant expression in this code. 

This leads to Wrong number of dimensions for this array [given 1 expected 0] for every line that accesses  an array member.

**Comment by WaynePhillipsEA** [comment]
Further info: doesn't repro inside a standard module procedure, but does repro in a class member.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 365.  Thanks!
