### ISSUE TITLE
Intellisense doesn't load enums for inline initialization

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1672]
**Describe the bug**
Intellisense doesn't load enums for inline initialization using a function with an enum argument, when it does load the enums that are part of the same function when the traditional method of setting the variable on a new line is used.

**To Reproduce**

-New StdExe

-Code:

```
    Private Enum foo
        abc
        def
        ghi
    End Enum
    Private Function DoFoo(ByVal f As foo) As Long
        
    End Function
    Private Sub GetFoo()
        Dim bar As Long = DoFoo
    End Sub
```
-Type parenthesis after DoFoo; this *should* bring up the enum values in Intellisense, however nothing comes up. 

-If you replace it with bar = DoFoo() on a new line, Intellisense does correctly list the values of foo.

**Expected behavior**
Enum values should be listed in this situation

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.383
 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 365.  Thanks!
