### ISSUE TITLE
reference list form old project still there when crating a new one but don;t work

### ISSUE THREAD

**Issue by bradPeg** [twinbasic/twinbasic#1674]
I opened a new project while I had another open and went to add references. The list from the first project was there but couldn't be used. I had to remove and readd the vbflexgrd and oleguid ones.

**Comment by fafalone** [comment]
Can't reproduce this; and I'm frequently loading and unloading many projects, usually with 3-6 up at once.

Is this repeatable, and can you be more specific with circumstances? If it's not repeatable, there's lots of one off odd behaviors, so wouldn't be surprised.

**Comment by bradPeg** [comment]
Seems to have been a one off can't reproduce it. I'll close this for now
