### ISSUE TITLE
Default variant declares not detected with ByVal in APIs

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1680]
**Describe the bug**
Unless disabled, the compiler provides a warning for when variables are declared without 'As type' which defaults them to `Variant`. I've found this very helpful. However I've noticed the warning is not provided in my API declares if the `ByVal` keyword is used. It's properly detected in subs/functions.

**To Reproduce**

`Private Declare Sub Foo Lib "bar" (fizz, ByVal buzz)`

You'll see fizz is flagged, but buzz is not.

**Expected behavior**
Should get warning with ByVal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.392

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 395, thanks
