### ISSUE TITLE
Call to Property Changed in user control failing

### ISSUE THREAD

**Issue by bcelestia** [twinbasic/twinbasic#1681]
I'm making use of a Serial Comms user control I found on PSC many moons ago. Have it working fine in VB6.
Twinbasic reports an error on Import.

![image](https://github.com/twinbasic/twinbasic/assets/101827535/26af77bd-b078-4789-ab4b-98f702e7c4e8)

![image](https://github.com/twinbasic/twinbasic/assets/101827535/2d7e5a98-025a-4872-b251-51434b1a02a1)

I've attached a simple version of the VB6 program.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [0.15.393]

[ECG Test Utility.zip](https://github.com/twinbasic/twinbasic/files/12645604/ECG.Test.Utility.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 395, thanks.

Whilst I totally agree regarding the incorrect use of `PropertyChanged`, we need to match VBx here so the member signature now matches the VBx version.  In future, yes we should definitely add helpful guidance here.
