### ISSUE TITLE
Intellisense fails to populate for `ReDim UDT.`

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1682]
**Describe the bug**
It doesn't list anything. Ideally it should just list the array members, but even just listing them all would be far preferable to none.

**To Reproduce**

```
   Private Type foo
        a As Long
        b As Long
        c() As Byte
   End Type
   
   Sub DoFoo()
        Dim f As foo
        ReDim f.
   End Sub
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.393
 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 395, thanks
