### ISSUE TITLE
Text goes into bubble on panes when they have focus

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1684]
**Describe the bug**
If you click on a pane like Watch or Variables and start typing, the text will appear in an orange bubble.

**To Reproduce**

Click on side panes

Start typing

**Expected behavior**
Shouldn't draw text. Ideally shouldn't take keyboard focus at all

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/8d3e317c-8f0e-4d9d-9afa-fb8452504d7a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.397

**Additional context**
Just seems to be Variables, Watch, Project Explorer, and History. Seems to interfere with the Project Explorer as well.

**Comment by WaynePhillipsEA** [comment]
FYI some of the panes support text filters (e.g. File explorer), that's where this comes from.  I'll get this fixed
