### ISSUE TITLE
Need to implement additional interfaces on classes

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1685]
Was digging into why some code wasn't working as expected, I found that tB classes do not implement `IConnectionPointContainer`. 

```
Dim oCls As New Class1
Dim pCon As IConnectionPointContainer
Dim pUnk As oleexp.IUnknown
Set pUnk = oCls
pUnk.QueryInterface IID_IConnectionPointContainer, pCon
If (pCon Is Nothing) Then
    Debug.Print "no"
Else
    Debug.Print "yes"
End If
```

VB6->yes 

tB->no

Couldn't find any reference to this issue anywhere, so wanted to add it for tracking purposes. Since Connection Points are well documented COM objects, I would think this falls under the kind of compatibility tB is going for.

I can't recall any other documented interfaces implemented by classes, but that may need to be investigated.

**Comment by WaynePhillipsEA** [comment]
IConnectionPointContainer has to be implemented in order to expose events.  As such, if you add an event to the class, tB will certainly implement it for you.

Though I agree, for max back-compat, we should copy VB6 behaviour and implement even when no events are exposed.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 398.  Thanks.
