### ISSUE TITLE
ChilKat component failure

### ISSUE THREAD

**Issue by 63ewc** [twinbasic/twinbasic#1702]
Long time user of the Chilkat Active X within many vb6 apps. On converting a fewer smaller utility apps created into TwinBASIC and after cleaning up I find that ChilKat cannot be successfully used although the component is enabled in the Settings as shown

![image](https://github.com/twinbasic/twinbasic/assets/9310589/8e1ca014-61b0-408c-8c49-bed222f990fe)

I continually obtain the error 91 'Object Variable or With Block Variable Not Set'

Created a small app directly in TwinBASIC and no change in behavior. 

Creating as 32bit. 32 Bit version of Chilkat.

**Desktop (please complete the following information):**
 - OS: Windows 10 with all current updates
 - twinBASIC compiler version IDE_Beta_415. Executable dated 8th July 2022

**Comment by WaynePhillipsEA** [comment]
Could you scroll along to the right in the `Enabled Libraries` list, and turn off the `Use ActiveX Controls` feature.  Then save the Settings file.  See if that helps.

**Comment by 63ewc** [comment]
Good afternoon

Thats the fix!! It is a referenced component so unlicking the Use ActiveX Controls sorted out the problem.

Thanks for the prompt response.

On another note I can compile successfully my apps as X64 even though the bound third party controls are all 64 bit at the moment. How is this possible?

The 64bit version also runs from the created executable as it is should. My understanding is that all the controls must be 64bit to work!


Kind Regards



Edward Cooper
________________________________

**Comment by bclothier** [comment]
I'm not 100% sure but if it really did run in 64-bit, it might be that they configured for DLL surrogacy which would allow you to run 32-bit components in 64-bit executable albeit at a huge performance penalty.
