### ISSUE TITLE
tB doesn't recognize qualified private types within classes

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1705]
**Describe the bug**
If this isn't a regression it's pretty shocking it hasn't been discovered by now (and if it has, apologies, I couldn't find the right terms to bring it up).

If you have a private type within a class, you can't refer to it by ClassName.Type.

**To Reproduce**
In class (.cls or .twin):

```
Class Class1

    Private Type RECT
        Left            As Long
        Top             As Long
        Right           As Long
        Bottom          As Long
    End Type

    Public Sub TestRc()
        Dim rc As Class1.RECT
        rc.Bottom = 1
        Debug.Print rc.Bottom
    End Sub

End Class
```

(Remove Class/End Class and name Class1 if using .cls)

**Expected behavior**
VB6 allows this kind of qualified reference.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.414

**Additional context**

**Comment by WaynePhillipsEA** [comment]
It does appear to be just something that has been missed and not a regression.  Weird that VBx allows this qualified reference to the private UDT that is not exposed outside the scope of itself, and yet doesn't offer the same for Enums.  Typical VBx inconsistency.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 420.  For better consistency, tB allows the qualifier to be used on private Enums as well, where VBx doesn't.  This should not lead to any back-compat problems.
