### ISSUE TITLE
Callbacks from InterSystems Caché/Iris ActiveX to the Visual Basic User Interface fails

### ISSUE THREAD

**Issue by flaviofornazier** [twinbasic/twinbasic#1706]
The ActiveX works fine on TB, but includes a special feature that allows Caché/Iris server code refer to elements of the client user interface. These property and method references are called callbacks because they cause a message to be sent from the server to the client when the reference is made. The client looks up the form and control, issues an OLE call, and returns the result to the server. Specifically, server code can access properties of any controls on the client user interface, via two methods. The server code can also use the following Visual Basic methods, if the form includes controls that provide these methods: AddItem(), RemoveItem(), Refresh(), Move(), Clear(), Hide(), Show() and SetFocus() In order to make callbacks available for a particular form, there are two requirements: 
- The form must contain a VisM control (ActiveX from InterSystems Caché/Iris)
- Before make the first server reference to a control on that form, make a call like the following (usually in the Form_Load event code):

CreateDispatch Me, VisM1

Here, Me is the Visual Basic reference to the current form, and VisM1 is the name of the VisM ActiveX on that form. The CreateDispatch function is part of the attached module called VBRUN.BAS, which must be included in project. This function 
creates a list of the controls on the form and stores them, for future reference, in a hidden property of the VisM ActiveX.

- To Reproduce
To refer to a property of a control, we use the following special server code syntax:
_[formname!]controlname[(controlindex)].propertyname[(propertyindex)]
or just: set variable=_Text1.Text
Please see attached module called "vmrun.bas" (119 lines)

- Expected behavior
Normal execution like in VB6.

- Screenshots
![TB_Error](https://github.com/twinbasic/twinbasic/assets/50641373/9540d04f-0ffa-420c-880b-63478979eb15)
The control in TB is a textbox named txtInfo.

 - OS: Windows 7, 8, 10, 11]
 - TwinBASIC beta-x-415

No Additional context.
[vmrun.zip](https://github.com/twinbasic/twinbasic/files/13212098/vmrun.zip)

Thank you in advance.

**Comment by WaynePhillipsEA** [comment]
First, please investigate whether the control list that you're sending over is correct (at the line `VisM.ControlClasses = ClassList$ + vbLf$`).  Check the value matches the one that you're sending in the VB6 version.

**Comment by flaviofornazier** [comment]
Issue solved. Thanks @WaynePhillipsEA.

**Comment by flaviofornazier** [comment]
Closed.
