### ISSUE TITLE
VBA.IsArrayInitialized() causes compile error as of v417 with Constant Function Folding set to Yes

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1710]
**Describe the bug**
The built-in function IsArrayInitialized() with Project Property "Constant Function Folding" set to "Yes" worked until tB v417 - since then the following error occurs when using IsArrayInitialized():  ```[LINKER] compilation (codegen) error detected in 'MyModule.testbug' at line #21```, and the project cannot be compiled.

**To Reproduce**
Set Project Property "Constant Function Folding" set to Yes.
Then run the following:
```vba
Sub TestBug()
     Dim items() As String
     Debug.Print VBA.IsArrayInitialized(items) '<--- line #21 throws the error
End Sub
```
 - OS: Windows 11
 - twinBASIC v417, v418, v419

**Additional context**
This issue breaks Projects that use the twinBASIC Package "mscorlib's ArrayList drop-in replacement" v1.5.139.0.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 420.  Thanks!
