### ISSUE TITLE
Crash when hovering an interface name implementing another interface

### ISSUE THREAD

**Issue by Theadd** [twinbasic/twinbasic#1711]
**Describe the bug**
Compiler crashes when hovering an interface name implementing another interface.

**To Reproduce**
1. Type the following in a *.twin file:
```vb
Public Interface ICloneable
    ' Function Clone() As Variant
End Interface

Public Interface IList ' Extends ICollection
    Implements ICloneable
    
    ' Function Clone() As Variant Implements ICloneable.Clone
    ' ...
End Interface
```
2. Hover the `IList` interface name.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/78041/3ef8817a-ef8f-4603-916d-c9ab28368125)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version: at least from BETA 415 to BETA 420, not checked in older versions.

**Additional context**
That interface inheritance chain is trying to simulate the one in .NET **ArrayList**, for a real example project just include the TWINPACK **mscorlib's ArrayList drop-in replacement** in any project or directly get its source from the [github repo](https://github.com/Theadd/ArrayList), then mouse hover on any `IArrayList` occurrence in the code.

Thanks! =)

**Comment by fafalone** [comment]
`Extends` is the correct syntax. The crashing is definitely a bug and it should indicate an error instead.

You'd use `Public Interface IList Extends IClonable`. Or if you do mean to implement it, you'd do so in a class,

```
Class IList

Implements IClonable
```

**Comment by Theadd** [comment]
Hi @fafalone ,

I was already using the `Extends` syntax in all interface inheritances, except the one with `Implements ICloneable`, which was just to get a single interface inheriting from two different ones, one via Extends and the other via implements, and that was actually working.

I've moved the `Implements ICloneable` down to those classes implementing the `IList` interface instead of having it on the `IList` interface itself and included those changes in the `ArrayList` twin package v1.6.0.

Thanks!

**Comment by fafalone** [comment]
You can have it inherit from multiple interfaces by chaining them like 

Interface One


Interface Two Extends One

Interface Three Extends Two


Three will contain all the methods of 1 and 2. 


What do you mean it was working though... really confused by how it could.

**Comment by Theadd** [comment]
Hi @fafalone ,

> What do you mean it was working though... really confused by how it could.

Well, It **is** working like multiple interface inheritance for an interface, to reproduce:

1. Demo project based on `ArrayListLib v1.5`: [InterfaceImplementingAnother.twinproj.zip](https://github.com/twinbasic/twinbasic/files/13262235/InterfaceImplementingAnother.twinproj.zip)
2. Run `DemoModule.RunDEMO`

Related code:
[IArrayList.twin#L64-L67](https://github.com/Theadd/ArrayList/blob/fdcf5fc0740cc5e71fd8fcf4733f179e55e7d57f/ArrayListLib/Sources/IArrayList.twin#L64-L67)
```vb
Public Interface IArrayList Extends IListRange
    Implements ICloneable
    
    Function Clone() As Variant Implements ICloneable.Clone
```

[ArrayList.twin#L100](https://github.com/Theadd/ArrayList/blob/fdcf5fc0740cc5e71fd8fcf4733f179e55e7d57f/ArrayListLib/Sources/ArrayList.twin#L100)
```vb
Public Function Clone() As Variant Implements IArrayList.Clone
```

[ListRange.twin#L82](https://github.com/Theadd/ArrayList/blob/fdcf5fc0740cc5e71fd8fcf4733f179e55e7d57f/ArrayListLib/Sources/ListRange.twin#L82)
```vb
Public Function Clone() As Variant Implements ArrayList.Clone, IArrayList.Clone
```
