### ISSUE TITLE
BorderStyle and Min, Max buttons

### ISSUE THREAD

**Issue by sokinkeso** [twinbasic/twinbasic#1712]
**Describe the bug**
On a Form, selecting BorderStyle = vbFixedSingle , should show on the title-bar of the form the Minimize and/or Maximize buttons, the same way as with BorderStyle= vbSizable. (if ControlBox=True then must appear the [X] button, and Min/Max buttons if they are selected)

**Expected behavior**
Match vb6 form's behavior.

**Comment by fafalone** [comment]
I posted a temp workaround for this [here](https://github.com/twinbasic/twinbasic/discussions/1707#discussioncomment-7470157).

**Comment by sokinkeso** [comment]
> I posted a temp workaround for this [here](https://github.com/twinbasic/twinbasic/discussions/1707#discussioncomment-7470157).
I haven't seen the opened issue, and your workaround.
Thank you fafalone, I'm closing this as duplicate.
