### ISSUE TITLE
Interface popup info does not show origin module or description

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1721]
**Describe the bug**
There's the normal " in " but the package isn't listed after it. Nor is the description given anywhere.

**To Reproduce**

- Add tbShellLib to project or add interface with description
- Declare variable of that interface or one from the package with a description like IPinnedList
- Hover over it for advanced info popup

**Expected behavior**
Origin and description given

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/122384dd-77a3-41cb-b678-2e47086127ec)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.423
 
**Additional context**

**Comment by fafalone** [comment]
Confirmed still an issue as of Beta 440.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 444.  Thanks.
