### ISSUE TITLE
Form Min/Max sizes interpreted as pixels even when scalemode is not

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1738]
**Describe the bug**
The default scalemode is twips, but even when left in twips, the Form.MinWidth/Form.MinHeight/Form.MaxWidth/Form.MaxHeight properties are seemingly interpreted as pixels, which results in a confusing size change when it's the only value given in pixels. 

**To Reproduce**
Set those properties, run, size/drag form.

**Expected behavior**
The units should be annotated. Ideally, given as the Form.ScaleMode units, but in any case, given unit notations like other width/height fields.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.423

**Additional context**

**Comment by EduardoVB** [comment]
The ScaleMode property sets the units for internal form's space or canvas. External units of the form, like Width and Height are always in the "ScaleMode" of the Screen (it does not have the property to change it), that is in twips.

IMO Min and Max should be also in twips, to follow the rule.

**Comment by fafalone** [comment]
I could live with that.

**Comment by Kr00l** [comment]
> The ScaleMode property sets the units for internal form's space or canvas. External units of the form, like Width and Height are always in the "ScaleMode" of the Screen (it does not have the property to change it), that is in twips.
> 
> IMO Min and Max should be also in twips, to follow the rule.

Never realized that. Thx
Well, tB could offer a Screen.ScaleMode property which inherits from the "new" Screen**s**.ScaleMode. :)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 596.  Thanks.
