### ISSUE TITLE
Exponent computation bug

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1741]
**Describe the bug**
Thought I'd offer a more detailed analysis of the exponent bug reported by Ever on Discord. There's *very* serious issues with computing exponents in a fairly normal circumstance.

<table><tr><td>VB6<br>
0 ^ (1 - 1) = 1<br>
0 ^ (2 - 1) = 0<br>
0 ^ (3 - 1) = 0<br>
1 ^ (1 - 1) = 1<br>
1 ^ (2 - 1) = 1<br>
1 ^ (3 - 1) = 1<br>
2 ^ (1 - 1) = 1<br>
2 ^ (2 - 1) = 2<br>
2 ^ (3 - 1) = 4<br>
3 ^ (1 - 1) = 1<br>
3 ^ (2 - 1) = 3<br>
3 ^ (3 - 1) = 9<br>
4 ^ (1 - 1) = 1<br>
4 ^ (2 - 1) = 4<br>
4 ^ (3 - 1) = 16<br>
5 ^ (1 - 1) = 1<br>
5 ^ (2 - 1) = 5<br>
5 ^ (3 - 1) = 25</td><td>twinBASIC<br>
0 ^ (1 - 1) = 1<br>
<b>0 ^ (2 - 1) = 1</b><br>
<b>0 ^ (3 - 1) = 1</b><br>
<b>1 ^ (1 - 1) = 0</b><br>
1 ^ (2 - 1) = 1<br>
<b>1 ^ (3 - 1) = 2</b><br>
<b>2 ^ (1 - 1) = 0</b><br>
<b>2 ^ (2 - 1) = 1</b><br>
2 ^ (3 - 1) = 4<br>
<b>3 ^ (1 - 1) = 0</b><br>
<b>3 ^ (2 - 1) = 1</b><br>
<b>3 ^ (3 - 1) = 8</b><br>
<b>4 ^ (1 - 1) = 0</b><br>
<b>4 ^ (2 - 1) = 1</b><br>
4 ^ (3 - 1) = 16<br>
<b>5 ^ (1 - 1) = 0</b><br>
<b>5 ^ (2 - 1) = 1</b><br>
<b>5 ^ (3 - 1) = 32</b>
</td></Tr></table>

VB gives the expected values, but tB values make no sense at all. 3^2 = 8, 4^=16, 5^2 = 32?? Ever suggest parsing was reversed; but that doesn't explain it either; 5^-2 is 0.04, not 32. 

**To Reproduce**

```vba
Dim fizz As Long
Dim buzz As Long

Dim i As Long, j As Long
For i = 0 To 5
    For j = 1 To 3
        fizz = i: buzz = j
        Debug.Print i & " ^ (" & j & " - 1) = " & fizz ^ (buzz - 1)
    Next j
Next i
```

**Expected behavior**
Values should match VB6.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.423

**Additional context**
Weird this bug has gone unnoticed until now.

**Comment by EduardoVB** [comment]
I think it is doing the opposite operation:
1^0 is doing 0^1 and 5^2 is doing 2^5

**Comment by fafalone** [comment]
Ah yes that kind of reversal explains it, good catch.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 427.  Thanks!
