### ISSUE TITLE
Cannot Close IDE

### ISSUE THREAD

**Issue by bcelestia** [twinbasic/twinbasic#1752]
Run Twinbasic IDE
Choose Standard Exe
Try to close IDE via menu
After choosing Discard changes - nothing happens
Similar when Top right X is pressed.

Have tried on both Version 427 & 429.
Version 423 worked fine

Have to use Task Manager to close the IDE

OS - Win 10

**Comment by fafalone** [comment]
Doesn't reproduce for me, also on Win10 (1809 Enterprise LTSC).

**Comment by WaynePhillipsEA** [comment]
It only happens if you've closed the PROBLEMS panel

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 430.  Thanks!
