### ISSUE TITLE
Class with private type for class properties.  Type members of existing instance overwritten in new instance.

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#1754]
**Describe the bug**
This issue is present in Beta IDE 424 through to Beta IDE 430

I use private types in my Class definitions to  collate property and state variables.  For class Var I think I'm seeing the members of the private type being overwritten by values provided for a new instance.

The behaviour would be consistent with the properties being defined in the predeclaredId and then each instance overwriting the values of the PredeclaredId, but I cannot see where I have made such a mistake.

All my classes use PredeclaredId's and have the default member set to the constructor method (Deb - short for Debutante) so that new instances of a class can be constructed as 
```
Dim myVar as Var = Var(myValue)
```
The code below
```
Public Sub testvarclass()
    
    Dim myVar1 As Var = Var(42)
    Debug.Print myVar1.IsNumeric, myVar1.Cargo, TypeName(myVar1.Cargo)
    Debug.Print
    
    Dim myVar2 As Var = Var("42")
    Debug.Print myVar1.IsNumeric, myVar1.Cargo, TypeName(myVar1.Cargo)
    Debug.Print
    
    Dim myVar3 As Var = Var("Hello")
    Debug.Print myVar1.IsNumeric, myVar1.Cargo, TypeName(myVar1.Cargo)
    Debug.Print
    
End Sub
```

gives the output
```
[DEBUGGER] global variables have been cleared
Executing 'FBase.Pootle.testvarclass'...
True           42           Integer
True          42            String
False         Hello         String
(time taken: 0.000651s)
```
the expected output should be
```
True           42           Integer
True           42           Integer
True           42           Integer
```

**Additional context**
The twinbasic project is attached.

[FBase2024Jan29.zip](https://github.com/twinbasic/twinbasic/files/14083880/FBase2024Jan29.zip)

WIndows 11
Beta Ide 430 32 bit (and also visible in 242,425,426,427,428 and 429

**Comment by FullValueRider** [comment]
Stupid is as stupid does.
Can anyone spot the obvious mistake
```
 [ DefaultMember ]
    Public Function Deb(ByRef ipItem As Variant) As Var
        With New Var
            Return ConstructInstance(ipItem)
        End With
    End Function
```


`

**Comment by wqweto** [comment]
Missing a dot like in `.ConstructInstance`?

**Comment by FullValueRider** [comment]
spot on as they say.  It eleuded diagnostics because I thought I'd already fixed that particular bug but it obviously didn't get saved.  The thought came to me today as I was fixing the second puncture during a 40km bike ride.

**Comment by wqweto** [comment]
This has been one the more hideous bugs in the new IDE. I've personally been biten by `Ctrl+S` refusing to save and then on exit IDE remaining silent to outstanding modifications a few times. The bitter taste of the incident remained for several days.
