### ISSUE TITLE
Unable to disambiguate InStr() with inline IIf()

### ISSUE THREAD

**Issue by jpbro** [twinbasic/twinbasic#1759]
**Describe the bug**
tB can't disambiguate use of  InStr() with an inline IIf() call.

**To Reproduce**
Add this code:
    Dim SomeString As String
    Dim SomeCharacter As String
    
    If InStr(1, SomeString, SomeCharacter, IIf(True, vbTextCompare, vbBinaryCompare)) Then
       MsgBox "A"
    End If

The Problems pane will complain:

    {ERROR} /SL5StockNG/Sources/modStrings.bas [927,17]: Unable to disambiguate between overloaded methods in call to 'InStr'.  2 Incompatible matches found:
       VBA.Strings.InStr ( ByRef String1 As Variant, ByRef String2 As Variant, Optional ByVal Compare As VbCompareMethod = TB_BUILTIN_CURRENT_MODULE_TEXTCOMPARE_MODE ) As Variant
       VBA.Strings.InStr ( ByRef Start As Variant, ByRef String1 As Variant, ByRef String2 As Variant, Optional ByVal Compare As VbCompareMethod = TB_BUILTIN_CURRENT_MODULE_TEXTCOMPARE_MODE ) As Variant

Get rid of the IIF:

    If InStr(1, SomeString, SomeCharacter, vbTextCompare) Then

And everything works as expected.

**Expected behavior**
For Instr() to be able to compile when using an inline IIf()

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 433

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 440, thanks!
