### ISSUE TITLE
IDE behavior on New/Open->Cancel

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1764]
This relates to #788 which was closed due to being very old.

But the behavior of the IDE is still the same: If you have a project open, then bring up the New or Open dialogs, the project is immediately closed, so if you hit cancel, you're just left with a blank IDE. 

This seems to be by design so I'm not filling this out as a bug report; but thought it might be worth discussing whether it *should* be that way.

**Comment by jpbro** [comment]
It should not be that way IMO. I don't know of any other software that does this, and it makes the Cancel button kind of useless.

**Comment by fafalone** [comment]
I'd agree unloading the current project should wait so you can cancel back to it; but unless it's a simple matter of reordering some calls that could be done in under an hour... it's not something worth delaying v1 for if it's a major redesign.

**Comment by sokinkeso** [comment]
> I'd agree unloading the current project should wait so you can cancel back to it; but unless it's a simple matter of reordering some calls that could be done in under an hour... it's not something worth delaying v1 for if it's a major redesign.

That for sure! This one is not a v1 stopper.. it is likely a first impression maker rather than an issue..

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 438

**Comment by EduardoVB** [comment]
Hello. The order is not right.
When selecting to start a new project or open an existing one, and there is currently open a project that has unsaved changes, the IDE immediately has to ask "Save/Not to save/Cancel". If the user selected Cancel, then do nothing (cancels the opening of new project). If Save, then save it, but do not close the currently open project. If Not to save, then do not save but still do not close the currently open project.

After that, the user is presented with another dialog. It can be the New project dialog, or if the user is opening an existing project, the file browser to select the project file.
In both cases there is a cancel button. If the user cancels that operation, the currently open project must remain open.

If the user doesn't cancel at that point, and goes ahead, at that time the current project is closed (saved or not).

You can check that behavior in the VB6 IDE.
