### ISSUE TITLE
Can't declare WithEvents as part of same-line series

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1767]
**Describe the bug**
In VB6 if you have class `Class1`, on a Form you can do the follow:

`Private a As Long, b As Long, WithEvents c As Class1`

In tB, this fails during design time with 'Syntax error: No handler for this symbol underlining c, and c is an unrecognized symbol elsewhere in the form.

**To Reproduce**
Attached.

**Expected behavior**
Matching VB6 in understanding this syntax.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.438
 
**Additional context**

[ClassDeclTest.zip](https://github.com/twinbasic/twinbasic/files/14185093/ClassDeclTest.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 440, thanks!
