### ISSUE TITLE
Type cast issue with OpenGL TLB library API

### ISSUE THREAD

**Issue by mobiltune** [twinbasic/twinbasic#1770]
**Describe the bug**
Compile error when passing an byte array to an imported API function from vbogl.tlb.

"{ERROR} [634,56]: Validation of call to 'glReadPixels' failed.  Argument for 'pixels': cannot coerce type 'Long' to '{void}'"

**To Reproduce**
1. Create a vb6 project with vbogl.tlb included as a reference (VB OpenGL 1.2 (ANSI) in References).
Note: I keep the vbogl.tlb under C:/windows/

2. Add this code to the form just for a test of the API in question:
Private Sub Form_Load()
    Dim Pixels() As Byte
    ReDim Pixels(0 To 1) As Byte
    
     'Read into the pixel byte buffer...
    glReadPixels 1, 1, 1, 1, GL_RGB, GL_UNSIGNED_BYTE, Pixels(0)
End Sub

3. Import VBP into TwinBasic (using version 439 from 2/7/2024)

You cannot compile due to the compile error from type cast.

**Expected behavior**
Expected behavior, in vb6 it is expected that we pass in a first byte cell from the array and this API then fills in the full byte array. I think this is failing in TwinBasic because it's a bit of a hack/workaround in VB6 to avoid using a pointer? I really don't know...

**Screenshots**
Screenshot in ZIP file with TLB and sample code/

**Desktop (please complete the following information):**
 - OS: Win 10
 - twinBASIC compiler version 439

[VBOpenGL.zip](https://github.com/twinbasic/twinbasic/files/14213237/VBOpenGL.zip)

[VBOpenGL.zip](https://github.com/twinbasic/twinbasic/files/14213244/VBOpenGL.zip)

**Comment by fafalone** [comment]
Same as #1688 I think

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 441.  Thanks.
