### ISSUE TITLE
Menu items don't show after a line separator

### ISSUE THREAD

**Issue by ElHado** [twinbasic/twinbasic#1771]
**Describe the bug**
I have an application with menu items. The items after a separator don't show up in the application. But they are in the IDE as usual:

IDE:
![IDE](https://github.com/twinbasic/twinbasic/assets/92795993/5b852700-6c88-4938-9354-c4906a2adcb8)
Application:
![App](https://github.com/twinbasic/twinbasic/assets/92795993/0d8fb52f-6932-41cf-9e57-85dde86cc089)

It don't matter if I start the application via IDE or if I compile it first.

**To Reproduce**
1. Create a new "Standard EXE"
2. Create a menu with 3 items
3. Make the 2nd item as separator
4. run the app and check

**Expected behavior**
All menu items should be accessible.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 441

**Comment by fafalone** [comment]
Looks like new item captions are being set to separators too.

Wayne while you're looking at this-- the menu editor is closing as soon as you use an add item option; the old behavior where it stayed open so you could more quickly edit them was better.

**Comment by ElHado** [comment]
I have to thank you 👍
