### ISSUE TITLE
Strange behavior with control array

### ISSUE THREAD

**Issue by marcoslm** [twinbasic/twinbasic#1773]
**Describe the bug**
Given an array of controls, such as picturebox - click event, the value of Index is always zero or an incremental sequence in each click event, depending on other parts of the code where properties of the controls in said array are varied.

**To Reproduce**
1. Run the attached example project.
2. Click repeatedly on any picturebox.
3. Uncomment the lines that are commented in the code.
4. Try clicking on the pictureboxes again.

**Expected behavior**
The value of Index in the Click event should correspond to the index of the clicked control.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 22H2
 - twinBASIC beta 445

**Additional context**
I think this has been happening since beta 424.
[ControlArrayIndexTest.zip](https://github.com/twinbasic/twinbasic/files/14230493/ControlArrayIndexTest.zip)

**Comment by fafalone** [comment]
Yup for me the index is always 0 no matter which control array element you click on.

**Comment by marcoslm** [comment]
I am closing this issue as I have confirmed that it has already been resolved in beta version 456.
