### ISSUE TITLE
Import attributes and prettifier clash

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#1777]
**Describe the bug**
When importing a .vbp project the Form attributes are still with "spaces".

```
[ FormDesignerId ("5126753B-57CA-434A-AD86-2E97D2723D28") ]
[ ClassId ("110DA2EE-BAF0-4ADE-A179-F84AA2FE8EFD") ]
[ InterfaceId ("4D2F6AA6-E7A4-4B49-9206-9DFBCD024D21") ]
[ EventInterfaceId ("5CF7BEE2-9DE8-4639-B97A-ED12BEE89FA8") ]
```

However, now the prettifier kicks in and removes the spaces. Now a "Form xyz ambigous" error appears.
Then we save the project, re-open. Prettifier has nothing to correct, no "ambigious" error anymore.

**To Reproduce**
Import any .vbp project. Open a .frm.twin file and wait until prettifier does the job. Error appears.

**Expected behavior**
The import should write the attributes already in "prettified" form.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.9.1111]

**Additional context**
Why does this prettifier of attributes crash the form with that "ambigous" error.

**Comment by WaynePhillipsEA** [comment]
I'm not seeing this problem, at least with BETA 450.  I will fix the spacing in the imported files though in the next release anyway.

**Comment by WaynePhillipsEA** [comment]
Spacing issue fixed in BETA.  Thanks
