### ISSUE TITLE
Default events not used

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1780]
**Describe the bug**
When no event has been coded for a form yet, selecting Form1 from the drop down inserts a prototype for Form_Activate, the first alphabetically, instead of Form_Load, the default.

**To Reproduce**
New StdExe

Select Form1 from middle dropdown in code editor for Form1.twin

**Expected behavior**
Use default event.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - twinBASIC compiler version 0.15.449

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Yes, it's doing the same with controls such as Label too.  I'll get that fixed.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 451, thanks
