### ISSUE TITLE
Annoying ding when tabbing between empty textboxes

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1785]
**Describe the bug**
Pressing tab to change focus from one textbox to the next in the tab order causes a ding sound to play.

**To Reproduce**
-New StdExe
-Place several TextBoxes on form, set text to empty.
-Run, click on first textbox, press tab.

**Expected behavior**
No ding. VB6 has no ding here, even if comctl6 is used.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.15.451
 
**Additional context**
Not a regression; seems 423 was doing this too.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 452, thanks.
