### ISSUE TITLE
Clipboard.SetData 2nd parameter is optional

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1787]
**Describe the bug**
This isn't implemented yet, but it's turning a warning into an error.

**To Reproduce**
Type Clipboard.SetData 

**Expected behavior**
...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 0.15.451

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 452, thanks.
