### ISSUE TITLE
Default property use of control colored white

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1788]
**Describe the bug**
...when not part of an array.

**To Reproduce**
New StdExe\
Label\
Assign caption through default property use.

**Expected behavior**
Should be the same color as when part of a control array or normally. Or at least not such a bright white.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/f92ff72b-222a-4729-b956-0a5c84e6577b)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version 0.15.452

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 456, thanks
