### ISSUE TITLE
VB6FormImporter Error message lacks the module name.

### ISSUE THREAD

**Issue by cycle40** [twinbasic/twinbasic#1790]
**Is your feature request related to a problem? Please describe.**

When trying to import my VB6 project, I got error message like this :
(of course, this VB6 project can be compiled properly with VB6 compiler)
![image](https://github.com/twinbasic/twinbasic/assets/22705898/7c11848d-329a-45ae-bf8d-9dadf845eedb)
This message tells me the line number, but I have no idea which module it is.
So I can't figure out what the problem is. 

**Describe the solution you'd like**
Could you please add the name of the module as well?

**Describe alternatives you've considered**

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 456, thanks
