### ISSUE TITLE
If the settings of the controls in the form(*.frm) contain exponential expressions, they will cause errors during importing VBP

### ISSUE THREAD

**Issue by cycle40** [twinbasic/twinbasic#1795]
**Describe the bug**
At first, thank you for addressing Issue#1790.
Now i can know the file name which causes importing error.
![image](https://github.com/twinbasic/twinbasic/assets/22705898/0b54a449-5eb8-4ba8-a2e8-db6b39b8857b)

And I checked the line 222 of the file.
![image](https://github.com/twinbasic/twinbasic/assets/22705898/432849dc-c47c-450f-a014-b675a58f20c9)

Since "TabIndex=14" seems to be OK, I thought the problem might be that there is a number written in exponential representation on the line one above. After correcting the line and importing again, the error popup disappeared.

**To Reproduce**
1. Create a VB6 project containing a *.frm file with exponential expressions
2. Start twinBasic IDE and select VBP Import 
3. See a error message will pop up.

**Expected behavior**
Exponential expressions in FRM files can also be read.

(I don't think this happens very often and I didn't expect it to be written in exponential expressions in the control settings.
So, although it seems to be of low priority, I am reporting it just in case.)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - twinBASIC compiler version [twinBASIC_IDE_BETA_456]

**Comment by fafalone** [comment]
You're able to enter those values in your version of VB6? With the en-us version the only way I'd be able to get those is to manually edit the form in a text editor.

**Comment by cycle40** [comment]
Ok please try this.
1. Start VB6 IDE
2. Create New Project (Standard EXE).
3. Open Form1.frm designer
4. Set a PictureBox on it
5. Set these values.
![image](https://github.com/twinbasic/twinbasic/assets/22705898/d1c3ae73-a45d-41da-b3d1-944b2308d148)
6. Save Project.
7. Open Form1.frm by some text editor.
![image](https://github.com/twinbasic/twinbasic/assets/22705898/9dd39575-59ba-4952-82ab-c4f2f260c1b2)

**Comment by fafalone** [comment]
Ok yeah that reproduces. It doesn't stop the import though; after clicking ok the form is still importing for me, it just truncated the exponent.

[FloatPropTest.zip](https://github.com/twinbasic/twinbasic/files/14441810/FloatPropTest.zip)

**Comment by cycle40** [comment]
Thanks for confirming.
Even though I have been touching VB6 for a long time now, I never knew that property values are sometimes stored using exponential expressions.

It is the same behavior as here that if I press the OK button on the error message, the rest will be imported to the end.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 489, thanks
