### ISSUE TITLE
Date PropLet/Get not formatted correctly in Properties window

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1796]
**Describe the bug**
It's currently displayed as a number, rather formatted date.

**To Reproduce**
Add UserControl/ActiveX control with a Date property, e.g. the tB DTPicker.

**Expected behavior**
Display as date/time.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/2fcbb0e3-e3c1-41d7-8bbb-cfeb156442b1)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.457
 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 489, thanks
