### ISSUE TITLE
Double Clicking title bar (menu bar?) displays IDE internal error in DEBUG CONSOLE

### ISSUE THREAD

**Issue by cycle40** [twinbasic/twinbasic#1799]
**Describe the bug**
Double Clicking title bar (menu bar?) displays IDE internal error in DEBUG CONSOLE

**To Reproduce**
1. Start twinBasic IDE
2. Click on 'CANCEL'
3. Double Click title bar.
4. See error in DEBUG CONSOLE

**Expected behavior**
Maximize or UnMaximize Window.
(this should not be high priority.)

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/22705898/0864501c-0e40-415e-8274-02751d75a7d4)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 Pro]
 - twinBASIC compiler version [e.g. 0.15.460]

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 489, thanks
