### ISSUE TITLE
CommandButton.Value = True does not raise the Click event

### ISSUE THREAD

**Issue by EduardoVB** [twinbasic/twinbasic#1801]
**Describe the bug**

`CommandButton.Value = True `

does not raise the Click event like VB6 does.

**(please complete the following information):**
 - twinBASIC compiler version 461

**Comment by EduardoVB** [comment]
Also, the CommandButton must retain the value to True only while is performing the programmatic click but immediately must go back to False.
tB CommandButton now sets the True value permanently.

I think I already had seen this issue in the past, but could not find an open issue (I didn't search the closed ones).

It is not a too rarely used feature, although many people don't know about it.
Krool's CommandButtonW behaves correctly, at least in VB6 that I tested it.

**Comment by WaynePhillipsEA** [comment]
CommandButton.Value was marked as unimplemented.  It is now implemented in BETA 489.  Thanks!
