### ISSUE TITLE
Error evaluating constant expression on very simple expression

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1802]
**Describe the bug**
Normally I get this when there's a lot of cross-module calculations to be made. But now I'm getting it in a new project, with everything within a single module, in only a few lines.

**To Reproduce**

```vba
    Public Enum POWER_PLATFORM_ROLE
        PlatformRoleSlate = 8
    End Enum
 
    Public Const POWER_PLATFORM_ROLE_V2_MAX  = (PlatformRoleSlate + 1)
 
    Public Const POWER_PLATFORM_ROLE_VERSION_MAX = POWER_PLATFORM_ROLE_V2_MAX
```

**Expected behavior**
Evaluation of the constant expression.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.464
 - 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 488, thanks
