### ISSUE TITLE
UserControl designer x,y coordinates continually move down

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1803]
**Describe the bug**
The small box that displays the x,y of the cursor as it moves on the designer is moved down every time it updates. After it hits the bottom, a scrollbar appears, and it keeps moving down, seemingly without limit.

**To Reproduce**
-New StdExe
-Add Windows UserControl
-Move mouse on designer

**Expected behavior**
It should be stationary like with Form.

**Screenshots**
![image](https://github.com/twinbasic/twinbasic/assets/7834493/bc16512b-4322-477c-983f-5c545ade241f)

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - twinBASIC compiler version 0.15.466

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Can't repro this

**Comment by WaynePhillipsEA** [comment]
Actually I can.  It's not just happening on UserControls though.  It only happens when the yellow (x,y) bubble on the left overlaps the red (xs, ys) bubble on the right... i.e. when the control/form area is small

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 472, thanks
