### ISSUE TITLE
ComponentOne VSflex8

### ISSUE THREAD

**Issue by MGolubic** [twinbasic/twinbasic#1804]
Hello, 
my company is considering TwinBasic to continue 30+ VB projects (mainly accounting apps).
Biggest problem is with one control from ComponentOne - VSFlexGrid version 8.

When project is loaded/converted from old VB6 we get hundreds notifications of following error
TWIN BASIC [SERIALIZATION ERROR] Unable to find ActiveX control 'VSFlex8Ctl.VSFlexGrid'

Forms with control cannot be open. Also IDE is frozen for long time and/or getting IDE into safe mode.

If you make new project in TwinBasic control is working properly.

Working environment :
Windows 10 latest patch
TwinBasic - tried last 10 releases

Screenshot of error when loading form:
![image](https://github.com/twinbasic/twinbasic/assets/162959182/111841a3-57e0-47b9-8835-63b86047211a)

Non-bug related question:
Is there any solution or steps to follow, where you can easily remove control from FORM and re-add it (we have to do this for more 1000+ forms)?
We have complex vb project structure where some folders/forms are shared between project, how to implement same in TwinBasic?

**Comment by WaynePhillipsEA** [comment]
Unfortunately I don't have a licence for this commercial control, however...

I suspect you need to edit the COM references manually for this one, after you've imported the VBP.  You'll need to edit the symbol name of the reference.  It probably imports as `VSFlex8` but needs to be manually renamed to `VSFlex8Ctl` in the COM references dialog.

**Comment by MGolubic** [comment]
I tried to change alias of reference - not working.
Exported project and changed TBform  to VSFlex8 - still not working.

Next are two definitions in TBform, one is new project with drawn control (working one), other is imported, there are major differences.

{
	"(About)": "",
	"(Custom)": "",
	"AccessibleDescription": "",
	"AccessibleName": "",
	"AccessibleRole": null,
	"AccessibleValue": "",
	"Align": false,
	"AllowBigSelection": true,
	"AllowSelection": true,
	"AllowUserFreezing": "flexFreezeBoth",
	"AllowUserResizing": "flexResizeBoth",
	"Anchors": {
		"Bottom": false,
		"Left": true,
		"Right": false,
		"Top": true,
		"_className": "Anchors",
		"_clsid": "{8524D4B5-72A9-40A9-A189-29E7905C40CA}"
	},
	"Appearance": "flexXPThemes",
	"AutoResize": true,
	"AutoSearch": "flexSearchFromTop",
	"AutoSearchDelay": 2,
	"AutoSizeMode": "flexAutoSizeColWidth",
	"AutoSizeMouse": true,
	"BackColor": -2147483643,
	"BackColorAlternate": -2147483643,
	"BackColorBkg": -2147483636,
	"BackColorFixed": -2147483633,
	"BackColorFrozen": 0,
	"BackColorSel": -2147483635,
	"BorderStyle": "flexBorderFlat",
	"CausesValidation": false,
	"CellButtonPicture": 0,
	"ClipSeparators": null,
	"ColWidthMax": 0,
	"ColWidthMin": 0,
	"Cols": 10,
	"ComboSearch": "flexCmbSearchAll",
	"DataMember": null,
	"DataMode": "flexDMFree",
	"DataSource": null,
	"Dock": "vbDockNone",
	"DragIcon": "",
	"DragMode": "vbManual",
	"Editable": "flexEDNone",
	"Ellipsis": "flexNoEllipsis",
	"Enabled": true,
	"ExplorerBar": "flexExSortShowAndMove",
	"ExtendLastCol": false,
	"FillStyle": "flexFillSingle",
	"FixedCols": 1,
	"FixedRows": 1,
	"FloodColor": 192,
	"FocusRect": "flexFocusLight",
	"Font": {
		"Bold": false,
		"Italic": false,
		"Name": "MS Sans Serif",
		"Size": 8.25,
		"Strikethru": false,
		"Underline": false
	},
	"ForeColor": -2147483640,
	"ForeColorFixed": -2147483630,
	"ForeColorFrozen": 0,
	"ForeColorSel": -2147483634,
	"FormatString": null,
	"FrozenCols": 0,
	"FrozenRows": 0,
	"GridColor": -2147483633,
	"GridColorFixed": -2147483632,
	"GridLineWidth": 1,
	"GridLines": "flexGridFlat",
	"GridLinesFixed": "flexGridInset",
	"GroupCompare": "flexMCExact",
	"Height": 166,
	"HelpContextID": 0,
	"HighLight": "flexHighlightAlways",
	"Index": -1,
	"Left": 70,
	"MergeCells": "flexMergeNever",
	"MergeCellsFixed": "flexMergeNever",
	"MergeCompare": "flexMCExact",
	"MouseIcon": 0,
	"MousePointer": "flexDefault",
	"MultiTotals": true,
	"Name": "fGrid",
	"NodeClosedPicture": 0,
	"NodeOpenPicture": 0,
	"OLEDragMode": "flexOLEDragManual",
	"OLEDropMode": "flexOLEDropNone",
	"OutlineBar": "flexOutlineBarNone",
	"OutlineCol": 0,
	"OwnerDraw": "flexODNone",
	"PictureType": "flexPictureColor",
	"PicturesOver": false,
	"RightToLeft": false,
	"RowHeightMax": 0,
	"RowHeightMin": 0,
	"Rows": 2,
	"ScrollBars": "flexScrollBarBoth",
	"ScrollTips": false,
	"ScrollTrack": false,
	"SelectionMode": "flexSelectionListBox",
	"SheetBorder": -2147483642,
	"ShowComboButton": "flexSBFocus",
	"SubtotalPosition": "flexSTAbove",
	"TabBehavior": "flexTabControls",
	"TabIndex": 1,
	"TabStop": true,
	"Tag": null,
	"TextStyle": "flexTextFlat",
	"TextStyleFixed": "flexTextFlat",
	"ToolTipText": null,
	"Top": 68,
	"TreeColor": -2147483632,
	"Version": 801,
	"VirtualData": true,
	"Visible": true,
	"WallPaper": 0,
	"WallPaperAlignment": "flexPicAlignStretch",
	"WhatsThisHelpID": 0,
	"Width": 192,
	"WordWrap": false,
	"_IPersistStreamData": "AAkAANgTAAAoEQAAAwADAAAAAwABAAAACwD//wkAA1LjC5GPzhGd4wCqAEu4UQHuAACQAURCAQANTVMgU2FucyBTZXJpZgMAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAMABQAAgAMACAAAgAMADwAAgAMAEgAAgAMADQAAgAMADgAAgAMADAAAgAMABQAAgAMADwAAgAMAEAAAgAMAEAAAgAMAwAAAAAMABgAAgAMAAQAAAAMAAQAAAAsA//8LAP//AwADAAAAAwADAAAAAwABAAAAAwACAAAAAgABAAMAAgAAAAMACgAAAAMAAQAAAAMAAQAAAAMAAAAAAAMAAAAAAAMAAAAAAAMAAAAAAAsAAAAIAAAAAAALAAAAAwADAAAACwAAAAMAAAAAAAMAAAAAAAsA//8DAAAAAAADAAEAAAAEAAAAAEALAP//AwABAAAAAwAAAAAAAwAAAAAAAwAAAAAAAwAHAAAACwAAAAMAAAAAAAsAAAADAAAAAAADAAAAAAADAAAAAAADAAAAAAADAAEAAAALAAAAAwAAAAAAAwAAAAAAAwAAAAAAAwAAAAAAAwAAAAAACwD//wgAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAMAAwAAAAsA//8DAAAAAAADAAAAAAADAAMAAAADAAAAAAADAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAADAAkAAAAIAAIAAAAAAAgAAgAAAAAACAACAAAAAAADABgAAAA=",
	"_className": "VSFlex8.VSFlexGrid",
	"_clsid": "{C945E31A-102E-4A0D-8854-D599D7AED5FA}",
	"_isFrame": true
}

Imported  definition:

{
	 "AccessibleRole": 24,
	 "AccessibleValue": "",
	 "AccessibleDescription": "",
	 "AccessibleName": "",
	 "WallPaperAlignment": 9,
	 "ForeColorFrozen": 0,
	 "BackColorFrozen": 0,
	 "AllowUserFreezing": 3,
	 "FrozenCols": 0,
	 "FrozenRows": 0,
	 "AutoSizeMouse": -1,
	 "ComboSearch": 3,
	 "DataMember": "",
	 "VirtualData": -1,
	 "DataMode": 0,
	 "OleDropMode": 0,
	 "OleDragMode": 0,
	 "TextStyleFixed": 0,
	 "TextStyle": 0,
	 "WordWrap": 0,
	 "ShowComboButton": 1,
	 "Editable": 0,
	 "OwnerDraw": 0,
	 "TabBehavior": 0,
	 "PictureType": 0,
	 "RightToLeft": 0,
	 "FillStyle": 0,
	 "PicturesOver": 0,
	 "ExplorerBar": 7,
	 "Ellipsis": 0,
	 "OutlineCol": 0,
	 "OutlineBar": 0,
	 "SubtotalPosition": 1,
	 "MultiTotals": -1,
	 "AutoSearchDelay": 2,
	 "AutoSearch": 1,
	 "AutoSizeMode": 0,
	 "AutoResize": -1,
	 "MergeCompare": 0,
	 "MergeCells": 0,
	 "ScrollTips": 0,
	 "ScrollBars": 3,
	 "ScrollTrack": -1,
	 "FormatString": "",
	 "ExtendLastCol": 0,
	 "ColWidthMax": 0,
	 "ColWidthMin": 0,
	 "RowHeightMax": 0,
	 "RowHeightMin": 0,
	 "FixedCols": 1,
	 "FixedRows": 1,
	 "Cols": 10,
	 "Rows": 50,
	 "GridLineWidth": 1,
	 "GridLinesFixed": 2,
	 "GridLines": 1,
	 "SelectionMode": 3,
	 "AllowUserResizing": 3,
	 "AllowBigSelection": -1,
	 "AllowSelection": -1,
	 "HighLight": 1,
	 "FocusRect": 1,
	 "SheetBorder": -2147483642,
	 "FloodColor": 192,
	 "TreeColor": -2147483632,
	 "GridColorFixed": -2147483632,
	 "GridColor": -2147483633,
	 "BackColorAlternate": -2147483643,
	 "BackColorBkg": -2147483636,
	 "ForeColorSel": -2147483634,
	 "BackColorSel": -2147483635,
	 "ForeColorFixed": -2147483630,
	 "BackColorFixed": -2147483633,
	 "ForeColor": -2147483640,
	 "BackColor": -2147483643,
	 "MousePointer": 0,
	 "Font":[1,234,234,234,145,143,206,17,157,227,0,170,0,75,184,81,3,82,227,11,145,143,206,17,157,227,0,170,0,75,184,81,147,178,0,0,0,1,0,0,3,0,13,0,245,189,43,198,44,0,0,0,115,0,116,0,114,0,105,0,107,0,101,0,116,0,104,0,114,0,111,0,117,0,103,0,104,0,0,0,0,0,0,0,3,0,6,0,48,16,77,183,28,0,0,0,105,0,116,0,97,0,108,0,105,0,99,0,0,0,0,0,3,0,9,0,173,131,52,211,36,0,0,0,117,0,110,0,100,0,101,0,114,0,108,0,105,0,110,0,101,0,0,0,0,0,0,0,3,0,6,0,27,52,93,154,28,0,0,0,119,0,101,0,105,0,103,0,104,0,116,0,144,1,0,0,3,0,7,0,165,89,4,202,32,0,0,0,99,0,104,0,97,0,114,0,115,0,101,0,116,0,238,0,0,0,0,0,5,0,4,0,228,121,15,164,28,0,0,0,115,0,105,0,122,0,101,0,0,0,0,0,0,128,32,64,8,0,4,0,100,151,13,132,60,255,255,255,110,0,97,0,109,0,101,0,13,0,0,0,77,0,83,0,32,0,83,0,97,0,110,0,115,0,32,0,83,0,101,0,114,0,105,0,102,0,0,0],
	 "Enabled": -1,
	 "BorderStyle": 1,
	 "Appearance": 3,
	 "_cy": 1959661070,
	 "_cx": 1959668532,
	 "Width":418,
	 "Top":51,
	 "TabIndex": 1,
	 "Left":6,
	 "Height":136,
	 "FontName":"MS Sans Serif",
	 "_className": "VSFlex8Ctl.VSFlexGrid",
	 "Name":"fGrid","_isImportedActiveXControl": true
  }

**Comment by WaynePhillipsEA** [comment]
Don't be concerned by the differences at the JSON level - imported FRMs are persisted differently to new controls.  That is not the problem here.  

Please show me a screenshot where you have changed the `VSFlex8` to `VSFlex8Ctl` in the COM references.

**Comment by WaynePhillipsEA** [comment]
To be clear this is where you change the symbol:

<img width="488" alt="tbRefSymbolChange" src="https://github.com/twinbasic/twinbasic/assets/25738109/ba37eea2-1146-44a0-a379-ae15c5a05795">

You click the little pencil icon, and change it that way.

**Comment by MGolubic** [comment]
I loaded smaller project with only 10 forms with VSFlexGrid, replaced JSON in TBform, 
and it is working - error is gone.
But it would be too good if all worked, after this another error popped up with Crystal Report Viewer and DEP message. 
I will open new issue if i cant solve it.

Thank You for now.

**Comment by fafalone** [comment]
You can disable DEP for the IDE in the IDE settings, and for your compiled exe in project settings. It is enabled by default; I've hit problems with it too.

**Comment by MGolubic** [comment]
Thank you fafalone and Wayne, project is successfully loaded no errors in design.

I had changed loading values from collection to custom type since its not implemented.

Now there are some other problems, but I have to find time to analyze them.
