### ISSUE TITLE
Go to definition broken on coclasses

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1805]
**Describe the bug**
If you dim a variable as the coclass name itself rather than an interface, go to definition does not work.

**To Reproduce**

```vba
Interface IFoo Extends IUnknown
    
End Interface
CoClass foo
    [Default] Interface foo
End CoClass
Module MyModule

Sub test()
    Dim f As foo
End Sub
```

Go to definition on foo.

**Expected behavior**
Going to coclass definition

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.468

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 487, thanks
