### ISSUE TITLE
Step Into (F8 or F11)

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1809]
### Discussed in https://github.com/twinbasic/twinbasic/discussions/1808

<div type='discussions-op-text'>

<sup>Originally posted by **mayost** March 14, 2024</sup>
Hello

When I enter the code:

Private Sub Form_Load()
    Dim lngVar as Long
    do until lngVar=10
        Debug.print lngVar
    loop
    Stop
    End
end Sub

When it reaches: STOP
It does stop
But if I continue and press F8 to move forward one step, it reaches the END command and if I press F8 again to move forward, the ID gets stuck and does not allow anything to continue, it is on pause

Thanks</div>

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 503, thanks
