### ISSUE TITLE
DoEvents treated as label when placed before :

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1810]
**Describe the bug**
DoEvents treated as label when placed before :

**To Reproduce**
Use `DoEvents` in combination with another statement, e.g.

```vba
        Dim i As Long
        DoEvents: i = 1
```

**Expected behavior**
Treated as sub.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.472

**Additional context**
I'm not sure if this is only applying to syntax highlighting or compiling; it's very difficult to detect if DoEvents fired properly.

**Comment by WaynePhillipsEA** [comment]
Yes, this appears to be a hard coded exception in VB6, since this would ordinarily be treated as a line label.  e.g. the same does not occur for other builtin no-param functions like `Beep` and `Command`, which are treated as line labels.

**Comment by wqweto** [comment]
You can workaround with `Call Beep: i = 2` and `Call Command: i = 3` but you cannot use `Call DoEvents` which is a syntax error. Apparently `DoEvents` is some kind of intrinsic.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 478, thanks
