### ISSUE TITLE
Can't drag to select text in Project Explorer

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1811]
**Describe the bug**
When a label edit is initiated to rename a file in the Project Explorer, click and dragging to select text instead attempts to drag/drop the item.

**To Reproduce**
...

**Expected behavior**
Selecting the text.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10 
 - twinBASIC compiler version 0.15.472

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 478, thanks
