### ISSUE TITLE
MSCOMM32.OCX import file question.

### ISSUE THREAD

**Issue by Polocake1** [twinbasic/twinbasic#1813]
Describe the bug

I tried to import MSCOMM32.OCX to TWINBASIC. But when I wanted to write the code, an error message appeared.

![TWINBASIC_MSCOMM32 OCX_ERROR](https://github.com/twinbasic/twinbasic/assets/163824686/475c9b1e-0521-454b-9419-9523a0c0d5fb)

Expected behavior

Please explain how can I use MSCOMM32.OCX in TwinBASIC.

Note : I have successfully registered regsvr32 MSCOMM32.COX before.

 - OS:  Windows 11
 - twinBASIC IDE BETA 472

Thanks!

**Comment by sokinkeso** [comment]
Hi, registering an ocx with regsvr32 is for using it at runtime. For using it at design time you need either vb6 installed or another reg entry to do the same.

**Comment by fafalone** [comment]
That error is `CLASS_E_NOTLICENSED` ... VB6 components install licenses with them, you'll need that to use it.

**Comment by bcelestia** [comment]
There is a registry entry to license MSComm32.OCX at
https://forums.ni.com/t5/LabVIEW/Import-ActiveX-MSCOMM32-Error/td-p/1304976
Look for the Solution.
I've used it many times on different PC's.

**Comment by Polocake1** [comment]
I followed bcelestia's method and it works. Thanks.

**Comment by fafalone** [comment]
Nonissue/resolved, closing. Glad you got it working!
