### ISSUE TITLE
Feature request: Access DLL hInst without WinNativeForms

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1815]
**Is your feature request related to a problem? Please describe.**
When making a Standard DLL it's often desirable to leave out the large GUI package when that's not going to be used. But sometimes resources in the DLL need to be accessed.

**Describe the solution you'd like**
DllMain provides an hInstance for the DLL; I'd like for there to be some way of getting this without the `App` object-- assuming `App.hInstance` even correctly reported a DLL hInstance, which I haven't tested.

**Describe alternatives you've considered**
API

**Additional context**

**Comment by Greedquest** [comment]
QQ will it affect the compiled dll size, or just uncompiled .twinproj? Is it just a developer experience thing, not wanting 100 new things added to intellisense when you only needed one?
