### ISSUE TITLE
Updating a package fails

### ISSUE THREAD

**Issue by AlanSkyNet** [twinbasic/twinbasic#1816]
**Describe the bug**
In the Project settings under Library References, trying to update the VBCCR17 package, the IDE fails to update the components.

**To Reproduce**
Check the Available Packages tab, select the VBCCR17 checkbox.

**Expected behavior**
The IDE should say: please save the project and restart the IDE. Upon restart, the latest build should be loaded.

**Desktop (please complete the following information):**
 - Windows 11
 - twinBASIC compiler version build 479

**Additional context**

**Comment by fafalone** [comment]
You have to uncheck the package, choose 'Remove it' in the confirmation dialog, then add it again. The compiler will restart but you don't need to restart the IDE.

Just checked and had no issue updating VBCCR with these steps.

**Comment by AlanSkyNet** [comment]
Thx will try. I think I did that but then I had a question mark instead of the visual component.
