### ISSUE TITLE
Type and Enum block not auto-closed

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1817]
**Describe the bug**
When adding a new type you'd type `Public Type mytype`, press enter, and `End Type` would be automatically inserted. This currently isn't happening. Same with `Enum`. Other types of blocks like `Interface` and `Sub` are still working.

**To Reproduce**
Add UDT or Enum to new project.

**Expected behavior**
Automatic End Type/Enum insertion.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.483
 - 
**Additional context**
This has been going on for a few versions now.

**Comment by WaynePhillipsEA** [comment]
Both working for me in a new StdExe project

**Comment by WaynePhillipsEA** [comment]
Ah sorry, yes, not working with `Public`/`Private` prefix

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 485, thanks
