### ISSUE TITLE
Methods receiving ByRef UDT only recognize LongPtr when it's a variable or argument

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1818]
**Describe the bug**
tB allows passing a pointer to method expecting a UDT, which can then be used to manipulate the original without the user needing to worry about manually writing to the offset or copying, modifying, and restoring the UDT.

It should make no difference where the `LongPtr` comes from, but a codegen error comes when trying to compile or during runtime when in the IDE when the `LongPtr` supplied is a member of a UDT instead. There's a rather simple workaround of just using a temporary local variable; but that extra code shouldn't be needed; it makes this really handy feature a lot less elegant. 

**To Reproduce**
-New StdExe; Add Module
-Module:

```vba
Public Type foo
    ptr As LongPtr
End Type
Public Type bar
    Length As Integer
    flags As Long
End Type
Public Sub SetFlags(p As bar)
    p.flags = p.flags Or &H20
End Sub
```

Test call in `Form_Load`; this should work:

```vba
Private f As bar
Private Sub Form_Load() Handles Form.Load
    Dim t As foo
    t.ptr = VarPtr(f)
    SetFlags t.ptr
    Debug.Print f.flags
End Sub
```

But instead on compile, `[LINKER] compilation (codegen) error detected in 'Form1.Form_Load' at line [SetFlags t.ptr]` and the same as a runtime error if ran from the IDE.

Replacing the offending line with:

```vba
Dim lp As LongPtr = t.ptr
SetFlags lp
```

works.

**Expected behavior**
This indirection shouldn't be needed; a `LongPtr` is a `LongPtr`, and it should work whether as a variable, argument, or UDT member.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:   Windows 10 
 - twinBASIC compiler version 0.15.483

**Additional context**

**Comment by WaynePhillipsEA** [comment]
Yes, I'll get that fixed.  Just wrapping in `CLngPtr()`, or even just an extra parenthesis `SetFlags (t.ptr)` fixes it

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 485, thanks
