### ISSUE TITLE
tbGlobalSearchAddIn1.dll flagged as malware and quarantined

### ISSUE THREAD

**Issue by dhai80** [twinbasic/twinbasic#1819]
**Describe the bug**
tbGlobalSearchAddIn1.dll is flagged as malware by Cylance and quarantined.
This happens on startup of V479 and V486 in 32bit.  I have not checked earlier versions.

Twinbasic still works without this DLL.  
Regular search and "Find in project" also work without this DLL.  

This is the vendor who flags the dll:
Kingsoft
malware.kb.a.782
Trellix(FireEye)

**Comment by wqweto** [comment]
Add this file to Cylance exception list and don't worry about it as it's apparently a false positive by an outsourced AV software.

**Comment by WaynePhillipsEA** [comment]
Unfortunately there's not much we can do to prevent it.  The DLLs are already signed.  Once we reach a stable release, we can send all the files off to some of the common anti virus vendors for whitelisting.
