### ISSUE TITLE
Infinite IDE crash loop when interface has members foo and _foo

### ISSUE THREAD

**Issue by fafalone** [twinbasic/twinbasic#1820]
**Describe the bug**
This was originally identified in a derived interface, but applies within a single interface as well:

Normally names starting with an underscore work fine, except when there's already a method with the same name without the underscore;

```
3:41:03.390
0001 03:41:03.381 NATIVE EXCEPTION: ACCESS_VIOLATION  {no-basic-code}
     thread 0009: CompilerOrganizationParsingEnd
     thread 0008: CompilerPackageIntellisenseAwaiting
     thread 0007: CompilerPackageIntellisenseAwaiting
     thread 0006: CompilerPackageIntellisenseAwaiting
     thread 0005: CompilerPackageIntellisenseAwaiting
 >>> thread 0004: IntellisenseAfterCompilationStart
     thread 0003: CompilerPackageIntellisenseAwaiting
     thread 0002: ProjectPushCustomControlsToClientEnd
```

That error repeats until the safe mode breakout kicks in.

**To Reproduce**
New StdExe:

```vba
[InterfaceId("08DD6ADC-728D-4774-A13B-AEF6E1ACE8FC")]
Interface IFoo Extends IUnknown
    Sub test1(ByVal a As Long)
    Sub test2(ByVal a As Long)
    Sub test3(ByVal a As Long)
    Sub test2(ByVal a As Long)    
End Interface
```

Then rename the second `test2` by putting an underscore to make it `_test2`

**Expected behavior**
At the very least, this shouldn't cause a crash loop. Ideally it should work with both of them: This issue came up defining the Windows SDK provided version of `IBrowserService` and `IBrowserService2`. The first one has `NavigateToPidl`, the second inherits from the first and has `_NavigateToPidl`.\
It could be renamed if proper support would require major changes, but ideally since tB is trying to support leading underscores in names it should be possible as-is.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - twinBASIC compiler version 0.15.487
 
**Additional context**

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 494.  Thanks
