### ISSUE TITLE
Nested Frame Caption takes Background Color of Parent Frame

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1821]
**Describe the bug**
This started on v481. If VisualStyles=True, then a nested frame caption takes on the background color of its parent frame. See image below:

![nested frames](https://github.com/twinbasic/twinbasic/assets/26237126/7c1e20bb-a1f3-405d-b17f-397fd1429792)

**To Reproduce**
1. Create a standard EXE project.
2. Place two frames on the form (one inside the other).
3. Change background color of the parent frame.
4. Run the form (problem only shows at runtime).

**Expected behavior**
Not being a VB6'er, I'm not sure what the "expected" behavior is, but I like the pre-v481 behavior better.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC v481

**Comment by fafalone** [comment]
VB6 is closer to 481, but it's glitching on the font right now, not sure if it's just me. Uses the ugly fallback font

![image](https://github.com/twinbasic/twinbasic/assets/7834493/5e1308c4-7af4-4600-94bf-5727f5e7c375)
.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 490, thanks
