### ISSUE TITLE
Form with No Caption still has Title Bar

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1830]
**Describe the bug**
A form with no Caption  and with controlbox=false should not dislay a TitleBar (as in VB6)
In TwinBasic the form displays with an empty TitleBar

 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [507]

**Comment by dmrvb** [comment]
Hold on this, I think there might be other factors (Form Properties), I will try to pin them down.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 510, thanks
