### ISSUE TITLE
Labels created as part of a Control Array are Not Visible.

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1833]
**Describe the bug**
Labels created as part of a control array with Load are NOT visible.

The control elements exist and their properties can be set and read, and visible=true, but they are still not visible.

**To Reproduce**
Put a couple of labels on a form to be elements 1 and 2 of a control array.
Create elements 3 and 4 at run time using Load.

Test prog available upon request.

win 11 tB 515

**Comment by wqweto** [comment]
This works ok in BETA 587

**Comment by WaynePhillipsEA** [comment]
Closing as completed.  Thanks
