### ISSUE TITLE
Wrong Units on Form.MinWidth, and VB6 conflict

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1836]
tB Forms support a minWidth (and minHeight) property, (VB does not, but the tB minwidth/minHeight is a really good feature).

in tB the width property of a Form is specified in Twips (in the IDE properties box etc) but the minWidth property is specified in Pixels.
I think this is illogical and wrong and minWidth/height should also be specified in Twips because it realates so closely to Width.

Note that minwidth currently diverges from the pixel width of a Form if DPI awareness is on, another reason to specify in Twips).
Also note (really trivial issue) the tooltip help on the Form.width property in the IDE says that width is in Pixels but its actually in Twips.

and a real bug.....
If an imported VB project declares a variable called minwidth (probably to manually implement what minwidth does) then no warning is given but setting the minwidth variable actually sets the minwidth property with very unexpected results :smiley:  
Ideally a warning/error should be given.

win11 tB515

**Comment by fafalone** [comment]
A warning, and for compatibility the ambiguity should be resolved in favor of the variable.

**Comment by dmrvb** [comment]
Working in Pixels rather than Twips is a duplicare of issue 1738, sorry, but the conflict with the variable needs a warning.

**Comment by WaynePhillipsEA** [comment]
When you say `If an imported VB project declares a variable called minwidth...`, I take it you mean a variable declared at the form class level? (since a procedure level variable definitely shouldn't be interfering with it.)

**Comment by dmrvb** [comment]
Yes, its a form/class level private variable.

I was using this to record the form design-time size as the form loads, and then limiting the minimum form size to that size which requires subclassing, so your implementation of minwidth/height is just so much easier.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 596.  Thanks.
