### ISSUE TITLE
tB IDE Addin - implement File Get Property for Editor object

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1838]
**Is your feature request related to a problem? Please describe.**
There does not seem to be a convenient means to get File properties for the active Editor. The Editor class has a "Path" property but I would like it to return a File object [FileSystemItem] so that other file properties are easily exposed (Name, [FileSystemItem]Type, Path, Text, etc). 

**Describe the solution you'd like**
```vba
Dim activeFile as File
Set activeFile = host.ActiveEditors(0).File
host.DebugConsole.PrintText "file name:  " & activeFile.Name & " file type: " & activeFile.Type
```

**Describe alternatives you've considered**
I currently get the active Editor's File object by recursively searching the file system until File.Path=Editor.Path, which works fine, but ideally should be easier.

**Additional context**
This isn't high priority.

**Comment by sokinkeso** [comment]
You can get a FileSystemItem from the ActiveEditor with the following statement.

`Dim fsi As FileSystemItem = Host.FileSystem.ResolvePath(Host.ActiveEditors(0).Path)`

You can then check the Type of this item according to the  FileSystemItemType Enum
```
    Enum FileSystemItemType
        Folder = 0
        FileVIRTUALDOC = 1          ' Unicode, read-only
        FileOTHER = 2
        FileTWIN = 3                ' Unicode
        FileBAS = 4                 ' System ANSI
        FileCLS = 5                 ' System ANSI
        FileUIDESIGNER = 6          ' Unicode (JSON)
        FileJSON = 7                ' Unicode (JSON)
    End Enum
```
If the Item type is not 0  (a folder), then you can Declate a File variable and get more info.

Dim tmpFile as File
Set tmpFile = fsi  ' fsi is the FileSystemItem from above

**Comment by GCuser99** [comment]
Thanks Nikos!
