### ISSUE TITLE
Easy Means of Refreshing Imported Packages

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1848]
**Is your feature request related to a problem? Please describe.**
Projects that reference actively managed imported Packages (e.g. WinDevLib) can point to older/stale versions without developer frequently checking to see if there is a newer version. If/when the developer becomes aware of a newer Package version then must manually remove old reference and then add new reference.

**Describe the solution you'd like**
It would be very helpful to have a Refresh Imported Packages button on the Enabled Libraries tab of the Library References dialog that when clicked checks all imported Packages for newer versions and automatically removes/adds the old/new references.

**Comment by fafalone** [comment]
Sounds like a very good idea 😄 

https://github.com/twinbasic/twinbasic/issues/1320

**Comment by GCuser99** [comment]
Oops - should I close this one do you think?

**Comment by fafalone** [comment]
Well.. that post is buried back in 2022, so I'll close that one and leave this up.
