### ISSUE TITLE
Err.Raise reversion since v423

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1856]
**Describe the bug**
in v423 an Err.Raise in an MS Office Active DLL displayed the following (expected) dialog to user:

<img src="https://github.com/twinbasic/twinbasic/assets/26237126/5be5a328-cd1b-4e80-80c9-2a9093df275d" width=50% height=50%>

in v553, the same Err.Raise displays two dialogs back-to-back:

<img src="https://github.com/twinbasic/twinbasic/assets/26237126/51da17a9-ae2c-452b-b0bb-45d3a707acf0" width=50% height=50%>
<img src="https://github.com/twinbasic/twinbasic/assets/26237126/a8189fc7-c654-41cd-9e16-ff48e0b7532b" width=50% height=50%>

**Expected behavior**
v423 behavior is expected.

**Desktop:**
 - OS: Windows 11, MS Office 365
 - twinBASIC v553

**Additional context**
The reversion occurred between v423 and v500.

**Comment by GCuser99** [comment]
More info on this - Err.Raise seems to work fine in tB IDE. The problem seems only evident in the host (in this case Excel) that references the ActiveX DLL.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 569, thanks
