### ISSUE TITLE
TreeView Crashes VBIDE (Beta 258 and Newer)

### ISSUE THREAD

**Issue by jlegg0514** [twinbasic/twinbasic#1865]
**Describe the bug**
When using a tree view in a user control, clicking on the tree view crashes the VBIDE, throwing a "No such interface supported" error

**To Reproduce**
1. Open a new instance of twinBASIC
2. Click on Samples -> Sample 4. MyVBEAddin
3. Click on myToolWindow.tbcontrol and remove all controls
4. Create a new TreeView
5. Click on myToolWindow.twin, edit the file to look like the following:
```
Public Class myToolWindow

    Public myAddIn As myAddIn
    
    Private Sub TreeView1_Initialize() Handles TreeView1.Initialize
        TreeView1.Nodes.Add(, , "Test", "Test")
    End Sub
    
    Private Sub TreeView1_Click() Handles TreeView1.Click
        Exit Sub
    End Sub
            
End Class
```
6. Build the project
7. Open up Microsoft Access and go to the VBIDE
8. Click on the node in the TreeView

**Expected behavior**
The only node on the TreeView should be selected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC IDE BETA 558

**Additional context**
This error does not trigger in twinBASIC IDE BETA 557

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 566, thanks
