### ISSUE TITLE
popup menu not working/gives error

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#1868]
PopupMenu menuname gives an "unknown name" error in a module called Menus.twin at line 238   ParentForm.buildmenus.....

**To Reproduce**
Create a simople form with a menu and put the popupmenu in a command button.

Note that for testing I am creating all test progs in VB6 and importing into tB
Test prog available if required.

win11   tB 570

**Comment by dmrvb** [comment]
This bug is still oputstanding.

The offending line is now 252 rather than 238 

Would you like a little test prog?

**Comment by WaynePhillipsEA** [comment]
Hi, apologies, I just haven't had chance to look at this one yet.  A demo project is always helpful and typically means it's more likely I will get to it sooner since there's less effort needed from me ;)  Thanks

**Comment by fafalone** [comment]
This is likely related to the menu part of the issue I posted on Discord; PopupMenus are indeed not working at all; here's a demo twinproj but it's literally just clicking to add a menu with items then PopupMenu Menu1

[PopupMenu.zip](https://github.com/user-attachments/files/16980720/PopupMenu.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 604.  Thanks!
