### ISSUE TITLE
Add BorderColor Property to Form Label Control

### ISSUE THREAD

**Issue by GCuser99** [twinbasic/twinbasic#1876]
v577 has added to the Label control a BorderCustomOptions property to be used with new BorderStyle=vbCustomBorder enum value. Very nice!

For convenience, it would also be nice to have a BorderColor property to be used with BorderStyle=vbFixedSingleBorder.

FYI, VBA UserForm has a BorderColor property for Label control as well.

Thanks!

**Comment by GCuser99** [comment]
And same for all other controls that have the BorderStyle property would be useful.

**Comment by Kr00l** [comment]
vbFixedSingleBorder is by definition the native border "without customization". Adding support for color would be need to override it and that would be exactly as vbCustomBorder. So I think this request is not valid.
