### ISSUE TITLE
Event Click active on image not visible

### ISSUE THREAD

**Issue by plab25** [twinbasic/twinbasic#1878]
When i click on image that is not visible or not enabled the event click is not disable and run

**Comment by fafalone** [comment]
Checked and confirmed VB6 does not do this, thanks for reporting.

(Wayne, for clarity, the Click event fires for Image controls that are Enabled=False and Visible=False).

**Comment by plab25** [comment]
Hello

I confirm the Click event fires for Image controls that are Enabled=False or Visible=False


De : Jon ***@***.***>
Envoyé : jeudi 25 juillet 2024 04:55
À : twinbasic/twinbasic ***@***.***>
Cc : Philippe Laboure ***@***.***>; Author ***@***.***>
Objet : Re: [twinbasic/twinbasic] Event Click active on image not visible (Issue #1878)


Checked and confirmed VB6 does not do this, thanks for reporting.

(Wayne, for clarity, the Click event fires for Image controls that are Enabled=False and Visible=False).

**Comment by WaynePhillipsEA** [comment]
This will be fixed in the next release.  Thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 587, thanks!
