### ISSUE TITLE
Picturebox.Picture = LoadPicture(sFile) does not work

### ISSUE THREAD

**Issue by it-basixs** [twinbasic/twinbasic#1884]
In the current version (586) I cannot load images into a picturebox at runtime.

The same applies to the `LaVolpe AlphaImgControl` or the `sevLabel` from https://www.tools4vb.com/

Ty Andreas

**Comment by GCuser99** [comment]
Loading images into a tB native PictureBox control at runtime (v586) using ```Picturebox.Picture = LoadPicture(myFilePath)``` works for me. Does it work for you using older version of tB? What image type are you trying to load?

**Comment by WaynePhillipsEA** [comment]
If they are PNGs, you'll need to use `Global.LoadPicture`, since `LoadPicture` typically binds to the OLE implementation that doesn't support PNGs.

**Comment by it-basixs** [comment]
@All 

TY
