### ISSUE TITLE
VBA.Compilation.CurrentComponentCLSID will cause IDE crash

### ISSUE THREAD

**Issue by loquat** [twinbasic/twinbasic#1888]
windows 11 x64
tb 592

**Comment by loquat** [comment]
> This works for me
> 
> ```
>     Private Sub Form_Click()
>         MsgBox VBA.Compilation.CurrentComponentCLSID
>     End Sub
> ```
> 
> Which BETA are you testing?
> 
> Post sample failing code.

I use Sample5 MyCOMAddIn
in Module DllRegistration
add in first line:
    CONST AddInCLSID as string = vba.Compilation.CurrentComponentCLSID    'Like this
    Const AddinProjectName As String = VBA.Compilation.CurrentProjectName
the IDE will crash in restart loop

**Comment by WaynePhillipsEA** [comment]
Don't use these as part of constant expressions.   I will fix the crash in the next release, but this will not be supported and so will be considered invalid syntax.
