### ISSUE TITLE
We need a Template to show how to write an Excel Automation AddIn(User Defined Function in workbook)

### ISSUE THREAD

**Issue by loquat** [twinbasic/twinbasic#1891]
**Is your feature request related to a problem? Please describe.**
1. In VB6, we can write an ActiveX DLL with a Public Class and Public Function member and compile
2. Register that AX DLL, in Microsoft Excel x86, we DevTool - Excel AddIns - Automation, select the AX DLL
3. User Defined Functions can be used in worksheet.

**In tB i do it like this, but msexcel can not recognize that ax dll**
1.UsingActiveX template to create project
2.Write a Function like below, and compile to ActiveX DLL
Public Class Class1
Function MyAdd(Byval a, byval b)
return a+b
end function
End Class
3.Open Excel - DevTool - Excel AddIns - Automation, select the AX DLL
error shows: The selected file does not contain a new automation server or does not have sufficient permissions to register on the automation service

**Describe the solution you'd like**
To add a Template or Sample project to show us how to make it.

**Comment by loquat** [comment]
Excel automation addin is an ax dll to add user define formula functions which can call in worksheet.
which is different from VBA VBE addin as well as Com AddIn
for example: write in Range A3
=MyAdd(A1,A2)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 593, thanks
