### ISSUE TITLE
MonthView control changes month continuously after clicking arrow

### ISSUE THREAD

**Issue by VB6-Programming** [twinbasic/twinbasic#1898]
**Describe the bug**
Using the common controls MonthView control, after clicking the Next/Previous Month  arrow the display changes month without stopping.

**To Reproduce**
Place MonthView control on a form.
Preview or Run
Attempt to change the month using the arrows on the month line

**Expected behavior**
As VB6 or BETA 592

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version Since BETA 593

**Additional context**
Problem does not occur with DTPicker

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 613, thanks
