### ISSUE TITLE
PCRE tB support

### ISSUE THREAD

**Issue by loquat** [twinbasic/twinbasic#1901]
it seems PCRE donot have x64 dll for tB or vba 64bit

https://github.com/PCRE2Project/pcre2/releases
https://github.com/tannerhelland/PCRE2-VB6-DLL

**Comment by fafalone** [comment]
Should be possible to compile one... did you open the .sln in VS and try to compile?

**Comment by loquat** [comment]
> Should be possible to compile one... did you open the .sln in VS and try to compile?

I have tried, but it seems cannot add win64 compilation setting.

**Comment by fafalone** [comment]
I google pcre build windows, found [this repo](https://github.com/kiyolee/pcre2-win-build), opened the .sln, x64 was already selected, and it built with no change.

https://github.com/kiyolee/pcre2-win-build

**Comment by loquat** [comment]
really good, thanks, i will try
