### ISSUE TITLE
I found that after compiling, the window on the taskbar keeps flickering when the window is opened. I am currently using version 6.05.

### ISSUE THREAD

**Issue by sunliner2008** [twinbasic/twinbasic#1905]
I found that after compiling, the window on the taskbar keeps flickering when the window is opened. I am currently using version 6.05.

**Comment by sunliner2008** [comment]
![QQ录屏20241001014252 00_00_00-00_00_30~2](https://github.com/user-attachments/assets/c5e0481c-24a0-4d09-b6ef-295e837ba2a5)

**Comment by sunliner2008** [comment]
https://github.com/user-attachments/assets/68b92c2c-7551-47b5-803f-9c3f86991ee4

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 618, thanks
