### ISSUE TITLE
Diagnostics panel scrollbar doesn't work

### ISSUE THREAD

**Issue by DaveInCaz** [twinbasic/twinbasic#1909]
**Describe the bug**
The scroll bar in the IDE's Diagnostics window does not respond to mouse clicks.
![image](https://github.com/user-attachments/assets/385f84e3-5fdf-4fd6-9d61-6217cf9e7e7e)

But I can scroll the diag panel with the mouse wheel.

I also can't focus the diag panel by clicking the text in it either.

**To Reproduce**
I opened a VB6 form which had a ton of errors.

**Desktop (please complete the following information):**
 - OS: Win 11
 - twinBASIC compiler version: 608

**Comment by DaveInCaz** [comment]
In build 614 this is fixed! Scrolling works.

I still can't get the diag panel to accept focus however. But I'm not sure if that was intended. It could be useful however to allow rapid skipping through items in the list. (Or is there another way to do that?)

**Comment by fafalone** [comment]
In addition to each source file being collapsible you can click the icon/number of each category ( error, warning, etc) to toggle whether they appear in the list. And Wayne just added a feature where shift+click on the scroll bar goes to that location rather than page down.

**Comment by DaveInCaz** [comment]
The main issue I was reporting is solved, so I'll close this. Thanks for the help & input.
