### ISSUE TITLE
Error loading form

### ISSUE THREAD

**Issue by KemoHena** [twinbasic/twinbasic#1916]
See this video

https://github.com/user-attachments/assets/ebbffde1-82dc-447a-8a2d-2d940460db08

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. beta 621]

**Comment by WaynePhillipsEA** [comment]
There are a lot of compilation errors (red) that you need to look at.  First, check the project references to make sure there are no problems there. 

It looks like many of the compilation errors are 'Unrecognized symbol XYZ' ... which makes me think you'll be needing to turn OFF the 'Option Explicit' option when you import the VBP.

**Comment by KemoHena** [comment]
Now work after Turn OFF the 'Option Explicit'
Thank you

**Comment by WaynePhillipsEA** [comment]
Great.  Thanks for confirming.  I'll close this then.
