### ISSUE TITLE
BUG Report: RichClient form still visible and no continue option after breakpoint encountered

### ISSUE THREAD

**Issue by yereverluvinunclebert** [twinbasic/twinbasic#1941]
When running an RC form and a debug breakpoint is encountered within a subroutine any where in the code, if a code change is made there appears to be no way to continue as per VB6 (F5). The whole code run has stopped.  In addition, and unexpectedly, the RC form is still present and visible and does not close. It cannot be interacted with. The END and BREAK options are greyed out and the START button is available. Does not feel quite right. I have to close the IDE and restart every time. Not a friendly workflow. Probably caused by a failure to stop all the running aspects of the program including code running within the RC6 DLLs.

**Comment by fafalone** [comment]
The debug log should have indicated it but edit and continue is not supported yet 

Not sure what happened with that; we got some previews indicating it was coming short after the last major release pause between 423 and 424 but still no :(

**Comment by yereverluvinunclebert** [comment]
Understood. More importantly though is that during the execution abort, the execution of parts of the program is not fully terminated, leaving the graphical elements of RC on screen whist RC continues to pump the visual to the RC form. The only way out is to terminate the IDE.  We'll have to wait for a later iteration and assume that the whole proces improves. 

For the moment I am debugging in the VB6 IDE.

**Comment by WaynePhillipsEA** [comment]
Yes, it is known that Stop/end is not 100% functional yet.   Rather than terminate the whole IDE, you should be able to use the "restart the compiler" button (just to the right of the target build architecture drop down on the IDE toolbar)

**Comment by fafalone** [comment]
Did you try restarting the compiler? Shouldn't need to restart the IDE very often, especially for runtime issues.

![image](https://github.com/user-attachments/assets/c5079c98-e46b-4b9d-9880-bfd54126c34b)

**Comment by WaynePhillipsEA** [comment]
Just to clarify;  in twinBASIC, the compiler/debugger runs as a separate process to the IDE, and so indeed it is rare to need a full IDE shutdown and restart as the restart-compiler button is much quicker and just as effective 99% of the time.

**Comment by yereverluvinunclebert** [comment]
I am now familiar with the TwinBasic IDE and realise that remnants of the RC6 form sstill displayed can be ended using the compiler restart button.

**Comment by yereverluvinunclebert** [comment]
Closed
