### ISSUE TITLE
 Feature request - As per VB6 IDE - forms, classes and modules categorised by traditional type in VB6 project explorer

### ISSUE THREAD

**Issue by yereverluvinunclebert** [twinbasic/twinbasic#1949]
Having forms, classes and modules categorised by traditional type in VB6 project explorer, that is very convenient for me and it really helps being able to find the form, module or class by looking with my very old eyes in the right direction. At the moment I have to peer to find the one I am looking for and the process never fails to confuse me as they aren't where I expect them to be.

**Comment by WaynePhillipsEA** [comment]
![tbObjectView1](https://github.com/user-attachments/assets/eb4feae5-6c53-4573-8c5f-c5cb681b448a)

Try switching to object view.  It's experimental, but is probably closer to what you want.

**Comment by yereverluvinunclebert** [comment]
That's fine. that's perfect, I swear I pressed that earlier but nothing happened, otherwise I would not have raised the issue at all, perhaps the IDE was in a funny state, I was experimenting with a lot simultaneously. Anyway, very good, thanks!

**Comment by yereverluvinunclebert** [comment]
Done and dusted.
