### ISSUE TITLE
Best way to distribute a DLL library reference?

### ISSUE THREAD

**Issue by b-gonzalez** [twinbasic/twinbasic#1957]
I've created a library in VBA. I was able to import the .bas and .cls files into a TwinBasic project, create a DLL (64-bit), and run the code using the DLL. I then tried running the DLL on a different computer and it did not work. I got a 'class not registered' error. When I try to open the TwinBasic project without admin privileges, I get a notification about the project registering itself to HKEY_LOCAL_MACHINE. And since it's not running elevated, the registration of the DLL will fail. So I'm assuming that by not generating the DLL in TwinBasic on the computer I want to use it on, it is not registered. And that is the reason for the error.

Is there an easy way to register a DLL on a computer that it is not registered on e.g. using an installer? Or is there some other workaround / process that I should be considering?

Thanks!

**Comment by fafalone** [comment]
You'd use regsvr32 (in \Windows\System32) to register ActiveX DLLs. Some install creator programs have options to do that automatically but you can just manually enter it in a command prompt. Just need to run it with the path to the DLL; in an admin prompt if it's configured to register to HKLM, though that's only necessary for VB6; VBA will look in HKCU too.

**Comment by b-gonzalez** [comment]
Okay great. Thank you. I was able to get this working. And I will write a PowerShell script to automate this in the future.
