### ISSUE TITLE
Memory locked

### ISSUE THREAD

**Issue by cristianbuse** [twinbasic/twinbasic#1967]
**Describe the bug**
Run-time error -2147352563 (8002000D) - memory is locked

**To Reproduce**
```
Sub Main()
    Dim v As Variant
    
    For Each v In Array(1, 2, 3)
        Debug.Print v
    Next v
End Sub
```

**Expected behavior**
Code loops the array and prints 1, 2, 3 in the DEBUG CONSOLE

**Screenshots**
![image](https://github.com/user-attachments/assets/dcfd7148-ed7f-43dd-b3a2-06f37fe587a7)

**Comment by GCuser99** [comment]
same as [here](https://github.com/twinbasic/twinbasic/issues/1936) 😁

**Comment by cristianbuse** [comment]
Sorry for opening, did not check for existing issues first.
