### ISSUE TITLE
Unable to start twinbasic

### ISSUE THREAD

**Issue by mojear** [twinbasic/twinbasic#1973]
**Describe the bug**
Unable to start twinbasic

**Expected behavior**
When I click the shortcut icon, the IDE cannot be started and nothing is displayed, see the picture.

**Screenshots**
![2024-12-22 20 45 54](https://github.com/user-attachments/assets/194d948f-4c6f-4a5b-819c-1d5f9c64c43f)

**Desktop:**
 - OS: Windows 10 19045.5247
 - twinBASIC compiler version [twinBASIC BETA 622]

**Additional context**
After restarting the computer, Twinbasic still cannot be started.

**Comment by WaynePhillipsEA** [comment]
Start afresh.   Unzip the IDE ZIP file to a new location (not overwriting an existing folder), and try launching from the new location.
