### ISSUE TITLE
failed to open ide in 64-bit mode on windows 7

### ISSUE THREAD

**Issue by fxl447098457** [twinbasic/twinbasic#1975]
**Describe the bug**
failed to open ide in 64-bit mode but it's ok  in 32-bit mode .
twinbasic version:623.
os version:windows 7

**Screenshots**
![IVDEDE$0LR8S`B4N~LRIB_F](https://github.com/user-attachments/assets/c14a9021-0c4e-4f61-a469-595001183a72)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 627, thanks
