### ISSUE TITLE
Allow VS Code to open twinproj files directly

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#20]
**Describe the solution you'd like**
The twinBASIC VS code extension should allow opening of .twinproj files directly.   If the corresponding code-workspace file exists, that should be opened, and if the code-workspace file doesn't exist, a default one should be created.

**Additional context**
This will allow developers to share .twinproj files as a single file, rather than having to also share the code-workspace file.

**Comment by A9G-Data-Droid** [comment]
I just cloned a project where I can't load the code-workspace like in #273 except nothing is loaded at all.
I wish I could just open the project instead as I'm not sure how to fix the code-workspace.

**Comment by bclothier** [comment]
I think we can close this old issue since that the current IDE now take a command line to open a file, and we already have issue #1003 which converts the remaining cases.
