### ISSUE TITLE
After copy\paste I'm stuck in a "bad file format Invalid header > here 1 failed" loop

### ISSUE THREAD

**Issue by A9G-Data-Droid** [twinbasic/twinbasic#258]
**Describe the bug**
I cut a code block including a comment, a private backer, and a public getter function from one file. Then I pasted it in to a different file that was also open in VSCode\tB. VSCode got hung and eventually asked me if I wanted to kill and start over, which I did. There were some errors at the bottom about `"Failed to save 'filename.bas': Unable to write file (Unavailable (FileSystemError))"`

Now I can't work on this project at all. Every time I open it I get stuck in this "bad file format Invalid header > here 1 failed" loop. The two msgboxes I show below pop up back and forth. TwinBasic shows `"Not Connected [LSP, DAP, FS]"`. Game Over.

**To Reproduce**
1. Open a project with multiple files
2. Open all the files in different tabs
3. Cut a code block from one file with CTRL+X (It was 6 lines)
4. Paste it at the top of a different file with CTRL+V

**Expected behavior**
I would expect the newly pasted code to be parsed and colored. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26984068/124333294-9a6e9a00-db48-11eb-9f66-5a4f2980dab4.png)
![image](https://user-images.githubusercontent.com/26984068/124333314-a5c1c580-db48-11eb-9c1a-7cd04bc233c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Visual Studio Code Version: 1.57.1
 - twinBASIC compiler version: v0.10.3377

**Comment by A9G-Data-Droid** [comment]
UPDATE: 
It seems that the `WorkSpace.twinproj` file was sized 0. Totally empty. All the files were still visible in VSCode but for some reason it couldn't save them out to the .twinproj file. I had to start over from a backup.

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.   I've opened #259 and #260 in response to this.

Unfortunately I wasn't able to reproduce the problem.   In terms of the actual copy & paste operation, the compiler process doesn't get involved in that, but does of course reparse the code at the end point which potentially could've triggered something that put the compiler process in a bad state.  Or with VS code getting frozen, I guess something might've gone wrong inside VS code.  VS Code does that actual saving of the .twinproj file for us.

Shooting in the dark.... I don't suppose it's possible that there was a real disk error at the time, such as disk full? (either on the disk where the .twinproj file is stored, or the disk where the Windows temp folder is stored)

**Comment by A9G-Data-Droid** [comment]
@WaynePhillipsEA I was working from a network location. It could have temporarily been unavailable. I did not observe the remote disk disconnecting. Windows did not report the location down.

**Comment by WaynePhillipsEA** [comment]
With no recent reports of such a problem, I'm now going to close this.  Thanks.
