### ISSUE TITLE
vbSrcCopy constant not available in twinBASIC

### ISSUE THREAD

**Issue by dmrvb** [twinbasic/twinbasic#320]
**Describe the bug**
Reference to vbSrcCopy gives error "unrecognised symbol" in twinBASIC but works in VB6.

I suspect other inbuilt VB6 constants are also missing???.

This is a small issue but needs fixing for 100% compatibility.
An alternative would be for somebody to produce a module of VB constants when full compatibility is required.

win 10
twinBasic 3697

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.

None of the VBRUN type library constants/enumerations are yet included in twinBASIC as they mostly relate to forms.  They will be added once work is started on the VB6-compatible forms.  I'll leave this issue open for tracking purposes.

**Comment by fafalone** [comment]
Cleanup - vbSrcCopy and other constants have been available now for some time.
