### ISSUE TITLE
Unsupported special syntax for IVBPrint / Circle / Line / PSet / PaintPicture

### ISSUE THREAD

**Issue by EduardoVB** [twinbasic/twinbasic#324]
**A little background**
I'm testing BSPrinter available [here](http://www.balkesoft.com/bsprinter/).

The twinBASIC references needs OLE automation, Visual Basic objects and procedures (for the VB.Printer interface) and Balkesoft BSPrinter.

![imagen](https://user-images.githubusercontent.com/42319299/127792923-96b75995-9557-4a5d-960b-e1112a0a1f56.png)

This is the test code:

```
Module MainModule

    ' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
    Public Sub Main()
        Printer.Print "Testing"
        Printer.Circle (1000, 1000), 500
        Printer.Line (1500, 1500) -(1900, 1900) ,&HFF0000 , BF   ' &HFF0000 = vbBlue
        Printer.DrawWidth = 20
        Printer.PSet (2000, 2000), &HFF ' &HFF = vbRed
        Printer.PaintPicture LoadPicture("D:\test.bmp"), 0, 2500
        Printer.CurrentY = 3000
        PrintPreview.PrintEx "Test 2"
        PrintPreview.PrintDirect
    End Sub

    Public Property Get Printer() As Printer
        Set Printer = PrinterReplacement
    End Property
    
    Public Property Set Printer(nPrinter As Printer)
        Set PrinterReplacement = nPrinter
    End Property
End Module
```

Note: Printer and PrintPreview are actually the same object (same class and same instance)  from different interfaces.

**Describe the bug**
They seem to be several different issues.

1) Print pseudo-method not recognized.
2) Circle, Line and PSet weird VB syntax (different handle of parameters) not recognized (not automatically handled).
3) VB6's PaintPicture method is seen like with all parameters as required when the first three are only actually required.
4) Even the smalles code:

```
        PrintPreview.PrintEx "Test 2"
        PrintPreview.PrintDirect
```

does not work, it raises an error:

![imagen](https://user-images.githubusercontent.com/42319299/127793463-dbcab8b3-f916-4445-82f9-f66dfb37e12b.png)

**To Reproduce**
Download and install (or at least register the ocx) BSPrinter from [here](https://www.balkesoft.com/bsprinter/download.html).

Create a new tB project and set the references as shown above, and then paste the code from above.
Or use th tB project file instead: 
[BSPrinter twinBASIC test 1.zip](https://github.com/WaynePhillipsEA/twinbasic/files/6913894/BSPrinter.twinBASIC.test.1.zip)

**To Goal**
The idea is to quickly be able to offer printing in tB, even with print preview capability (but this would be limited to Windows projects only, because it relies on Windows APIs).
Also, the Printer interface could be added to BSPrinter for not needing to reference VB6's DLL.

**Comment by WaynePhillipsEA** [comment]
I'll leave the IVPPrint related things just for now as they require grammar changes, but I'll take a look at the PrintEx runtime error initially and come back to the IVBPrint stuff in a few weeks.

**Comment by WaynePhillipsEA** [comment]
So the runtime errors are fixed by settin the 'Project: COM Threading Model' to 'Single Threaded Apartment' in your Settings file.

**Comment by WaynePhillipsEA** [comment]
>VB6's PaintPicture method is seen like with all parameters as required when the first three are only actually required.

There's lots of special casing in VB6 for the drawing methods. For example, the PaintPicture method is defined in the type library with no optional values:

[id(0x00020005), helpstring("Draws the contents of a graphics file on a Form, PictureBox, or Printer object."), helpcontext(0x000dfa9d)]
        void PaintPicture(
                        [in] Picture* Picture, 
                        [in] single X1, 
                        [in] single Y1, 
                        [in] VARIANT Width1, 
                        [in] VARIANT Height1, 
                        [in] VARIANT X2, 
                        [in] VARIANT Y2, 
                        [in] VARIANT Width2, 
                        [in] VARIANT Height2, 
                        [in] VARIANT Opcode);

Yet, as you rightly point out, VB6 sees the VARIANTs as optional in the IDE.

**Comment by EduardoVB** [comment]
> So the runtime errors are fixed by changing the 'Project: COM Threading Model' to 'Single Threaded Apartment' in your Settings file.

I don't understand what is behind this, but that worked!
I was able to print a page.

All the "demo" stuff appears, I'll see what to do about that.
Thank you.

**Comment by WaynePhillipsEA** [comment]
I noticed the intellisense wasn't working for the PrintPreview object in the BSPrinter typelibrary.  That is now fixed in v0.10.3881.

**Comment by EduardoVB** [comment]
Some additional information that might be useful:

**[Circle method](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa230478(v=vs.60)) syntax:**

`object.Circle [Step] (x, y), radius, [color, start, end, aspect]`

translates to:

`object.Circle(ByVal Flags As Integer, ByVal X As Single, ByVal Y As Single, ByVal Radius As Single, ByVal Color As Long, ByVal StartArc As Single, ByVal EndArc As Single, ByVal Aspect As Single)`

The optional Step keyword in the original means that the X and Y are relative to the current position, if Step is not specifies, then X and Y are absolute.
Step is the word 'Step', literal.

Examples:

```
object.Circle (2000, 2000), 1000

```
equals to:

```
object.CurrentX = 500
object.CurrentY = 500
object.Circle Step(1500, 1500), 1000
```

How to convert from one syntax to the other?

The Flags parameter in the resulting syntax must have these flags:

```
1 -->   (2 ^ 0) Step was specified.
2 -->   (2 ^ 1) Color was specified
64 -->  (2 ^ 6) StartArc was specified
128 --> (2 ^ 7) EndArc was specified
256 --> (2 ^ 8) Aspect was specified

```

Flags 2, 3, 4, and 5 seem not to be used.


**[Line method](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa230480(v=vs.60)) syntax:**

`object.Line [Step] (x1, y1) [Step] - (x2, y2), [color], [B][F]`

translates to:

`object.Line(ByVal Flags As Integer, ByVal X1 As Single, ByVal Y1 As Single, ByVal X2 As Single, ByVal Y2 As Single, ByVal Color As Long)`

Flags:
```
1 -->   (2 ^ 0) First Step was specified
2 -->   (2 ^ 1) Color was specified
4 -->   (2 ^ 2) First coordinates were specified
8 -->   (2 ^ 3) Second Step was specified
16 -->  (2 ^ 4) B - flag (box, must draw a rectangle, not a line)
32 -->  (2 ^ 5) BF - flag (box filled, must draw a colored rectangle)
```


**[PSet method](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa230482(v=vs.60)) syntax**

`object.PSet [Step] (x, y), [color]`

translates to:

`PSet(ByVal Flags As Integer, ByVal X As Single, ByVal Y As Single, ByVal Color As Long)`

Flags:
```
1 -->   (2 ^ 0) Step was specified.
2 -->   (2 ^ 1) Color was specified
```


**[PaintPicture method](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/aa244140(v=vs.60)) syntax**

`object.PaintPicture picture, x1, y1, [width1, height1, x2, y2, width2, height2, opcode]`

From the fourth, parameters are optional.

**Comment by WaynePhillipsEA** [comment]
@EduardoVB, most helpful, thanks.

**Comment by mansellan** [comment]
FWIW these were a PITA for Rubberduck too, took several issues before we got the parsing correct iirc

**Comment by WaynePhillipsEA** [comment]
The special syntax for these are all now supported as of BETA 120.  Thanks!
