### ISSUE TITLE
VS code extension uncaught JS errors

### ISSUE THREAD

**Issue by uwbwsvd** [twinbasic/twinbasic#331]
![grafik](https://user-images.githubusercontent.com/41230018/128483363-a486c26e-c50d-4af3-a149-9769e133cad7.png)
twinBASIC 10.2930
VS-Code: 1.59.0

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  I hadn't noticed that VS code now monitors uncaught JS errors.

**Comment by WaynePhillipsEA** [comment]
As this was a VS code specific issue, and it looks increasingly unlikely that we'll return to use VS Code in the near future, it's time to close this one. Thanks.
