### ISSUE TITLE
"As New" arrays not supported

### ISSUE THREAD

**Issue by wqweto** [twinbasic/twinbasic#336]
**Describe the bug**

Following declaration does not compile
```
Private MyArray() As New Collection
```
This auto-instatiates the members upon access if not already set.

[Here](https://www.vbforums.com/showthread.php?892884-How-do-I-properly-exit-a-For-Next-loop-that-contains-a-With-block&p=5531281&viewfull=1#post5531281) is a thread with callsite bugs/problems VB6 has with locking such arrays.

**Desktop:**

 - OS: Win10
 - twinBASIC compiler version: 0.10.3988

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  Support for this was overlooked.

Looks like VBx support for this is a mess; thanks for the link.

**Comment by WaynePhillipsEA** [comment]
This should now be fixed in v0.10.4030.  However, we have insufficient test coverage on this, so there may be a few edge cases.  I'll leave this open until test coverage is improved.

**Comment by wqweto** [comment]
Btw, just notices a minor glitch testing this: `Private Sub Main` in a BAS module works fine as a startup routine in VB6 while in TB errors with

```
(compile error: [TestModule] does not contain 'Main', or it is inaccessible in this context)
```

**Comment by Kr00l** [comment]
Having a As New fixed array works in tB (like in VBx) but the compiler often disconnects and even crashes.

Having just the simple example below in a brand new project (win32). Can you repro ?
`Dim NewArray(0 To 1) As New StdPicture`

![image](https://user-images.githubusercontent.com/33756666/151753432-f1534807-269f-45ac-862b-dab8bdea4ed5.png)

Also having a WithEvents As New will throw below error.
![image](https://user-images.githubusercontent.com/33756666/151753777-92a05848-9357-43fd-b122-eea710a96739.png)

But declaring it as an array throws no error and it works. But is that intended and how to catch the events ?

**Comment by EduardoVB** [comment]
> Also having a WithEvents As New will throw below error.

In VBx `WithEvents` along with `As New` is not allowed either.

**Comment by Kr00l** [comment]
> > Also having a WithEvents As New will throw below error.
> 
> In VBx `WithEvents` along with `As New` is not allowed either.

Yes I know. I wanted to point out that it correctly throws out an error but the array version will not, but it should also.

**Comment by EduardoVB** [comment]
I supposed you knew, but not sure what the point was about.
When in doubt, I posted the message.

**Comment by wqweto** [comment]
Btw, TB supports `Private WithEvents MyArray() As MyClass` apparently, currently used as a cheap way to emulate control arrays.

Unfortunately in `MyArray_Click` event you don't get the array index raising it -- the events are "anonymous" and cannot discern the origin element.

This will probably evolve, I'm not sure such `WithEvents` implementation for arrays is "official" in TB.

**Comment by WaynePhillipsEA** [comment]
Various edge cases in this area have been fixed during the BETA phase, so let's close this now.  Thanks all.

**Comment by WaynePhillipsEA** [comment]
@wqweto   I expect Index support to land before v1 on that feature.
