### ISSUE TITLE
Static bookmarks

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#340]
**Is your feature request related to a problem?**
Not a real problem, but a wish since decades.

**Describe the solution you'd like**
I would like to see bookmarks stored along with the project, and restored on load.

**Describe alternatives you've considered**
I tried a bookmark manager from the marketplace, but couldn't get one working with tB.

**Additional context**
In the VS docs Ctrl K K is mentioned to set a bookmark, but that's unknown when using tB.

**Comment by WaynePhillipsEA** [comment]
It shouldn't be too hard to get this VS Code extension to work with tB:
     https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks

A quick debug of the 'bookmarks.toggle' command from there extension shows that they are having trouble with the multiple virtual filesystems that tB uses.  

tB uses two virtual filesystems;  one for the BUILD CONFIGURATIONS, and one for the PROJECT.  The bookmark extension is trying to refer to the active source code document inside our BUILD CONFIGURATIONS filesystem (twinbasic-builds:/...) which is invalid (it should be twinbasic:/...).  If I get chance, I'll open up an issue on there repository soon with further information.

**Comment by WaynePhillipsEA** [comment]
I've opened the issue over on their repository:  https://github.com/alefragnani/vscode-bookmarks/issues/458

Hopefully they'll fix it and then the two extensions should work together.

**Comment by KarlSevenSeven** [comment]
Apparently they don't fix it.
Do you have some other recommendation to get the bookmarks functionality?

**Comment by KarlSevenSeven** [comment]
I feel you can close this.
In the new IDE there will be your own system, or?

**Comment by WaynePhillipsEA** [comment]
Bookmarks have been supported in the IDE for a while now, so time to close this.  Thanks
