### ISSUE TITLE
MsgBox and 4K

### ISSUE THREAD

**Issue by Machmer** [twinbasic/twinbasic#380]
The MsgBox Dialog Box doesn't show the bottom line by 4K Resolutions.

![grafik](https://user-images.githubusercontent.com/89376688/130400661-7a1f0276-bf5d-4118-94e1-a23121dc77f8.png)

**Comment by Kr00l** [comment]
I guess it's DPI..

The tB manifest has no dpi aware flag set.
So, everything is blurry bitmap scaled by the OS.
Do you have 1 or more monitors?
Which dpi have each of those monitors?

There are 3 types of dpi awareness:
1. Default none, all bitmap scaled.
2. System dpi awarenes. (Primary monitor ok, each different monitor bitmap scaled)
3. Per monitor dpi aware. (Hard to implement, not seen in VB6 yet..)

You can try and edit the manifest to try option 2 and set your 4k monitor as the system dpi.
```
    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
        </windowsSettings>
    </application>
```

**Comment by Machmer** [comment]
1 monitor with 4K (3840 x 2160) and 150% Scale factor.
No improvments with the manifest.
Without Scaling all is fine, but I guess nobody will work with 100% and 4K (its to small).
Perhaps you will find a solution in the next updates.
If you want I can check it for you.

**Comment by Kr00l** [comment]
Ok, other way around.
Do you have the same issue on a VB6 generated MsgBox ?

**Comment by Machmer** [comment]
I have not been able to test this yet. But regardless, tb should fully support 4K. 4K is the standard and VB6 is no longer the reference. I think tb should be more modern und perhaps the replacement of VBA.

**Comment by Kr00l** [comment]
> I have not been able to test this yet. But regardless, tb should fully support 4K. 4K is the standard and VB6 is no longer the reference. I think tb should be more modern und perhaps the replacement of VBA.

tB calls the MessageBox API just like VB6. I think there is no "fault" on tB.

**Comment by WaynePhillipsEA** [comment]
I've not seen any other reports of problems like this, and so I believe this must've been an isolated issue.  Time to close.  Thanks.
