### ISSUE TITLE
TypeLib LPWSTR coercing

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#381]
**Describe the bug**
Any LPWSTR signature in a TypeLib is declared as {unsupported} in tB.
However, VB6 just recognises these 'As String' and is able to coerce from BSTR to LPWSTR.

**To Reproduce**
I have a .tlb with following declarations:
```
]
interface IDispatch : IUnknown
{
	typedef IDispatch *LPDISPATCH;
	HRESULT GetTypeInfoCount([out] LONG *pctInfo);
    	HRESULT GetTypeInfo([in] LONG itinfo, [in] LONG lcid, [out] LONG *pptinfo);
    	HRESULT GetIDsOfNames([in] REFIID riid, [in] LPWSTR *rgszNames, [in] LONG cNames, [in] LONG lcid, [in, out] LONG *rgDispID);
    	HRESULT Invoke([in] LONG DispIDMember, [in] REFIID riid, [in] LONG lcid, [in] SHORT wFlags, [in] DISPPARAMS *pdispparams, [in, out] VARIANT *pvarResult, [out] EXCEPINFO *pexcepinfo, [out] LONG *puArgErr);
};
```

To note is the `[in] LPWSTR *rgszNames` signature.

**Expected behavior**
Support of LPWSTR as string and be able to coerce.

**Screenshots**
tB
![image](https://user-images.githubusercontent.com/33756666/130417971-75a37696-f917-4cec-b40a-56b80d889dec.png)

VB6
![image](https://user-images.githubusercontent.com/33756666/130418437-1142c7a8-e7bd-4b95-9b4e-086f79da019e.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.4756]

**Additional context**
A declaration without asterisk shall also work, e.g. `[in] LPWSTR pszObjName` (used in IOleInPlaceUIWindow::SetActiveObject)

**Comment by Kr00l** [comment]
The same with LPSTR (single byte ANSI)
tB says it's unsupported. It shall be allowed like in VBx. I think there is **no** auto conversion from BSTR unicode to LPSTR ANSI (like for ANSI API calls), so the app needs to pre-convert via StrConv vbFromUnicode on their own. But I'm not 100% sure..

LPWSTR is no conversion needed by the app, just pass 1:1 the BSTR.

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l, I'll get the supported.

**Comment by WaynePhillipsEA** [comment]
Now supported, as of v0.13.32, thanks for reporting

**Comment by Kr00l** [comment]
I shortly open, but you can close again if you think not appropriate.

I want to bundle the OLEGuids.tlb into a OLEGuids TwinPackage.

The problem is in tB I cannot make an interface as `[in] LPWSTR *rgszNames`. I have to change to `ByVal rgszNames As LongPtr`
That is working for the package. However, I now run into a compatibility issue.

Question: Any way to allow this in tB or must I update the tlb (for VB6 and intermediary period) to `[in] LONG rgszNames` that I can pass it via StrPtr() in both worlds.

**Comment by WaynePhillipsEA** [comment]
If you're only calling the method, and not implementing it, you can safely define it as an ordinary String (BSTR).

**Comment by Kr00l** [comment]
Yes for now LongPtr and StrPtr() are fine for testing in tB.
Will close again and there are other issues and this would require in fact add. String datatypes which would be an overkill, at least for now.

**Comment by Kr00l** [comment]
I will replace all LPSTR and LPWSTR to LONG in my old OLEGuids.tlb so that the code base in VB6 and tB will be the same. (StrPtr())
This makes the transition between both worlds easier in future. (OLEguids.tlb and tB OLEGuids twin package)
