### ISSUE TITLE
Form min/max

### ISSUE THREAD

**Issue by EduardoVB** [twinbasic/twinbasic#40]
**Is your feature request related to a problem? Please describe.**
The ability to set minimum and maximum width and height of forms without having to resort to subclassing.

**Describe the solution you'd like**
The most straightforward way would be to add four ptoperties: MinWidth/MaxWidth/MinHeight/MaxHeight

**Describe alternatives you've considered**
Another way could be a method: 
Form.SetMinMax or simply Form.MinMax with the four parameters, all optional.
If a argument is not supplied it leaves the current setting for that min/max setting, if a argument is 0 it returns to unset (does not control that min or max).

The advantage of using a method instead of property would be not to pollute the property window with so many new properties. Or they could be in a property page instead of the property window.
Anyway, it could have both options, properties and method (like the Move method, or Scale method).

**Additional context**
VB6 was lacking of this very necessary feature.

**Comment by fafalone** [comment]
Feature added a while back.
