### ISSUE TITLE
VBA.DateTime properties

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#421]
**Is your feature request related to a problem? Please describe.**
The following VBA.DateTime members are defined as functions in tB.
```
Calendar
Date
Date$
Time
Time$
```
However, in VBx these are properties (get and let)

**Describe the solution you'd like**
For full compatibility it might be necessary to change these to a property.
However, those properties require admin privilege's (Let only). Otherwise VBx throws an error 70 Permission Denied.
They require admin privilege's as they change the system date/time.

**Describe alternatives you've considered**
Keep as functions in tB and encourage people to make API calls to change locale date/time. (which may not require admin privilege's)

**Additional context**
The following members are also properties, though they are read-only. So it might be applicable to change them from function to property (get only).
```
Now
Timer
```

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l, yes I've got these in my TODOs to implement them.  I very much dislike the property-lets here.. but we've really got to honour them for the backwards compatibility (perhaps with a warning).

**Comment by WaynePhillipsEA** [comment]
`Date` / `Date$` / `Time` / `Time$` property-let implementations are now available as of BETA 234.

**Comment by bclothier** [comment]
Do we have a warning flag for those? I also dislike the behavior of assigning to those properties and would want to flag accidental usage.

**Comment by WaynePhillipsEA** [comment]
Use of the Date/Time property-lets now produces a warning of TB0011 as of BETA 235

**Comment by mburns08109** [comment]
So, does this mean that my Now(optional Timezone as 'WhateverIsAppropriateHere') enhancement request is doomed?
