### ISSUE TITLE
Single-line If..Then..Else problem with Call keyword and Else branch

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#423]
**Describe the bug**
the below code gives a problem in the Else branch.

**To Reproduce**
```
Public Sub Main()
    Dim Bar As Long
    If 1 > 0 Then Call Foo() Else Bar = 1
End Sub

Private Sub Foo()
End Sub
```

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/132482021-a35403d5-13ac-4b05-aa75-57b08e83ef30.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5725]

**Additional context**
Removing the `Call` resolves it.
![image](https://user-images.githubusercontent.com/33756666/132482101-c3f214d3-c992-43d8-af0a-a1dca9bef4ed.png)

**Comment by fafalone** [comment]
Cleanup - No longer an error in design or run.
