### ISSUE TITLE
Collection Key performance (HashList)

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#428]
**Describe the bug**
I don't know if the VBA.Collection is in a finished or interim state.
But compared to VBx the HashList performance difference is huge.

**To Reproduce**
```
Public Sub Main()
    
    Const TestEntryCount& = 30000&
    Dim i&, T!, C As Collection
    Set C = New Collection
    T = Timer
    
    For i = 1 To TestEntryCount
        C.Add i, "K" & i
    Next i
    
    Debug.Print "Collection-Add:", Timer - T & " sec"
    Dim Item As Variant
    
    T = Timer
    For i = 1 To TestEntryCount
        Item = C.Item("K" & i)
    Next i
    Debug.Print "Collection-ItemByKey:", Timer - T & " sec"
    
End Sub
```

**Expected behavior**
Above code running uncompiled in VB6 IDE or in the VS Code IDE gives me following results:

VB6
Collection-Add:             0.1484375 sec
Collection-ItemByKey:       5.859375E-02 sec

tB
Collection-Add:              15.9707 sec
Collection-ItemByKey:        15.71484 sec

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.10.5788]

**Additional context**
n/a

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l.  It's currently implemented as a naive linked list rather than a hash list, hence the significant performance difference.  It is on my TODO list.  I'll try to get to it this week.

**Comment by Kr00l** [comment]
Here is a thread by Olaf Schmidt (vbRichClient) at vbForums which is a faster HashList than the VBx equivalent and being compatible.
[Simple and fast, lightweight HashList-Class (no APIs)](https://www.vbforums.com/showthread.php?834515-Simple-and-fast-lightweight-HashList-Class-(no-APIs))

**Comment by WaynePhillipsEA** [comment]
Yup, hopefully I'll get to that this month.

**Comment by WaynePhillipsEA** [comment]
This has been fixed in the latest releases of tB.  Thanks!
