### ISSUE TITLE
twinBasic extension is not found by VS Codium

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#430]
**Describe the bug**
As a trial I installed VS Codium to see what difference there is from MS VS Code.  VS Codium did not list twinbasic in the extensions menu
![NoTwinBasic](https://user-images.githubusercontent.com/81257042/133311050-200619be-1618-4217-b211-78b1048a223b.jpg)

WIndows 10
VS Codium  1.60.0

**Comment by WaynePhillipsEA** [comment]
Apparently VS Codium uses a different extension marketplace, https://open-vsx.org/, and we haven't registered twinBASIC there yet.

So for now you'd have to use the 'Download Extension' link on the following page (right side): https://marketplace.visualstudio.com/items?itemName=twinbasic.twinbasic

That will give you the VSIX installation file, and you should be able to open that VSIX file inside VS Codium to install it.  Hopefully...

**Comment by bclothier** [comment]
Because VS Code extension is currently paused, I think we can just close this and revisit if there's actual interest in using it in VS Codium.
