### ISSUE TITLE
Breakpoints getting reinstated unexpectedly

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#435]
**Describe the bug**
I'm seeing two cases of breakpoints being resurrected after being removed from a project.  The first case occurs when breakpoints are removed, Code in a project is run using "run procedure under cursor" which crashes.  Debugging is quitted by 'Stop debugging'.  Presto the removed breakpoints are back.

The second case is when breakpoints are removed and VSCode is then quitted using the  cross in the top right corner of the VSCode window.  Reopening VSCode reinstates the project along with the removed breakpoint.

Its not a killer problem but after a while it does become quite irritating.

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - twinBASIC compiler version [v0.10.5788]

**Comment by WaynePhillipsEA** [comment]
As this relates to the old VS Code plugin, and with no such reports on the newer IDE, it's time to close this.  Thanks.
