### ISSUE TITLE
Line number portability

### ISSUE THREAD

**Issue by madeinaus** [twinbasic/twinbasic#473]
**Describe the bug**
TB line numbers not portable to VBA

I don't think it's a deal breaker, because I'm not porting TB code to VBA, but just to note that the VBA I use doesn't accept 64 bit line numbers.  Somewhere along the line, we had to convert all our 64 bit line numbers to 16 bit, with the line numbers duplicated in different modules.  This meant that we could no longer use line numbers that were unique over the entire project. (We used line numbers for automatic error reporting.  Having each code line identified by a unique/primary key, which is preserved over code changes, is a good thing). 

In practice user-reports enabled us to identify modules where errors occurred (from unexpected data values), so there was no major loss, apart from the irritation of having to renumber when going from the good system in early versions of Microsoft Office Basics, to the more limited version used later.   Which will be the problem facing people if they get used to long TB line numbers, and try to port to VBA.

**Comment by wqweto** [comment]
> Having each code line identified by a unique/primary key, which is preserved over code changes, is a good thing

First time I hear anyone doing this. Every other language on the planet identifies (PK) code lines by source file + physical line number (offset) from the start of the source file e.g. `MyFile.cpp:1234`.

This is what you can easily get from PDB debug files for instance without incurring the run-time cost of assigning line-numbers to each and every VBx line of code.

With line numbers there is a hidden assignment (`Erl = 1234`) that is executed at run-time so line numbers do not come for free contrary to PDB approach which do allow mapping call-stack frames to source file + offset line with no performance overhead.

**Comment by WaynePhillipsEA** [comment]
There are lots of new features in tB that will not back-port to VBx, so I don't really see this as a concern.  However, I do appreciate you bringing it to my attention.  I will leave this issue open for now in case any others want to comment.

**Comment by mansellan** [comment]
Linking #65 Legacy Mode

**Comment by WaynePhillipsEA** [comment]
As discussed, I don't believe we need to be concerned about this.  Time to close.  Thanks
