### ISSUE TITLE
Round tripping appears to lead to the introduction of spurious characters at the start of cls and bas files.

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#477]
**Describe the bug**
I am round tripping my extremely dodgy code between twinBasic and VBA using the import and export commands via Mike Wolfs export bat file.

I'm doing this to take ensure I keep to strict VBA and to also take advantage of the (currently) superior code inspections of Rubberduck.

I'm seeing a 4 different cases of spurious characters appearing at the start of files.
1.  Many files affected but can be resolved by reloading the compiler
2. Characters appears when switching between modules and increase in  number each time I switch between modules
3. Just a couple of files affected when opening a workspace.
4. Characters appearing when running the Tester Method in Testing.bas.

If I delete the spurious characters and then close the workspace, then when I reload the workspace they return on any of the Steps below

**To Reproduce**
1. Load the attached project
2. if no spurious characters appear try running Tester in Testing.Bas or switching between modules or closing and reopening the workspace.

**Expected behavior**
No spurious characters

**Screenshots**

Example 1
![SpuriousCharacters1](https://user-images.githubusercontent.com/81257042/137796643-4736bd44-a7e2-448f-bc45-08440c79e2bb.jpg)
Example 2
![SpuriousCharacters2](https://user-images.githubusercontent.com/81257042/137796644-d4073faf-5b82-4d98-bf46-2104379ad96d.jpg)
Spurious characters removed
![Spuriouscharacters3](https://user-images.githubusercontent.com/81257042/137796646-0ae346f0-e24f-4a6d-a89d-75b4d8380a6e.jpg)
Project Closed and reopened
![SpuriousCharacters4](https://user-images.githubusercontent.com/81257042/137796649-88328cf3-209a-4523-968e-58828d8405e8.jpg)
After running Tester
![SpuriousCharacters5](https://user-images.githubusercontent.com/81257042/137796650-5a8ffcf1-5c64-4e5e-827e-a7bcebb62a7b.jpg)
Desktop (please complete the following information):

 - OS: [Windows 11]
 - twinBASIC compiler version [v0.11.99]

**Additional context**
Add any other context about the problem here
[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7368116/VBALib.zip)
.

**Comment by bclothier** [comment]
Just to be sure, you should check that the encoding did not get charged when round tripping. VBx expects the code file to be encoded using system code page. Loading it with utf8 or different encoding can lead to problems.
