### ISSUE TITLE
Enter License Key throws error

### ISSUE THREAD

**Issue by A9G-Data-Droid** [twinbasic/twinbasic#479]
**Describe the bug**
I found the option to enter a license key but it doesn't work.

**To Reproduce**
1. Press `F1`
2. Type `twin`
3. Click `twinBASIC: Enter License Key`

**Expected behavior**
I expected to see the interface for entering a license key.

**Screenshots**
![image](https://user-images.githubusercontent.com/26984068/137845975-586f2657-2763-4e36-b2ed-715f4f588bf5.png)

![image](https://user-images.githubusercontent.com/26984068/137845925-c87e2610-636a-4caa-83ff-bb87d979d4ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version v0.11.99

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  You'll need to open a project in order to use this command.  As of v0.11.114 the command wont appear in the command palette if a twinBASIC project is not loaded.

BTW, just creating or opening a form will trigger the request for the licence key.
