### ISSUE TITLE
Debugging console app does not work

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#48]
**Describe the bug**
Currently, it is not possible to debug a console app. In version 0.9.1602, one can build and run it successfully. However, trying to debug it prevents the console window from appearing, and the stdin/stdout does not get handled (see #47 ), so it will hang.

**To Reproduce**
1. Create a twinBASIC project.
2. Via the settings, mark the project as a console app
3. Define the declares as in #47 
4. Add code to Main():
```
Public Sub Main()
            WriteStdOut "What's Your Name?"
            Dim Response As String = ReadStdIn()
End Sub
```
5. Press F5 to debug. No console window is shown.
6. It will hang on the `ReadStdIn` since there's no way to respond to it.

**Expected behavior**
I see two possible ways to fix this.
1) We can show a console window
2) We can redirect the streams to VSC's debug console. 

The option 2 would be more steamlined but I'm mixed on how it may be presented differently from what I may see in a console window.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 0.9.1602

**Comment by WaynePhillipsEA** [comment]
If we went with [1], the Console window would have be visible all the time during the debug session, which actually starts as soon as the tB project is opened.  So the Console window would suit behind the main VS code window until you need it.     Not sure on that one.

[2] seems more sensible, but I'll have to see what options we have in VS code / Node.js for redirecting the stdin/stdout etc

**Comment by WaynePhillipsEA** [comment]
This has been handled for some time by the IDE displaying the console window alongside the debug session, so I will now close this.  Thanks.
