### ISSUE TITLE
Problems with Overloaded functions

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#532]
**Describe the bug**
I have created a Lyst Class which is a wrapper for the ArrayList object.  I'm expanding the utility of the count method so that I end up with 4 signatures

```
Count() as long - the number of items in the Lyst
Count(Variant) as long - The number of items in the Lyst equal to Variant
Count(Variant,IComparer) as long- the number of items in the Lyst where IComparer is true 
Count(Variant1,IComparer1,Variant2,IComparer2) as long
```
for reference there are 6 comparers cmpEQ,cmpNEQ,cmpMT,cmpLT,cmpMTEQ and cmpLTEQ - the number of items in the Lyst where both IComparer1 and ICOmparer2 are true

I have encountered two issues.

1.  If only the first two signatures are present then Lyst.count calls the code for Lyst.count(Variant)
2.  If either of or both of the last two signatures are present then I get a runtime error

![Overloaderror](https://user-images.githubusercontent.com/81257042/144746907-560c7bf0-0a0a-4fb7-8465-a699a1c76d83.jpg)

**To Reproduce**
In the attached project run the tester method in the testing Module

[TwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7655870/TwinLib64.zip)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - twinBASIC compiler version v0.13.19

**Comment by FullValueRider** [comment]
I've now tried two functions with the signature

```
public function test(long) as boolean
public function test(long, long) as boolean
```
and I'm getting an underline at the call site which gives the error message 'unable to disambiguate between overloaded methods

**Comment by WaynePhillipsEA** [comment]
At the moment, overloads are only supported in early-bound code.   In your screenshot, I can see that myItem is a Variant, so the calls are late-bound.  Late-bound calls (through IDispatch) don't yet have the logic needed for the overload disambiguation at runtime (it's on my TODO list).

**Comment by WaynePhillipsEA** [comment]
> I've now tried two functions with the signature
> 
> ```
> public function test(long) as boolean
> public function test(long, long) as boolean
> ```
> 
> and I'm getting an underline at the call site which gives the error message 'unable to disambiguate between overloaded methods

I'm not seeing that problem in this snippet.  Could you provide a full snippet showing the problem?  Thanks...
```
    Public Sub Main()
        test 5
        test 5, 6
    End Sub
    
    Public Function test(A As Long) As Boolean
        Debug.Print "test(" & A & ")"
    End Function
    
    Public Function test(A As Long, B As Long) As Boolean
        Debug.Print "test(" & A & "," & B & ")"
    End Function
```

```
Executing 'NewProject.MainModule.Main'...
test(5)
test(5,6)
(time taken: 0.0000588s)

```

**Comment by FullValueRider** [comment]
Thanks.  Your code helped me unravel the error I was making.  I has a variant in the call site which should have been a long.  The code below highlight test in Test CVar(5) and has the cannot disambiguate message. Definitely a case 'can't see wood for trees' on my part. 

```
Public Sub Main()
    test CVar(5)
    test 5, 6
End Sub

Public Function test(A As Long) As Boolean
    Debug.Print "test(" & A & ")"
End Function

Public Function test(A As Long, B As Long) As Boolean
    Debug.Print "test(" & A & "," & B & ")"
End Function

```

**Comment by bclothier** [comment]
Closing this as this seems to be solved. Reopen if this is still a problem.
