### ISSUE TITLE
Q: How to debug ActiveX DLL?

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#562]
**Describe the bug**
Results from tB DLL are different from VB6 DLL.

**To Reproduce**
I don't know.

**Expected behavior**
Same result from a tB compiled DLL as from tB compiled DLL.

**Desktop (please complete the following information):**
 - OS: Windows
 - twinBASIC 0.13.31
 -
**Additional context**
I have an older source for an ActiveX DLL.
It is very well tested und unchanged since years.
Built with VB6 it runs fine.
I have a test app that proves it.

I want to have the very same functionality using the identical source, but using tB.

Something goes wrong.
The tB compiled DLL is usable, but the result is different, in this case just no result.
I need to find out the reason.
I don't need to check the data I feed to the DLL, it is exactly the same.
In the test app alone I can't find out what goes wrong, as the DLL only returns a result and no more info.

---

How can I start debugging?
Any hint is welcome.

**Comment by WaynePhillipsEA** [comment]
At this very moment, it's difficult to debug a tB DLL, because you can't attach the debugger to another process (issue #109)

For now you'll probably have to run tests inside the DLL project to try to find out what is wrong.

**Comment by EduardoVB** [comment]
Also a related question is if tB will allow to run project groups, like VB6 does. Where the DLL project and the client consumer project run in source code together. Will it? It is very important for component development.

**Comment by WaynePhillipsEA** [comment]
@EduardoVB yes, this is very much planned

**Comment by mansellan** [comment]
If I recall correctly, support for project groups (`.vbg`) in VB6 was extremely rudimentary. I may be wrong (I last used the feature 20 years ago!) but I vaguely remember having to manually build each project in turn, then mess around with RegSvr32 between each OCX change.

Hopefully tB can do much better here!

**Comment by KarlSevenSeven** [comment]
> At this very moment, I appreciate that it's difficult to debug a tB DLL, because you can't attach the debugger to another process (issue #109)
> 
> For now you'll probably have to run tests inside the DLL project to try to find out what is wrong.

In theory I shouldn't try to debug the ActiveX source.
There is no error in the source that should be fixed.
On the other hand, you can't find out what the problem is.
I think the best is to stop the effort for now.
I'll wait until version 0.5.xxx or so.
Perhaps the error is found by other means.

**Comment by KarlSevenSeven** [comment]
> If I recall correctly, support for project groups (`.vbg`) in VB6 was extremely rudimentary. I may be wrong (I last used the feature 20 years ago!) but I vaguely remember having to manually build each project in turn, then mess around with RegSvr32 between each OCX change.

No, that is quite easy even for me.
No need to register controls.

In the VBP file:
Reference=*\A(Name of the ActiveX project)

This is quite crude syntax.
How should one know that A has to be written?

**Comment by EduardoVB** [comment]
> If I recall correctly, support for project groups (`.vbg`) in VB6 was extremely rudimentary. I may be wrong (I last used the feature 20 years ago!) 

It works very well.

The purpose is to be able to develop, test and debug a component without having to compile it first.

> but I vaguely remember having to manually build each project in turn, then mess around with RegSvr32 between each OCX change.

It used to be smooth until Vista, but now, specially on Windows 10, there are some issues.
It still works fine for simple cases, but when you compile different component versions, you need to manually unregister the old one before compiling the new one, to avoid polluting the registry and having possible problems later.

> Hopefully tB can do much better here!

Yes... but as I say, VB6 works very well regarding to being able to develop, test, etc.
I don't think I used the feature in VB5 or VB4 so IDK how it was before.

What problems did you have?

**Comment by WaynePhillipsEA** [comment]
> > At this very moment, I appreciate that it's difficult to debug a tB DLL, because you can't attach the debugger to another process (issue #109)
> > For now you'll probably have to run tests inside the DLL project to try to find out what is wrong.
> 
> In theory I shouldn't try to debug the ActiveX source. There is no error in the source that should be fixed. On the other hand, you can't find out what the problem is. I think the best is to stop the effort for now. I'll wait until version 0.5.xxx or so. Perhaps the error is found by other means.

Can you give me any hints as to what functions in your library are not returning the expected results?  I'd be happy to debug it further, but would need more detail from you.

**Comment by KarlSevenSeven** [comment]
Wayne, I appreciate your will to find and fix the issue.
But, unfortunately, the conditions to find out are complicated.

The input data for the DLL is some data and some parameters.
The output is a string of data that shows up as a graphical result in the test app.

In fact I have ONE single result only which is there or not.
I can't say or detect which DETAIL is wrong.

Tomorrow I'll try to find out more about the return data.
I'll TRY to make a very stripped down test app that shows the output as readable data.
Tomorrow.

**Comment by WaynePhillipsEA** [comment]
No worries.  If you'd rather wait a while, that's obviously fine as well.  I just didn't want you leaving it on my account, as I'm always eager to quash them bugs!

**Comment by KarlSevenSeven** [comment]
Couldn't wait until tomorrow.
No chance to compare the output data.
The VB6 DLL returns a result data count of e.g. 14, the tB DLL always 0.
If you want, I can send the working test app over to you.
But in fact that's too much to expect from you.

**Comment by WaynePhillipsEA** [comment]
I'm going to close this as I believe the functionality needed is covered by #109. Thanks.
