### ISSUE TITLE
Dialogs like MsgBox sometimes appear behind the VS Code IDE

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#588]
**Describe the bug**
MsgBox and other dialogs sometimes appear _behind_ the VS Code IDE window.

**Expected behavior**
For the dialogs to appear correctly, in front of the IDE window.

**Desktop (please complete the following information):**
 - twinBASIC compiler version 0.13.50

**Additional context**
This has been a known issue since the very first release of twinBASIC, but I don't believe we've had an actual bug report for it.

**Comment by WaynePhillipsEA** [comment]
This should now (finally) be fixed in v0.13.51.    The debugger should now detect when a dialog window is hidden by VS Code , and will step in to bring it to the foreground.  When this happens, you'll see a message notification in the Debug Console:
<img width="457" alt="tbHiddenWindowFix" src="https://user-images.githubusercontent.com/25738109/146930856-ce55eb50-65e2-452b-a910-99d43b495d2c.png">
(this will be removed once we've confirmed the fix is good)

**Comment by AntsAntix** [comment]
This happens(ed) even with the compiled tB executable. I noticed that the File/Printer dialogue ALWAYS opened in the background, but had parked it to investigate it later.

**Comment by EduardoVB** [comment]
Close this VSCode related issue?
