### ISSUE TITLE
Input/InputB functions missing (filesystem)

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#621]
**Describe the bug**
The VBx `Input` and `InputB` functions are not implemented in tB.
[MSDN Input function](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/input-function)

**To Reproduce**
```
Module MainModule

    ' This project type is set to 'Standard EXE' in the Settings file, so you need a Main() subroutine to run when the EXE is started.
    Public Sub Main()
        MsgBox ReadTextFile(_MyFile_)
    End Sub

    Public Function ReadTextFile(ByRef FileName As String) As String
        Dim FNum As Integer, IsOpen As Boolean
        On Error GoTo Error_Handler
        FNum = FreeFile()
        Open FileName For Input As #FNum
        IsOpen = True
        ' Read the entire contents in one single operation
        ReadTextFile = Input(LOF(FNum), FNum)
        ' intentionally flow into the error handler to close the file
        Error_Handler:
        If IsOpen Then Close #FNum
        If Err Then Err.Raise Err.Number, , Err.Description
    End Function
    
End Module
```

**Expected behavior**
To have these functions implemented.

**Screenshots**
![image](https://user-images.githubusercontent.com/33756666/147850454-18957157-36fa-495b-b4e4-6f462892b7ec.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.13.61]

**Additional context**
VBx does not offer any intellisense for it.
`Input(number, [ # ]filenumber)`
tB could do better here.

**Comment by Kr00l** [comment]
Extra info.
The Input and InputB functions are part of the `[_HiddenModule]`
![image](https://user-images.githubusercontent.com/33756666/147907766-65c8adcc-78b8-4f3e-a6bc-569fc7f05132.png)

**Comment by WaynePhillipsEA** [comment]
Thanks @Kr00l I will get onto them this week.

**Comment by WaynePhillipsEA** [comment]
Now available in BETA 151.  Finally ;)
