### ISSUE TITLE
Parameter hints don't play well with WordWrap

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#633]
**Describe the bug**
Parameter hints don't play well with WordWrap.
The length of the parameter hint makes the line longer.

See here for sample project:
https://github.com/WaynePhillipsEA/twinbasic/issues/627#issue-1092649990

**To Reproduce**
1. load the sample project
2. Activate WordWrap
3. Resize the editor

**Expected behavior**
Editor line should fit in window.

**Screenshots**
https://user-images.githubusercontent.com/88059532/148035307-2ef3f77d-7768-46e4-bdf1-35bbd5bbd2c5.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC 0.13.62

**Additional context**
Not very important.

**Comment by WaynePhillipsEA** [comment]
Unfortunately, this is a VS Code thing, and nothing that we currently have control over.   I'll leave it open, as we may want to ask the VS Code team to look at it, or we can probably just wait until we move to Theia (#458).

**Comment by KarlSevenSeven** [comment]
To wait is the best choice for now.
As said, the importance is very minor.
Thank you.

**Comment by KarlSevenSeven** [comment]
How to activate the parameter hints in the new IDE (beta 90)?
I like the feature.

**Comment by EduardoVB** [comment]
Maybe to close this issue since it was related to VSCode?
