### ISSUE TITLE
GoSub /  Return

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#639]
**Describe the bug**
GoSub /  Return is missing

**Expected behavior**
To be part of the language.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - twinBASIC  0.13.61]

**Comment by WaynePhillipsEA** [comment]
Thanks for opening the issue.  This was known to be missing, but it looks like we didn't have an open issue for tracking it.  We do now :)

**Comment by fafalone** [comment]
Closing since `GoSub/Return` is now available for some time.
