### ISSUE TITLE
ActiveX:  Methods with ParamArray appear to be misbehaving

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#684]
**Describe the bug**
I compiled my my TwinLib64 library to an ActiveX. Code in TwinLib64 is strictly vanilla VBA because I round trip the library between VBA and twinBasic.  For the ActiveX compilation everything is 64 bit.  The compiled code is that of version 0.1.3.0 as uploaded to the package manager.

When I add the ActiveX library the VBA code compiles OK

When I run VBA code that calls into the ActiveX library I get an error
![ActiveXParamArrayFail](https://user-images.githubusercontent.com/81257042/150649802-92fec7f0-71a1-44d3-b66c-65f8ee11fef3.jpg)

I can't inspect the content of the s.Integers Lyst because I get a message saying that that functionality is not implemented yet.

In the picture above the Lyst object Deb, AddRange, and Items methods seems to work OK

However, 
1. The call to Fmt.Dbg does not produce any output in the Immediate window
```
Public Sub Dbg(ByVal ipFormatTemplate As String, ParamArray ipParamarray() As Variant )
```
2.  The call to mySums.Add is the line which gives the error
```
Public Function Add(ParamArray ipArgArray() As Variant) As Lyst
```
The above problems are not evident in the when the library code is run in VBA

 - OS: [ Windows 11]
 - twinBASIC compiler version [0.13.90]

The Word file with the macros I was testing.
[AoC2021usingTwinLib64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7918998/AoC2021usingTwinLib64.zip)

The compiled ActiveX
[TwinLib64_win64.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7919000/TwinLib64_win64.zip)

**Comment by FullValueRider** [comment]
Here is the Library in a Word. Dotm file.

[VBALib.zip](https://github.com/WaynePhillipsEA/twinbasic/files/7919136/VBALib.zip)
I

**Comment by WaynePhillipsEA** [comment]
Is this still an issue?

**Comment by FullValueRider** [comment]
I think time has killed this one.

**Comment by FullValueRider** [comment]
Looks like this one has timed out.  Not noticing any issues in similar code in current IDE 321
