### ISSUE TITLE
Unsafe editing mode after copying a project

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#716]
**Describe the bug**
If I copy a project then open the workspace I am asked to trust the code.  
The editing mode that results from accepting trust shows both the 32 and 64 bit options selected under the Build configuration in the Explorer pane.
  
![TwinBasicBuildOptionsBothSelected](https://user-images.githubusercontent.com/81257042/152975983-f24f091e-e16b-42d4-b8d4-3daa819bf758.jpg)

If I edit in this mode  I very soon get to the point where the editor cannot save changes.  At this point the edited code cannot be recovered because the editor remains in a confused state even if I close VSCode (by itself or forced through task manager) and reopen.

When this happens I have just closed vscode, deleted the copied project )because there is only a small amount of editing), recopied the original project and started again.  When I do this, the code I get is not from the newly copied project, but from the previous (now deleted copy of the project).  i.e, the edits that could not be saved previously are present.

**Expected behavior**
The code should be that in the workspace and not from some editing buffer maintained by VSCode.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - twinBASIC compiler version [e.g. 014.8]

**Comment by WaynePhillipsEA** [comment]
Please check to see if you've the 'hot exit' feature of VS code enabled (File > Preferences > Settings).  You'll probably want that feature OFF to prevent VS Code restoring unsaved documents.

**Comment by WaynePhillipsEA** [comment]
I've not seen any recent reports of this.  With it also being related to the older VS Code edition of tB, I'm inclined to close this now.  Thanks
