### ISSUE TITLE
vbNormal is ambiguous

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#718]
**Describe the bug**
Often the constant vbNormal is used without full qualifier. However, this leads to an error in tB.

![image](https://user-images.githubusercontent.com/33756666/153004393-6b1d6f35-ff03-49bc-ae83-3bcbb345d039.png)

![image](https://user-images.githubusercontent.com/33756666/153004527-797bebdb-5d9f-4304-bb54-310aedf32f51.png)

**To Reproduce**
n/a

**Expected behavior**
I don't know how VBx orders them and which enum is finally chosen. But something similar is needed I guess.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. 0.14.9]

**Additional context**
This is a wider problem than vbNormal alone for sure.

**Comment by WaynePhillipsEA** [comment]
VB6 will use the order of the references order to determine the priority there (VBRUN vs VBA).  At the moment tB doesn't expose those two in the references list, but it should, so that the priority can be adjusted.

**Comment by Kr00l** [comment]
I just put it in here as it best fits, maybe we shall rename the title more specific.

So, in VB6 the order for "Visual Basic*" is fixed and can't be changed. IMO that's something to consider for full back-compat.

So, as you see the OLE Automation reference cannot be put higher in priority.

![image](https://user-images.githubusercontent.com/33756666/154796388-8557057c-dfb4-4480-b637-a17e1c4eaf1b.png)

in tB the order is now as following:
![image](https://user-images.githubusercontent.com/33756666/154796405-c9ba5893-7424-4e6e-985b-bef7a022efe6.png)

However, when I just use `LoadPicture()` (without the VB. namespace) then it uses in fact the `stdole.StdFunctions.LoadPicture` which of course won't work with a byte stream.
![image](https://user-images.githubusercontent.com/33756666/154796446-15e2d5c7-79c0-40e6-87ab-2adc56d977b0.png)

in VB6 the `LoadPicture()` will use the VB. namespace as this is higher in priority.

**Comment by wqweto** [comment]
This look like such a landmine field I would consider "wrapping" oleaut reference as compiler intrinsic so to drop the explicit `OLE Automation` line in references and *Do the Right Thing* about which is which and which function gets called.

**Comment by bclothier** [comment]
I'm a bit confused by this suggestion:

> "wrapping" oleaut reference as compiler intrinsic so to drop the explicit OLE Automation line in references

I believe that is already the case in VBx? You are free to deselect the reference and it won't prevent OLE automation from happening. The only difference is that you cannot early-bind the objects contained within the library within the codebase?

**Comment by wqweto** [comment]
Deselecting the reference will prevent instantiating `StdFont` and `StdPicture` coclasses which is non-obvious to troubleshoot.

Apparently its `LoadPicture`/`SavePicture` functions are already "shadowed" by VBx runtime so these will not be missed.

My idea is that the whole typelib is so miniscule it can be handled internaly by the compiler with no explicit reference needed.

**Comment by bclothier** [comment]
While I agree in theory there shouldn't be a problem with including the library, I wonder how it'll impact the back-compat if it's always implicitly included. In a default VBx project, OLE automation is usually the first optional reference in the list(?) so they usually have higher precedence than other optional references, unless one takes care to rearrange the order. I think that's very rarely done in a VBA project. More likely, some VBA developers will unselect it for some misguided reasons. So in theory, one could then re-implement or use the `StdFont` in some other library and use that instead. Then now what? How will tB know that we should be using that `StdFont`, not the one from the `stdole2` type library?

I think that is a good candidate for an inspection (c.f. #51 ) to warn the developers about such nonstandard setup. At most we can alert them and then leave it up to them to fix however they want (or not).

**Comment by Kr00l** [comment]
> 
> Apparently its `LoadPicture`/`SavePicture` functions are already "shadowed" by VBx runtime so these will not be missed.

Well, it's worth another discussion. But this issue is about that VBA, VB and VBRUN needs preceding to any references selected, if it's oleaut or something else doesn't matter.

**Comment by mburns08109** [comment]
Would it be feasible for any such "Auto-included" libraries to be also automatically placed at the END of the references list by default? If a different sequencing is needed - then simply reference it manually and in the needed priority sequence.

This would have both the blessings of simplicity and overridability.
