### ISSUE TITLE
Settings do show text only after import

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#743]
**Describe the bug**
I imported a VBP, then wanted to check the settings.
But there is text only.

**To Reproduce**
1. Import a VB6 ActiveX project 
2. Go to settings in the project tree.

**Expected behavior**
Access to the settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/88059532/154479953-12a195a2-9261-4cd3-9625-cfcdff7d9a33.png)

**Desktop (please complete the following information):**
 - OS Windows 10
 - twinBASIC 0.14.24

**Additional context**
Not sure if the issue comes up with every VB6 ActiveX projects.
In here it does.
I can send Wayne a project in private in order to play with.

**Comment by KarlSevenSeven** [comment]
I tried that of course, but no luck.
Settings stay scrambled.

**Comment by WaynePhillipsEA** [comment]
Looks like an old VSCode, so let's close this now.  Thanks
