### ISSUE TITLE
PropertyBags & PropertyChanged Method

### ISSUE THREAD

**Issue by jpbro** [twinbasic/twinbasic#745]
**Is your feature request related to a problem? Please describe.**
I'm trying to start building my VB6 DLLs as tB DLLs, and I'm currently unable to build most of them because PropertyBags and the PropertyChanged method aren't implemented yet.

This is a known issue as note by @WaynePhillipsEA here: https://github.com/WaynePhillipsEA/twinbasic/issues/703#issuecomment-1031860339_ but I thought it deserved it's own Issue for tracking/discussion purposes.

**Describe the solution you'd like**
I would like to see the VB6 PropertyBag object and PropertyChanged methods implemented in tB.

**Describe alternatives you've considered**
A) Having a different serializing object, and therefore having to change the source code to use the new object.
B) Rolling my own PropertyBag replacement.

**Additional context**
Binary compatibility with the VB6 PropertyBag object will be very important as I currently push PropertyBag contents around the internet to clients that may not be up-to-date and won't be able to understand a new serialization format.

**Comment by WaynePhillipsEA** [comment]
As of v0.14.30, PropertyBag is now implemented, with VB6 binary compatibility.

**Comment by WaynePhillipsEA** [comment]
As of v0.14.31, PropertyBag_VB5 interface is also supported.
