### ISSUE TITLE
Form.show

### ISSUE THREAD

**Issue by DinyaZ** [twinbasic/twinbasic#746]
**Is your feature request related to a problem? Please describe.**
I create a little app in VB6, with MyForm and a module with Sub Main.  It works, and starts the form:

Sub main()
  MyForm.Show 
End Sub

In TWB this doesnt work, gives error message:
Executing 'NewProject.MainModule.Main'...
(compile error: codegen error; check for compilation errors)

and works only with

Public Sub Main()
 With New MyForm
      .Show
  End With
End Sub

**Describe the solution you'd like**
Is it possible with the VB6 style simple MyForm.show ?

**Comment by dmrvb** [comment]
I think this is a tricky one, there will be a lot of tricky GUI decisions to make.
For 100% compatibility then this needs to be done, but the current approach is more logical/consistent with OOP.
I have a project with collections of Forms and that extra automatic first instance causes a lot of confusion.
Maybe this needs to be part of a "full vb compatibility" option.
Ive said before, it would be ok with me to have less than 100% compatibility and an upgrade wizard if that gives us a nicer language.
Would it be possible to put a  "Public MyForm as New Myform" in the main module as a fix for this???

**Comment by retailcoder** [comment]
Wouldn't this be just a matter of specifying a predeclared ID for forms?

**Comment by bclothier** [comment]
FWIW, that is a good candidate to showcase what tB can do for analyzing the code and making suggestions.

**Comment by DinyaZ** [comment]
> Maybe this needs to be part of a "full vb compatibility" option. Ive said before, it would be ok with me to have less than 100% compatibility and an upgrade wizard if that gives us a nicer language.
.
.
I think the 100% compatibility is the main and advertised goal of this project, at least in v1 version. 
If someone has a large VB6 written project, it can be a real nightmare to hunt for the little various hidden "errors", incompatibilities.

**Comment by WaynePhillipsEA** [comment]
As noted, it should just be a case of adding the `[ PredeclaredId ]` attribute to the form class.  We need to add that automatically for all new forms.

**Comment by bclothier** [comment]
Agree for back-compat but can we at least flag as a hint/suggestion? I don't think it's always the best idea to code against the default instance and I think that tB can provide better way to control a singleton or keep multiple instances unpolluted with shared state.

**Comment by WaynePhillipsEA** [comment]
Yeah I'm not a big fan either, but many will of course expect it.  So I can see us perhaps needing a couple of project or IDE preferences... one for this, and perhaps one for choosing the syntax for events (`Handles` vs the old school way).

**Comment by WaynePhillipsEA** [comment]
This has been implemented for a while now.  TIme to close.  Thanks
