### ISSUE TITLE
Unload Me not implemented ?

### ISSUE THREAD

**Issue by aliensoftGB** [twinbasic/twinbasic#783]
Not sure if this has been reported previously, but here it goes.

**Describe the bug**
END statement not implemented
Unload statement not implemented

**To Reproduce**
    Private Sub Command1_Click() Handles Command1.Click
        MsgBox "Click OK to Close.", vbOKOnly + vbInformation
    End  **'//Does nothing**
   Unload Me **'//Does nothing**
    End Sub

**Expected behaviour**
Should End & Terminate the exe.

 - OS: Windows 10
 - twinBASIC BETA 7

**Comment by DinyaZ** [comment]
I tried to test today a small VB6 project, but found theese issues immediately. Important missing items....!

**Comment by VB6-Programming** [comment]
There is a Me.Close

**Comment by dmrvb** [comment]
We need a Forms collection too.
A common way to end a multi-form VB6 app is:

Dim F as Form
For each F in Forms
  Unload F
next

and..........
 F.visible=false
does not work as expected, but I was going to wait till the GUI was a bit more developed before raising bug reports

**Comment by OldestCoderInTown** [comment]
The only way I have to close my program is to click on th X  in the top right. 

Any idea when END might work?

**Comment by WaynePhillipsEA** [comment]
`End` statement is now implemented in BETA 65.  We'll leave this open for tracking `Unload` support.

**Comment by WaynePhillipsEA** [comment]
`Unload` is now support in BETA 72, thanks!
