### ISSUE TITLE
Compile to VBA Source Files

### ISSUE THREAD

**Issue by sancarn** [twinbasic/twinbasic#80]
P.S. this might already be a feature that I am unaware of

It would be great if twinBasic files could be compiled to compatable *.cls and *.bas files. Alternatively compiling directly to xlam/xlsm/xlsb great too.

I personally love the feature set in twinBasic, but we don't get the permissions from IT in our organisation to run executables or even load DLLs onto the system. So a src-->src compiler would be greatly beneficial to us.

I'd imagine in some cases this compilation will be kind of ugly, and in some instances it may be impossible. However having a subset of twinBasic which has this capability would be great.

**Comment by bclothier** [comment]
To clarify - are you envisioning some kind of a transpiler where twinBasic's extensions is compiled into a compatible VBA syntax? e.g. overloads => explicit method calls?

**Comment by sancarn** [comment]
@bclothier indeed. A source to vba compatible source transpiler is what I’m envisioning. And If stuff isn’t possible directly in an ideal world it’d be emulated, similar to how BabelJS works

**Comment by WaynePhillipsEA** [comment]
We definitely want to offer better VBA integration.  The question at the moment is how to do that.  One possibility is using our VCOM technology as seen in vbWatchdog, where the compiled binary (both 32-bit and 64-bit) is loaded completely from inside the VBA project.  But there's lots of possibilities, and transpiling is certainly one of them.

**Comment by WindowStations** [comment]
If the aim is 100 percent vb6/vba compatibility, then I think you must have these abilities sooner than later.  First, the ability to open .vbp/.vba projects, and the ability to save the project files in the visual basic format/s.  Then, a similar ability to use the same build/compiler switches as VB6.EXE, C2.EXE, and LINK.EXE.   What is the question?  Wouldn't TB just write to the corresponding files, converting the language parts to their vb counterparts?

**Comment by sancarn** [comment]
> One possibility is using our VCOM technology as seen in vbWatchdog, where the compiled binary (both 32-bit and 64-bit) is loaded completely from inside the VBA project.

Hmm does this load type information also, or would an external type library require registering for type information? If so that'd be unfortunate at least. That said, I could easily see this being the goto method as it will be a lot simpler than transpiling, i imagine.

In fairness, there's no stopping a transpiler being a community project also. @WaynePhillipsEA is the twinBasic grammar public?

**Comment by WaynePhillipsEA** [comment]
@sancarn No, it doesn't require any type library.  Wrapper classes are created in the VBA project (called ErrEx in vbWatchdog) that expose the class objects, and these just forward the calls/requests on to the compiled binary.

The grammar isn't public.  twinBASIC uses a table-based parser that is compiled in;  the grammar rules are not text based like they are in ANTLR.   For a transpiler, I would suggest waiting for #51 as we'll probably have to expose the internal AST to make that feature possible, and it would give a good base to start a transpiler.

**Comment by WaynePhillipsEA** [comment]
I'm going to close this as out-of-scope.  As discussed, this request come could potentially be picked up by the community once #51 is resolved.  Thanks.
