### ISSUE TITLE
VB6 can't see ActiveX control created by tB

### ISSUE THREAD

**Issue by rboeckka** [twinbasic/twinbasic#809]
Yesterday i tryed Mike Wolfe's explanation to create an active-x control; for me  it worked with access 2003, but i could not see the same control in access 2010 - here it is not listed. In vb6 i also could not find this control. 
I think, i need an explanation, which different types of active-x controls are possible and how can i use it from different apps like word, access, excel and vb6.

**Comment by WaynePhillipsEA** [comment]
Is your installation of Office 2010 also 32-bit?   On my machine I have Office 2003 (32-bit) and Office 365 (64-bit), and both can see ActiveX controls created by twinBASIC, provided I compile the ActiveX control to both bitness using twinBASIC.

I'm not sure why VB6 can't see the tB ActiveX controls; I will look into that.

**Comment by rboeckka** [comment]
This was my first idea; my office 2010 is in c:\program files(x86), so its 100% 32 bit code. 

 

Btw. my son is LLVM contributor and very deeply involved with llvm and mlir. If you come to a problematic situation with llvm, I think he is able to help.

Currently he is working on a compiler version of python as open source version, based on mlir, if you are interested, his github account is https://github.com/zero9178

 

Greetings from austria

Reinhard

 

Von: WaynePhillipsEA ***@***.*** 
Gesendet: Montag, 25. April 2022 10:00
An: WaynePhillipsEA/twinbasic
Cc: rboeckka; Author
Betreff: Re: [WaynePhillipsEA/twinbasic] Different types of active-x control? (Issue #809)

 

Is your installation of Office 2010 also 32-bit? On my machine I have Office 2003 (32-bit) and Office 365 (64-bit), and both can see ActiveX controls created by twinBASIC, provided I compile the ActiveX control to both bitness using twinBASIC.

I'm not sure why VB6 can't see the tB ActiveX controls; I will look into that.

**Comment by WaynePhillipsEA** [comment]
> This was my first idea; my office 2010 is in c:\program files(x86), so its 100% 32 bit code.

OK that's good.   Do you happen to run Access 2010 with the 'Run as administrator' option?  If you do, then it won't be able to see the ActiveX control unless you register it into the HKEY_LOCAL_MACHINE registry hive.   By default, twinBASIC projects register into the HKEY_CURRENT_USER registry hive.    You can change this in your project settings from within twinBASIC.  Open Settings and then type 'registry' into the search bar at the top.   Tick that option and then change the value to 'YES', then save the Settings file and close down the IDE.  

Now you must restart the IDE with the 'Run as administrator' option, and when you rebuild the ActiveX control, it will now register into the HKEY_LOCAL_MACHINE hive.

**Comment by rboeckka** [comment]
You hit the point! Access 2010 and vb6 are started as admin, Access 2003 was started normal. I changed it in Access 2010 and the active x control is visible.

 

Von: WaynePhillipsEA ***@***.*** 
Gesendet: Montag, 25. April 2022 12:00
An: WaynePhillipsEA/twinbasic
Cc: rboeckka; Author
Betreff: Re: [WaynePhillipsEA/twinbasic] Different types of active-x control? (Issue #809)

 

This was my first idea; my office 2010 is in c:\program files(x86), so its 100% 32 bit code.

OK that's good. Do you happen to run Access 2010 with the 'Run as administrator' option? If you do, then it won't be able to see the ActiveX control unless you register it into the HKEY_LOCAL_MACHINE registry hive. By default, twinBASIC projects register into the HKEY_CURRENT_USER registry hive. You can change this in your project settings from within twinBASIC. Open Settings and then type 'registry' into the search bar at the top. Tick that option and then change the value to 'YES', then save the Settings file and close down the IDE.

Now you must restart the IDE with the 'Run as administrator' option, and when you rebuild the ActiveX control, it will now register into the HKEY_LOCAL_MACHINE hive.

**Comment by bclothier** [comment]
FWIW, the issue with running as admin & HKCU registration is a known issue (not just for tB but COM / Windows in general). People will need to be careful about not running HKCU registration as an admin. When running as admin, HKLM is the appropriate action (but with the downside of being unable to update/unregister as an non-admin).

**Comment by rboeckka** [comment]
Now i understand the problematic with the registration; for vb6 i could not find a solution to use this control.

**Comment by rboeckka** [comment]
I already registered in HKLM; vb6 does not list this control, in access it is listed. When i search this control from the v6 ui - components - i get: the file: xxx.dll could not registred as activeX-component. (bad translation)

**Comment by WaynePhillipsEA** [comment]
I will look into the VB6 issue further tomorrow.  Thanks.

**Comment by WaynePhillipsEA** [comment]
I've not seen any recent reports of this problem, so I'm going to assume it is fixed.
