### ISSUE TITLE
allow displaying events in debug console in ascending or descending order

### ISSUE THREAD

**Issue by lunasoft2001** [twinbasic/twinbasic#825]
**Is your feature request related to a problem? Please describe.**
in the debug console the last event is shown last. For some users it may be more comfortable to display in reverse order

**Snapshot**
![Captura de Pantalla 2022-05-03 a las 15 21 02](https://user-images.githubusercontent.com/12692231/166460784-546575b5-298f-41c4-ac73-0bb342c8687f.png)

**Comment by WaynePhillipsEA** [comment]
This is now supported, in BETA 30, via the new ellipses menu > 'Invert Output Direction'.  Thanks.
