### ISSUE TITLE
ActiveX single procedures run in different order

### ISSUE THREAD

**Issue by KarlSevenSeven** [twinbasic/twinbasic#845]
**Describe the bug**
I don't know if the following will help at all...

I made a debug output into my ActiveX source.
For **every** single procedure.
When I compare the output of the VB generated DLL with the tB one, I see a different order in execution.
Of course using the very same data.

I assume this will be the cause of the main problem.

**Expected behavior**
Same execution order

**Screenshots**
Here the WinMerge from both debug output files, left side is ok:
![image](https://user-images.githubusercontent.com/88059532/168793508-7912cc83-5abf-4aac-b739-0b05eb77aee3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Beta 40

**Additional context**
What should I check next?

**Comment by WaynePhillipsEA** [comment]
OK, this just got interesting.  So in VB6, with the following code you will see different ordering of the execution of procedures depending on whether you compile to Native Code or PCode.  

```vb
Module MyModule

    Public g_Log As String

    Public Sub Test()
        Dim LHS As New MyClass
        Dim RHS As New MyClass2
        Set LHS.Target = RHS.Clone
        MsgBox g_Log
    End Sub

End Module

Class MyClass

    Public Sub Class_Initialize()
        g_Log = g_Log & vbCrLf & "MyClass.Class_Initialize was called"
    End Sub

    Public Property Set Target(ByVal Value As MyClass2)
        g_Log = g_Log & vbCrLf & "MyClass.Target was called"
    End Property

End Class

Class MyClass2
	
    Public Sub Class_Initialize()
        g_Log = g_Log & vbCrLf & "MyClass2.Class_Initialize was called"
    End Sub

    Public Function Clone() As MyClass2
        g_Log = g_Log & vbCrLf & "MyClass2.Clone was called"
    End Function

End Class
```

In VB6-PCode:
<img width="168" alt="tbOrderDiscrepencyPCode" src="https://user-images.githubusercontent.com/25738109/168963592-5febfe59-5b4b-428b-ab8e-632637b75ca1.png">

In VB6-NativeCode:
<img width="166" alt="tbOrderDiscrepencyNativeCode" src="https://user-images.githubusercontent.com/25738109/168963610-fd96668d-c009-4c30-8f4d-8ba62ff5cc4d.png">

As you can see, if you compile to Native Code, the LHS Class_Initialize gets promoted and is called FIRST, but this doesn't happen in PCode compilation.  When running in the IDE, the result is the same as the PCode compilation of course, and tB currently behaves the same as the PCode compilation.

Unfortunately, for ultimate compatibility, we're probably going to need a switch to simulate the different compilation behaviours. <sigh>

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven could you compile your AX dll in VB6 using PCode compilation, and check if the order of execution then matches the tB output.  Then, also check if the Pcode-compiled DLL exhibits the same problem that you are encountering, to determine if the order of execution is likely to blame.

**Comment by KarlSevenSeven** [comment]
I'll do so, wait.

**Comment by KarlSevenSeven** [comment]
The order of execution is different VB6-native vs. VB6-pcode.
But the result is the same, DLL works as expected however it is compiled it VB6.
![image](https://user-images.githubusercontent.com/88059532/168979007-789803c3-45de-44b7-90cf-71f2b492cff3.png)

Then I compared VB6-pcode vs. tB:
![image](https://user-images.githubusercontent.com/88059532/168979185-a3b2130b-e167-4481-887e-be10163203c3.png)

And no, I don't get the same result in the test app, just nothing.

**Comment by KarlSevenSeven** [comment]
I now see that the test app still runs, so the DLL still writes debug output.
Will wait now until this ended.
Perhaps there is a result that I couldn't see because I didn't wait for a long time?

**Comment by WaynePhillipsEA** [comment]
> Then I compared VB6-pcode vs. tB:

Those two outputs look the same apart from the two extra entries `EvtProgress.NodeCount` and `EvtProgress.StructureCount`.  Those two extra entries did not appear in your opening screenshot (T:\BAAD_AXOUT.TXT), so it looks like these new entries are dependant on something in the run.   So it looks like the order of execution of tB is matching VB6-pcode correctly.  So the issue is likely something else.

**Comment by KarlSevenSeven** [comment]
I'll comment out the debug output for the progress and see what I can find.

**Comment by wqweto** [comment]
Compiling to Native Code w/ No Optimization might be worth trying too because out of order execution is often introduced by perf optimizations.

**Comment by WaynePhillipsEA** [comment]
> Compiling to Native Code w/ No Optimization might be worth trying too because out of order execution is often introduced by perf optimizations.

At the assembly instruction level, yes that would be expected.   But for external calls where side effects are involved, no, the optimizer should not be reordering calls.

Also, from my tests, the order appears to be deterministic in both cases - just different in both cases.  See my earlier note:

> NativeCode compilation appears to promote the full LHS evaluation, except for the final element. e.g. for Set LHS.Intermediate.Target = RHS.Clone, the LHS.Intermediate expression is evaluated first, then the RHS.Clone, and then the .Target property-set. In PCode/IDE/tB, the RHS.Clone gets executed first, and then the full LHS last. That's quite a difference.

**Comment by KarlSevenSeven** [comment]
> Compiling to Native Code w/ No Optimization might be worth trying too because out of order execution is often introduced by perf optimizations.

Good idea, will try later.
First I need to find the root of the issue.
Thank you.

**Comment by KarlSevenSeven** [comment]
Another different order.
Not sure if it affects the result, but different is different.

![image](https://user-images.githubusercontent.com/88059532/168997212-fd1850cf-5305-476c-9025-a4eb196a0018.png)

```
Public Function BoundingBoxesWithinTolerance(ByRef ElementA As GeoElement, _
    ByRef ElementB As GeoElement, ByVal Tolerance As Double) As Boolean
    
    BoundingBoxesWithinTolerance = False
        If ElementA.X1 <= ElementB.X2 + Tolerance Then _
            If ElementB.X1 <= ElementA.X2 + Tolerance Then _
                If Min(ElementA.Y1, ElementA.Y2) <= Max(ElementB.Y1, ElementB.Y2) + Tolerance Then _
                    BoundingBoxesWithinTolerance = (Max(ElementA.Y1, ElementA.Y2) + Tolerance >= Min(ElementB.Y1, ElementB.Y2))
End Function

Function Min(ByVal X As Double, ByVal Y As Double) As Double
    Min = IIf(X < Y, X, Y)
End Function

Function Max(ByVal X As Double, ByVal Y As Double) As Double
    Max = IIf(X > Y, X, Y)
End Function
```

**Comment by KarlSevenSeven** [comment]
Should we split the issue?
This has nothing to do with the execution order.

**Comment by KarlSevenSeven** [comment]
I waited some versions to give my AX project a try.
So many things were done in the meantime, so I thought it's time to do so.

Former last test was with tB 47, now I tried again with tb 74.

Again I have the debug output files.
Unfortunately things went worse not better.
From # 9495 on.

At this point I have no idea what I could test deeper in order to provide more info.
Perhaps you can WinMerge the 2 files to get an impression.
[tB_vs_VB_2022-07-14.zip](https://github.com/twinbasic/twinbasic/files/9115696/tB_vs_VB_2022-07-14.zip)

Once again: I can't shrink the test app/example.

**Comment by wqweto** [comment]
The order of execution function in `If A() And B() Then` statement differ between VB6 IDE and native compiled.

In VB6 IDE function `A` is called first then function `B` while when native compiled `B` is called before `A` which is not apparent and needless optimization (if any).

[Here](https://github.com/wqweto/VbAsyncSocket/blame/7a0575939186815a17193cd54729019c4559abb5/src/cTlsSocket.cls#L2212) is an actual line of code for example which introduced the [heisenbug](https://en.wikipedia.org/wiki/Heisenbug) which remained undetected for 8 months.
```
If SearchCollection(cStatuses, lIdx, RetVal:=baCert) And pvArraySize(baCert) > 0 Then
```
In IDE the function `SearchCollection` is called first and populates output variable `baCert` after which `pvArraySize` is called to check if the returned byte-array is empty.

In native compiled binary **apparently** array size is checked **before** calling `SearchCollection` (which returns empty byte-arrays in most of the cases). So because the variable contains garbage from previous evaluations in current routine we end up inside the body of the `If` statement **but** with an empty byte-array (Certificate Revocation List in this case) which does not bomb out immediately with a VB6 trappable error but the API call taints the connection leading to spradic timeouts etc. typical memory corruption indeterminate nastiness.

The other thing to consider is that in a similar `If A() And MyVar > 0 Then` statement `A` is called before `MyVar > 0` is evaluated both in IDE and native compiled so evaluation order looks good.

I think that it's not possible any moderately sane code to depend on `B` being called before `A` buggy order of evaluation **only** when running compiled, so TB can safely resort to "normal" evaluation order and deviate slightly from VB6 binaries behavior in this regard.

VBA is always interpreted in the IDE so it's not possible this behavior to be observed there so TB will always match VBA nicely.

**Comment by EduardoVB** [comment]
What tB would do when there are VB6 bugs, also when there are IDE/compiled discrepancies that can be seen as a bug? 

My opinion is to fix them, even if that will require some adaptation from the source code that already coded some workaround for those situations.

**Comment by KarlSevenSeven** [comment]
The order of execution of functions in If A() And B() Then statement differ between VB6 IDE and native compiled.

I don't see a difference between P-Code and Native compilation.
Didn't check in the IDE.

```
Dim DD As Boolean
DD = True

Dim a  As Boolean
Dim b  As Boolean
Dim ok As Boolean

a = True
b = True

ok = False
If a Then
    If b Then
        ok = True
    End If
End If
If DD Then Debug.Print "1: ", ok

ok = False
If a = True Then
    If b = True Then
        ok = True
    End If
End If
If DD Then Debug.Print "2: ", ok

If (a And b) Then ok = True Else ok = False
If DD Then Debug.Print "3: ", ok

ok = (a And b)
If DD Then Debug.Print "4: ", ok

ok = IIf((a And b), True, False)
If DD Then Debug.Print "5: ", ok
```

All the above gives the same result.
Version 1/2 is the safest IMO, and should be the fastest as if the first condition is false, the second condition is not evaluated.
This is how I write such most of the times.
I think it has to do with my very first steps with Commodore Basic and GW Basic...

**Comment by KarlSevenSeven** [comment]
I'm curious what will happen if the LLVM compiler chimes in.
Hopefully the whole order story doesn't start from scratch.

**Comment by wqweto** [comment]
@KarlSevenSeven A() and B() must be functions. Its the order of execution these functions that differ. While evaluating If A() And B() Then the compiled binary first executes B() but the IDE first executes A() which is the expected order.

**Comment by KarlSevenSeven** [comment]
```
VB IDE         VB6 Nat NoOpt   VB6 Nat Fast    VB6 P-Code        tB

1:              1:             1:              1:                 1:
ev. A           ev. A          ev. A           ev. A              ev. A 
ev. B           ev. B          ev. B           ev. B              ev. B
1 = True        1 = Wahr       1 = Wahr        1 = Wahr           1 = True

2:              2:             2:              2:                 2:
ev. A           ev. A          ev. A           ev. A              ev. A 
ev. B           ev. B          ev. B           ev. B              ev. B 
2 = True        2 = Wahr       2 = Wahr        2 = Wahr           2 = True 

3:              3:             3:              3:                 3:
ev. A           ev. A          ev. B           ev. A              ev. A 
ev. B           ev. B          ev. A           ev. B              ev. B 
3 = True        3 = Wahr       3 = Wahr        3 = Wahr           3 = True  

4:              4:             4:              4:                 4:
ev. A           ev. A          ev. B           ev. A              ev. A 
ev. B           ev. B          ev. A           ev. B              ev. B 
4 = True        4 = Wahr       4 = Wahr        4 = Wahr           4 = True  

5:              5:             5:              5:                 5:
ev. A           ev. A          ev. A           ev. A              ev. A 
ev. B           ev. B          ev. B           ev. B              ev. B 
5 = True        5 = Wahr       5 = Wahr        5 = Wahr           5 = True 
```

**Comment by wqweto** [comment]
Worth mentioning is that `Compile to Native Code` is set by default (not p-code) and the `Optimize for Fast Code` is the default optimization level (not small code) so the problem is endemic.

Also, just tested that `Optimize for Small Code` does mess up the execution order so it might be a recent bug e.g. it could have been introduced in SP6 (this hypothesis has to be tested to be sure).

**Comment by KarlSevenSeven** [comment]
I suspect the above execution order thing is not the main showstopper for my AX project.

This is more suspicious:
![image](https://user-images.githubusercontent.com/88059532/180637939-a7705b97-3640-4573-b060-8b4b57d830eb.png)

**Comment by wqweto** [comment]
Can you compare logs from VB6 binary compiled with Optimize for Small Code against TB? Should match unless there are more undefined behavior implemented differently in both compilers.

**Comment by KarlSevenSeven** [comment]
> Can you compare logs from VB6 binary compiled with Optimize for Small Code against TB? Should match unless there is more of so called “undefined behavior” implemented differently in both compilers.

Done, the VB AX runs fine.
https://github.com/twinbasic/twinbasic/issues/845#issuecomment-1129739728
Is in the same order now.
For now I should stay with this opt setting, it will reduce the differences.

Now this comes out:
![image](https://user-images.githubusercontent.com/88059532/180642387-facf1c0f-761c-4cbd-ad81-2fe52cbe50bb.png)

For further debugging I really need instructions.

**Comment by wqweto** [comment]
You can compare the logs without the first column (the autonumber) and figure out why VB6 log contains double entries for 4090 and 4091 both being `GeoList.Count`.

Is this property called twice in the parent expression?

It looks like `GeoList.Count` order is swapped 4091 vs 4093 but it's just doubled on 4090 + 4091 in VB6 log and a better compare without the autonumber will reveal what's going on.

**Comment by KarlSevenSeven** [comment]
Found something.
Property Get Nodes() is left too early on error.
Not sure if this is a problem, still investigating.

```
Public Property Get Nodes() As Variant

'<CSCustomCode> 353
DL 12, "Entered - " & "Contour.Nodes"
'</CSCustomCode> 353

On Error Resume Next

DL 556, "Get Nodes BEFORE A"
DL 553, "*A: " & UBound(ElementStartPoints)

DL 557, "Get Nodes BEFORE B"
DL 554, "*B: " & Elements.Count("Get Nodes 1")

DL 558, "Get Nodes BEFORE C"
DL 555, "*C: " & UBound(ElementStartPoints) <> Elements.Count("Get Nodes 2") - 1

DL 559, "Get Nodes BEFORE If UBound(ElementStartPoints)..."
If UBound(ElementStartPoints) <> Elements.Count("Get Nodes 3") - 1 Then RecalculateNodes

DL 560, "Get Nodes BEFORE Nodes = ElementStartPoints"
Nodes = ElementStartPoints
    
DL 561, "Get Nodes BEFORE Exit Property"
Exit Property
    
DL 562, "Get Nodes AFTER Exit Property 1"
RecalculateNodes

DL 563, "Get Nodes AFTER Exit Property 2"

Nodes = ElementStartPoints

DL 564, "Get Nodes BEFORE End Property 1"

End Property
```
![image](https://user-images.githubusercontent.com/88059532/180752296-48bf9fd1-39d5-4834-a092-4ffd1157c629.png)

**Comment by wqweto** [comment]
This appears to be more of the same. Check out this minimum repro test
```
Option Explicit

Private Function B(sText As String) As Long
    Print "B: " & sText
End Function

Private Sub Form_Click()
    Dim ElementStartPoints() As String
    
    On Error Resume Next
    If UBound(ElementStartPoints) <> B("Get Nodes 3") Then
        Print "RecalculateNodes"
    End If
End Sub
```
When compiled you get `B: Get Nodes 3` before `RecalculateNodes` in output while in VB IDE you don't get `B` called at all as the `UBound` is called first and it fails.

**Comment by KarlSevenSeven** [comment]
> This appears to be more of the same.

Yes you are right.
Means I should stop my trials until this is solved.

> a better compare without the autonumber
Tried that, and it works well the first few lines until WinMerge can't sync anymore.

Seems @WaynePhillipsEA needs to get to the issue before any more investigation makes sense.

**Comment by WaynePhillipsEA** [comment]
Thanks guys, I've logged it and will hopefully get to it tomorrow morning.

**Comment by WaynePhillipsEA** [comment]
@wqweto I'm not able to repro using your example.  In tB, I just get to the expected RecalculateNodes line (i.e. B doesn't get called).

**Comment by WaynePhillipsEA** [comment]
@wqweto apologies, I see what you meant now, that this is a difference between VB6 p-code and native code compilation.

**Comment by WaynePhillipsEA** [comment]
After a cursory look, this is going to require more extensive investigative work.  On the face of it, it looks like we'd have to offer a switch to model the native-code-fast compilation quirks of VB6.   I fear that this work won't make it into the v1 release and will probably have to wait until v2.

For now, provided we are matching the IDE / p-code behaviour, I'm fine with that.

**Comment by KarlSevenSeven** [comment]
The VB6 born DLL runs fine in P-Code, and in any other optimisation setting.
Today I compiled it to P-Code, all ok, runs as expected.

Yesterday I compiled it to optimized small.
A few days ago it was found that the evaluation order is the same as P-Code.
It looks like there are more differences, so I'll stay with P-Code now.

So the evaluation order is probably **NOT** the cause for not working in tB.

But things like this?
![image](https://user-images.githubusercontent.com/88059532/180960638-ad25fe47-59aa-4e45-9f87-1847c5ff75f3.png)


@WaynePhillipsEA 
I very know that my AX real world example issue is annoying, complicated, cumbersome to debug, and perhaps not important to you.

I tried to find the root of the problem.
Some things were found and fixed.
The real problem is still not found, and I don't have a real idea what to try next.

The reason why I'm after having it in tB is speed, the VB generated DLL suffers from the slow class destruction issue.
The simple question is if there is a chance to get it working **before V1 or V2 or at all**.

**Comment by WaynePhillipsEA** [comment]
On the contrary, it is *very* important to me.  I want *all* VB6 code to run in tB, and that most certainly includes your project.

The difficult aspect is time.  At this moment, my time needs to mostly be spent on implementing missing functionality as opposed to tracking down edge cases.  Why? Because edge cases only affect the few, and the missing features more likely have wider consequences.

That's not to say that edge cases won't get fixed.  They will, but I personally can't afford the time to go too deeply down a rabbit hole looking for them at this moment.  If they are presented to me as minimal viable repros, then they are significantly more likely to get fixed.

I very much appreciate the effort you've put in to tracking down the issues so far.  It feels like you're getting closer...

**Comment by KarlSevenSeven** [comment]
> my time needs to mostly be spent on implementing missing functionality as opposed to tracking down edge cases.

Understood.

I'm not so sure the example is a rare edge case.
I observe unconsistent behavior and debug output under the same conditions.
I was not aware of it until this morning.
Which makes it even harder if not impossible to debug.

See this (compiled in beta 85):
https://user-images.githubusercontent.com/88059532/180984404-09b3c31a-a2c2-45e8-9d39-c5673d326932.mp4

> If they are presented to me as minimal viable repros

I know that's needed.
Believe me, I try to get such.
Not possible, the debug output is always a bit or totally different.

> It feels like you're getting closer...

I feel the exact opposite.

**Comment by wqweto** [comment]
> But things like this?

You are the only one with understanding of your source code. You have to find the offending lines of code which produce different logs VB vs TB and create reproducible snippet if you think this different order of execution is preventing your component from working correctly (doubt it, if it works both p-code and native compiled which **do** produce different execution order).

There is a bug in TB but order of execution is not it. Compile VB to p-code and compare logs b/n VB p-code vs TB so that there is less noise in the logs. This way the differences are more meaningful.

My bet is that p-code vs TB there should be no diffs based on order of execution. I'm really curious why there are **any** diffs b/n these two.

**Comment by KarlSevenSeven** [comment]
> You have to find the offending lines of code

Haha, good hint ;-)
I try my best all the time...
... but I really can't track why a Class_Initialize simply doesn't happen in tB while it does in VB.
Or the Class_Initialize happens with no apparent reason.
It doesn't matter how well I know the code.

> Compile VB to p-code and compare logs b/n VB p-code vs TB so that there is less noise in the logs.

Already done, and yes, the noise is less.

> My bet is that p-code vs TB there should be no diffs based on order of execution.

You lose:
![image](https://user-images.githubusercontent.com/88059532/181001914-f2d42549-7ad1-42ab-beff-547558d4663f.png)

But the result is the same, so this shouldn't be the cause of the problems.

**Comment by WaynePhillipsEA** [comment]
Did you accidentally close this @KarlSevenSeven ?

**Comment by KarlSevenSeven** [comment]
The problems are gone in beta 107.
Wayne investigated with my large source and found + fixed the problem(s).
I did some tests now using a lot of data, all is fine.
Surprisingly the tB generated DLL works A LOT faster than the VB6 compiled one.
Even when compile to native -  fast.

**Comment by wqweto** [comment]
I wonder what these “auto-implemented OUT parameters” which were failing actually are? Can anyone shed more info?

**Comment by WaynePhillipsEA** [comment]
Apologies as I wasn't clear.  It was a problem with auto implemented property-get members for class fields, where the retval argument was being treated with in-out ByRef semantics rather than out-only semantics (inside the implementation).  This was only a problem for objects, and only then when the member was called in a loop (since the compiler can legitimately provide a stale pointer 
in a temporary variable with the expectation that the caller will ignore it due to out-only semantics).

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven weird that the unoptimized tB build is much faster than the VB6 native build... wouldn't have expected that.

**Comment by KarlSevenSeven** [comment]
https://github.com/twinbasic/twinbasic/discussions/212#discussion-3404844

**Comment by WaynePhillipsEA** [comment]
@KarlSevenSeven yes, that's quite probable

**Comment by wqweto** [comment]
@WaynePhillipsEA Just wondering if TB will ever need to keep a list of active objects like VBx does so to be able to free zombie instances (i.e. self or cyclic-referencing ones).

I was quite surprised VBx does this and fires `Class_Terminate` on cyclic-referenced instanced on app terminate which might be hard to emulate for 100% compatibility.

**Comment by WaynePhillipsEA** [comment]
Yes, tB will need to do it, but I can hereby guarantee my implementation won't have the same (awful) performance impact that VBx suffers from ;)   Just for reference, this was discussed in #687

**Comment by KarlSevenSeven** [comment]
To give an idea how much faster the tB generated DLL is:
tB took 706 sec.
VB took 1704 sec.

Wow!

Curious what the same with LLVM will be.

**Comment by WaynePhillipsEA** [comment]
> To give an idea how much faster the tB generated DLL is: tB took 706 sec. VB took 1704 sec.
> 
> Wow!
> 
> Curious what the same with LLVM will be.

Oh wow, that is significant
