### ISSUE TITLE
Compiler repeatedly crashes on the following code:

### ISSUE THREAD

**Issue by Greedquest** [twinbasic/twinbasic#884]
**Describe the bug**
See https://stackoverflow.com/questions/72415183/defaultdict-in-twinbasic-crashes-compiler

**To Reproduce**
```vba
Private Class DefaultDict(Of T)
    Implements Scripting.Dictionary Via dict
    Private dict As Dictionary
    Private defaultValue As T

    Public Property Get Item(ByVal key As Variant) As Variant Implements Scripting.Dictionary.Item
        If Not dict.Exists(key) Then
            dict(key) = defaultValue
        End If
        Return dict(key)
    End Property
End Class
```
```vba
Dim dict As New DefaultDict(Of Long)
dict("foo") += 1 'foo key defaults to 0
Debug.Print dict("foo") 'should be 1
```

**Expected behavior**
I think the syntax is valid, maybe it isn't. Would expect a compiler error not a repeated restart

**Desktop (please complete the following information):**
 - OS: Windows 11
 - TB IDE v 49

**Comment by Greedquest** [comment]
Realised it's invalid as #665 COM references can't be used in implements Via.

Still the use of Generics + COM reference implements via seems to result in the repeated crash which is buggy.

**Comment by WaynePhillipsEA** [comment]
I'm the upcoming release, COM references are allowed with the Implements-Via feature, so I will check this is fixed before release.  Thanks.

**Comment by WaynePhillipsEA** [comment]
I'm not seeing a hard crash here anymore in recent builds, so I'll now close this.  Thanks.
