### ISSUE TITLE
Missing Printer and Printers objects

### ISSUE THREAD

**Issue by OldestCoderInTown** [twinbasic/twinbasic#893]
Hi.

I would like to be able to commit the output from my projects, onto paper.

printer.print and printer.enddoc woul dbe the most pressing things to have working. Then we can get into printer.font items.

**Comment by WaynePhillipsEA** [comment]
Thanks for opening this issue.  We'll keep this open to track the progress of implementing the Printer and Printers objects.

**Comment by OldestCoderInTown** [comment]
Hi, is there any sign of this becoming a thing?

@WaynePhillipsEA

**Comment by WaynePhillipsEA** [comment]
Not yet @OldestCoderInTown, sorry!  I will get to it eventually.

**Comment by OldestCoderInTown** [comment]
@WaynePhillipsEA 

Do you know if I could use BSPrinter with twinBasic?

**Comment by WaynePhillipsEA** [comment]
I think so...  I can't exactly remember who wrote it, but I seem to recall they were here in the early days, making a few adjustments so that it would work with tB, so it's definitely worth a try.

**Comment by WaynePhillipsEA** [comment]
Ah it was @EduardoVB... See here https://github.com/twinbasic/twinbasic/issues/325

**Comment by OldestCoderInTown** [comment]
I am now able to print, on paper, in a variety of sizes.

This makes my twinBasic project almost ready for roll out in a production environment.

**Comment by uwbwsvd** [comment]
I played around with BSPrinter.
Win32 TB v0.15.123
As I inserted this code:
  ```
Private Sub PrintPreview1_PrepareReport(Cancel As Boolean) Handles PrintPreview1.PrepareReport
        Printer.FontSize = 24
        Printer.Print "Hallo World"
    End Sub
```
The preview doesn't work anymore. See attached video

[print1.zip](https://github.com/twinbasic/twinbasic/files/9601441/print1.zip)

https://user-images.githubusercontent.com/41230018/191089460-c5f00be7-aefe-4be8-96ed-10364738b1d1.mp4
