### ISSUE TITLE
Missing ScaleMode property

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#900]
_Originally posted by @camomille22003 in https://github.com/WaynePhillipsEA/twinbasic/issues/772#issuecomment-1156559392_

> Version 54 fixed the Implements-Via feature issues, the code is starting to look like the original.
> There are still some problems anchoring buttons on a frame and pixel / twips conversions.
> 
> ![Image1](https://user-images.githubusercontent.com/33807881/173854451-2d62056a-988e-42fe-9a27-a25de62c3a86.jpg)

**Comment by bclothier** [comment]
@camomille22003 -- FYI it's not clear to me if this is in fact the same issue as reported by #899. Please confirm if this is same or different issue. 

In regards to the frame control, that is already a known issue, see #797.

**Comment by WaynePhillipsEA** [comment]
I think this is the missing feature of `ScaleMode` for forms.  Currently, all measurements (except for the Screen object properties) are in pixels, which is a known issue.  It's a known issue, but not one that we already have an issue for, so we can keep it open.  Thanks.

**Comment by camomille22003** [comment]
> @camomille22003- Pour votre information, je ne sais pas s'il s'agit en fait du même problème que celui signalé par [le # 899](https://github.com/WaynePhillipsEA/twinbasic/issues/899) . Veuillez confirmer s'il s'agit du même problème ou d'un problème différent.
> 
> En ce qui concerne le contrôle du cadre, c'est déjà un problème connu, voir #797 .

"pixels/twips/pixels" is different from #899 but as Wayne said ScaleMode missing.
