### ISSUE TITLE
Control Array support

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#909]
Missing the ability to create a group of controls by duplicating a control and creating an index

![Image12](https://user-images.githubusercontent.com/33807881/174077253-2ccdcefd-6438-4c00-96eb-8b73d49ac58f.jpg)

**Comment by bclothier** [comment]
This is a known issue, under #706. However, having it as its own issue may be easier to track so we'll keep this open.

**Comment by bclothier** [comment]
See also: #937

**Comment by WaynePhillipsEA** [comment]
Control arrays have been supported for some time now.  Time to close this.  Thanks.
