### ISSUE TITLE
Support use of third-party ActiveX controls in tB forms

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#917]

**Comment by wqweto** [comment]
This was already moved to Q3 2022 but will probably have to slip to Q4 again (which is fine)

The entire [milestones](https://github.com/twinbasic/twinbasic/milestones) section if not maintained should be better closed IMO. Too much hassle to move issues between milestones when best would be to have an accurate (maintained) single [roadmap](https://github.com/twinbasic/twinbasic/issues/335) tracking issue.

I'll be the a happy bunny if the entire Q4 is allotted to this issue and probably its twin one [Finish ActiveX control creation support](https://github.com/twinbasic/twinbasic/issues/916) which are major one, error-prone and require some research for retrofitting exact VB6 behavior.

**Comment by WaynePhillipsEA** [comment]
Yeah, I'm finding it hard to keep roadmaps and milestones up-to-date.  I sincerely apologise for that.

I can't see this taking a full quarter.. we have a working implementation for most parts, and IMO it just needs further refinement to get the implementation as close as possible to VBx.  I'm expecting to have this pretty much done by end of Oct now, but we'll see.

**Comment by fafalone** [comment]
Definitely hotly anticipating the glorious day where I get a chance to fire up the x64 conversions of my shell controls.

Plus maybe Krool can port his Common Controls?

**Comment by WaynePhillipsEA** [comment]
This feature has been available for some time now, so time to close this.  Thanks
