### ISSUE TITLE
Missing Duplicate control with increment

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#937]
![Image1](https://user-images.githubusercontent.com/33807881/175277907-b47b3b44-3ea9-4f42-8a5a-ee7de60e286c.jpg)

**Comment by OldestCoderInTown** [comment]
I’m trying to use 3 radio buttons, in a frame. 

This works really well in VB6 by letting me set actions based on the button’s index.

Do we have a timescale for this functionality?

**Comment by WaynePhillipsEA** [comment]
This feature has been available for some time now.  Thanks.
