### ISSUE TITLE
the jewels of my dreams

### ISSUE THREAD

**Issue by camomille22003** [twinbasic/twinbasic#938]
![Image4](https://user-images.githubusercontent.com/33807881/175469883-c525958f-3d4f-42a9-b91d-9c0135b5e20b.jpg)

**Comment by wqweto** [comment]
Some of these are less shiny :-))

**Comment by WaynePhillipsEA** [comment]
Line control is now supported in BETA 68

**Comment by WaynePhillipsEA** [comment]
DriveListBox control is now supported in BETA 112

**Comment by rexxitall** [comment]
A dream of me would be a customizeable source code control :) Just as simple as a RhichText control  ;) Scintilla is not that handy.

**Comment by WaynePhillipsEA** [comment]
DirListBox is also now supported in the latest BETA.

**Comment by WaynePhillipsEA** [comment]
FileListBox is now available in BETA 119

**Comment by dmrvb** [comment]
Its great to see the GUI side of tB moving forwards. When will be able to import a VB form (most controls working, modal/non modal forms, control arrays etc etc) ?
The Microsoft FileList/DirList controls are pretty much rubbish, ok if you want to write software that looks like something created by a beginer hobbyist 20 years ago.  How can we get some good modern TreeView and FileList based graphic controls easily available in tB??? I believe that fafalone has the knowledge and expertise to create these things. Something that can ultimately compile directly into the EXE would be the dream.

**Comment by WaynePhillipsEA** [comment]
Roughly.... PictureBox is up next (early this coming week).  Then it's importing of forms (later this week).   Then control arrays (next week).   Then non-modal forms (next week).

TreeView is already available in the latest betas, though not supporting images just yet.

**Comment by dmrvb** [comment]
Integrating the windows file system into the Treeview (and ListView) is the tricky bit and its way beyond my knowledge of Windows.
![image](https://user-images.githubusercontent.com/83877219/189523329-3b13b182-10a8-4fc5-9f64-8f3ff76228a9.png)

**Comment by fafalone** [comment]
I've been preparing my ShellTree control for tB; as soon as you can use tB UserControls on tB forms (hopefully next few weeks), a tB native version of that should be out shortly. The interfaces will be defined in-project so no external depends needed. 

A slightly modified version of the VB control already works in ocx form, but obviously that's limited so x86. The tB version is being re-done in x64 compatible.

The ShellBrowser control is much, much more complex, that will a bit longer, but once the tree is done I'm going to start on that too, since by that time the PictureBox I need will be there too.

**Comment by dmrvb** [comment]
That is really good news. Ive just spent the last few days doing a work around for a bug in the (now unsupported) ShellTree control that I am currently using.   The ShellBrowse would also be great. I appreciate its hard work but I hope the tB makes us all feel that writing code is now a future investment, whilst working in VB always felt like a very uncertain future.

**Comment by dmrvb** [comment]
> Roughly.... PictureBox is up next (early this coming week). Then it's importing of forms (later this week). Then control arrays (next week). Then non-modal forms (next week).
> 
> TreeView is already available in the latest betas, though not supporting images just yet.

This is exciting stuff, so once we can import a form this will be getting very close to a V1 release?  There is still the VB graphics system to do and a few missing odds and ends, but if a straightforward VB project can be imported and compiled then you can claim success and give yourself a few days off?????

**Comment by WaynePhillipsEA** [comment]
PictureBox is now available in BETA 120.   Nearly all of the main methods and properties are supported (e.g. Circle, Line, PSet, Print, TextWidth, TextHeight, Cls, Picture, hDC, CurrentX, CurrentY, FillColor, FillStyle, BackColor, ForeColor, DrawWidth, DrawMode, DrawStyle, AutoRedraw, FontTransparent and Picture) but notably the PaintPicture and Point methods are not yet implemented.

**Comment by WaynePhillipsEA** [comment]
Closing this now as #706 better covers this.  Thanks
