### ISSUE TITLE
Change property with double click

### ISSUE THREAD

**Issue by EduardoVB** [twinbasic/twinbasic#946]
**Is your feature request related to a problem? Please describe.**

In VB6 we can double click in a property and it changes its value, in case of enumerations to the next value and in case of True/False it toggles the value.

It is useful to quickly change a property value without having to display the combobox.

**Describe the solution you'd like**

If possible (or when appropriate) add that function to tB.

**Additional context**

VBA IDEs also work like that (tested Word and Access)

**Comment by WaynePhillipsEA** [comment]
This is now supported in BETA 63.  Thanks!

**Comment by Kr00l** [comment]
I am re-opening this because of a tiny difference between VBx and tB. That's why the double click feels currently not so good in tB.

In tB the drop-down is opened after a click:
![tB_DblClick_Prop](https://user-images.githubusercontent.com/33756666/176167465-5d71c0bf-56c0-4ee5-a3f0-e06702b1f226.gif)
So a double click can accidently happen if the closing attempt is too quick.

In VBx the drop-down field only opens when clicking on the arrow button, should we replicate this?
![VBx_DblClick_Prop](https://user-images.githubusercontent.com/33756666/176167895-11df0130-963c-4414-88ce-c6de6ce8ba57.gif)

**Comment by wqweto** [comment]
Try double clicking on the caption, not on the value in the property grid.

**Comment by Kr00l** [comment]
> Try double clicking on the caption, not on the value in the property grid.

Yeah. I just wanted to point out that a click on the value alone should not show the drop-down lost.

**Comment by EduardoVB** [comment]
> Try double clicking on the caption, not on the value in the property grid.

Yes, double clicking on the property name fires the default action. In case of a dialog (like the font dialog) it displays the dialog, in case of a color it displays the color selector. In case of a value, if it can be toggled, it does.

I guess I should have explained the issue better in the OP.

**Comment by wqweto** [comment]
> Yeah. I just wanted to point out that a click on the value alone should not show the drop-down list.

This is a makes sense for an HTML based property grid and I'm not very convinced by VB IDE's decision to drop down on exact click on the tiny drop-arrow only.

This is one of the main reasons I always use F4 to dropdown the list (or show custom property pages) in VB IDE and not fiddle with clicking tiny buttons with my shaky old hands and creaky mouse :-))

**Comment by bclothier** [comment]
FWIW, I never really liked double-click on the editbox area feature. 

Also, in Access' property sheet (not VBIDE), the double click does not work on certain properties that aren't a simple enumeration, even though they have a dropdown. That makes more sense. In those properties, the text is also editable. In VBIDE's property sheet, the dropdown doesn't seem to be editable.

**Comment by WaynePhillipsEA** [comment]
I don't feel particularly strongly on it, but I would prefer to keep the single click to drop-down.  The greater surface area for the click seems more natural to me.

**Comment by mwolfe02** [comment]
What about having the double-click work on the property label _instead of_ the property value?  It would be less discoverable, but you would avoid the accidental value change problem that @Kr00l mentioned.

**Comment by WaynePhillipsEA** [comment]
Any more thoughts on this one?  Would @mwolfe02's suggestion (above) be more suitable?

**Comment by wqweto** [comment]
Btw, w/ "caption" I meant "label" above.

These both work in VB IDE already i.e. double-click on both label and value for both dropdown and ellipses button perform default/"next value" action.

In addition F4 from keyboard for dropdowns show the list (as in std ComboBox), for ellipses button clicks it and for values with no buttons selects all text on currently positioned row.

**Comment by Kr00l** [comment]
I like the compromise suggested by @mwolfe02

**Comment by EduardoVB** [comment]
VB6 works by double clicking on property names.

**Comment by bclothier** [comment]
I also favor the suggestion from mwolfe02. I think it's much more inline with what other comboboxes in other application does and is less astonishing.

**Comment by WaynePhillipsEA** [comment]
As of BETA 74, double clicking on the property caption will now perform the action (toggle, enumeration switch etc), and the double-click handler from ernumeration values has been removed to avoid confusion.  Thanks all.
