### ISSUE TITLE
VBCCR ComboBox bogus fix

### ISSUE THREAD

**Issue by Kr00l** [twinbasic/twinbasic#960]
**Describe the bug**
The VBCCR ComboBox will consume the escape/return key when the drop-down list is open.
This is necessary to not invoke the potential closure of the Form or so when just "escaping" the drop-down list.

**To Reproduce**
Make KeyPreview to True on a Form. Listen for escape key.

**Expected behavior**
The Form_KeyDown should not be fired when closing the drop-down list in a VBCCR ComboBox.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - twinBASIC compiler version [e.g. BETA 67]

**Additional context**
I see you have currently a quirk fix for the tab key as Krools ComboBox "mistakenly" consuming it.
Maybe this also plays here a role.
To note is that indeed the tab key is "consumed".
However, the "default" implementation still do something with the tab key on TranslateAccelerator.
That's why I am consuming it because I don't care about the tab key, call the default implementation as it handles focusing next or previous control.
So I think you are correct in returning S_FALSE in the default implementation and thus "eating" the message. However, VB6 still handles the tab key in a way.
Maybe that kind of fix will then remove the quirk fix. (?)

**Comment by WaynePhillipsEA** [comment]
Additionally KeyPreview was firing before the TranslateAccelerator... fixed in next release!   Thanks!
