### ISSUE TITLE
Beta 67 just...stopped working for me.

### ISSUE THREAD

**Issue by mburns08109** [twinbasic/twinbasic#966]
**Describe the bug**
Infinite spinner in IDE

**To Reproduce**
Launch twinBasic.
get project prompt
select new standard EXE project
dialog closes
"please wait" with circle opens
circle spins - a few seconds later you see (one time) a "reloading from FILE" in the background
do while circle spins
  twiddle fingers
Loop (as n-> infinity)

**Expected behavior**
uhm, the IDE to actually open and work?

**Screenshots**
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/11444628/177038351-7417e09f-277d-4249-8dc6-1289b53bc83d.png">

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I don't _think_ that any of the pieces are quarantined anymore, either.
It worked the last time I fired it up.

**Comment by WaynePhillipsEA** [comment]
Can't explain that one.  Let's see how you get on with BETA 68.

**Comment by WaynePhillipsEA** [comment]
I'll close this for now.  If you have a similar experience with BETA 68, we can re-open to investigate.  Thanks.
