### ISSUE TITLE
DefaultMember With Variant as DefaultMember parameter results in call to DefaultMember when the instance is in a variant and the variant is tested for IsEmpty (phew)nce.

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#967]
**Describe the bug**

This issue took a bit of headscratching to elucidate.

Stuff about PredeclaredIds is for context and not part of the issue.

I have encountered a difference between VBA and TwinBasic in relation to the behaviour of the DefaultMember when the parameter for the DefaultMember is declared as a Variant and an instance of the class is placed in a variant and then that variant is tested for IsEmpty.

I have a class which has a PredeclaredId.
The Class has a DefaultMember (Item).
The DefaultMember in takes a single parameter declared as Variant

I can create and populate an instance of the PredecalredId.

If I assign the populated instance to a variant and then test the variant for IsEmpty I get a value of True, which is Incorrect.
This does not happen if I change the parameter to Long.  
This does not happen in VBA.

In the code below, the Classes Seq and Hkvp have PredeclaredIds and a factory method of Deb to generate new instances.
Both have Item methods as the DefaultMember
For Seq the method signature is
```
 Public Property Get Item(ByVal ipIndex As Long) As Variant
```
For Hkvp the method signature is
```
Public Property Get Item(ByRef Key As Variant) As Variant
```
The problem is demonstrated by tthe following code
```
Sub test()
    Dim myC As Collection = New Collection
    With myC
        .Add 10
        .Add 20
        .Add 30
        .Add 40
        .Add 50
        .Add 60
        .Add 70
        .Add 80
        .Add 90
    End With
    
    Dim myS As Seq = Seq.Deb.Add(10, 20, 30, 40, 50, 60, 70, 80, 90)
    
    Dim myH As Hkvp = Hkvp.Deb.AddPairs(VBA.Split("a,b,c,d,e,f,g,h,i", ","), Array(10, 20, 30, 40, 50, 60, 70, 80, 90))
    
    Dim myVar As Variant
    Debug.Print "Empty: Expecting True: Found ", VBA.IsEmpty(myVar),
    Debug.Print
    Set myVar = myC
    Debug.Print "myC: Expecting False, 9: Found ", VBA.IsEmpty(myVar), myC.Count
    Debug.Print
    Set myVar = myS
    Debug.Print "myS: Expecting False, 9: Found ", VBA.IsEmpty(myVar), myS.Count
    Debug.Print
    Set myVar = myH
    Debug.Print "myH: Expecting False, 9: Found ", VBA.IsEmpty(myVar), myH.Count
    
End Sub
```
The output from the above code is
```
No timeline information was provided.
H
Default
Executing 'Lib.Pootle.test'...
Empty: Expecting True: Found              True          
myC: Expecting False, 9: Found            False          9 

myS: Expecting False, 9: Found            False          9 

myH: Expecting False, 9: Found            True           9 
```
If I change Seq.Item to use long rather than variant the output is
```
Empty: Expecting True: Found              True          
myC: Expecting False, 9: Found            False          9 

myS: Expecting False, 9: Found            True           9 

myH: Expecting False, 9: Found            True           9 
```

The above behaviour can be demonstrated with the simpler code below
Class ItemClass
```
Option Explicit

'@DefaultMember
Public Property Get Item(ByRef ipIndex As Variant) As Variant
    Debug.Print "I should not be visible when variant holding an instance is tested for empty"
End Property
```
Module TestItemClass
```
Option Explicit

Sub Test()
    Dim myM As New ItemClass
    Dim myVar As Variant
    Set myVar = myM
    Debug.Print VBA.IsEmpty(myVar)
    
End Sub
```
Which gives the output
```
Executing 'Lib.TestItemClass.Test'...
I should not be visible when variant holding an instance is tested for empty
True
(time taken: 0.000061s)
```
Changing to variant to long gives the output
```
Executing 'Lib.TestItemClass.Test'...
False
(time taken: 0.0000552s)
```

**Expected behavior**
The behaviour should be the same as that of VBA.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - twinBASIC compiler version Ide Beta 67

**Comment by FullValueRider** [comment]
Edited to correct the code in Sub Test()

**Comment by mburns08109** [comment]
Wow... that WAS a mouthfull!

**Comment by WaynePhillipsEA** [comment]
Thanks for reporting.  Indeed, it appears the default member Variant parameter is wrongly being treated as `Optional` in the IDispatch implementation.  This will be fixed in the next update.
