### ISSUE TITLE
Implements Via does not recognise PredeclaredId as target for new instance

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#971]
**Describe the bug**
I was playing around with Implements via today.

I wrote a small wrapper for a scripting dictionary where the implements via statement was

```VB
Implements Scripting.Dictionary via Host = New Scripting.Dictionary
```

when tested , everything worked as expected.
I have a version of Olaf Scmidts cHashd class where I have implemented Deb/ConstructInstance as the factory methods.  Thus in twinbasic I can say
```VB
Dim myHash as cHashD = cHashD.Deb
```
Tests I have for my version of the cHAshD class shows that the factory method is working fine.

However, the PredeclaredId is not recognised when I use cHashD  in an Implements statement.  In Addition, the factory methods (Deb and ConstructInstance) are highlighted as being duplicate methods.

![ImplementsViaPredecalredId](https://user-images.githubusercontent.com/81257042/177644888-74d18217-23fb-416d-b012-45158935b2f9.jpg)

The initialisation codede of cHashD shows no errors
```VB
Class cHashD
    Attribute VB_GlobalNameSpace = False
    Attribute VB_Creatable = True
    Attribute VB_PredeclaredId = True
    Attribute VB_Exposed = True
    Option Explicit
    ' https://www.vbforums.com/showthread.php?834515-Simple-and-fast-lightweight-HashList-Class-(no-APIs)
    '@Description("cHashD by Olaf Schmidt August 2016 (enhanced about mixed, variable KeyTypes and Remove-functions in 2020")

    Private Const NoEntry As Variant = Empty
    Private Const DynTakeOver As Long = 4, HMul As Long = 3727 'fixed HashSlot-amount and Hash-Multiplikator

    Private Type HashTableEntry
        Count As Long
        DataIdxsStat(0 To DynTakeOver - 1) As Long
        DataIdxsDyn() As Long
    End Type
    
    Private W() As Integer, saW As SAFEARRAY1D
    
    Private mLastExpectedMaxCount As Long, mEnsureUniqueKeys As Boolean, mLastH As Long
    Private mCount As Long, mDTUB As Long, mHashTableSize As Long, mCompareMode As VbCompareMethod
    Private HashTable() As HashTableEntry, mKeys(), mValues()  'both pairing-arrays are of type Variant
    Private mFIndexes() As Long, mFCount As Long, mFUB As Long 'three vars, to handle the deletes


    Public Function Deb() As cHashD
        With New cHashD
            Return .ConstructInstance
        End With
    End Function

    Friend Function ConstructInstance() As cHashD
        saW.cDims = 1:  saW.cbElements = 2
        saW.cLocks = 1: saW.fFeatures = &H11 'FADF_AUTO=&H1 || FADF_FIXEDSIZE=&H10
        BindArray W, VarPtr(saW)
    
        mCompareMode = vbBinaryCompare
        ReInit 16384 'at startup we set it up, to behave ideally for up to 16384 Items
        
        If LWC(97) = 0 Then InitLWC
            
    End Function

etc........
```

**Expected behavior**
It would be useful (to me at least) if predeclaredIds could be used in Implements Via constucts.

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler Beta Ide 68

**Comment by FullValueRider** [comment]
Revised title

**Comment by WaynePhillipsEA** [comment]
For the predeclaredID problem, I'm not prepared to fix it at this point as there is a viable workaround by setting the field in the class constructor:

```
    Implements cHashD Via Host
    Sub New()
    	Set Host = cHashD.Deb
    End Sub
```

The reason for no fix here is that the Implements-Via feature already causes some complexities around ensuring the dependent underlying coclass/interface is in the required (semi-)compiled state before compiling the coclass, and to add predeclared IDs into the mix would make this more complicated than it needs to be.  It might be something we can revisit later, but for now the workaround should suffice.

With regards to the clash of `Deb` and `ConstructInstance` in the outer Class, this would be expected due to the import of those members from the Implements-Via interface, and we currently don't allow for overriding in that manner.

**Comment by FullValueRider** [comment]
Thanks for the feedback.  Unfortunately the workaround doesn't work as in the Hkvp class the Deb and .ConstructInstance methods are flagged up as Duplicate methods with cHashD and Hkvp being cited as the two sources.

Reverting cHashD to its original form produces code that works fine so there is an easy workaround and consequently  this issue can be treated as an FYI until such time some other issue means it needs to be addressed.

Cheers
