### ISSUE TITLE
Implements via: Member of baseclass in Derived class not recognised by IDE goto definition

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#972]
**Describe the bug**
I have a class (Hkvp) which is derived from a baseclass (cHashD) using implements via.

```
Class Hkvp
Implements cHashD Via Host = New cHashD
'etc....
```
The Reinit method of cHashD has been updated from a sub to a function to return the instance of Me) to allow chaining
This allows me to say
```
Dim myHkvp as Hkvp = Hkvp.Deb.Reinit(EnsureUniqueKeys:=False)
```

If I place the cursor on Reinit then the pop up box with the method signature is displayed.  However, If I right click and select goto definition, the IDE reports "No type definition for Reinit"

**Update**
If I try running the code then
```
Dim myHkvp as Hkvp = Hkvp.Deb.Reinit(EnsureUniqueKeys:=False)
````
gives an error

![reiniterror](https://user-images.githubusercontent.com/81257042/177708466-3858d756-ee53-421d-a2be-33fb5f7660e2.jpg)

but
```
 Dim myHkvp As Hkvp = Hkvp.Deb
    myHkvp.ReInit(ensureuniquekeys:=False)
```
runs without error.
**Expected behavior**
The IDE should go to the definition in the base class. The chained method should run as expected.

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version IDE Beta 68

**Comment by FullValueRider** [comment]
I updated the above post as I mistakenly has the second case of reinit when I reported that code was running fine.

The workaround is, as noted, not to chain the methods.

**Comment by WaynePhillipsEA** [comment]
Could you provide a test project for this one? thanks.

**Comment by FullValueRider** [comment]
[All.zip](https://github.com/twinbasic/twinbasic/files/9070813/All.zip)
The issue is demonstrated in Module TestHkvp, Test14_DuplicateKeys

**Comment by WaynePhillipsEA** [comment]
The Goto definition problem should now be fixed in BETA 75.  Thanks.

**Comment by WaynePhillipsEA** [comment]
Just looked into this, and it is being handled correctly.   Your call to `Hkvp.Deb.ReInit` returns an object of type `cHashD`, and you're trying to set it to a variable of type `Hkvp`.  Whilst the `Hkvp` type is the one implementing the `cHashD` here (due to the Implements-Via feature), back-casting to the outer type is not supported.   That will only be supported with full inheritance.

With the Goto definition issue already fixed, I'll now close this.  Thanks.
