### ISSUE TITLE
my RC6 application does not launch in Twinbasic

### ISSUE THREAD

**Issue by Napstore9** [twinbasic/twinbasic#974]
When executing the RC6 code in TB I see the message in DEBUG CONSOLE:

![cfMain](https://user-images.githubusercontent.com/106245272/177965258-3edd8e98-81b8-432e-ba3d-934ae5dc4624.PNG)
![ModBas](https://user-images.githubusercontent.com/106245272/177965268-87b173c4-0586-49be-9528-984c965b43d0.PNG)

And when I generate the executable file it works
![exec](https://user-images.githubusercontent.com/106245272/177968361-8910531d-c145-4eb4-9ae9-a6cc3c1c5fee.PNG)

TwinBASIC IDE BETA 68
Windows 10 64x

**Comment by WaynePhillipsEA** [comment]
Welcome, and thanks for the report.

At the moment, our forms only support modal behaviour, so the call to `cfForm.Form.Show` is blocking until you close the form (so `Cairo.WidgetForms.EnterMessageLoop` won't be hit).   Unfortunately I'm not familiar with RC6/Cairo, so I can't help much but suggest to wait until we support non-modal forms, which should be in the next few weeks.

**Comment by Napstore9** [comment]
> Bienvenue et merci pour le reportage.
> 
> Pour le moment, nos formulaires ne prennent en charge que le comportement modal, donc l'appel à `cfForm.Form.Show`est bloqué jusqu'à ce que vous fermiez le formulaire (il `Cairo.WidgetForms.EnterMessageLoop`ne sera donc pas touché). Malheureusement, je ne suis pas familier avec RC6/Cairo, donc je ne peux pas m'empêcher de suggérer d'attendre jusqu'à ce que nous prenions en charge les formulaires non modaux, ce qui devrait être dans les prochaines semaines.

Thank you for your reply

we look forward to this being taken care of.

**Comment by WaynePhillipsEA** [comment]
Please excuse my ignorance with regards to RC6/Cairo!  I might've been mistaken here.  `cfForm.Form` is not a native (twinBASIC) Form, right?  If that is the case, then please ignore my previous reply.

**Comment by WaynePhillipsEA** [comment]
If you could upload your twinproj file, I will take a look at this for you.

**Comment by Napstore9** [comment]
Okay

[RC6test.zip](https://github.com/twinbasic/twinbasic/files/9073078/RC6test.zip)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 71, thanks for reporting!
