### ISSUE TITLE
Maximized title bar incorrect outside IDE

### ISSUE THREAD

**Issue by CJCK** [twinbasic/twinbasic#976]
**Describe the bug**
If the application is maximized outside the IDE, the text/icons in the title bar touches the top of the screen. The white space disappears.

**To Reproduce**
1. Run twinBASIC.exe and open Standard Exe.
2. Click start/continue tool button.
3. Click the maximize button.
4. CORRECT: The title bar is shown correctly.
5. Now Save the Project and Build it.
6. Launch the exe.
7. Click the maximize button.
8. WRONG: The text and buttons in the tittle bar now touches the top of the screen. 

**Expected behavior**
Expect to have a space between the title bar text/buttons when window is maximized outside the IDE.

**Screenshots**
Screen shot attached showing the space that goes missing when maximized. 

**Desktop (please complete the following information):**
 - OS: Windows 10]
 - twinBASIC: Beta 68

**Additional context**
![Untitled](https://user-images.githubusercontent.com/102760934/178046486-fc81488f-fd6b-408a-a387-65e857e505a4.png)

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 70, thanks!

**Comment by CJCK** [comment]
Wow, that was quick ..... !
