### ISSUE TITLE
OptionButton - behaviour different from VB6

### ISSUE THREAD

**Issue by VB6-Programming** [twinbasic/twinbasic#978]
1. If OptionButtons are created on a form, and none are selected in the IDE FormBuilder (.Value=False for all), VB6 and twinBASIC both select the first OptionButton (correctly) at runtime.
But if one OptionButton is selected in the Form Builder (.Value=True), say the second button, VB6 honours this selection but twinBASIC still selects the first OptionButton (incorrect).
_Note this only applies to OptionButtons on the surface of the form, any in containers (e.g. Frame) are ignored by both VB6 and twinBASIC at runtime (strange but at least it is consistent)._

2. VB6 only allows 1 OptionButton in a group to be selected in the Form Builder (a previously selected one will be deselected), twinBASIC allows multiple OptionButtons to be selected (incorrect).
(also applies when Copy/Paste or Duplicate is used, VB6 only allows 1 selected button).
 
3. The Style property (and associated properties) for graphical (command button style) OptionButtons is not available (you probably know this).

 - OS:  Windows 10
 - twinBASIC compiler version Beta70

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 71, thanks!
