### ISSUE TITLE
Difference between Array() and Redim(0,-1)

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#983]
**Describe the bug**
I encountered the following today
![EmptyArray](https://user-images.githubusercontent.com/81257042/178540190-714bae21-09e6-4d02-b72d-b3a8934eefe0.jpg)

myExpected was generated from myArray =Array()
myResults was generated via Redim myArray(0,-1) where the -1 is the result of a calculation

This is just an FYI as I'm not sure if there are actually any errors here although it feels like the redim should have generated an error as Dim myArray(0 to -1) is not legal.

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version Beta Ide 71

**Comment by FullValueRider** [comment]
Bah, humbug.  This was a consequence of an OERN.  Removing the OERN led to an error at the redim statement.  I still find the difference in the representation of an empty array interesting, but close this if of no interest/utility.

**Comment by WaynePhillipsEA** [comment]
The IDE difference is purely between an uninitialized array (i.e. SAFEARRAY pointer is nullptr), and an array that is initialized with zero elements (SAFEARRAY is populated with cElements of any dimension being zero).   I'll close this now as I don't think it's worthy of changing the minor UI discrepancy here.
