### ISSUE TITLE
Run in compiler errors while try to use arrays as arguments.

### ISSUE THREAD

**Issue by rexxitall** [twinbasic/twinbasic#986]
[QTREE.zip](https://github.com/twinbasic/twinbasic/files/9105296/QTREE.zip)

**Comment by WaynePhillipsEA** [comment]
Please reduce the problem down to a minimal example.   I don't have the `slope64` or `AutoCAD 2021` references to be able to test this.  Thanks.

**Comment by rexxitall** [comment]
remove the references by two clicks they are not needed. The code is able to run standalone.

**Comment by rexxitall** [comment]
[QTREE.zip](https://github.com/twinbasic/twinbasic/files/9110388/QTREE.zip)
Anyhow here is the code without them

**Comment by rexxitall** [comment]
[QTREE.zip](https://github.com/twinbasic/twinbasic/files/9110494/QTREE.zip)
references killed

**Comment by WaynePhillipsEA** [comment]
As far as I can see, this is a valid point of error in your code.

<img width="732" alt="gh_986" src="https://user-images.githubusercontent.com/25738109/179225524-8cc9c72f-d353-4760-98ef-ce3513234d66.png">

Since `Points` hasn't been dimensioned with ReDim, `UBound` is expected to fail.   The error description is not correct, as it should be `Subscript out of range`, but the error itself looks to be correct.

**Comment by rexxitall** [comment]
Funny, it runs well in VBA. Points should be there. Did you change the path to the text data files ? look for "R:\" in the code. i add something like this in the SEARCH_TRIANGLES    
On Error Resume Next
N = UBound(HANDLES)
If Err.Number <> 0 Then Exit Function
which makes it run. But this code is fixed to avoid the strange compiler errors i got with the first version where i use arrays() as parameters. I really do not usually use WILLY as sub name :D I will play a bit with it next week :) And also big thanks, the result runs way faster then in VBA :) !!!

**Comment by WaynePhillipsEA** [comment]
Apologies, I missed those files as they weren't in your second ZIP.  Indeed, now with loading those files it gets much further, and now halts at the `UBound(HANDLES)` line, same as you.    But when that happens you'll see in the `Variables` panel the same issue, in that the `HANDLES` array is not initialized, and so UBound would expect to throw an error at that point.

I haven't investigated any further to see why `HANDLES` has not been initialized, so I can't confirm whether it is a compiler issue or not.  I will leave it to you to dig deeper and perhaps provide a minimal example demonstrating any problem you find. I'll leave this issue open for the time being.

Glad to hear it runs faster than VBA ;)

**Comment by rexxitall** [comment]
Thanks for your time. I think we can close it if you put a more meaningfull text on the "array not filled" error message and on the error message which comes up if the parameters of a procedure do not match its definition. Especially cause both tell "make a error issue on github" :) I used the first code with the parameter array arguents again and i made a version without the acad things for you. Just in case you want to play with it for the error messages
[R.zip](https://github.com/twinbasic/twinbasic/files/9125738/R.zip)
.

**Comment by rexxitall** [comment]
I figured out why VBA7 does not show a error. ubound returns -1 if the array is not initialized. By this the for next loops are not executed and the code works.

**Comment by WaynePhillipsEA** [comment]
```
Public Sub TestUBound()
    Dim myArray() As Long
    MsgBox UBound(myArray)
End Sub
```

Gives the expected `subscript out of range`  error in Access VBA7 (both 32-bit and 64-bit).

**Comment by vbBaka** [comment]
yeah. u cant use lbound/ubound if the array is undimmed.
and it should act like that for back-compatibility.
but I don't mind an array check. right now I use CopyMemory to get the bound or error trapping (for strings)

**Comment by dmrvb** [comment]
There is an API call  "GetSafeArrayDim" that works with undimmed arrays. I prefer this to error handling as its neater code and faster. Maybe this could be built into a future version of tB?

**Comment by rexxitall** [comment]
That do not explains why the code was perfectly running in autocad VBA :) It should not but it does. i use the mouse pointer "debugger var inspect"  over the n=ubound(... variable  and it shows  -1 as result. As far as i remember Autodesk was doing a lot with vba around version 2015 and 2016. They call it VBA 7 Version 2 at that times. 2015 was unusuable slow and 2016 was running like hell. On monday i will provide a screenshot. I am not t hat sure if in this case backwards compability is such a gift. in any case it will so or so raise an error cause -1 is not a valid array bound. So the developer will hit its nose directly to the array witch causes the error. If you want compability then the peoples will use on error resume next. So it would be more convinient to get -1 and you can use if then :) If you want both i suggest to use a ompilerflag where you can turn of more advanced features on or off. Freebasic does it by defining the "lang" switch. Great idea but somehow they never provides a VBA language switch *grin*. Witch in fact turns the thing into another esotheric "only compatible with itselv" crap. But this is just my personal opinion :)

**Comment by vbBaka** [comment]
and wheres that GetSafeArrayDim API? can't find it.
or maybe u mean SafeArrayGetDim?

**Comment by dmrvb** [comment]
Sorry yes, I had renamed it with an alias, and its too hot here to think straight.
I prefer not to use the "as any" in my API declares so do a set of alias names, one for a single array, one for a double array etc etc.,

**Comment by WaynePhillipsEA** [comment]
@rexxitall did you test the minimal `TestUBound` that I provided earlier, in your AutoCAD VBA?   I am very sceptical that there would be a difference here between AutoCAD VBA and Office VBA, so that should also throw the error for you.

A `-1` UBound result would indicate the array has been dimensioned, but contains no elements (or if the array does have elements, then the lower bound is negative, but that would be somewhat unusual).  

For example `?UBound(Array())` would give `-1`.   But that is different from an uninitialized array, which should always throw the error.

**Comment by wqweto** [comment]
@rexxitall Which version of AutoCAD original code is execute on?

**Comment by rexxitall** [comment]
I usually run Acad 2020 Could run also the newest ones cause we have a subscription. But it takes me always half a day to adjust ACAD :D Its usually not worth by the 3 minor updates they made during a year. I also do not noticed any kind of changes by the Versions. Except the ones as they made VBA7 fast. It seems to be a Autodesk mantra in Autocad never ever change anything in the API. Does not matter how stupid it is. Which has also its beauty. Its no fun to rewrite code again and again and again just because someones wants too made a API more "excellent" :) Code i wrote in 2008 still works perfect without changes. That's why i stopped using PHP years ago. After a upgrade a whole price calculation program for civil constructions was destroyed. 2 Years of my work lost. No, thanks 🗡️

**Comment by WaynePhillipsEA** [comment]
LBound/UBound error codes and descriptions should now match VBx.  As such, let's close this.
