### ISSUE TITLE
I have a prog that ran fine in 65 but has erros in 73

### ISSUE THREAD

**Issue by OldestCoderInTown** [twinbasic/twinbasic#987]
**Describe the bug**
I have a prog that ran fine in 65 but has erros in 73

I get this in a red box  "Sorry, twinBASIC doesn't yet support non-modal forms.  To show a modal form use Show(vbModal)"

I am not aware of asking it to show anything, never mind a non modal form.

**To Reproduce**

I load and run the prog which shows this error.

I went back to 65 and it runs ok, I have now gone back to 72 for testing. That also fails.

**Desktop (please complete the following information):**
Windows 10 Pro
 - twinBASIC compiler version 73

**Additional context**

**Comment by FullValueRider** [comment]
Try reading the bullet points for release 72

**Comment by OldestCoderInTown** [comment]
I have read the bullet points, but remain ignorant of how to resolve a bit of code that needs changed, when I didn't write it, and the editor tells me I can't change it.

**Comment by WaynePhillipsEA** [comment]
When you hit that error, use the Callstack to view how you got there.   You can't (and shouldn't) change the code in the WinNativeForms package, but instead need to change the originating code which calls the form Show() method, which will be inside your project.

**Comment by WaynePhillipsEA** [comment]
Apologies, I just noticed the F5 key (and the start button) is broken in BETA 71/72 when the startup object is a form, causing this problem.  If you build the exe, or preview the form, or run something like `Form1.Show(vbModal)` in the debug console, it will work as usual.  This will be fixed shortly in BETA 73, thanks for reporting.

**Comment by WaynePhillipsEA** [comment]
Fixed in BETA 74, thanks.

**Comment by OldestCoderInTown** [comment]
Working fine now. thanks.
