### ISSUE TITLE
Enumeration member with the same name as a function is allowed by twinBasic but not in VBA

### ISSUE THREAD

**Issue by FullValueRider** [twinbasic/twinbasic#991]
**Describe the bug**
I ran into a problem which turned out to be an emumeration member being given the same name as a VBA function.

The following code does not run on VBA but compiles and runs in twinbasic.
```
Public Enum Blocker
        Abs=32
    End Enum

    Public Sub TestBlocker()
        Debug.Print Abs(-5), VBA.Abs(-5)
    End Sub
```

However, in twinBasic the output is 32,5 and not 5,5

VBA flags the enumeration member as an error.
![IllegalEnumMember](https://user-images.githubusercontent.com/81257042/179352579-a371689a-9f78-4d8c-8905-61db3151d212.jpg)

There is a workaround, as shown, which is to prefix the function call with VBA.

**Expected behavior**
twinBasic should draw attention to the name conflict

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - twinBASIC compiler version IDE Beta 75

**Comment by mburns08109** [comment]
I just know I'm stepping in something here, asking this, but...
1) does VB6 do the same (can't check for myself @ work right now)
2) Assuming it doesn't (for the sake of argument), which behavior should govern (by default?/option setting?), if there is a difference, VB6 or VBA?

**Comment by FullValueRider** [comment]
I'd assume that the default behaviour would be that of VBA. More importantly, what's going on with the (-5) if Abs(-5) reports 32.
