### ISSUE TITLE
Form Controls collection

### ISSUE THREAD

**Issue by WaynePhillipsEA** [twinbasic/twinbasic#992]
As mentioned in #990, the WinNativeForms form Controls property is not yet populated (returns Nothing).

Issue created for tracking purposes.

**Comment by AntsAntix** [comment]
Will this solution then include a generic **Control** object against which the Controls property can be enumerated?

**Comment by WaynePhillipsEA** [comment]
The `Control` type is already supported, same as VB6.

**Comment by AntsAntix** [comment]
Hi Wayne

I have been recovering from being whacked by COVID and wanted to reply earlier . . .

The VB6 implementation of Control is different to the MSFORMS implementation. The latter includes key events. This means that any migration of MSFORMS to WinNaturalForms that relies on the MSFORMS.Control will not work.

Was this the intention - that VB6 will take precedence?

Regards

Ant
________________________________

**Comment by bclothier** [comment]
See #584. It'll be solved eventually but apparently not in focus just yet.
