### ISSUE TITLE
ActiveX Control crashes if there are no events defined.

### ISSUE THREAD

**Issue by bclothier** [twinbasic/twinbasic#997]
**Describe the bug**
It appears that if an ActiveX control is created but does not expose any events, it will crash. See discord.

**To Reproduce**
1. Create a new ActiveX Control project
2. Trim the code to minimum, just a `Sub New()`, no events
3. Build the project
4. Try to load the control in a VBA host. It then crashes.

**Expected behavior**
No crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - twinBASIC compiler version 79

**Comment by WaynePhillipsEA** [comment]
This should now be fixed in BETA 79.  Thanks!
